/***********************************************************************/
/*                                                                     */
/*  FILE        :cpubSIT4.c                                            */
/*  DATE        :Sun, Jul 16, 2006                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
#include	<machine.h>
                  
#include	"cm_equ1.h"
#include	"ssc_wrms.h"
#include	"CPU_REG.h"
#include	"ssc_ver1.h"


#ifdef __cplusplus
//#include <ios>					// Remove the comment when you use ios                  
//int ios_base::Init::init_cnt;		// Remove the comment when you use ios
#endif
#ifdef __cplusplus
extern "C" {
#endif
void main(void);
#ifdef __cplusplus
}
#endif


#define SR_Init_AllEI	0x40000010				// shima(ins) 全割込み許可

extern	U2b	cpuab_hs_out0;
extern	void DO_Rifresh(void);

extern	void WDT_Rifresh(void);
extern	void hmi1_init1(void);
extern	void hmi1_init2(void);
extern	void hmi1_init3(void);
extern	void hmi1_main(void);
extern	void hmi2_init1(void);
extern	void hmi2_init2(void);
extern	void hmi2_init3(void);
extern	void hmi2_main(void);
//extern	void cbk_init1(void);
//extern	void cbk_init2(void);
//extern	void cbk_init3(void);
//extern	void cbk_main(void);
extern	void ASM_DMK1_DATA_INIT(void);
extern	void ASM_DMK1_SOFT_INIT(void);//

extern	void ET1_LDCMD_IF(void);
extern	void SCI_VUP_MAIN(void);
extern	void hmi2_test(void);

extern	void hmi2_int3(void);

extern	void ASM_DMY1_SOFT_INIT(void);		//cb_src\y_src\ssa_y.src

extern	S2b CMP_ERR_STSA_INF4;
extern	void draw_smple(void); 
extern	U2b SEQ_DP_TOP[1600/2];

extern	void COP1_START_INIT1();
extern	void COP1_MAIN_SEQ_DAT_REF();
extern	void COP1_INT_WR();
extern	void COP1_ENC_WR();
extern	void COP1_DPRAM_CLR1();//2002-12


extern	void COP1_MAIN_TLINK_DAT_REF();//2003-01-31
extern	U2b		cop_enc_int_enb;
extern	U2b		cop_wait_tim;//2002-12-16 


void main(void)
{
//;	*******************************************
//;	***	割込み許可前1回処理					***
//;	*******************************************


	COP1_DPRAM_CLR1();
	hmi1_init1();
	hmi2_init1();
	//cbk_init1();
	ASM_DMK1_SOFT_INIT();//
	

//;	*******************************************
//;	***	割込み許可							***
//;	*******************************************
	set_cr(SR_Init_AllEI);					// 全割込み許可

//2002-12-16 optionのdpram等のﾁｪｯｸ完了を待つ
//	cop_wait_tim=30000/5;//2.5sec ok
//	cop_wait_tim=1000/5;//試し    ok
	cop_wait_tim=2500/5;//2.5sec
	while(cop_wait_tim){
		WDT_Rifresh();
	}

//;	*******************************************
//;	***	割込み許可後1回処理					***
//;	*******************************************
	hmi1_init2();
	hmi2_init2();
//	cbk_init2();

//;	*******************************************
//;	***	初期ﾃﾞｰﾀ送信						***
//;	*******************************************
//FIT_SRCで初期ﾃﾞｰﾀをCPUAへ送信
	cpuab_hs_out0 |= 0x80;
	DO_Rifresh();

//2002-12-16 optionのdpram等のﾁｪｯｸ完了を待つ
//	cop_wait_tim=2500/5;//2.5sec
//	while(cop_wait_tim){
//		WDT_Rifresh();
//	}


//;	*******************************************
//;	***	初期ﾃﾞｰﾀ受信						***
//;	*******************************************

//;	*******************************************
//;	***	初期ﾃﾞｰﾀ受信後1回処理				***
//;	*******************************************
	hmi1_init3();
	hmi2_init3();
//	cbk_init3();
	ASM_DMK1_DATA_INIT();
	ASM_DMY1_SOFT_INIT();		//cb_src\y_src\ssa_y.src 2002-08-24 SAITO

//2002-12-06
	COP1_START_INIT1();


#if	( SIT_TYPE_SEL == TYPE_SIT4 )
//	PEDR = 0;					// *LCD_ONイネーブル
#endif


//;	*******************************************
//;	***	MAINｽｷｬﾝ処理						***
//;	*******************************************
	while(1)
	{
		WDT_Rifresh();
		hmi1_main();
		hmi2_main();
		ASM_K1_CTRL_MAIN();
		//cbk_main();
//V06m移動		ET1_LDCMD_IF();						// V05
		SCI_VUP_MAIN();
//		if(CMP_ERR_STSA_INF4){
//			SEQ_DP_TOP[101]=0x00ff;
//			SEQ_DP_TOP[107]=0x00ff;
//			draw_smple();
//		}
	//2002-12-06
//V05j 2007/12/11 割り込みへ		COP1_MAIN_SEQ_DAT_REF();

	//2003-01-31
//		COP1_MAIN_TLINK_DAT_REF();//2003-01-31// SAITO 2004-05-21 DEL

		//定周期へCOP1_INT_ENC_REF();
		cop_enc_int_enb=1;

	}
}


