
	.DATA.L		H'202,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~8
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~16
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~24
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~32
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~40
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~48
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~56
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~64
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~72
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~80
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~88
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~96
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~104
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~112
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~120
	.DATA.L		H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0,	H'0	;~128
	.DATA.B		H'5A,	H'0

	.DATA.B		4,	1,	2,	3,	1,	3,	8,	H'0	;âÊñ ÇPÉwÉbÉ_Å[

	.DATA.B		d'0,	d'0							;ï∂éöÇP
	.DATA.W		H'0,	d'0,	d'0,	d'1
	.DATA.B		d'2,	d'2,	d'0,	d'5,	d'8,	H'0,	H'0,	H'0
	.DATA.B		d'0,	d'0							;ï∂éöÇQ
	.DATA.W		H'0,	d'320,	d'96,	d'2
	.DATA.B		d'2,	d'2,	d'0,	d'5,	d'8,	H'0,	H'0,	H'0
	.DATA.B		d'0,	d'0							;ï∂éöÇR
	.DATA.W		H'0,	d'320,	d'144,	d'3
	.DATA.B		d'2,	d'2,	d'0,	d'5,	d'8,	H'0,	H'0,	H'0
	.DATA.B		d'0,	d'0							;ï∂éöÇS
	.DATA.W		H'0,	d'320,	d'208,	d'4
	.DATA.B		d'2,	d'2,	d'0,	d'5,	d'8,	H'0,	H'0,	H'0

	.DATA.B		d'1,	d'0							;ÉJÅ[É\ÉãÇP
	.DATA.W		H'0,	d'0,	d'320,	d'1
	.DATA.B		d'1,	d'1,	d'5,	d'2,	d'3,	H'0,	H'0,	H'0

	.DATA.B		d'1,	d'0							;ê›íËílÇP
	.DATA.W		H'0,	d'480,	d'176,	d'16
	.DATA.B		d'1,	d'1,	d'0,	d'3,	d'3,	H'0,	H'0,	H'0
	.DATA.B		d'1,	d'0							;ê›íËílÇQ
	.DATA.W		H'0,	d'480,	d'240,	d'16
	.DATA.B		d'1,	d'1,	d'0,	d'3,	d'3,	H'0,	H'0,	H'0

	.DATA.B		d'3,	d'0							;é¿ë™ílÇP
	.DATA.W		H'0,	d'480,	d'96,	d'8
	.DATA.B		d'2,	d'2,	d'0,	d'7,	d'7,	H'0,	H'0,	H'0
	.DATA.B		d'3,	d'0							;é¿ë™ílÇQ
	.DATA.W		H'0,	d'480,	d'144,	d'8
	.DATA.B		d'2,	d'2,	d'0,	d'7,	d'7,	H'0,	H'0,	H'0
	.DATA.B		d'3,	d'0							;é¿ë™ílÇR
	.DATA.W		H'0,	d'480,	d'208,	d'8
	.DATA.B		d'2,	d'2,	d'0,	d'7,	d'7,	H'0,	H'0,	H'0

	.DATA.B		d'1,	d'0							;ÇrÇvÅ|ÇkÇ`ÇlÇoÇP
	.DATA.W		H'0,	d'0,	d'272,	d'1
	.DATA.B		d'1,	d'1,	d'5,	d'2,	d'3,	H'0,	H'0,	H'0

	.DATA.B		d'0,	d'0							;ÉOÉâÉtÉBÉbÉNÇP
	.DATA.W		H'0,	d'0,	d'400,	d'640,	d'0
	.DATA.B		d'0,	d'2,	d'3,	H'0,	H'0,	H'0
	.DATA.B		d'0,	d'0							;ÉOÉâÉtÉBÉbÉNÇQ
	.DATA.W		H'0,	d'320,	d'400,	d'0,	d'80
	.DATA.B		d'0,	d'2,	d'3,	H'0,	H'0,	H'0
	.DATA.B		d'0,	d'1							;ÉOÉâÉtÉBÉbÉNÇR
	.DATA.W		H'0,	d'0,	d'416,	d'128,	d'64
	.DATA.B		d'0,	d'2,	d'3,	H'0,	H'0,	H'0


