
	.DATA.W		D'4,	D'1,	D'1,	D'1,	D'1
	.DATA.B		H'5A,	H'0

CHR_CODE_TOP:
	.DATA.B		d'10, H'0
	.DATA.W		"Å@"
	.DATA.W		"ê∂"
	.DATA.W		"Å@"
	.DATA.W		"éY"
	.DATA.W		"Å@"
	.DATA.b		H'20, H'20, H'20, H'20, H'20, H'20

	.DATA.B		d'8, H'0
	.data.b		"ƒ"
	.data.b		"∞"
	.data.b		"¿"
	.data.b		"Ÿ"
	.data.b		"∂"
	.data.b		"≥"
	.data.b		"›"
	.data.b		"¿"
	.data.b		H'20, H'20, H'20, H'20, H'20, H'20, H'20, h'20

	.DATA.B		d'8, H'0
	.data.b		"€"
	.data.b		"Ø"
	.data.b		"ƒ"
	.data.b		"∂"
	.data.b		"≥"
	.data.b		"›"
	.data.b		"¿"
	.data.b		" "
	.data.b		H'20, H'20, H'20, H'20, H'20, H'20, H'20, h'20

	.DATA.B		d'8, H'0
	.DATA.W		"å^"
	.data.b		"“"
	.data.b		"›"
	.data.b		"√"
	.data.b		"≈"
	.data.b		"›"
	.data.b		"Ω"
	.data.b		H'20, H'20, H'20, H'20, H'20, H'20, H'20, h'20

	.DATA.B		h'5a, h'0

CSR_CODE_TOP:
	.DATA.B		d'16, H'0, H'20, H'20, H'82, H'a9, H'82, H'ab, H'82, H'ad, H'82, H'af, H'82, H'b1, H'43, H'44, H'b3, H'b4
	.DATA.B		h'5a, h'0

SWL_CODE_TOP:
	.DATA.B		d'08, H'0, H'20, H'20, H'82, H'a9, H'82, H'ab, H'82, H'ad, H'82, H'af, H'82, H'b1, H'43, H'44, H'b3, H'b4
	.DATA.B		h'5a, h'0

S56_CODE_TOP:
	.DATA.B		d'08, H'0, H'20, H'20, H'82, H'a9, H'82, H'ab, H'82, H'ad
	.DATA.B		h'5a, h'0

MES_CODE_TOP:
	.DATA.B		d'40, H'0
	.DATA.B		H'31, H'32, H'33, H'34, H'35, H'36, H'37, H'38, H'39, H'20
	.DATA.B		H'20, H'20, H'20, H'20, H'20, H'20, H'20, H'20, H'20, H'20
	.DATA.B		H'20, H'20, H'20, H'20, H'20, H'20, H'20, H'20, H'20, H'20
	.DATA.B		H'20, H'20, H'20, H'20, H'20, H'20, H'20, H'20, H'20, H'20
	.DATA.B		h'5a, h'0


