
;/*     ê›íËílêßå‰èÓïÒÉeÅ[ÉuÉã      */

;SV0001
    .data.w 0, 0
    .data.l _SV_PUR1SV_B4
    .data.w 0, 50, h'0004, 4, 0, 2, 1, 0, 2, 0;
;SV0002
    .data.w 0, 0
    .data.l _SV_PUR2SV_B41
    .data.w 0, 51, h'0004, 4, 0, 3, 1, 0, 2, 0;
;SV0003
    .data.w 0, 0
    .data.l _SV_DANSUU_SRV
    .data.w 51, 0, 0, 2, 0, 2, 1, h'0004, 2, 0;
;SV0004
    .data.w 0, 0
    .data.l _SV_TAIKIKAKU_SRV
    .data.w 54, 85, h'0100, 2, 0, 3, 1, h'0004, 2, 0;
;SV0005
    .data.w 0, 0
    .data.l _SV_TAIKIPOS_SRV
    .data.w 56, 91, h'0400, 4, 2, 4, 1, h'0004, 2, 0;
;SV0006
    .data.w 0, 0
    .data.l _SV_DAIHAITO_SRV
    .data.w 80, 117, h'1000, 4, 2, 5, 1, h'0004, 2, 0;
;SV0007
    .data.w 0, 0
    .data.l _SV_HOASEI_SRV
    .data.w 72, 118, 0, 2, 0, 6, 1, h'0004, 2, 0;
;SV0008
    .data.w 0, 0
    .data.l _SV_1DANDEG_SRV
    .data.w 74, 86, h'0100, 2, 0, 7, 1, h'0004, 2, 0;
;SV0009
    .data.w 0, 0
    .data.l _SV_1DANPOS_SRV
    .data.w 75, 92, h'0400, 4, 2, 8, 1, h'0004, 2, 0;
;SV0010
    .data.w 0, 0
    .data.l _SV_1DANSPD_SRV
    .data.w 70, 97, 0, 2, 1, 9, 1, h'0004, 4, 0;
;SV0011
    .data.w 0, 0
    .data.l _SV_1DANTIM_SRV
    .data.w 0, 97, 0, 2, 2, 10, 1, h'0004, 2, 1;
;SV0012
    .data.w 0, 0
    .data.l _SV_2DANDEG_SRV
    .data.w 74, 87, h'0100, 2, 0, 11, 1, h'0004, 2, 0;
;SV0013
    .data.w 0, 0
    .data.l _SV_2DANPOS_SRV
    .data.w 75, 93, h'0400, 4, 2, 12, 1, h'0004, 2, 0;
;SV0014
    .data.w 0, 0
    .data.l _SV_2DANSPD_SRV
    .data.w 70, 98, 0, 2, 1, 13, 1, h'0004, 2, 0;
;SV0015
    .data.w 0, 0
    .data.l _SV_2DANTIM_SRV
    .data.w 0, 98, 0, 2, 2, 14, 1, h'0004, 2, 1;
;SV0016
    .data.w 0, 0
    .data.l _SV_3DANDEG_SRV
    .data.w 74, 88, h'0100, 2, 0, 15, 1, h'0004, 2, 0;
;SV0017
    .data.w 0, 0
    .data.l _SV_3DANPOS_SRV
    .data.w 75, 94, h'0400, 4, 2, 16, 1, h'0004, 2, 0;
;SV0018
    .data.w 0, 0
    .data.l _SV_3DANSPD_SRV
    .data.w 70, 99, 0, 2, 1, 17, 1, h'0004, 2, 0;
;SV0019
    .data.w 0, 0
    .data.l _SV_3DANTIM_SRV
    .data.w 81, 99, 0, 2, 2, 18, 1, h'0004, 2, 1;
;SV0020
    .data.w 0, 0
    .data.l _SV_4DANDEG_SRV
    .data.w 74, 89, h'0100, 2, 0, 19, 1, h'0004, 2, 0;
;SV0021
    .data.w 0, 0
    .data.l _SV_4DANPOS_SRV
    .data.w 75, 95, h'0400, 4, 2, 20, 1, h'0004, 2, 0;
;SV0022
    .data.w 0, 0
    .data.l _SV_4DANSPD_SRV
    .data.w 70, 100, 0, 2, 1, 21, 1, h'0004, 2, 0;
;SV0023
    .data.w 0, 0
    .data.l _SV_4DANTIM_SRV
    .data.w 0, 100, 0, 2, 2, 22, 1, h'0004, 2, 1;
;SV0024
    .data.w 0, 0
    .data.l _SV_5DANDEG_SRV
    .data.w 74, 90, h'0100, 2, 0, 23, 1, h'0004, 2, 0;
;SV0025
    .data.w 0, 0
    .data.l _SV_5DANPOS_SRV
    .data.w 75, 96, h'0400, 4, 2, 24, 1, h'0004, 2, 0;
;SV0026
    .data.w 0, 0
    .data.l _SV_5DANSPD_SRV
    .data.w 70, 101, 0, 2, 1, 25, 1, h'0004, 2, 0;
;SV0027
    .data.w 0, 0
    .data.l _SV_5DANTIM_SRV
    .data.w 0, 101, 0, 2, 2, 26, 1, h'0004, 2, 1;
;SV0028
    .data.w 0, 0
    .data.l _SV_TAIKSPD_SRV
    .data.w 70, 102, 0, 2, 1, 27, 1, h'0004, 2, 0;
;SV0029
    .data.w 0, 0
    .data.l _SV_TAIKTIM_SRV
    .data.w 0, 102, 0, 2, 2, 28, 1, h'0004, 2, 1;
;SV0030
    .data.w 0, 0
    .data.l _SV_DANSUU_SRV
    .data.w 51, 0, 0, 2, 0, 2, 1, h'0004, 0, 0;
;SV0031
    .data.w 0, 0
    .data.l _SV_TAIKIKAKU_SRV
    .data.w 54, 85, h'0100, 2, 0, 3, 1, h'0004, 0, 0;
;SV0032
    .data.w 0, 0
    .data.l _SV_TAIKIPOS_SRV
    .data.w 56, 91, h'0400, 4, 2, 4, 1, h'0004, 0, 0;
;SV0033
    .data.w 0, 0
    .data.l _SV_DAIHAITO_SRV
    .data.w 80, 117, h'1000, 4, 2, 5, 1, h'0004, 0, 0;
;SV0034
    .data.w 0, 0
    .data.l _SV_HOASEI_SRV
    .data.w 72, 118, 0, 2, 0, 6, 1, h'0004, 0, 0;
;SV0035
    .data.w 0, 0
    .data.l _SV_DANSUU_SRV
    .data.w 51, 0, 0, 2, 0, 2, 1, h'0004, 2, 0;
;SV0036
    .data.w 0, 0
    .data.l _SV_TAIKIKAKU_SRV
    .data.w 54, 85, h'0100, 2, 0, 3, 1, h'0004, 2, 0;
;SV0037
    .data.w 0, 0
    .data.l _SV_TAIKIPOS_SRV
    .data.w 56, 91, h'0400, 4, 2, 4, 1, h'0004, 2, 0;
;SV0038
    .data.w 0, 0
    .data.l _SV_DAIHAITO_SRV
    .data.w 80, 117, h'1000, 4, 2, 5, 1, h'0004, 2, 0;
;SV0039
    .data.w 0, 0
    .data.l _SV_HOASEI_SRV
    .data.w 72, 118, 0, 2, 0, 6, 1, h'0004, 2, 0;
;SV0040
    .data.w 0, 0
    .data.l _SV_6DANDEG_SRV
    .data.w 74, 107, h'0100, 2, 0, 7, 1, h'0004, 2, 0;
;SV0041
    .data.w 0, 0
    .data.l _SV_6DANPOS_SRV
    .data.w 75, 112, h'0400, 4, 2, 8, 1, h'0004, 2, 0;
;SV0042
    .data.w 0, 0
    .data.l _SV_6DANSPD_SRV
    .data.w 70, 97, 0, 2, 1, 9, 1, h'0004, 2, 0;
;SV0043
    .data.w 0, 0
    .data.l _SV_6DANTIM_SRV
    .data.w 0, 97, 0, 2, 2, 10, 1, h'0004, 2, 1;
;SV0044
    .data.w 0, 0
    .data.l _SV_7DANDEG_SRV
    .data.w 74, 108, h'0100, 2, 0, 11, 1, h'0004, 2, 0;
;SV0045
    .data.w 0, 0
    .data.l _SV_7DANPOS_SRV
    .data.w 75, 113, h'0400, 4, 2, 12, 1, h'0004, 2, 0;
;SV0046
    .data.w 0, 0
    .data.l _SV_7DANSPD_SRV
    .data.w 70, 98, 0, 2, 1, 13, 1, h'0004, 2, 0;
;SV0047
    .data.w 0, 0
    .data.l _SV_7DANTIM_SRV
    .data.w 0, 98, 0, 2, 2, 14, 1, h'0004, 2, 1;
;SV0048
    .data.w 0, 0
    .data.l _SV_8DANDEG_SRV
    .data.w 74, 109, h'0100, 2, 0, 15, 1, h'0004, 2, 0;
;SV0049
    .data.w 0, 0
    .data.l _SV_8DANPOS_SRV
    .data.w 75, 114, h'0400, 4, 2, 16, 1, h'0004, 2, 0;
;SV0050
    .data.w 0, 0
    .data.l _SV_8DANSPD_SRV
    .data.w 70, 99, 0, 2, 1, 17, 1, h'0004, 2, 0;
;SV0051
    .data.w 0, 0
    .data.l _SV_8DANTIM_SRV
    .data.w 0, 99, 0, 2, 2, 18, 1, h'0004, 2, 1;
;SV0052
    .data.w 0, 0
    .data.l _SV_9DANDEG_SRV
    .data.w 74, 110, h'0100, 2, 0, 19, 1, h'0004, 2, 0;
;SV0053
    .data.w 0, 0
    .data.l _SV_9DANPOS_SRV
    .data.w 75, 115, h'0400, 4, 2, 20, 1, h'0004, 2, 0;
;SV0054
    .data.w 0, 0
    .data.l _SV_9DANSPD_SRV
    .data.w 70, 100, 0, 2, 1, 21, 1, h'0004, 2, 0;
;SV0055
    .data.w 0, 0
    .data.l _SV_9DANTIM_SRV
    .data.w 0, 100, 0, 2, 2, 22, 1, h'0004, 2, 1;
;SV0056
    .data.w 0, 0
    .data.l _SV_10DANDEG_SRV
    .data.w 74, 111, h'0100, 2, 0, 23, 1, h'0004, 2, 0;
;SV0057
    .data.w 0, 0
    .data.l _SV_10DANPOS_SRV
    .data.w 75, 116, h'0400, 4, 2, 24, 1, h'0004, 2, 0;
;SV0058
    .data.w 0, 0
    .data.l _SV_10DANSPD_SRV
    .data.w 70, 101, 0, 2, 1, 25, 1, h'0004, 2, 0;
;SV0059
    .data.w 0, 0
    .data.l _SV_10DANTIM_SRV
    .data.w 0, 101, 0, 2, 2, 26, 1, h'0004, 2, 1;
;SV0060
    .data.w 0, 0
    .data.l _SV_TAIKSPD_SRV
    .data.w 70, 102, 0, 2, 1, 27, 1, h'0004, 2, 0;
;SV0061
    .data.w 0, 0
    .data.l _SV_TAIKTIM_SRV
    .data.w 0, 102, 0, 2, 2, 28, 1, h'0004, 2, 1;
;SV0062
    .data.w 0, 0
    .data.l _SV_PUR1SV_B4
    .data.w 0, 50, 0, 4, 0, 2, 1, h'0008, 2, 0;
;SV0063
    .data.w 0, 0
    .data.l _SV_PUR2SV_B41
    .data.w 0, 51, 0, 4, 0, 3, 1, h'0008, 2, 0;
;SV0064
    .data.w 0, 0
    .data.l _SV_EJEKK1_C4
    .data.w 5, 1, 0, 2, 0, 4, 1, h'0080, 2, 0;
;SV0065
    .data.w 0, 0
    .data.l _SV_EJEKK2_C4
    .data.w 5, 2, 0, 2, 0, 4, 2, h'0080, 2, 0;
;SV0066
    .data.w 0, 0
    .data.l _SV_MISSK1_C9
    .data.w 5, 46, 0, 2, 0, 5, 1, h'0080, 2, 0;
;SV0067
    .data.w 0, 0
    .data.l _SV_MISSK2_C9
    .data.w 5, 46, 0, 2, 0, 5, 2, h'0080, 2, 0;
;SV0068
    .data.w 0, 0
    .data.l _SV_RCLS11_C17
    .data.w 5, 3, 0, 2, 0, 6, 1, h'0080, 2, 0;
;SV0069
    .data.w 0, 0
    .data.l _SV_RCLS12_C17
    .data.w 5, 3, 0, 2, 0, 6, 2, h'0080, 2, 0;
;SV0070
    .data.w 0, 0
    .data.l _SV_RCLS21_C17
    .data.w 5, 4, 0, 2, 0, 8, 1, h'0080, 2, 0;
;SV0071
    .data.w 0, 0
    .data.l _SV_RCLS22_C17
    .data.w 5, 4, 0, 2, 0, 8, 2, h'0080, 2, 0;
;SV0072
    .data.w 0, 0
    .data.l _SV_RCLS31_C17
    .data.w 5, 5, 0, 2, 0, 10, 1, h'0080, 2, 0;
;SV0073
    .data.w 0, 0
    .data.l _SV_RCLS32_C17
    .data.w 5, 5, 0, 2, 0, 10, 2, h'0080, 2, 0;
;SV0074
    .data.w 0, 0
    .data.l _SV_RCLS41_C17
    .data.w 5, 6, 0, 2, 0, 12, 1, h'0080, 2, 0;
;SV0075
    .data.w 0, 0
    .data.l _SV_RCLS42_C17
    .data.w 5, 6, 0, 2, 0, 12, 2, h'0080, 2, 0;
;SV0076
    .data.w 0, 0
    .data.l _SV_RCLS51_C18
    .data.w 5, 7, 0, 2, 0, 7, 1, h'0080, 2, 0;
;SV0077
    .data.w 0, 0
    .data.l _SV_RCLS52_C18
    .data.w 5, 7, 0, 2, 0, 7, 2, h'0080, 2, 0;
;SV0078
    .data.w 0, 0
    .data.l _SV_RCLS61_C18
    .data.w 5, 8, 0, 2, 0, 9, 1, h'0080, 2, 0;
;SV0079
    .data.w 0, 0
    .data.l _SV_RCLS62_C18
    .data.w 5, 8, 0, 2, 0, 9, 2, h'0080, 2, 0;
;SV0080
    .data.w 0, 0
    .data.l _SV_RCLS71_C18
    .data.w 5, 9, 0, 2, 0, 11, 1, h'0080, 2, 0;
;SV0081
    .data.w 0, 0
    .data.l _SV_RCLS72_C18
    .data.w 5, 9, 0, 2, 0, 11, 2, h'0080, 2, 0;
;SV0082
    .data.w 0, 0
    .data.l _SV_RCLS81_C18
    .data.w 5, 10, 0, 2, 0, 13, 1, h'0080, 2, 0;
;SV0083
    .data.w 0, 0
    .data.l _SV_RCLS82_C18
    .data.w 5, 10, 0, 2, 0, 13, 2, h'0080, 2, 0;
;SV0084
    .data.w 0, 0
    .data.l _SV_EJEKK3_C5
    .data.w 5, 1, 0, 2, 0, 4, 1, h'0080, 2, 0;
;SV0085
    .data.w 0, 0
    .data.l _SV_EJETIM_C5
    .data.w 6, 2, 0, 2, 1, 4, 2, h'0080, 2, 0;
;SV0086
    .data.w 0, 0
    .data.l _SV_BRDIG_C1
    .data.w 96, 0, h'0100, 2, 0, 13, 1, h'0001, 0, 0;
;SV0087
    .data.w 0, 0
    .data.l _SV_BRTIME_C1
    .data.w 97, 68, 0, 2, 0, 14, 1, h'0001, 0, 0;
;SV0088
    .data.w 0, 0
    .data.l _PV_SEARCH_C15
    .data.w 47, 0, 0, 2, 0, 1, 1, 0, 0, 0;
;SV0089
    .data.w 0, 0
    .data.l _SV_PUR1SV_B4
    .data.w 0, 50, 0, 4, 0, 2, 1, h'0008, 2, 0;
;SV0090
    .data.w 0, 0
    .data.l _SV_PUR2SV_B41
    .data.w 0, 51, 0, 4, 0, 3, 1, h'0008, 2, 0;
;SV0091
    .data.w 0, 0
    .data.l _SV_ATUOS0_D9
    .data.w 20, 19, 0, 4, 2, 5, 1, h'0004, 2, 0;
;SV0092
    .data.w 0, 0
    .data.l _SV_ATUOS1_D9
    .data.w 20, 19, 0, 4, 2, 6, 1, h'0004, 2, 0;
;SV0093
    .data.w 0, 0
    .data.l _SV_OVERE1_A26
    .data.w 21, 128, 0, 2, 0, 4, 1, h'0014, 2, 0;
;SV0094
    .data.w 0, 0
    .data.l _SV_OVERE2_A26
    .data.w 22, 129, 0, 2, 0, 4, 2, h'0014, 2, 0;
;SV0095
    .data.w 0, 0
    .data.l _SV_OVERE3_A26
    .data.w 23, 130, 0, 2, 0, 4, 3, h'0014, 2, 0;
;SV0096
    .data.w 0, 0
    .data.l _SV_ATUOS2_D9
    .data.w 20, 19, 0, 4, 2, 8, 1, h'0004, 2, 0;
;SV0097
    .data.w 0, 0
    .data.l _SV_ROALM1_A26
    .data.w 24, 131, 0, 2, 0, 7, 1, h'0014, 2, 0;
;SV0098
    .data.w 0, 0
    .data.l _SV_ROALM2_A26
    .data.w 25, 132, 0, 2, 0, 7, 2, h'0014, 2, 0;
;SV0099
    .data.w 0, 0
    .data.l _SV_ROALM3_A26
    .data.w 26, 133, 0, 2, 0, 7, 3, h'0014, 2, 0;
;SV0100
    .data.w 0, 0
    .data.l _SV_HOASEI_SRV
    .data.w 72, 118, 0, 2, 0, 9, 1, h'0004, 2, 0;
;SV0101
    .data.w 0, 0
    .data.l _SV_SPDDAN_B1
    .data.w 73, 0, 0, 2, 2, 10, 1, h'0004, 2, 0;
;SV0102
    .data.w 0, 0
    .data.l _SV_DAIKA1_C27
    .data.w 42, 1, 0, 4, 2, 2, 1, 0, 2, 0;
;SV0103
    .data.w 0, 0
    .data.l _SV_DAIKA2_C27
    .data.w 43, 2, 0, 4, 2, 2, 2, 0, 2, 0;
;SV0104
    .data.w 0, 0
    .data.l _SV_DAITY1_C27
    .data.w 45, 3, 0, 2, 0, 5, 1, 0, 2, 0;
;SV0105
    .data.w 0, 0
    .data.l _SV_DAITY2_C27
    .data.w 46, 4, 0, 2, 0, 5, 2, 0, 2, 0;
;SV0106
    .data.w 0, 0
    .data.l _SV_EJESAT1_C4
    .data.w 53, 1, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0107
    .data.w 0, 0
    .data.l _SV_EJEKK1_C4
    .data.w 5, 1, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0108
    .data.w 0, 0
    .data.l _SV_EJESTP1_C4
    .data.w 53, 2, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0109
    .data.w 0, 0
    .data.l _SV_EJEKK2_C4
    .data.w 5, 2, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV0110
    .data.w 0, 0
    .data.l _SV_EJESAT1_C4A
    .data.w 53, 22, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV0111
    .data.w 0, 0
    .data.l _SV_EJEKK1_C4A
    .data.w 5, 22, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV0112
    .data.w 0, 0
    .data.l _SV_EJESTP1_C4A
    .data.w 53, 23, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV0113
    .data.w 0, 0
    .data.l _SV_EJEKK2_C4A
    .data.w 5, 23, 0, 2, 0, 2, 4, h'0020, 2, 0;
;SV0114
    .data.w 0, 0
    .data.l _SV_EJESAT1_C4B
    .data.w 53, 24, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0115
    .data.w 0, 0
    .data.l _SV_EJEKK1_C4B
    .data.w 5, 24, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0116
    .data.w 0, 0
    .data.l _SV_EJESTP1_C4B
    .data.w 53, 25, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0117
    .data.w 0, 0
    .data.l _SV_EJEKK2_C4B
    .data.w 5, 25, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV0118
    .data.w 0, 0
    .data.l _SV_AUTSTA_C41
    .data.w 53, 26, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV0119
    .data.w 0, 0
    .data.l _SV_AUTKK1_C41
    .data.w 5, 26, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV0120
    .data.w 0, 0
    .data.l _SV_AUTSTP_C41
    .data.w 53, 27, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV0121
    .data.w 0, 0
    .data.l _SV_AUTKK2_C41
    .data.w 5, 27, 0, 2, 0, 4, 4, h'0020, 2, 0;
;SV0122
    .data.w 0, 0
    .data.l _SV_AUTSTA_C41A
    .data.w 53, 28, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0123
    .data.w 0, 0
    .data.l _SV_AUTKK1_C41A
    .data.w 5, 28, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0124
    .data.w 0, 0
    .data.l _SV_AUTSTP_C41A
    .data.w 53, 29, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0125
    .data.w 0, 0
    .data.l _SV_AUTKK2_C41A
    .data.w 5, 29, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV0126
    .data.w 0, 0
    .data.l _SV_AUTSTA_C41B
    .data.w 53, 30, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV0127
    .data.w 0, 0
    .data.l _SV_AUTKK1_C41B
    .data.w 5, 30, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV0128
    .data.w 0, 0
    .data.l _SV_AUTSTP_C41B
    .data.w 53, 31, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV0129
    .data.w 0, 0
    .data.l _SV_AUTKK2_C41B
    .data.w 5, 31, 0, 2, 0, 6, 4, h'0020, 2, 0;
;SV0130
    .data.w 0, 0
    .data.l _SV_EJESTA_C5
    .data.w 53, 1, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0131
    .data.w 0, 0
    .data.l _SV_EJEKK3_C5
    .data.w 5, 1, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0132
    .data.w 0, 0
    .data.l _SV_EJESTP_C5
    .data.w 53, 2, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0133
    .data.w 0, 0
    .data.l _SV_EJETIM_C5
    .data.w 6, 2, 0, 2, 1, 1, 4, h'0020, 2, 0;
;SV0134
    .data.w 0, 0
    .data.l _SV_EJESTA_C5A
    .data.w 53, 22, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV0135
    .data.w 0, 0
    .data.l _SV_EJEKK3_C5A
    .data.w 5, 22, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV0136
    .data.w 0, 0
    .data.l _SV_EJESTP_C5A
    .data.w 53, 23, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV0137
    .data.w 0, 0
    .data.l _SV_EJETIM_C5A
    .data.w 6, 23, 0, 2, 1, 2, 4, h'0020, 2, 0;
;SV0138
    .data.w 0, 0
    .data.l _SV_EJESTA_C5B
    .data.w 53, 24, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0139
    .data.w 0, 0
    .data.l _SV_EJEKK3_C5B
    .data.w 5, 24, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0140
    .data.w 0, 0
    .data.l _SV_EJESTP_C5B
    .data.w 53, 25, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0141
    .data.w 0, 0
    .data.l _SV_EJETIM_C5B
    .data.w 6, 25, 0, 2, 1, 3, 4, h'0020, 2, 0;
;SV0142
    .data.w 0, 0
    .data.l _SV_AUTSTA_C51
    .data.w 53, 26, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV0143
    .data.w 0, 0
    .data.l _SV_AUTKK3_C51
    .data.w 5, 26, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV0144
    .data.w 0, 0
    .data.l _SV_AUTSTP_C51
    .data.w 53, 27, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV0145
    .data.w 0, 0
    .data.l _SV_AUTTIM_C51
    .data.w 6, 27, 0, 2, 1, 4, 4, h'0020, 2, 0;
;SV0146
    .data.w 0, 0
    .data.l _SV_AUTSTA_C51A
    .data.w 53, 28, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0147
    .data.w 0, 0
    .data.l _SV_AUTKK3_C51A
    .data.w 5, 28, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0148
    .data.w 0, 0
    .data.l _SV_AUTSTP_C51A
    .data.w 53, 29, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0149
    .data.w 0, 0
    .data.l _SV_AUTTIM_C51A
    .data.w 6, 29, 0, 2, 1, 5, 4, h'0020, 2, 0;
;SV0150
    .data.w 0, 0
    .data.l _SV_AUTSTA_C51B
    .data.w 53, 30, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV0151
    .data.w 0, 0
    .data.l _SV_AUTKK3_C51B
    .data.w 5, 30, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV0152
    .data.w 0, 0
    .data.l _SV_AUTSTP_C51B
    .data.w 53, 31, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV0153
    .data.w 0, 0
    .data.l _SV_AUTTIM_C51B
    .data.w 6, 31, 0, 2, 1, 6, 4, h'0020, 2, 0;
;SV0154
    .data.w 0, 0
    .data.l _SV_MISSTA1_C9
    .data.w 53, 46, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0155
    .data.w 0, 0
    .data.l _SV_MISSK1_C9
    .data.w 5, 46, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0156
    .data.w 0, 0
    .data.l _SV_MISSTP1_C9
    .data.w 53, 46, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0157
    .data.w 0, 0
    .data.l _SV_MISSK2_C9
    .data.w 5, 46, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV0158
    .data.w 0, 0
    .data.l _SV_MISSTA2_C9
    .data.w 53, 47, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0159
    .data.w 0, 0
    .data.l _SV_MISSK3_C9
    .data.w 5, 47, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0160
    .data.w 0, 0
    .data.l _SV_MISSTP2_C9
    .data.w 53, 47, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0161
    .data.w 0, 0
    .data.l _SV_MISSK4_C9
    .data.w 5, 47, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV0162
    .data.w 0, 0
    .data.l _SV_MISSTA3_C9
    .data.w 53, 48, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0163
    .data.w 0, 0
    .data.l _SV_MISSK5_C9
    .data.w 5, 48, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0164
    .data.w 0, 0
    .data.l _SV_MISSTP3_C9
    .data.w 53, 48, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0165
    .data.w 0, 0
    .data.l _SV_MISSK6_C9
    .data.w 5, 48, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV0166
    .data.w 0, 0
    .data.l _SV_MISSTA4_C9
    .data.w 53, 49, 0, 2, 0, 7, 1, h'0020, 2, 0;
;SV0167
    .data.w 0, 0
    .data.l _SV_MISSK7_C9
    .data.w 5, 49, 0, 2, 0, 7, 2, h'0020, 2, 0;
;SV0168
    .data.w 0, 0
    .data.l _SV_MISSTP4_C9
    .data.w 53, 49, 0, 2, 0, 7, 3, h'0020, 2, 0;
;SV0169
    .data.w 0, 0
    .data.l _SV_MISSK8_C9
    .data.w 5, 49, 0, 2, 0, 7, 4, h'0020, 2, 0;
;SV0170
    .data.w 0, 0
    .data.l _SV_RCLSTA11_C17
    .data.w 53, 3, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0171
    .data.w 0, 0
    .data.l _SV_RCLS11_C17
    .data.w 5, 3, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0172
    .data.w 0, 0
    .data.l _SV_RCLSTP12_C17
    .data.w 53, 3, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0173
    .data.w 0, 0
    .data.l _SV_RCLS12_C17
    .data.w 5, 3, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV0174
    .data.w 0, 0
    .data.l _SV_RCLSTA21_C17
    .data.w 53, 4, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV0175
    .data.w 0, 0
    .data.l _SV_RCLS21_C17
    .data.w 5, 4, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV0176
    .data.w 0, 0
    .data.l _SV_RCLSTP22_C17
    .data.w 53, 4, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV0177
    .data.w 0, 0
    .data.l _SV_RCLS22_C17
    .data.w 5, 4, 0, 2, 0, 2, 4, h'0020, 2, 0;
;SV0178
    .data.w 0, 0
    .data.l _SV_RCLSTA31_C17
    .data.w 53, 5, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0179
    .data.w 0, 0
    .data.l _SV_RCLS31_C17
    .data.w 5, 5, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0180
    .data.w 0, 0
    .data.l _SV_RCLSTP32_C17
    .data.w 53, 5, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0181
    .data.w 0, 0
    .data.l _SV_RCLS32_C17
    .data.w 5, 5, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV0182
    .data.w 0, 0
    .data.l _SV_RCLSTA41_C17
    .data.w 53, 6, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV0183
    .data.w 0, 0
    .data.l _SV_RCLS41_C17
    .data.w 5, 6, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV0184
    .data.w 0, 0
    .data.l _SV_RCLSTP42_C17
    .data.w 53, 6, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV0185
    .data.w 0, 0
    .data.l _SV_RCLS42_C17
    .data.w 5, 6, 0, 2, 0, 4, 4, h'0020, 2, 0;
;SV0186
    .data.w 0, 0
    .data.l _SV_RCLSTA51_C18
    .data.w 53, 7, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0187
    .data.w 0, 0
    .data.l _SV_RCLS51_C18
    .data.w 5, 7, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0188
    .data.w 0, 0
    .data.l _SV_RCLSTP52_C18
    .data.w 53, 7, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0189
    .data.w 0, 0
    .data.l _SV_RCLS52_C18
    .data.w 5, 7, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV0190
    .data.w 0, 0
    .data.l _SV_RCLSTA61_C18
    .data.w 53, 8, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV0191
    .data.w 0, 0
    .data.l _SV_RCLS61_C18
    .data.w 5, 8, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV0192
    .data.w 0, 0
    .data.l _SV_RCLSTP62_C18
    .data.w 53, 8, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV0193
    .data.w 0, 0
    .data.l _SV_RCLS62_C18
    .data.w 5, 8, 0, 2, 0, 6, 4, h'0020, 2, 0;
;SV0194
    .data.w 0, 0
    .data.l _SV_RCLSTA71_C18
    .data.w 53, 9, 0, 2, 0, 7, 1, h'0020, 2, 0;
;SV0195
    .data.w 0, 0
    .data.l _SV_RCLS71_C18
    .data.w 5, 9, 0, 2, 0, 7, 2, h'0020, 2, 0;
;SV0196
    .data.w 0, 0
    .data.l _SV_RCLSTP72_C18
    .data.w 53, 9, 0, 2, 0, 7, 3, h'0020, 2, 0;
;SV0197
    .data.w 0, 0
    .data.l _SV_RCLS72_C18
    .data.w 5, 9, 0, 2, 0, 7, 4, h'0020, 2, 0;
;SV0198
    .data.w 0, 0
    .data.l _SV_RCLSTA81_C18
    .data.w 53, 10, 0, 2, 0, 8, 1, h'0020, 2, 0;
;SV0199
    .data.w 0, 0
    .data.l _SV_RCLS81_C18
    .data.w 5, 10, 0, 2, 0, 8, 2, h'0020, 2, 0;
;SV0200
    .data.w 0, 0
    .data.l _SV_RCLSTP82_C18
    .data.w 53, 10, 0, 2, 0, 8, 3, h'0020, 2, 0;
;SV0201
    .data.w 0, 0
    .data.l _SV_RCLS82_C18
    .data.w 5, 10, 0, 2, 0, 8, 4, h'0020, 2, 0;
;SV0202
    .data.w 0, 0
    .data.l _SV_RCLSTA11_C19
    .data.w 53, 11, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0203
    .data.w 0, 0
    .data.l _SV_RCLS11_C19
    .data.w 5, 11, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0204
    .data.w 0, 0
    .data.l _SV_RCLSTP12_C19
    .data.w 53, 11, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0205
    .data.w 0, 0
    .data.l _SV_RCLS12_C19
    .data.w 5, 11, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV0206
    .data.w 0, 0
    .data.l _SV_RCLSTA21_C19
    .data.w 53, 12, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV0207
    .data.w 0, 0
    .data.l _SV_RCLS21_C19
    .data.w 5, 12, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV0208
    .data.w 0, 0
    .data.l _SV_RCLSTA22_C19
    .data.w 53, 12, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV0209
    .data.w 0, 0
    .data.l _SV_RCLS22_C19
    .data.w 5, 12, 0, 2, 0, 2, 4, h'0020, 2, 0;
;SV0210
    .data.w 0, 0
    .data.l _SV_RCLSTA31_C19
    .data.w 53, 13, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0211
    .data.w 0, 0
    .data.l _SV_RCLS31_C19
    .data.w 5, 13, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0212
    .data.w 0, 0
    .data.l _SV_RCLSTA32_C19
    .data.w 53, 13, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0213
    .data.w 0, 0
    .data.l _SV_RCLS32_C19
    .data.w 5, 13, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV0214
    .data.w 0, 0
    .data.l _SV_RCLSTA41_C19
    .data.w 53, 14, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV0215
    .data.w 0, 0
    .data.l _SV_RCLS41_C19
    .data.w 5, 14, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV0216
    .data.w 0, 0
    .data.l _SV_RCLSTA42_C19
    .data.w 53, 14, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV0217
    .data.w 0, 0
    .data.l _SV_RCLS42_C19
    .data.w 5, 14, 0, 2, 0, 4, 4, h'0020, 2, 0;
;SV0218
    .data.w 0, 0
    .data.l _SV_RCLSTA51_C19
    .data.w 53, 15, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0219
    .data.w 0, 0
    .data.l _SV_RCLS51_C20
    .data.w 5, 15, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0220
    .data.w 0, 0
    .data.l _SV_RCLSTA52_C20
    .data.w 53, 15, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0221
    .data.w 0, 0
    .data.l _SV_RCLS52_C20
    .data.w 5, 15, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV0222
    .data.w 0, 0
    .data.l _SV_RCLSTA61_C20
    .data.w 53, 16, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV0223
    .data.w 0, 0
    .data.l _SV_RCLS61_C20
    .data.w 5, 16, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV0224
    .data.w 0, 0
    .data.l _SV_RCLSTA62_C20
    .data.w 53, 16, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV0225
    .data.w 0, 0
    .data.l _SV_RCLS62_C20
    .data.w 5, 16, 0, 2, 0, 6, 4, h'0020, 2, 0;
;SV0226
    .data.w 0, 0
    .data.l _SV_RCLSTA71_C20
    .data.w 53, 17, 0, 2, 0, 7, 1, h'0020, 2, 0;
;SV0227
    .data.w 0, 0
    .data.l _SV_RCLS71_C20
    .data.w 5, 17, 0, 2, 0, 7, 2, h'0020, 2, 0;
;SV0228
    .data.w 0, 0
    .data.l _SV_RCLSTA72_C20
    .data.w 53, 17, 0, 2, 0, 7, 3, h'0020, 2, 0;
;SV0229
    .data.w 0, 0
    .data.l _SV_RCLS72_C20
    .data.w 5, 17, 0, 2, 0, 7, 4, h'0020, 2, 0;
;SV0230
    .data.w 0, 0
    .data.l _SV_RCLSTA81_C20
    .data.w 53, 18, 0, 2, 0, 8, 1, h'0020, 2, 0;
;SV0231
    .data.w 0, 0
    .data.l _SV_RCLS81_C20
    .data.w 5, 18, 0, 2, 0, 8, 2, h'0020, 2, 0;
;SV0232
    .data.w 0, 0
    .data.l _SV_RCLSTA82_C20
    .data.w 53, 18, 0, 2, 0, 8, 3, h'0020, 2, 0;
;SV0233
    .data.w 0, 0
    .data.l _SV_RCLS82_C20
    .data.w 5, 18, 0, 2, 0, 8, 4, h'0020, 2, 0;
;SV0234
    .data.w 0, 0
    .data.l _SV_DANSUU_SRV
    .data.w 51, 0, 0, 2, 0, 2, 1, h'0004, 2, 0;
;SV0235
    .data.w 0, 0
    .data.l _SV_TAIKIKAKU_SRV
    .data.w 54, 85, h'0100, 2, 0, 3, 1, h'0004, 2, 0;
;SV0236
    .data.w 0, 0
    .data.l _SV_TAIKIPOS_SRV
    .data.w 56, 91, h'0400, 4, 2, 4, 1, h'0004, 2, 0;
;SV0237
    .data.w 0, 0
    .data.l _SV_DAIHAITO_SRV
    .data.w 80, 117, h'1000, 4, 2, 5, 1, h'0004, 2, 0;
;SV0238
    .data.w 0, 0
    .data.l _SV_HOASEI_SRV
    .data.w 72, 118, 0, 2, 0, 6, 1, h'0004, 2, 0;
;SV0239
    .data.w 0, 0
    .data.l _SV_1DANDEG_SRV
    .data.w 74, 86, h'0100, 2, 0, 7, 1, h'0004, 2, 0;
;SV0240
    .data.w 0, 0
    .data.l _SV_1DANPOS_SRV
    .data.w 75, 92, h'0400, 4, 2, 8, 1, h'0004, 2, 0;
;SV0241
    .data.w 0, 0
    .data.l _SV_1DANSPD_SRV
    .data.w 70, 97, 0, 2, 1, 9, 1, h'0004, 2, 0;
;SV0242
    .data.w 0, 0
    .data.l _SV_1DANTIM_SRV
    .data.w 0, 97, 0, 2, 2, 10, 1, h'0004, 2, 1;
;SV0243
    .data.w 0, 0
    .data.l _SV_2DANDEG_SRV
    .data.w 74, 87, h'0100, 2, 0, 11, 1, h'0004, 2, 0;
;SV0244
    .data.w 0, 0
    .data.l _SV_2DANPOS_SRV
    .data.w 75, 93, h'0400, 4, 2, 12, 1, h'0004, 2, 0;
;SV0245
    .data.w 0, 0
    .data.l _SV_2DANSPD_SRV
    .data.w 70, 98, 0, 2, 1, 13, 1, h'0004, 2, 0;
;SV0246
    .data.w 0, 0
    .data.l _SV_2DANTIM_SRV
    .data.w 0, 98, 0, 2, 2, 14, 1, h'0004, 2, 1;
;SV0247
    .data.w 0, 0
    .data.l _SV_3DANDEG_SRV
    .data.w 74, 88, h'0100, 2, 0, 15, 1, h'0004, 2, 0;
;SV0248
    .data.w 0, 0
    .data.l _SV_3DANPOS_SRV
    .data.w 75, 94, h'0400, 4, 2, 16, 1, h'0004, 2, 0;
;SV0249
    .data.w 0, 0
    .data.l _SV_3DANSPD_SRV
    .data.w 70, 99, 0, 2, 1, 17, 1, h'0004, 2, 0;
;SV0250
    .data.w 0, 0
    .data.l _SV_3DANTIM_SRV
    .data.w 81, 99, 0, 2, 2, 18, 1, h'0004, 2, 1;
;SV0251
    .data.w 0, 0
    .data.l _SV_4DANDEG_SRV
    .data.w 74, 89, h'0100, 2, 0, 19, 1, h'0004, 2, 0;
;SV0252
    .data.w 0, 0
    .data.l _SV_4DANPOS_SRV
    .data.w 75, 95, h'0400, 4, 2, 20, 1, h'0004, 2, 0;
;SV0253
    .data.w 0, 0
    .data.l _SV_4DANSPD_SRV
    .data.w 70, 100, 0, 2, 1, 21, 1, h'0004, 2, 0;
;SV0254
    .data.w 0, 0
    .data.l _SV_4DANTIM_SRV
    .data.w 0, 100, 0, 2, 2, 22, 1, h'0004, 2, 1;
;SV0255
    .data.w 0, 0
    .data.l _SV_5DANDEG_SRV
    .data.w 74, 90, h'0100, 2, 0, 23, 1, h'0004, 2, 0;
;SV0256
    .data.w 0, 0
    .data.l _SV_5DANPOS_SRV
    .data.w 75, 96, h'0400, 4, 2, 24, 1, h'0004, 2, 0;
;SV0257
    .data.w 0, 0
    .data.l _SV_5DANSPD_SRV
    .data.w 70, 101, 0, 2, 1, 25, 1, h'0004, 2, 0;
;SV0258
    .data.w 0, 0
    .data.l _SV_5DANTIM_SRV
    .data.w 0, 101, 0, 2, 2, 26, 1, h'0004, 2, 1;
;SV0259
    .data.w 0, 0
    .data.l _SV_TAIKSPD_SRV
    .data.w 70, 102, 0, 2, 1, 28, 1, h'0004, 2, 0;
;SV0260
    .data.w 0, 0
    .data.l _SV_TAIKTIM_SRV
    .data.w 0, 102, 0, 2, 2, 29, 1, h'0004, 2, 1;
;SV0261
    .data.w 0, 0
    .data.l _SV_MOKKAN_SRV
    .data.w 148, 143, h'0400, 2, 2, 30, 1, h'0004, 2, 0;
;SV0262
    .data.w 0, 0
    .data.l _SV_DANSUU_SRV
    .data.w 51, 0, 0, 2, 0, 2, 1, h'0004, 0, 0;
;SV0263
    .data.w 0, 0
    .data.l _SV_TAIKIKAKU_SRV
    .data.w 54, 85, h'0100, 2, 0, 3, 1, h'0004, 0, 0;
;SV0264
    .data.w 0, 0
    .data.l _SV_TAIKIPOS_SRV
    .data.w 56, 91, h'0400, 4, 2, 4, 1, h'0004, 0, 0;
;SV0265
    .data.w 0, 0
    .data.l _SV_DAIHAITO_SRV
    .data.w 80, 117, h'1000, 4, 2, 5, 1, h'0004, 0, 0;
;SV0266
    .data.w 0, 0
    .data.l _SV_HOASEI_SRV
    .data.w 72, 118, 0, 2, 0, 6, 1, h'0004, 0, 0;
;SV0267
    .data.w 0, 0
    .data.l _SV_MOKKAN_SRV
    .data.w 148, 19, h'0400, 2, 2, 7, 1, h'0004, 0, 0;
;SV0268
    .data.w 0, 0
    .data.l _SV_DANSUU_SRV
    .data.w 51, 0, 0, 2, 0, 2, 1, h'0004, 2, 0;
;SV0269
    .data.w 0, 0
    .data.l _SV_TAIKIKAKU_SRV
    .data.w 54, 85, h'0100, 2, 0, 3, 1, h'0004, 2, 0;
;SV0270
    .data.w 0, 0
    .data.l _SV_TAIKIPOS_SRV
    .data.w 56, 91, h'0400, 4, 2, 4, 1, h'0004, 2, 0;
;SV0271
    .data.w 0, 0
    .data.l _SV_DAIHAITO_SRV
    .data.w 80, 117, h'1000, 4, 2, 5, 1, h'0004, 2, 0;
;SV0272
    .data.w 0, 0
    .data.l _SV_HOASEI_SRV
    .data.w 72, 118, 0, 2, 0, 6, 1, h'0004, 2, 0;
;SV0273
    .data.w 0, 0
    .data.l _SV_6DANDEG_SRV
    .data.w 74, 107, h'0100, 2, 0, 7, 1, h'0004, 2, 0;
;SV0274
    .data.w 0, 0
    .data.l _SV_6DANPOS_SRV
    .data.w 75, 112, h'0400, 4, 2, 8, 1, h'0004, 2, 0;
;SV0275
    .data.w 0, 0
    .data.l _SV_6DANSPD_SRV
    .data.w 70, 97, 0, 2, 1, 9, 1, h'0004, 2, 0;
;SV0276
    .data.w 0, 0
    .data.l _SV_6DANTIM_SRV
    .data.w 0, 97, 0, 2, 2, 10, 1, h'0004, 2, 1;
;SV0277
    .data.w 0, 0
    .data.l _SV_7DANDEG_SRV
    .data.w 74, 108, h'0100, 2, 0, 11, 1, h'0004, 2, 0;
;SV0278
    .data.w 0, 0
    .data.l _SV_7DANPOS_SRV
    .data.w 75, 113, h'0400, 4, 2, 12, 1, h'0004, 2, 0;
;SV0279
    .data.w 0, 0
    .data.l _SV_7DANSPD_SRV
    .data.w 70, 98, 0, 2, 1, 13, 1, h'0004, 2, 0;
;SV0280
    .data.w 0, 0
    .data.l _SV_7DANTIM_SRV
    .data.w 0, 98, 0, 2, 2, 14, 1, h'0004, 2, 1;
;SV0281
    .data.w 0, 0
    .data.l _SV_8DANDEG_SRV
    .data.w 74, 109, h'0100, 2, 0, 15, 1, h'0004, 2, 0;
;SV0282
    .data.w 0, 0
    .data.l _SV_8DANPOS_SRV
    .data.w 75, 114, h'0400, 4, 2, 16, 1, h'0004, 2, 0;
;SV0283
    .data.w 0, 0
    .data.l _SV_8DANSPD_SRV
    .data.w 70, 99, 0, 2, 1, 17, 1, h'0004, 2, 0;
;SV0284
    .data.w 0, 0
    .data.l _SV_8DANTIM_SRV
    .data.w 0, 99, 0, 2, 2, 18, 1, h'0004, 2, 1;
;SV0285
    .data.w 0, 0
    .data.l _SV_9DANDEG_SRV
    .data.w 74, 110, h'0100, 2, 0, 19, 1, h'0004, 2, 0;
;SV0286
    .data.w 0, 0
    .data.l _SV_9DANPOS_SRV
    .data.w 75, 115, h'0400, 4, 2, 20, 1, h'0004, 2, 0;
;SV0287
    .data.w 0, 0
    .data.l _SV_9DANSPD_SRV
    .data.w 70, 100, 0, 2, 1, 21, 1, h'0004, 2, 0;
;SV0288
    .data.w 0, 0
    .data.l _SV_9DANTIM_SRV
    .data.w 0, 100, 0, 2, 2, 22, 1, h'0004, 2, 1;
;SV0289
    .data.w 0, 0
    .data.l _SV_10DANDEG_SRV
    .data.w 74, 111, h'0100, 2, 0, 23, 1, h'0004, 2, 0;
;SV0290
    .data.w 0, 0
    .data.l _SV_10DANPOS_SRV
    .data.w 75, 116, h'0400, 4, 2, 24, 1, h'0004, 2, 0;
;SV0291
    .data.w 0, 0
    .data.l _SV_10DANSPD_SRV
    .data.w 70, 101, 0, 2, 1, 25, 1, h'0004, 2, 0;
;SV0292
    .data.w 0, 0
    .data.l _SV_10DANTIM_SRV
    .data.w 0, 101, 0, 2, 2, 26, 1, h'0004, 2, 1;
;SV0293
    .data.w 0, 0
    .data.l _SV_TAIKSPD_SRV
    .data.w 70, 102, 0, 2, 1, 28, 1, h'0004, 2, 0;
;SV0294
    .data.w 0, 0
    .data.l _SV_TAIKTIM_SRV
    .data.w 0, 102, 0, 2, 2, 29, 1, h'0004, 2, 1;
;SV0295
    .data.w 0, 0
    .data.l _SV_MOKKAN_SRV
    .data.w 148, 19, h'0400, 2, 2, 30, 1, h'0004, 2, 0;
;SV0296
    .data.w 0, 0
    .data.l _SV_RNZTIM_A12
    .data.w 0, 0, 0, 2, 0, 16, 1, h'0001, 0, 0;
;SV0297
    .data.w 0, 0
    .data.l _SV_RNZRPM_A12
    .data.w 0, 0, 0, 2, 0, 18, 1, h'0001, 0, 0;
;SV0298
    .data.w 0, 0
    .data.l _SV_HOSTIM_A12
    .data.w 0, 0, 0, 2, 0, 2, 1, h'0001, 0, 0;
;SV0299
    .data.w 0, 0
    .data.l _SV_TAIKI1_A12
    .data.w 76, 0, h'0100, 2, 0, 4, 1, h'0005, 0, 0;
;SV0300
    .data.w 0, 0
    .data.l _SV_TAIKI2_A12
    .data.w 77, 0, h'0100, 2, 0, 6, 1, h'0005, 0, 0;
;SV0301
    .data.w 0, 0
    .data.l _SV_TAIKI3_A12
    .data.w 78, 0, h'0100, 2, 0, 8, 1, h'0005, 0, 0;
;SV0302
    .data.w 0, 0
    .data.l _SV_PSDIMD_A1
    .data.w 0, 0, 0, 2, 0, 20, 1, h'0001, 0, 0;
;SV0303
    .data.w 0, 0
    .data.l _SV_RNADIR_SEL1
    .data.w 60, 0, 0, 2, 0, 1, 1, h'0001, 0, 0;
;SV0304
    .data.w 0, 0
    .data.l _SV_INCDIR_SEL1
    .data.w 60, 0, 0, 2, 0, 2, 1, h'0001, 0, 0;
;SV0305
    .data.w 0, 0
    .data.l _SV_INCPLS_1REV
    .data.w 61, 0, 0, 2, 0, 3, 1, h'0001, 0, 0;
;SV0306
    .data.w 0, 0
    .data.l _SV_INCPLS_HOSN
    .data.w 62, 0, 0, 2, 0, 4, 1, h'0001, 0, 0;
;SV0307
    .data.w 0, 0
    .data.l _SV_INCPLS_HOSM
    .data.w 62, 0, 0, 2, 0, 5, 1, h'0001, 0, 0;
;SV0308
    .data.w 0, 0
    .data.l _SV_MOTRPM_MAXM
    .data.w 62, 0, 0, 2, 1, 6, 1, h'0001, 0, 0;
;SV0309
    .data.w 0, 0
    .data.l _SV_MOTMAX_FREQ
    .data.w 63, 0, 0, 4, 0, 7, 1, h'0001, 0, 0;
;SV0310
    .data.w 0, 0
    .data.l _SV_RNAORG_POS1
    .data.w 0, 0, 0, 4, 3, 8, 1, h'0100, 0, 0;
;SV0311
    .data.w 0, 0
    .data.l _SV_RNAPOS_MAXP
    .data.w 120, 0, 0, 4, 3, 10, 1, h'0001, 0, 0;
;SV0312
    .data.w 0, 0
    .data.l _SV_RNAPOS_MINP
    .data.w 119, 0, 0, 4, 3, 11, 1, h'0001, 0, 0;
;SV0313
    .data.w 0, 0
    .data.l _SV_DNDINC_SPD1
    .data.w 65, 0, 0, 2, 2, 1, 1, h'0001, 0, 0;
;SV0314
    .data.w 0, 0
    .data.l _SV_UPAREA_SPD1
    .data.w 66, 0, 0, 2, 2, 2, 1, h'0001, 0, 0;
;SV0315
    .data.w 0, 0
    .data.l _SV_STDINC_SPD1
    .data.w 66, 0, 0, 2, 2, 3, 1, h'0001, 0, 0;
;SV0316
    .data.w 0, 0
    .data.l _SV_REVDAT_SPD1
    .data.w 66, 0, 0, 2, 2, 4, 1, h'0001, 0, 0;
;SV0317
    .data.w 0, 0
    .data.l _SV_REVDAT_SPD2
    .data.w 66, 0, 0, 2, 0, 5, 1, h'0001, 0, 0;
;SV0318
    .data.w 0, 0
    .data.l _SV_REVDAT_SPD3
    .data.w 66, 0, 0, 2, 0, 6, 1, h'0001, 0, 0;
;SV0319
    .data.w 0, 0
    .data.l _SV_TEPDAT_SPD1
    .data.w 66, 0, 0, 2, 0, 7, 1, h'0001, 0, 0;
;SV0320
    .data.w 0, 0
    .data.l _SV_TEPLAT_DAT1
    .data.w 66, 0, 0, 2, 0, 8, 1, h'0001, 0, 0;
;SV0321
    .data.w 0, 0
    .data.l _SV_TEPLAT_DAT2
    .data.w 66, 0, 0, 2, 0, 9, 1, h'0001, 0, 0;
;SV0322
    .data.w 0, 0
    .data.l _SV_RCLSA1_A17
    .data.w 5, 0, 0, 2, 0, 1, 1, h'0020, 0, 0;
;SV0323
    .data.w 0, 0
    .data.l _SV_RCLSA2_A17
    .data.w 5, 0, 0, 2, 0, 1, 2, h'0020, 0, 0;
;SV0324
    .data.w 0, 0
    .data.l _SV_RCLSB1_A17
    .data.w 5, 0, 0, 2, 0, 2, 1, h'0020, 0, 0;
;SV0325
    .data.w 0, 0
    .data.l _SV_RCLSB2_A17
    .data.w 5, 0, 0, 2, 0, 2, 2, h'0020, 0, 0;
;SV0326
    .data.w 0, 0
    .data.l _SV_RCLSC1_A17
    .data.w 5, 0, 0, 2, 0, 3, 1, h'0020, 0, 0;
;SV0327
    .data.w 0, 0
    .data.l _SV_RCLSC2_A17
    .data.w 5, 0, 0, 2, 0, 3, 2, h'0020, 0, 0;
;SV0328
    .data.w 0, 0
    .data.l _SV_RCLSD1_A17
    .data.w 5, 0, 0, 2, 0, 4, 1, h'0020, 0, 0;
;SV0329
    .data.w 0, 0
    .data.l _SV_RCLSD2_A17
    .data.w 5, 0, 0, 2, 0, 4, 2, h'0020, 0, 0;
;SV0330
    .data.w 0, 0
    .data.l _SV_RCLSE1_A17
    .data.w 5, 0, 0, 2, 0, 5, 1, h'0020, 0, 0;
;SV0331
    .data.w 0, 0
    .data.l _SV_RCLSE2_A17
    .data.w 5, 0, 0, 2, 0, 5, 2, h'0020, 0, 0;
;SV0332
    .data.w 0, 0
    .data.l _SV_RCLSF1_A18
    .data.w 5, 0, 0, 2, 0, 6, 1, h'0020, 0, 0;
;SV0333
    .data.w 0, 0
    .data.l _SV_RCLSF2_A18
    .data.w 5, 0, 0, 2, 0, 6, 2, h'0020, 0, 0;
;SV0334
    .data.w 0, 0
    .data.l _SV_RCLSG1_A18
    .data.w 5, 0, 0, 2, 0, 7, 1, h'0020, 0, 0;
;SV0335
    .data.w 0, 0
    .data.l _SV_RCLSG2_A18
    .data.w 5, 0, 0, 2, 0, 7, 2, h'0020, 0, 0;
;SV0336
    .data.w 0, 0
    .data.l _SV_RCLSH1_A18
    .data.w 5, 0, 0, 2, 0, 8, 1, h'0020, 0, 0;
;SV0337
    .data.w 0, 0
    .data.l _SV_RCLSH2_A18
    .data.w 5, 0, 0, 2, 0, 8, 2, h'0020, 0, 0;
;SV0338
    .data.w 0, 0
    .data.l _SV_COUNT1_A1
    .data.w 29, 0, 0, 2, 0, 1, 1, h'0008, 0, 0;
;SV0339
    .data.w 0, 0
    .data.l _SV_COUNT2_A1
    .data.w 29, 0, 0, 2, 0, 2, 1, h'0008, 0, 0;
;SV0340
    .data.w 0, 0
    .data.l _SV_COUNT3_A1
    .data.w 29, 0, 0, 2, 0, 3, 1, h'0008, 0, 0;
;SV0341
    .data.w 0, 0
    .data.l _SV_TIMER1_A1
    .data.w 29, 0, 0, 2, 2, 4, 1, h'0008, 0, 0;
;SV0342
    .data.w 0, 0
    .data.l _SV_TIMER2_A1
    .data.w 29, 0, 0, 2, 2, 5, 1, h'0008, 0, 0;
;SV0343
    .data.w 0, 0
    .data.l _SV_TIMER3_A1
    .data.w 29, 0, 0, 2, 2, 6, 1, h'0008, 0, 0;
;SV0344
    .data.w 0, 0
    .data.l _SV_MAXHIZ_A24
    .data.w 10, 0, 0, 2, 0, 3, 1, h'010, 0, 0;
;SV0345
    .data.w 0, 0
    .data.l _SV_MAXHI3_A24
    .data.w 10, 0, 0, 2, 0, 3, 2, h'010, 0, 0;
;SV0346
    .data.w 0, 0
    .data.l _SV_MAXKAJ_A24
    .data.w 0, 53, 0, 2, 0, 4, 1, h'010, 0, 0;
;SV0347
    .data.w 0, 0
    .data.l _SV_MAXKA2_A24
    .data.w 0, 53, 0, 2, 0, 4, 2, h'018, 0, 0;
;SV0348
    .data.w 0, 0
    .data.l _SV_MAXKA3_A24
    .data.w 0, 53, 0, 2, 0, 4, 3, h'010, 0, 0;
;SV0349
    .data.w 0, 0
    .data.l _SV_KOUKAJ_A24
    .data.w 35, 53, 0, 2, 0, 5, 1, h'010, 0, 0;
;SV0350
    .data.w 0, 0
    .data.l _SV_KOUKA2_A24
    .data.w 36, 53, 0, 2, 0, 5, 2, h'010, 0, 0;
;SV0351
    .data.w 0, 0
    .data.l _SV_KOUKA3_A24
    .data.w 37, 53, 0, 2, 0, 5, 3, h'010, 0, 0;
;SV0352
    .data.w 0, 0
    .data.l _SV_KOUSEI_A24
    .data.w 0, 0, 0, 2, 0, 6, 1, h'010, 0, 0;
;SV0353
    .data.w 0, 0
    .data.l _SV_APARAD_A24
    .data.w 0, 0, 0, 2, 0, 7, 1, h'010, 0, 0;
;SV0354
    .data.w 0, 0
    .data.l _SV_GENITI_A21
    .data.w 18, 0, 0, 4, 0, 2, 1, h'0054, 0, 0;
;SV0355
    .data.w 0, 0
    .data.l _SV_KANDO_A21
    .data.w 19, 0, 0, 4, 0, 3, 1, h'0054, 0, 0;
;SV0356
    .data.w 0, 0
    .data.l _SV_DNSTOP_A21
    .data.w 6, 0, 0, 2, 0, 4, 1, h'0054, 0, 0;
;SV0357
    .data.w 0, 0
    .data.l _SV_UPDATA_A21
    .data.w 8, 0, 0, 4, 0, 5, 1, h'0054, 0, 0;
;SV0358
    .data.w 0, 0
    .data.l _SV_UPSTOP_A21
    .data.w 6, 0, 0, 2, 0, 6, 1, h'0054, 0, 0;
;SV0359
    .data.w 0, 0
    .data.l _SV_DNDATA_A21
    .data.w 9, 0, 0, 4, 0, 7, 1, h'0054, 0, 0;
;SV0360
    .data.w 0, 0
    .data.l _SV_MODORI_A21
    .data.w 0, 0, 0, 2, 0, 8, 1, h'0054, 0, 0;
;SV0361
    .data.w 0, 0
    .data.l _SV_SSEIDO_A21
    .data.w 0, 0, 0, 2, 0, 9, 1, h'0054, 0, 0;
;SV0362
    .data.w 0, 0
    .data.l _SV_POINT_A1
    .data.w 33, 0, 0, 2, 0, 1, 1, h'0054, 0, 0;
;SV0363
    .data.w 0, 0
    .data.l _SV_GENITI_A47
    .data.w 0, 0, 0, 4, 0, 2, 1, h'0020, 0, 0;
;SV0364
    .data.w 0, 0
    .data.l _SV_KANDO_A47
    .data.w 0, 0, 0, 4, 0, 3, 1, h'0020, 0, 0;
;SV0365
    .data.w 0, 0
    .data.l _SV_DNSTOP_A47
    .data.w 0, 0, 0, 2, 0, 4, 1, h'0020, 0, 0;
;SV0366
    .data.w 0, 0
    .data.l _SV_UPDATA_A47
    .data.w 0, 0, 0, 4, 0, 5, 1, h'0020, 0, 0;
;SV0367
    .data.w 0, 0
    .data.l _SV_UPSTOP_A47
    .data.w 0, 0, 0, 2, 0, 6, 1, h'0020, 0, 0;
;SV0368
    .data.w 0, 0
    .data.l _SV_DNDATA_A47
    .data.w 0, 0, 0, 4, 0, 7, 1, h'0020, 0, 0;
;SV0369
    .data.w 0, 0
    .data.l _SV_MODORI_A47
    .data.w 0, 0, 0, 2, 0, 8, 1, h'0020, 0, 0;
;SV0370
    .data.w 0, 0
    .data.l _SV_SSEIDO_A47
    .data.w 0, 0, 0, 2, 0, 9, 1, h'0020, 0, 0;
;SV0371
    .data.w 0, 0
    .data.l _SV_POINT_A47
    .data.w 0, 0, 0, 1, 0, 1, 1, h'0020, 0, 0;
;SV0372
    .data.w 0, 0
    .data.l _SV_GENITI_A48
    .data.w 0, 0, 0, 4, 0, 2, 1, h'0020, 0, 0;
;SV0373
    .data.w 0, 0
    .data.l _SV_KANDO_A48
    .data.w 0, 0, 0, 4, 0, 3, 1, h'0020, 0, 0;
;SV0374
    .data.w 0, 0
    .data.l _SV_DNSTOP_A48
    .data.w 0, 0, 0, 2, 0, 4, 1, h'0020, 0, 0;
;SV0375
    .data.w 0, 0
    .data.l _SV_UPDATA_A48
    .data.w 0, 0, 0, 4, 0, 5, 1, h'0020, 0, 0;
;SV0376
    .data.w 0, 0
    .data.l _SV_UPSTOP_A48
    .data.w 0, 0, 0, 2, 0, 6, 1, h'0020, 0, 0;
;SV0377
    .data.w 0, 0
    .data.l _SV_DNDATA_A48
    .data.w 0, 0, 0, 4, 0, 7, 1, h'0020, 0, 0;
;SV0378
    .data.w 0, 0
    .data.l _SV_MODORI_A48
    .data.w 0, 0, 0, 2, 0, 8, 1, h'0020, 0, 0;
;SV0379
    .data.w 0, 0
    .data.l _SV_SSEIDO_A48
    .data.w 0, 0, 0, 2, 0, 9, 1, h'0020, 0, 0;
;SV0380
    .data.w 0, 0
    .data.l _SV_POINT_A47
    .data.w 0, 0, 0, 1, 0, 1, 1, h'0020, 0, 0;
;SV0381
    .data.w 0, 0
    .data.l _SV_BARAUP_A49
    .data.w 0, 0, 0, 2, 0, 1, 1, 0, 0, 0;
;SV0382
    .data.w 0, 0
    .data.l _SV_BARADN_A49
    .data.w 0, 0, 0, 2, 0, 2, 1, 0, 0, 0;
;SV0383
    .data.w 0, 0
    .data.l _SV_BARKIJ_A45
    .data.w 0, 0, 0, 2, 0, 3, 1, 0, 0, 0;
;SV0384
    .data.w 0, 0
    .data.l _SV_DAILUP_A49
    .data.w 0, 0, 0, 2, 0, 4, 1, 0, 0, 0;
;SV0385
    .data.w 0, 0
    .data.l _SV_DAILDN_A49
    .data.w 0, 0, 0, 2, 0, 5, 1, 0, 0, 0;
;SV0386
    .data.w 0, 0
    .data.l _SV_DAIRUP_A49
    .data.w 0, 0, 0, 2, 0, 6, 1, 0, 0, 0;
;SV0387
    .data.w 0, 0
    .data.l _SV_DAIRDN_A49
    .data.w 0, 0, 0, 2, 0, 7, 1, 0, 0, 0;
;SV0388
    .data.w 0, 0
    .data.l _PV_GAIN_BAK1L
    .data.w 29, 0, 0, 2, 0, 1, 1, 0, 0, 0;
;SV0389
    .data.w 0, 0
    .data.l _PV_GAIN_BAK1R
    .data.w 29, 0, 0, 2, 0, 1, 2, 0, 0, 0;
;SV0390
    .data.w 0, 0
    .data.l _PV_GAIN_BAK2L
    .data.w 29, 0, 0, 2, 0, 2, 1, 0, 0, 0;
;SV0391
    .data.w 0, 0
    .data.l _PV_GAIN_BAK2R
    .data.w 29, 0, 0, 2, 0, 2, 2, 0, 0, 0;
;SV0392
    .data.w 0, 0
    .data.l _PV_GAIN_BAK3L
    .data.w 29, 0, 0, 2, 0, 3, 1, 0, 0, 0;
;SV0393
    .data.w 0, 0
    .data.l _PV_GAIN_BAK3R
    .data.w 29, 0, 0, 2, 0, 3, 2, 0, 0, 0;
;SV0394
    .data.w 0, 0
    .data.l _PV_GAIN_BAK4L
    .data.w 29, 0, 0, 2, 0, 4, 1, 0, 0, 0;
;SV0395
    .data.w 0, 0
    .data.l _PV_GAIN_BAK4R
    .data.w 29, 0, 0, 2, 0, 4, 2, 0, 0, 0;
;SV0396
    .data.w 0, 0
    .data.l _PV_GAIN_BAK5L
    .data.w 29, 0, 0, 2, 0, 5, 1, 0, 0, 0;
;SV0397
    .data.w 0, 0
    .data.l _PV_GAIN_BAK5R
    .data.w 29, 0, 0, 2, 0, 5, 2, 0, 0, 0;
;SV0398
    .data.w 0, 0
    .data.l _PV_OF_BAKL
    .data.w 32, 0, 0, 2, 0, 6, 1, 0, 0, 0;
;SV0399
    .data.w 0, 0
    .data.l _PV_OF_BAKR
    .data.w 32, 0, 0, 2, 0, 6, 2, 0, 0, 0;
;SV0400
    .data.w 0, 0
    .data.l _PV_OF_AVE_BAKL
    .data.w 29, 0, 0, 2, 0, 7, 1, 0, 0, 0;
;SV0401
    .data.w 0, 0
    .data.l _PV_OF_AVE_BAKR
    .data.w 29, 0, 0, 2, 0, 7, 2, 0, 0, 0;
;SV0402
    .data.w 0, 0
    .data.l _PV_OF_AVE_BAKT
    .data.w 29, 0, 0, 2, 0, 8, 1, 0, 0, 0;
;SV0403
    .data.w 0, 0
    .data.l _PV_GENITI_B2
    .data.w 34, 0, 0, 4, 0, 9, 1, 0, 0, 0;
;SV0404
    .data.w 0, 0
    .data.l _SV_GENITI_CHK
    .data.w 0, 0, 0, 4, 0, 9, 2, 0, 0, 0;
;SV0405
    .data.w 0, 0
    .data.l _SV_CILTN1_A50
    .data.w 41, 0, 0, 1, 0, 1, 1, 0, 0, 0;
;SV0406
    .data.w 0, 0
    .data.l _SV_CILDN1_A50
    .data.w 40, 0, 0, 2, 0, 1, 2, 0, 0, 0;
;SV0407
    .data.w 0, 0
    .data.l _SV_CILUP1_A50
    .data.w 40, 0, 0, 2, 0, 1, 3, 0, 0, 0;
;SV0408
    .data.w 0, 0
    .data.l _SV_CILTN2_A50
    .data.w 41, 0, 0, 1, 0, 2, 1, 0, 0, 0;
;SV0409
    .data.w 0, 0
    .data.l _SV_CILDN2_A50
    .data.w 40, 0, 0, 2, 0, 2, 2, 0, 0, 0;
;SV0410
    .data.w 0, 0
    .data.l _SV_CILUP2_A50
    .data.w 40, 0, 0, 2, 0, 2, 3, 0, 0, 0;
;SV0411
    .data.w 0, 0
    .data.l _SV_CILTN3_A50
    .data.w 41, 0, 0, 1, 0, 3, 1, 0, 0, 0;
;SV0412
    .data.w 0, 0
    .data.l _SV_CILDN3_A50
    .data.w 40, 0, 0, 2, 0, 3, 2, 0, 0, 0;
;SV0413
    .data.w 0, 0
    .data.l _SV_CILUP3_A50
    .data.w 40, 0, 0, 2, 0, 3, 3, 0, 0, 0;
;SV0414
    .data.w 0, 0
    .data.l _SV_CILTN4_A50
    .data.w 41, 0, 0, 1, 0, 4, 1, 0, 0, 0;
;SV0415
    .data.w 0, 0
    .data.l _SV_CILDN4_A50
    .data.w 40, 0, 0, 2, 0, 4, 2, 0, 0, 0;
;SV0416
    .data.w 0, 0
    .data.l _SV_CILUP4_A50
    .data.w 40, 0, 0, 2, 0, 4, 3, 0, 0, 0;
;SV0417
    .data.w 0, 0
    .data.l _SV_CILTN5_A50
    .data.w 41, 0, 0, 1, 0, 5, 1, 0, 0, 0;
;SV0418
    .data.w 0, 0
    .data.l _SV_CILDN5_A50
    .data.w 40, 0, 0, 2, 0, 5, 2, 0, 0, 0;
;SV0419
    .data.w 0, 0
    .data.l _SV_CILUP5_A50
    .data.w 40, 0, 0, 2, 0, 5, 3, 0, 0, 0;
;SV0420
    .data.w 0, 0
    .data.l _SV_CILTN6_A50
    .data.w 41, 0, 0, 1, 0, 6, 1, 0, 0, 0;
;SV0421
    .data.w 0, 0
    .data.l _SV_CILDN6_A50
    .data.w 40, 0, 0, 2, 0, 6, 2, 0, 0, 0;
;SV0422
    .data.w 0, 0
    .data.l _SV_CILUP6_A50
    .data.w 40, 0, 0, 2, 0, 6, 3, 0, 0, 0;
;SV0423
    .data.w 0, 0
    .data.l _SV_INCPOS_KP01
    .data.w 67, 0, 0, 2, 0, 1, 1, h'0001, 0, 0;
;SV0424
    .data.w 0, 0
    .data.l _SV_RNAPOS_KP01
    .data.w 67, 0, 0, 2, 0, 2, 1, h'0001, 0, 0;
;SV0425
    .data.w 0, 0
    .data.l _SV_ACCLAT__TIM1
    .data.w 67, 0, 0, 2, 0, 3, 1, h'0001, 0, 0;
;SV0426
    .data.w 0, 0
    .data.l _SV_SSCURV_TIM1
    .data.w 0, 0, 0, 2, 0, 4, 1, h'0001, 0, 0;
;SV0427
    .data.w 0, 0
    .data.l _SV_UPAREA_INP1
    .data.w 62, 0, 0, 2, 0, 5, 1, h'0001, 0, 0;
;SV0428
    .data.w 0, 0
    .data.l _SV_DNAREA_INP1
    .data.w 62, 0, 0, 2, 0, 6, 1, h'0001, 0, 0;
;SV0429
    .data.w 0, 0
    .data.l _SV_OBJARA_INP1
    .data.w 62, 0, 0, 2, 0, 7, 1, h'0001, 0, 0;
;SV0430
    .data.w 0, 0
    .data.l _SV_INPPOS_TIM1
    .data.w 67, 0, 0, 2, 0, 8, 1, h'0001, 0, 0;
;SV0431
    .data.w 0, 0
    .data.l _SV_ARACHK_LNG1
    .data.w 62, 0, 0, 2, 3, 9, 1, h'0001, 0, 0;
;SV0432
    .data.w 0, 0
    .data.l _SV_UPAREA_DIG1
    .data.w 67, 0, 0, 2, 1, 10, 1, h'0001, 0, 0;
;SV0433
    .data.w 0, 0
    .data.l _SV_UPAREA_JUDG
    .data.w 68, 0, 0, 4, 1, 1, 1, h'0001, 0, 0;
;SV0434
    .data.w 0, 0
    .data.l _SV_DNAREA_JUDG
    .data.w 68, 0, 0, 4, 1, 2, 1, h'0001, 0, 0;
;SV0435
    .data.w 0, 0
    .data.l _SV_RNA_STLORK
    .data.w 0, 0, 0, 4, 3, 3, 1, h'0001, 0, 0;
;SV0436
    .data.w 0, 0
    .data.l _SV_OUTPLS_HOSA
    .data.w 62, 0, 0, 2, 0, 5, 1, h'0001, 0, 0;
;SV0437
    .data.w 0, 0
    .data.l _SV_OUTPLS_HOSB
    .data.w 62, 0, 0, 2, 0, 6, 1, h'0001, 0, 0;
;SV0438
    .data.w 0, 0
    .data.l _SV_UPHOLD_DIG
    .data.w 68, 0, 0, 2, 1, 7, 1, h'0001, 0, 0;
;SV0439
    .data.w 0, 0
    .data.l _SV_MACINE_SEL1
    .data.w 29, 0, 0, 2, 0, 8, 1, h'0001, 0, 0;
;SV0440
    .data.w 0, 0
    .data.l _SV_NEG_OFS_LNG
    .data.w 0, 0, 0, 4, 3, 9, 1, h'0001, 0, 0;
;SV0441
    .data.w 0, 0
    .data.l _SV_INCHEN_ELNG
    .data.w 40, 0, 0, 2, 0, 1, 1, h'0001, 0, 0;
;SV0442
    .data.w 0, 0
    .data.l _SV_INCENC_ELNG
    .data.w 5, 0, 0, 2, 0, 2, 1, h'0001, 0, 0;
;SV0443
    .data.w 0, 0
    .data.l _SV_INCRNA_ELNG
    .data.w 67, 0, 0, 2, 3, 3, 1, h'0001, 0, 0;
;SV0444
    .data.w 0, 0
    .data.l _SV_INCSTP_ELNG
    .data.w 67, 0, 0, 2, 0, 4, 1, h'0001, 0, 0;
;SV0445
    .data.w 0, 0
    .data.l _SV_RNASTP_ELNG
    .data.w 67, 0, 0, 2, 3, 5, 1, h'0001, 0, 0;
;SV0446
    .data.w 0, 0
    .data.l _SV_INCREV_ELNG
    .data.w 67, 0, 0, 2, 0, 6, 1, h'0001, 0, 0;
;SV0447
    .data.w 0, 0
    .data.l _SV_RNAREV_ELNG
    .data.w 67, 0, 0, 2, 3, 7, 1, h'0001, 0, 0;
;SV0448
    .data.w 0, 0
    .data.l _SV_DAIHAI_LNG1
    .data.w 121, 0, 0, 2, 1, 8, 1, h'0001, 0, 0;
;SV0449
    .data.w 0, 0
    .data.l _SV_DAIHAI_LNG2
    .data.w 122, 0, 0, 2, 1, 9, 1, h'0001, 0, 0;
;SV0450
    .data.w 0, 0
    .data.l _SV_DAIHAI_LNG3
    .data.w 62, 0, 0, 2, 3, 10, 1, h'0001, 0, 0;
;SV0451
    .data.w 0, 0
    .data.l _SV_AMPERR_VLT1
    .data.w 52, 0, 0, 2, 2, 1, 1, h'0001, 0, 0;
;SV0452
    .data.w 0, 0
    .data.l _SV_AMPERR_TIM1
    .data.w 0, 0, 0, 2, 1, 2, 1, h'0001, 0, 0;
;SV0453
    .data.w 0, 0
    .data.l _SV_AMPERR_VLT2
    .data.w 52, 0, 0, 2, 2, 3, 1, h'0001, 0, 0;
;SV0454
    .data.w 0, 0
    .data.l _SV_AMPERR_TIM2
    .data.w 0, 0, 0, 2, 1, 4, 1, h'0001, 0, 0;
;SV0455
    .data.w 0, 0
    .data.l _SV_AMPERR_VLT3
    .data.w 52, 0, 0, 2, 2, 5, 1, h'0001, 0, 0;
;SV0456
    .data.w 0, 0
    .data.l _SV_AMPERR_TIM3
    .data.w 0, 0, 0, 2, 1, 6, 1, h'0001, 0, 0;
;SV0457
    .data.w 0, 0
    .data.l _SV_AMP100P_VLT
    .data.w 2, 0, 0, 2, 1, 7, 1, h'0001, 0, 0;
;SV0458
    .data.w 0, 0
    .data.l _SV_RNAORG_SIN
    .data.w 60, 0, 0, 2, 0, 8, 1, 0, 0, 0;
;SV0459
    .data.w 0, 0
    .data.l _SV_RNAORG_PLS
    .data.w 71, 0, 0, 4, 0, 9, 1, 0, 0, 0;
;SV0460
    .data.w 0, 0
    .data.l _SV_MISSTA5_C10
    .data.w 53, 103, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0461
    .data.w 0, 0
    .data.l _SV_MISSK1_C10
    .data.w 5, 103, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0462
    .data.w 0, 0
    .data.l _SV_MISSTP5_C10
    .data.w 53, 103, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0463
    .data.w 0, 0
    .data.l _SV_MISSK2_C10
    .data.w 5, 103, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV0464
    .data.w 0, 0
    .data.l _SV_MISSTA6_C10
    .data.w 53, 104, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0465
    .data.w 0, 0
    .data.l _SV_MISSK3_C10
    .data.w 5, 104, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0466
    .data.w 0, 0
    .data.l _SV_MISSTP6_C10
    .data.w 53, 104, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0467
    .data.w 0, 0
    .data.l _SV_MISSK4_C10
    .data.w 5, 104, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV0468
    .data.w 0, 0
    .data.l _SV_MONALM_S01
    .data.w 0, 0, 0, 2, 0, 1, 1, 0, 0, 0;
;SV0469
    .data.w 0, 0
    .data.l _SV_MONALM_S02
    .data.w 0, 0, 0, 2, 0, 2, 1, 0, 0, 0;
;SV0470
    .data.w 0, 0
    .data.l _SV_MONALM_S03
    .data.w 0, 0, 0, 2, 0, 3, 1, 0, 0, 0;
;SV0471
    .data.w 0, 0
    .data.l _SV_MONALM_S04
    .data.w 0, 0, 0, 2, 0, 4, 1, 0, 0, 0;
;SV0472
    .data.w 0, 0
    .data.l _SV_DEB_SEL0
    .data.w 0, 0, 0, 2, 0, 1, 1, 0, 0, 0;
;SV0473
    .data.w 0, 0
    .data.l _SV_DEB_ADR0
    .data.w 69, 0, 0, 4, 0, 1, 2, 0, 0, 0;
;SV0474
    .data.w 0, 0
    .data.l _SV_DEB_SEL1
    .data.w 0, 0, 0, 2, 0, 2, 1, 0, 0, 0;
;SV0475
    .data.w 0, 0
    .data.l _SV_DEB_ADR1
    .data.w 69, 0, 0, 4, 0, 2, 2, 0, 0, 0;
;SV0476
    .data.w 0, 0
    .data.l _SV_DEB_SEL2
    .data.w 0, 0, 0, 2, 0, 3, 1, 0, 0, 0;
;SV0477
    .data.w 0, 0
    .data.l _SV_DEB_ADR2
    .data.w 69, 0, 0, 4, 0, 3, 2, 0, 0, 0;
;SV0478
    .data.w 0, 0
    .data.l _SV_DEB_SEL3
    .data.w 0, 0, 0, 2, 0, 4, 1, 0, 0, 0;
;SV0479
    .data.w 0, 0
    .data.l _SV_DEB_ADR3
    .data.w 69, 0, 0, 4, 0, 4, 2, 0, 0, 0;
;SV0480
    .data.w 0, 0
    .data.l _SV_DEB_SEL4
    .data.w 0, 0, 0, 2, 0, 5, 1, 0, 0, 0;
;SV0481
    .data.w 0, 0
    .data.l _SV_DEB_ADR4
    .data.w 69, 0, 0, 4, 0, 5, 2, 0, 0, 0;
;SV0482
    .data.w 0, 0
    .data.l _SV_SEQDT1_A91
    .data.w 49, 0, 0, 2, 0, 1, 1, 0, 0, 0;
;SV0483
    .data.w 0, 0
    .data.l _SV_SEQDT2_A91
    .data.w 49, 0, 0, 2, 0, 2, 1, 0, 0, 0;
;SV0484
    .data.w 0, 0
    .data.l _SV_SEQDT3_A91
    .data.w 49, 0, 0, 2, 0, 3, 1, 0, 0, 0;
;SV0485
    .data.w 0, 0
    .data.l _SV_SEQDT4_A91
    .data.w 49, 0, 0, 2, 0, 4, 1, 0, 0, 0;
;SV0486
    .data.w 0, 0
    .data.l _SV_EJESAT1_C4
    .data.w 53, 1, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0487
    .data.w 0, 0
    .data.l _SV_EJEKK1_C4
    .data.w 5, 1, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0488
    .data.w 0, 0
    .data.l _SV_EJESTP1_C4
    .data.w 53, 2, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0489
    .data.w 0, 0
    .data.l _SV_EJEKK2_C4
    .data.w 5, 2, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV0490
    .data.w 0, 0
    .data.l _SV_EJESAT1_C4A
    .data.w 53, 22, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV0491
    .data.w 0, 0
    .data.l _SV_EJEKK1_C4A
    .data.w 5, 22, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV0492
    .data.w 0, 0
    .data.l _SV_EJESTP1_C4A
    .data.w 53, 23, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV0493
    .data.w 0, 0
    .data.l _SV_EJEKK2_C4A
    .data.w 5, 23, 0, 2, 0, 2, 4, h'0020, 2, 0;
;SV0494
    .data.w 0, 0
    .data.l _SV_EJESAT1_C4B
    .data.w 53, 24, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0495
    .data.w 0, 0
    .data.l _SV_EJEKK1_C4B
    .data.w 5, 24, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0496
    .data.w 0, 0
    .data.l _SV_EJESTP1_C4B
    .data.w 53, 25, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0497
    .data.w 0, 0
    .data.l _SV_EJEKK2_C4B
    .data.w 5, 25, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV0498
    .data.w 0, 0
    .data.l _SV_AUTSTA_C41
    .data.w 53, 26, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV0499
    .data.w 0, 0
    .data.l _SV_AUTKK1_C41
    .data.w 5, 26, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV0500
    .data.w 0, 0
    .data.l _SV_AUTSTP_C41
    .data.w 53, 27, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV0501
    .data.w 0, 0
    .data.l _SV_AUTKK2_C41
    .data.w 5, 27, 0, 2, 0, 4, 4, h'0020, 2, 0;
;SV0502
    .data.w 0, 0
    .data.l _SV_AUTSTA_C41A
    .data.w 53, 28, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0503
    .data.w 0, 0
    .data.l _SV_AUTKK1_C41A
    .data.w 5, 28, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0504
    .data.w 0, 0
    .data.l _SV_AUTSTP_C41A
    .data.w 53, 29, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0505
    .data.w 0, 0
    .data.l _SV_AUTKK2_C41A
    .data.w 5, 29, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV0506
    .data.w 0, 0
    .data.l _SV_AUTSTA_C41B
    .data.w 53, 30, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV0507
    .data.w 0, 0
    .data.l _SV_AUTKK1_C41B
    .data.w 5, 30, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV0508
    .data.w 0, 0
    .data.l _SV_AUTSTP_C41B
    .data.w 53, 31, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV0509
    .data.w 0, 0
    .data.l _SV_AUTKK2_C41B
    .data.w 5, 31, 0, 2, 0, 6, 4, h'0020, 2, 0;
;SV0510
    .data.w 0, 0
    .data.l _SV_EJESTA_C5
    .data.w 53, 1, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0511
    .data.w 0, 0
    .data.l _SV_EJEKK3_C5
    .data.w 5, 1, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0512
    .data.w 0, 0
    .data.l _SV_EJESTP_C5
    .data.w 53, 2, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0513
    .data.w 0, 0
    .data.l _SV_EJETIM_C5
    .data.w 6, 2, 0, 2, 1, 1, 4, h'0020, 2, 0;
;SV0514
    .data.w 0, 0
    .data.l _SV_EJESTA_C5A
    .data.w 53, 22, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV0515
    .data.w 0, 0
    .data.l _SV_EJEKK3_C5A
    .data.w 5, 22, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV0516
    .data.w 0, 0
    .data.l _SV_EJESTP_C5A
    .data.w 53, 23, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV0517
    .data.w 0, 0
    .data.l _SV_EJETIM_C5A
    .data.w 6, 23, 0, 2, 1, 2, 4, h'0020, 2, 0;
;SV0518
    .data.w 0, 0
    .data.l _SV_EJESTA_C5B
    .data.w 53, 24, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0519
    .data.w 0, 0
    .data.l _SV_EJEKK3_C5B
    .data.w 5, 24, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0520
    .data.w 0, 0
    .data.l _SV_EJESTP_C5B
    .data.w 53, 25, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0521
    .data.w 0, 0
    .data.l _SV_EJETIM_C5B
    .data.w 6, 25, 0, 2, 1, 3, 4, h'0020, 2, 0;
;SV0522
    .data.w 0, 0
    .data.l _SV_AUTSTA_C51
    .data.w 53, 26, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV0523
    .data.w 0, 0
    .data.l _SV_AUTKK3_C51
    .data.w 5, 26, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV0524
    .data.w 0, 0
    .data.l _SV_AUTSTP_C51
    .data.w 53, 27, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV0525
    .data.w 0, 0
    .data.l _SV_AUTTIM_C51
    .data.w 6, 27, 0, 2, 1, 4, 4, h'0020, 2, 0;
;SV0526
    .data.w 0, 0
    .data.l _SV_AUTSTA_C51A
    .data.w 53, 28, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0527
    .data.w 0, 0
    .data.l _SV_AUTKK3_C51A
    .data.w 5, 28, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0528
    .data.w 0, 0
    .data.l _SV_AUTSTP_C51A
    .data.w 53, 29, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0529
    .data.w 0, 0
    .data.l _SV_AUTTIM_C51A
    .data.w 6, 29, 0, 2, 1, 5, 4, h'0020, 2, 0;
;SV0530
    .data.w 0, 0
    .data.l _SV_AUTSTA_C51B
    .data.w 53, 30, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV0531
    .data.w 0, 0
    .data.l _SV_AUTKK3_C51B
    .data.w 5, 30, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV0532
    .data.w 0, 0
    .data.l _SV_AUTSTP_C51B
    .data.w 53, 31, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV0533
    .data.w 0, 0
    .data.l _SV_AUTTIM_C51B
    .data.w 6, 31, 0, 2, 1, 6, 4, h'0020, 2, 0;
;SV0534
    .data.w 0, 0
    .data.l _SV_ATUOS0_D9
    .data.w 20, 19, h'0004, 4, 2, 2, 1, h'0004, 2, 0;
;SV0535
    .data.w 0, 0
    .data.l _SV_ATUOS1_D9
    .data.w 20, 19, h'0004, 4, 2, 2, 2, h'0004, 2, 0;
;SV0536
    .data.w 0, 0
    .data.l _SV_ATUOS2_D9
    .data.w 20, 19, h'0004, 4, 2, 2, 3, h'0004, 2, 0;
;SV0537
    .data.w 0, 0
    .data.l _SV_BARANS_C27
    .data.w 44, 21, h'0004, 2, 2, 1, 1, h'0020, 2, 0;
;SV0538
    .data.w 0, 0
    .data.l _SV_DAIKA1_C27
    .data.w 42, 76, h'0004, 4, 2, 2, 1, 0, 2, 0;
;SV0539
    .data.w 0, 0
    .data.l _SV_DAIKA2_C27
    .data.w 43, 76, h'0004, 4, 2, 2, 2, 0, 2, 0;
;SV0540
    .data.w 0, 0
    .data.l _SV_DAITY1_C27
    .data.w 45, 77, h'0004, 2, 2, 1, 1, 0, 2, 0;
;SV0541
    .data.w 0, 0
    .data.l _SV_DAITY2_C27
    .data.w 46, 77, h'0004, 2, 2, 1, 2, 0, 2, 0;
;SV0542
    .data.w 0, 0
    .data.l _SV_SEQDT1_A91
    .data.w 49, 0, 0, 2, 0, 1, 1, 0, 0, 0;
;SV0543
    .data.w 0, 0
    .data.l _SV_SEQDT2_A91
    .data.w 49, 0, 0, 2, 0, 2, 1, 0, 0, 0;
;SV0544
    .data.w 0, 0
    .data.l _SV_SEQDT3_A91
    .data.w 49, 0, 0, 2, 0, 3, 1, 0, 0, 0;
;SV0545
    .data.w 0, 0
    .data.l _SV_SEQDT4_A91
    .data.w 49, 0, 0, 2, 0, 4, 1, 0, 0, 0;
;SV0546
    .data.w 0, 0
    .data.l _SV_NEXTNO_D1
    .data.w 48, 1, h'0084, 2, 0, 1, 1, 0, 0, 0;
;SV0547
    .data.w 0, 0
    .data.l _SV_ATUOS0_D9
    .data.w 20, 19, h'0004, 4, 2, 1, 1, h'0030, 2, 0;
;SV0548
    .data.w 0, 0
    .data.l _SV_ATUOS1_D9
    .data.w 20, 19, h'0004, 4, 2, 1, 2, h'0030, 2, 0;
;SV0549
    .data.w 0, 0
    .data.l _SV_ATUOS2_D9
    .data.w 20, 19, h'0004, 4, 2, 1, 3, h'0030, 2, 0;
;SV0550
    .data.w 0, 0
    .data.l _SV_DAIKA1_C27
    .data.w 42, 76, h'0004, 4, 2, 1, 1, 0, 2, 0;
;SV0551
    .data.w 0, 0
    .data.l _SV_DAIKA2_C27
    .data.w 43, 76, h'0004, 4, 2, 1, 2, 0, 2, 0;
;SV0552
    .data.w 0, 0
    .data.l _SV_MISSTA1_C9
    .data.w 53, 46, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0553
    .data.w 0, 0
    .data.l _SV_MISSK1_C9
    .data.w 5, 46, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0554
    .data.w 0, 0
    .data.l _SV_MISSTP1_C9
    .data.w 53, 46, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0555
    .data.w 0, 0
    .data.l _SV_MISSK2_C9
    .data.w 5, 46, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV0556
    .data.w 0, 0
    .data.l _SV_MISSTA2_C9
    .data.w 53, 47, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV0557
    .data.w 0, 0
    .data.l _SV_MISSK3_C9
    .data.w 5, 47, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV0558
    .data.w 0, 0
    .data.l _SV_MISSTP2_C9
    .data.w 53, 47, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV0559
    .data.w 0, 0
    .data.l _SV_MISSK4_C9
    .data.w 5, 47, 0, 2, 0, 2, 4, h'0020, 2, 0;
;SV0560
    .data.w 0, 0
    .data.l _SV_MISSTA3_C9
    .data.w 53, 48, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0561
    .data.w 0, 0
    .data.l _SV_MISSK5_C9
    .data.w 5, 48, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0562
    .data.w 0, 0
    .data.l _SV_MISSTP3_C9
    .data.w 53, 48, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0563
    .data.w 0, 0
    .data.l _SV_MISSK6_C9
    .data.w 5, 48, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV0564
    .data.w 0, 0
    .data.l _SV_MISSTA4_C9
    .data.w 53, 49, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV0565
    .data.w 0, 0
    .data.l _SV_MISSK7_C9
    .data.w 5, 49, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV0566
    .data.w 0, 0
    .data.l _SV_MISSTP4_C9
    .data.w 53, 49, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV0567
    .data.w 0, 0
    .data.l _SV_MISSK8_C9
    .data.w 5, 49, 0, 2, 0, 4, 4, h'0020, 2, 0;
;SV0568
    .data.w 0, 0
    .data.l _SV_MISSTA5_C10
    .data.w 53, 103, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0569
    .data.w 0, 0
    .data.l _SV_MISSK1_C10
    .data.w 5, 103, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0570
    .data.w 0, 0
    .data.l _SV_MISSTP5_C10
    .data.w 53, 103, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0571
    .data.w 0, 0
    .data.l _SV_MISSK2_C10
    .data.w 5, 103, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV0572
    .data.w 0, 0
    .data.l _SV_MISSTA6_C10
    .data.w 53, 104, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV0573
    .data.w 0, 0
    .data.l _SV_MISSK3_C10
    .data.w 5, 104, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV0574
    .data.w 0, 0
    .data.l _SV_MISSTP6_C10
    .data.w 53, 104, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV0575
    .data.w 0, 0
    .data.l _SV_MISSK4_C10
    .data.w 5, 104, 0, 2, 0, 6, 4, h'0020, 2, 0;
;SV0576
    .data.w 0, 0
    .data.l _SV_LSAABN_AGL1
    .data.w 55, 0, H'0100, 4, 0, 1, 1, H'0001, 0, 0;
;SV0577
    .data.w 0, 0
    .data.l _SV_LSAABN_AGL2
    .data.w 55, 0, H'0100, 4, 0, 2, 1, H'0001, 0, 0;
;SV0578
    .data.w 0, 0
    .data.l _SV_PLSALO_PLS
    .data.w 67, 0, 0, 2, 0, 3, 1, H'0001, 0, 0;
;SV0579
    .data.w 0, 0
    .data.l _SV_PLSAHI_PLS
    .data.w 67, 0, 0, 2, 0, 4, 1, H'0001, 0, 0;
;SV0580
    .data.w 0, 0
    .data.l _SV_MOADR0_SQH
    .data.w 0, 0, 0, 2, 0, 6, 1, H'0001, 0, 0;
;SV0581
    .data.w 0, 0
    .data.l _SV_MOADR0_SQL
    .data.w 82, 0, 0, 2, 0, 6, 2, H'0001, 0, 0;
;SV0582
    .data.w 0, 0
    .data.l _SV_MOADR1_SQH
    .data.w 0, 0, 0, 2, 0, 7, 1, H'0001, 0, 0;
;SV0583
    .data.w 0, 0
    .data.l _SV_MOADR1_SQL
    .data.w 82, 0, 0, 2, 0, 7, 2, H'0001, 0, 0;
;SV0584
    .data.w 0, 0
    .data.l _SV_MOADR2_SQH
    .data.w 0, 0, 0, 2, 0, 8, 1, H'0001, 0, 0;
;SV0585
    .data.w 0, 0
    .data.l _SV_MOADR2_SQL
    .data.w 82, 0, 0, 2, 0, 8, 2, H'0001, 0, 0;
;SV0586
    .data.w 0, 0
    .data.l _SV_MOADR3_SQH
    .data.w 0, 0, 0, 2, 0, 9, 1, H'0001, 0, 0;
;SV0587
    .data.w 0, 0
    .data.l _SV_MOADR3_SQL
    .data.w 82, 0, 0, 2, 0, 9, 2, H'0001, 0, 0;
;SV0588
    .data.w 0, 0
    .data.l _SV_MOADR4_SQH
    .data.w 0, 0, 0, 2, 0, 10, 1, H'0001, 0, 0;
;SV0589
    .data.w 0, 0
    .data.l _SV_MOADR4_SQL
    .data.w 82, 0, 0, 2, 0, 10, 2, H'0001, 0, 0;
;SV0590
    .data.w 0, 0
    .data.l _SV_MOADR5_SQH
    .data.w 0, 0, 0, 2, 0, 11, 1, H'0001, 0, 0;
;SV0591
    .data.w 0, 0
    .data.l _SV_MOADR5_SQL
    .data.w 82, 0, 0, 2, 0, 11, 2, H'0001, 0, 0;
;SV0592
    .data.w 0, 0
    .data.l _SV_MOADR6_SQH
    .data.w 0, 0, 0, 2, 0, 12, 1, H'0001, 0, 0;
;SV0593
    .data.w 0, 0
    .data.l _SV_MOADR6_SQL
    .data.w 82, 0, 0, 2, 0, 12, 2, H'0001, 0, 0;
;SV0594
    .data.w 0, 0
    .data.l _SV_MOADR7_SQH
    .data.w 0, 0, 0, 2, 0, 13, 1, H'0001, 0, 0;
;SV0595
    .data.w 0, 0
    .data.l _SV_MOADR7_SQL
    .data.w 82, 0, 0, 2, 0, 13, 2, H'0001, 0, 0;
;SV0596
    .data.w 0, 0
    .data.l _SV_MOADR8_SQH
    .data.w 0, 0, 0, 2, 0, 14, 1, H'0001, 0, 0;
;SV0597
    .data.w 0, 0
    .data.l _SV_MOADR8_SQL
    .data.w 82, 0, 0, 2, 0, 14, 2, H'0001, 0, 0;
;SV0598
    .data.w 0, 0
    .data.l _SV_MOADR9_SQH
    .data.w 0, 0, 0, 2, 0, 15, 1, H'0001, 0, 0;
;SV0599
    .data.w 0, 0
    .data.l _SV_MOADR9_SQL
    .data.w 82, 0, 0, 2, 0, 15, 2, H'0001, 0, 0;
;SV0600
    .data.w 0, 0
    .data.l _SV_MOADRA_SQH
    .data.w 0, 0, 0, 2, 0, 16, 1, H'0001, 0, 0;
;SV0601
    .data.w 0, 0
    .data.l _SV_MOADRA_SQL
    .data.w 82, 0, 0, 2, 0, 16, 2, H'0001, 0, 0;
;SV0602
    .data.w 0, 0
    .data.l _SV_MOADRB_SQH
    .data.w 0, 0, 0, 2, 0, 17, 1, H'0001, 0, 0;
;SV0603
    .data.w 0, 0
    .data.l _SV_MOADRB_SQL
    .data.w 82, 0, 0, 2, 0, 17, 2, H'0001, 0, 0;
;SV0604
    .data.w 0, 0
    .data.l _SV_MOADRC_SQH
    .data.w 0, 0, 0, 2, 0, 18, 1, H'0001, 0, 0;
;SV0605
    .data.w 0, 0
    .data.l _SV_MOADRC_SQL
    .data.w 82, 0, 0, 2, 0, 18, 2, H'0001, 0, 0;
;SV0606
    .data.w 0, 0
    .data.l _SV_MOADRD_SQH
    .data.w 0, 0, 0, 2, 0, 19, 1, H'0001, 0, 0;
;SV0607
    .data.w 0, 0
    .data.l _SV_MOADRD_SQL
    .data.w 82, 0, 0, 2, 0, 19, 2, H'0001, 0, 0;
;SV0608
    .data.w 0, 0
    .data.l _SV_MOADRE_SQH
    .data.w 0, 0, 0, 2, 0, 20, 1, H'0001, 0, 0;
;SV0609
    .data.w 0, 0
    .data.l _SV_MOADRE_SQL
    .data.w 82, 0, 0, 2, 0, 20, 2, H'0001, 0, 0;
;SV0610
    .data.w 0, 0
    .data.l _SV_MOADRF_SQH
    .data.w 0, 0, 0, 2, 0, 21, 1, H'0001, 0, 0;
;SV0611
    .data.w 0, 0
    .data.l _SV_MOADRF_SQL
    .data.w 82, 0, 0, 2, 0, 21, 2, H'0001, 0, 0;
;SV0612
    .data.w 0, 0
    .data.l _SV_DAIHAITO_SRV
    .data.w 84, 117, h'1000, 4, 2, 1, 1, H'0004, 2, 0;
;SV0613
    .data.w 0, 0
    .data.l _SV_HOASEI_SRV
    .data.w 86, 0, 0, 2, 0, 1, 2, H'0004, 2, 0;
;SV0614
    .data.w 0, 0
    .data.l _SV_KAJYUU_OBJP
    .data.w 85, 53, 0, 2, 0, 2, 1, H'0004, 2, 0;
;SV0615
    .data.w 0, 0
    .data.l _SV_KAJYUU_PRS
    .data.w 87, 53, 0, 2, 0, 2, 2, H'0004, 2, 0;
;SV0616
    .data.w 0, 0
    .data.l _SV_KJSTR_STEP1
    .data.w 53, 0, 0, 2, 0, 2, 3, H'0004, 2, 0;
;SV0617
    .data.w 0, 0
    .data.l _SV_KJSTR_DIG1
    .data.w 55, 0, H'0100, 2, 0, 2, 4, H'0004, 2, 0;
;SV0618
    .data.w 0, 0
    .data.l _SV_KJEND_STEP1
    .data.w 53, 0, 0, 2, 0, 2, 5, H'0004, 2, 0;
;SV0619
    .data.w 0, 0
    .data.l _SV_KJEND_DIG1
    .data.w 55, 0, H'0100, 2, 0, 2, 6, H'0004, 2, 0;
;SV0620
    .data.w 0, 0
    .data.l _SV_OVERLIDE_COF
    .data.w 83, 0, 0, 2, 0, 10, 1, H'0004, 2, 0;
;SV0621
    .data.w 0, 0
    .data.l _SV_DND_STOPDIG1
    .data.w 55, 0, H'0100, 2, 0, 12, 1, H'0004, 2, 0;
;SV0622
    .data.w 0, 0
    .data.l _SV_OVERLIDE_COF
    .data.w 83, 0, 0, 2, 0, 4, 1, H'0004, 2, 0;
;SV0623
    .data.w 0, 0
    .data.l _SV_SMPSTR_KAJ
    .data.w 0, 53, 0, 2, 0, 3, 1, H'0008, 0, 0;
;SV0624
    .data.w 0, 0
    .data.l _SV_SMPSTR_AGL
    .data.w 55, 0, H'0100, 2, 0, 5, 1, H'0008, 0, 0;
;SV0625
    .data.w 0, 0
    .data.l _SV_SMPSTR_FUK
    .data.w 0, 0, 0, 2, 0, 5, 1, H'0008, 0, 0;
;SV0626
    .data.w 0, 0
    .data.l _SV_SMPSTR_SEH
    .data.w 0, 0, 0, 2, 0, 7, 1, H'0008, 0, 0;
;SV0627
    .data.w 0, 0
    .data.l _SV_SMPSTR_SQL
    .data.w 82, 0, 0, 2, 0, 7, 2, H'0008, 0, 0;
;SV0628
    .data.w 0, 0
    .data.l _SV_SMPMAX_CNT
    .data.w 91, 0, 0, 2, 0, 9, 1, H'0008, 0, 0;
;SV0629
    .data.w 0, 0
    .data.l _SV_SMPTRG_CNT
    .data.w 92, 0, 0, 2, 0, 10, 1, H'0008, 0, 0;
;SV0630
    .data.w 0, 0
    .data.l _SV_SMPCYC_TIM
    .data.w 0, 0, 0, 2, 0, 5, 1, H'0008, 0, 0;
;SV0631
    .data.w 0, 0
    .data.l _SV_ORGRUP_DEG
    .data.w 5, 0, 0, 2, 0, 1, 1, h'0001, 0, 0;
;SV0632
    .data.w 0, 0
    .data.l _SV_ORGRDN_DEG
    .data.w 5, 0, 0, 2, 0, 2, 1, h'0001, 0, 0;
;SV0633
    .data.w 0, 0
    .data.l _SV_ORGLUP_DEG
    .data.w 5, 0, 0, 2, 0, 3, 1, h'0001, 0, 0;
;SV0634
    .data.w 0, 0
    .data.l _SV_ORGLDN_DEG
    .data.w 5, 0, 0, 2, 0, 4, 1, h'0001, 0, 0;
;SV0635
    .data.w 0, 0
    .data.l _SV_ORGSOK_PLS
    .data.w 40, 0, 0, 4, 0, 5, 1, h'0001, 0, 0;
;SV0636
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT1
    .data.w 0, 0, 0, 4, 0, 6, 1, h'0001, 0, 0;
;SV0637
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT2
    .data.w 0, 0, 0, 4, 0, 7, 1, h'0001, 0, 0;
;SV0638
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT3
    .data.w 88, 0, 0, 4, 3, 1, 1, h'0001, 0, 0;
;SV0639
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT4
    .data.w 0, 0, 0, 4, 0, 2, 1, h'0001, 0, 0;
;SV0640
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT5
    .data.w 0, 0, 0, 4, 0, 10, 1, h'0001, 0, 0;
;SV0641
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT6
    .data.w 0, 0, 0, 4, 0, 11, 1, h'0001, 0, 0;
;SV0642
    .data.w 0, 0
    .data.l _SV_ORGSTRK_LEN1
    .data.w 0, 0, 0, 4, 3, 12, 1, h'0001, 0, 0;
;SV0643
    .data.w 0, 0
    .data.l _SV_ORGSTRK_LEN2
    .data.w 0, 0, 0, 4, 3, 13, 1, h'0001, 0, 0;
;SV0644
    .data.w 0, 0
    .data.l _SV_RNAORGMEM_LEG1
    .data.w 0, 0, 0, 4, 3, 1, 1, h'0100, 0, 0;
;SV0645
    .data.w 0, 0
    .data.l _SV_RNAORG_SIN1
    .data.w 60, 0, 0, 2, 0, 2, 1, 0, 0, 0;
;SV0646
    .data.w 0, 0
    .data.l _SV_RNAORG_PLS1
    .data.w 89, 0, 0, 4, 0, 2, 2, 0, 0, 0;
;SV0647
    .data.w 0, 0
    .data.l _SV_RNAORGMEM_LEG2
    .data.w 0, 0, 0, 4, 3, 3, 1, h'0100, 0, 0;
;SV0648
    .data.w 0, 0
    .data.l _SV_RNAORG_SIN2
    .data.w 60, 0, 0, 2, 0, 4, 1, 0, 0, 0;
;SV0649
    .data.w 0, 0
    .data.l _SV_RNAORG_PLS2
    .data.w 90, 0, 0, 4, 0, 4, 2, 0, 0, 0;
;SV0650
    .data.w 0, 0
    .data.l _SV_ORGMEM_DEG1A
    .data.w 88, 0, 0, 4, 3, 5, 1, h'0001, 0, 0;
;SV0651
    .data.w 0, 0
    .data.l _SV_ORGMEM_DEGS1
    .data.w 60, 0, 0, 2, 0, 5, 2, h'0001, 0, 0;
;SV0652
    .data.w 0, 0
    .data.l _SV_ORGMEM_DEG2A
    .data.w 88, 0, 0, 4, 3, 6, 1, h'0001, 0, 0;
;SV0653
    .data.w 0, 0
    .data.l _SV_ORGMEM_DEGS2
    .data.w 60, 0, 0, 2, 0, 6, 2, h'0001, 0, 0;
;SV0654
    .data.w 0, 0
    .data.l _SV_ORGMPL_SEL1
    .data.w 60, 0, 0, 2, 0, 7, 1, h'0001, 0, 0;
;SV0655
    .data.w 0, 0
    .data.l _SV_ORGMPL_SEL2
    .data.w 60, 0, 0, 2, 0, 8, 1, h'0001, 0, 0;
;SV0656
    .data.w 0, 0
    .data.l _SV_HOSRAG_PLS1
    .data.w 67, 0, 0, 2, 0, 9, 1, h'0001, 0, 0;
;SV0657
    .data.w 0, 0
    .data.l _SV_HOSRAG_PLS2
    .data.w 67, 0, 0, 2, 0, 10, 1, h'0001, 0, 0;
;SV0658
    .data.w 0, 0
    .data.l _SV_HOSEI_SPD
    .data.w 65, 0, 0, 2, 2, 11, 1, h'0001, 0, 0;
;SV0659
    .data.w 0, 0
    .data.l _SV_MANSAM_LEN
    .data.w 0, 0, 0, 2, 3, 1, 1, h'0001, 0, 0;
;SV0660
    .data.w 0, 0
    .data.l _SV_DANSAM_LEN
    .data.w 0, 0, 0, 2, 3, 2, 1, h'0001, 0, 0;
;SV0661
    .data.w 0, 0
    .data.l _SV_RUNSAMER_LEN1
    .data.w 0, 0, 0, 2, 3, 3, 1, h'0001, 0, 0;
;SV0662
    .data.w 0, 0
    .data.l _SV_RUNSAMER_LEN2
    .data.w 0, 0, 0, 2, 3, 4, 1, h'0001, 0, 0;
;SV0663
    .data.w 0, 0
    .data.l _SV_MANSAMER_PLS
    .data.w 67, 0, 0, 2, 0, 5, 1, h'0001, 0, 0;
;SV0664
    .data.w 0, 0
    .data.l _SV_RUNSAMER_PLS
    .data.w 67, 0, 0, 2, 0, 6, 1, h'0001, 0, 0;
;SV0665
    .data.w 0, 0
    .data.l _SV_RNADIR_SEL2
    .data.w 60, 0, 0, 2, 0, 7, 1, h'0001, 0, 0;
;SV0666
    .data.w 0, 0
    .data.l _SV_SMP_CNT
    .data.w 40, 0, 0, 2, 0, 1, 1, H'0008, 0, 0;
;SV0667
    .data.w 0, 0
    .data.l _SV_MOADR0_SQH
    .data.w 0, 0, 0, 2, 0, 12, 1, H'0001, 0, 0;
;SV0668
    .data.w 0, 0
    .data.l _SV_MOADR0_SQL
    .data.w 82, 0, 0, 2, 0, 12, 2, H'0001, 0, 0;
;SV0669
    .data.w 0, 0
    .data.l _SV_MOADR1_SQH
    .data.w 0, 0, 0, 2, 0, 14, 1, H'0001, 0, 0;
;SV0670
    .data.w 0, 0
    .data.l _SV_MOADR1_SQL
    .data.w 82, 0, 0, 2, 0, 14, 2, H'0001, 0, 0;
;SV0671
    .data.w 0, 0
    .data.l _SV_MOADR2_SQH
    .data.w 0, 0, 0, 2, 0, 16, 1, H'0001, 0, 0;
;SV0672
    .data.w 0, 0
    .data.l _SV_MOADR2_SQL
    .data.w 82, 0, 0, 2, 0, 16, 2, H'0001, 0, 0;
;SV0673
    .data.w 0, 0
    .data.l _SV_MOADR3_SQH
    .data.w 0, 0, 0, 2, 0, 18, 1, H'0001, 0, 0;
;SV0674
    .data.w 0, 0
    .data.l _SV_MOADR3_SQL
    .data.w 82, 0, 0, 2, 0, 18, 2, H'0001, 0, 0;
;SV0675
    .data.w 0, 0
    .data.l _SV_MOADR4_SQH
    .data.w 0, 0, 0, 2, 0, 13, 1, H'0001, 0, 0;
;SV0676
    .data.w 0, 0
    .data.l _SV_MOADR4_SQL
    .data.w 82, 0, 0, 2, 0, 13, 2, H'0001, 0, 0;
;SV0677
    .data.w 0, 0
    .data.l _SV_MOADR5_SQH
    .data.w 0, 0, 0, 2, 0, 15, 1, H'0001, 0, 0;
;SV0678
    .data.w 0, 0
    .data.l _SV_MOADR5_SQL
    .data.w 82, 0, 0, 2, 0, 15, 2, H'0001, 0, 0;
;SV0679
    .data.w 0, 0
    .data.l _SV_MOADR6_SQH
    .data.w 0, 0, 0, 2, 0, 17, 1, H'0001, 0, 0;
;SV0680
    .data.w 0, 0
    .data.l _SV_MOADR6_SQL
    .data.w 82, 0, 0, 2, 0, 17, 2, H'0001, 0, 0;
;SV0681
    .data.w 0, 0
    .data.l _SV_MOADR7_SQH
    .data.w 0, 0, 0, 2, 0, 19, 1, H'0001, 0, 0;
;SV0682
    .data.w 0, 0
    .data.l _SV_MOADR7_SQL
    .data.w 82, 0, 0, 2, 0, 19, 2, H'0001, 0, 0;
;SV0683
    .data.w 0, 0
    .data.l _SV_TRD_CNT
    .data.w 40, 0, 0, 2, 0, 1, 1, H'0008, 0, 0;
;SV0684
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT1
    .data.w 0, 0, 0, 4, 0, 6, 1, h'0001, 0, 0;
;SV0685
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT2
    .data.w 0, 0, 0, 4, 0, 7, 1, h'0001, 0, 0;
;SV0686
    .data.w 0, 0
    .data.l _SV_HOSRAG_PLS1
    .data.w 67, 0, 0, 2, 0, 1, 1, h'0001, 0, 0;
;SV0687
    .data.w 0, 0
    .data.l _SV_HOSRAG_PLS2
    .data.w 67, 0, 0, 2, 0, 1, 2, h'0001, 0, 0;
;SV0688
    .data.w 0, 0
    .data.l _SV_HOSEI_SPD
    .data.w 65, 0, 0, 2, 2, 1, 3, h'0001, 0, 0;
;SV0689
    .data.w 0, 0
    .data.l _SV_RNADIR_SEL2
    .data.w 60, 0, 0, 2, 0, 2, 1, h'0001, 0, 0;
;SV0690
    .data.w 0, 0
    .data.l _SV_FCLS_STR_DEG
    .data.w 95, 0, 0, 2, 1, 3, 1, h'0001, 0, 0;
;SV0691
    .data.w 0, 0
    .data.l _SV_FCLS_STR_HENS
    .data.w 67, 0, 0, 2, 3, 3, 2, h'0001, 0, 0;
;SV0692
    .data.w 0, 0
    .data.l _SV_FCLS_ZIKI_SPD1
    .data.w 65, 0, 0, 2, 2, 4, 1, h'0001, 0, 0;
;SV0693
    .data.w 0, 0
    .data.l _SV_FCLS_ZIKI_SPD2
    .data.w 65, 0, 0, 2, 2, 4, 2, h'0001, 0, 0;
;SV0694
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_DEGA
    .data.w 95, 0, 0, 2, 1, 5, 1, h'0001, 0, 0;
;SV0695
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_DEGB
    .data.w 95, 0, 0, 2, 1, 5, 2, h'0001, 0, 0;
;SV0696
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_DEGC
    .data.w 95, 0, 0, 2, 1, 5, 3, h'0001, 0, 0;
;SV0697
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_DEGD
    .data.w 95, 0, 0, 2, 1, 5, 4, h'0001, 0, 0;
;SV0698
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_RNAA
    .data.w 67, 0, 0, 2, 3, 6, 1, h'0001, 0, 0;
;SV0699
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_RNAB
    .data.w 67, 0, 0, 2, 3, 6, 2, h'0001, 0, 0;
;SV0700
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_RNAC
    .data.w 67, 0, 0, 2, 3, 6, 3, h'0001, 0, 0;
;SV0701
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_RNAD
    .data.w 67, 0, 0, 2, 3, 6, 4, h'0001, 0, 0;
;SV0702
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_PGA
    .data.w 67, 0, 0, 2, 0, 7, 1, h'0001, 0, 0;
;SV0703
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_PGB
    .data.w 67, 0, 0, 2, 0, 7, 2, h'0001, 0, 0;
;SV0704
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_PGC
    .data.w 67, 0, 0, 2, 0, 7, 3, h'0001, 0, 0;
;SV0705
    .data.w 0, 0
    .data.l _SV_SYNC_ERR_PGD
    .data.w 67, 0, 0, 2, 0, 7, 4, h'0001, 0, 0;
;SV0706
    .data.w 0, 0
    .data.l _SV_INCENC_ELNG
    .data.w 5, 0, 0, 2, 0, 8, 1, h'0001, 0, 0;
;SV0707
    .data.w 0, 0
    .data.l _SV_INCRNA_ELNG
    .data.w 67, 0, 0, 2, 3, 8, 2, h'0001, 0, 0;
;SV0708
    .data.w 0, 0
    .data.l _SV_IPS_ADR0
    .data.w 32, 0, 0, 2, 0, 17, 1, 0, 0, 0;
;SV0709
    .data.w 0, 0
    .data.l _SV_IPS_ADR1
    .data.w 32, 0, 0, 2, 0, 17, 2, 0, 0, 0;
;SV0710
    .data.w 0, 0
    .data.l _SV_IPS_ADR2
    .data.w 32, 0, 0, 2, 0, 17, 3, 0, 0, 0;
;SV0711
    .data.w 0, 0
    .data.l _SV_IPS_ADR3
    .data.w 32, 0, 0, 2, 0, 17, 4, 0, 0, 0;
;SV0712
    .data.w 0, 0
    .data.l _SV_SUB_NET0
    .data.w 32, 0, 0, 2, 0, 18, 1, 0, 0, 0;
;SV0713
    .data.w 0, 0
    .data.l _SV_SUB_NET1
    .data.w 32, 0, 0, 2, 0, 18, 2, 0, 0, 0;
;SV0714
    .data.w 0, 0
    .data.l _SV_SUB_NET2
    .data.w 32, 0, 0, 2, 0, 18, 3, 0, 0, 0;
;SV0715
    .data.w 0, 0
    .data.l _SV_SUB_NET3
    .data.w 32, 0, 0, 2, 0, 18, 4, 0, 0, 0;
;SV0716
    .data.w 0, 0
    .data.l _SV_DEF_GAT0
    .data.w 32, 0, 0, 2, 0, 19, 1, 0, 0, 0;
;SV0717
    .data.w 0, 0
    .data.l _SV_DEF_GAT1
    .data.w 32, 0, 0, 2, 0, 19, 2, 0, 0, 0;
;SV0718
    .data.w 0, 0
    .data.l _SV_DEF_GAT2
    .data.w 32, 0, 0, 2, 0, 19, 3, 0, 0, 0;
;SV0719
    .data.w 0, 0
    .data.l _SV_DEF_GAT3
    .data.w 32, 0, 0, 2, 0, 19, 4, 0, 0, 0;
;SV0720
    .data.w 0, 0
    .data.l 0;_SV_ATCOL_CYCìWé¶âÔóp
    .data.w 96, 0, 0, 2, 0, 1, 1, H'0008, 0, 0;
;SV0721
    .data.w 0, 0
    .data.l 0;_SV_ATCOL_STNOìWé¶âÔóp
    .data.w 53, 0, 0, 2, 0, 2, 1, H'0008, 0, 0;
;SV0722
    .data.w 0, 0
    .data.l 0;_SV_ATCOL_STAGìWé¶âÔóp
    .data.w 5, 0, 0, 2, 0, 2, 2, H'0008, 0, 0;
;SV0723
    .data.w 0, 0
    .data.l 0;_SV_ATCOL_SPNOìWé¶âÔóp
    .data.w 53, 0, 0, 2, 0, 2, 3, H'0008, 0, 0;
;SV0724
    .data.w 0, 0
    .data.l 0;_SV_ATCOL_SPAGìWé¶âÔóp
    .data.w 5, 0, 0, 2, 0, 2, 4, H'0008, 0, 0;
;SV0725
    .data.w 0, 0
    .data.l _SV_WAVE_SCL1U
    .data.w 98, 120, h'0400, 4, 2, 1, 1, 0, 0, 0;
;SV0726
    .data.w 0, 0
    .data.l _SV_WAVE_SCL2U
    .data.w 100, 53, H'0020, 2, 0, 2, 2, 0, 0, 0;
;SV0727
    .data.w 0, 0
    .data.l _SV_WAVE_SCL1D
    .data.w 99, 120, h'0400, 4, 2, 4, 1, 0, 0, 0;
;SV0728
    .data.w 0, 0
    .data.l _SV_WAVE_SCL2D
    .data.w 101, 53, H'0020, 2, 0, 5, 2, 0, 0, 0;
;SV0729
    .data.w 0, 0
    .data.l _SV_WAVE_SCL3U
    .data.w 98, 120, h'0400, 4, 2, 1, 1, 0, 0, 0;
;SV0730
    .data.w 0, 0
    .data.l _SV_WAVE_SCL4U
    .data.w 124, 0, H'0020, 2, 0, 2, 2, 0, 0, 0;
;SV0731
    .data.w 0, 0
    .data.l _SV_WAVE_SCL3D
    .data.w 99, 120, h'0400, 4, 2, 4, 1, 0, 0, 0;
;SV0732
    .data.w 0, 0
    .data.l _SV_WAVE_SCL4D
    .data.w 125, 0, H'0020, 2, 0, 5, 2, 0, 0, 0;
;SV0733
    .data.w 0, 0
    .data.l _SV_WAVE_PAGE
    .data.w 102, 0, 0, 2, 0, 7, 1, 0, 0, 0;
;SV0734
    .data.w 0, 0
    .data.l _SV_SMPCYC_TIM
    .data.w 103, 0, 0, 2, 0, 11, 1, H'0008, 0, 0;
;SV0735
    .data.w 0, 0
    .data.l _SV_TRDCSR_RNAU
    .data.w 104, 127, h'0400, 4, 2, 2, 1, H'0008, 0, 0;
;SV0736
    .data.w 0, 0
    .data.l _SV_TRDCSR_RNAD
    .data.w 105, 127, h'0400, 4, 2, 3, 1, H'0008, 0, 0;
;SV0737
    .data.w 0, 0
    .data.l _SV_SMPTRG_CNT1
    .data.w 106, 0, 0, 2, 0, 10, 2, H'0008, 0, 0;
;SV0738
    .data.w 0, 0
    .data.l _SV_BRDIG_C2
    .data.w 107, 0, 0, 2, 0, 13, 2, h'0001, 0, 0;
;SV0739
    .data.w 0, 0
    .data.l _SV_BRTIME_C2
    .data.w 107, 0, 0, 2, 0, 14, 2, h'0001, 0, 0;
;SV0740
    .data.w 0, 0
    .data.l _SV_INTER_TIM
    .data.w 108, 0, 0, 2, 0, 15, 1, h'0001, 0, 0;
;SV0741
    .data.w 0, 0
    .data.l _SV_TIMER4_A1
    .data.w 109, 0, 0, 2, 2, 13, 1, h'0008, 0, 0;
;SV0742
    .data.w 0, 0
    .data.l _SV_KASIN_KAJ
    .data.w 0, 53, 0, 2, 0, 3, 1, h'0008, 0, 0;
;SV0743
    .data.w 0, 0
    .data.l _SV_EPMGRP_MXL
    .data.w 0, 0, 0, 4, 1, 2, 1, 0, 0, 0;
;SV0744
    .data.w 0, 0
    .data.l _SV_EPMGRP_MXR
    .data.w 0, 0, 0, 4, 1, 2, 2, 0, 0, 0;
;SV0745
    .data.w 0, 0
    .data.l _SV_EPMCSR_TIM
    .data.w 110, 0, 0, 2, 0, 3, 1, 0, 0, 0;
;SV0746
    .data.w 0, 0
    .data.l _SV_SRVPAR_B0
    .data.w 52, 0, 0, 2, 2, 1, 1, h'0001, 0, 0;
;SV0747
    .data.w 0, 0
    .data.l _SV_SRVPAR_B1
    .data.w 52, 0, 0, 2, 2, 3, 1, h'0001, 0, 0;
;SV0748
    .data.w 0, 0
    .data.l _SV_SRVPAR_B2
    .data.w 67, 0, 0, 2, 0, 5, 1, h'0001, 0, 0;
;SV0749
    .data.w 0, 0
    .data.l _SV_SRVPAR_B3
    .data.w 2, 0, 0, 2, 0, 7, 1, h'0001, 0, 0;
;SV0750
    .data.w 0, 0
    .data.l _SV_SRVPAR_B4
    .data.w 52, 0, 0, 2, 0, 9, 1, h'0001, 0, 0;
;SV0751
    .data.w 0, 0
    .data.l _SV_SRVPAR_B5
    .data.w 52, 0, 0, 2, 0, 11, 1, h'0001, 0, 0;
;SV0752
    .data.w 0, 0
    .data.l _SV_SRVPAR_B6
    .data.w 60, 0, 0, 2, 0, 13, 1, h'0001, 0, 0;
;SV0753
    .data.w 0, 0
    .data.l _SV_SRVPAR_B7
    .data.w 65, 0, 0, 2, 0, 13, 2, h'0001, 0, 0;
;SV0754
    .data.w 0, 0
    .data.l _SV_WAVE_SCL5U
    .data.w 112, 122, H'0020, 4, 2, 3, 2, 0, 0, 0;
;SV0755
    .data.w 0, 0
    .data.l _SV_WAVE_SCL5D
    .data.w 126, 122, H'0020, 4, 2, 6, 2, 0, 0, 0;
;SV0756
    .data.w 0, 0
    .data.l _SV_WAVE_SCL6U
    .data.w 127, 0, H'0020, 4, 2, 3, 2, 0, 0, 0;
;SV0757
    .data.w 0, 0
    .data.l _SV_WAVE_SCL6D
    .data.w 128, 0, H'0020, 4, 2, 6, 2, 0, 0, 0;
;SV0758
    .data.w 0, 0
    .data.l _SV_SRVPAR_B8
    .data.w 111, 0, 0, 2, 1, 15, 1, h'0001, 0, 0;
;SV0759
    .data.w 0, 0
    .data.l _SV_SRVPAR_B9
    .data.w 2, 0, 0, 2, 0, 17, 1, h'0001, 0, 0;
;SV0760
    .data.w 0, 0
    .data.l _SV_MOTRPM_MAXP
    .data.w 62, 0, 0, 2, 1, 19, 1, h'0001, 0, 0;
;SV0761
    .data.w 0, 0
    .data.l _SV_ACCLAT__TIMP
    .data.w 67, 0, 0, 2, 0, 21, 1, h'0001, 0, 0;
;SV0762
    .data.w 0, 0
    .data.l _SV_ONESTR_SPD2
    .data.w 66, 0, 0, 2, 0, 10, 1, h'0001, 0, 0;
;SV0763
    .data.w 0, 0
    .data.l _SV0_TAL1_CNT
    .data.w 113, 0, 0, 4, 0, 1, 1, 0, 0, 0;
;SV0764
    .data.w 0, 0
    .data.l _SV0_LOT1_CNT
    .data.w 114, 50, 0, 4, 0, 2, 1, 0, 0, 0;
;SV0765
    .data.w 0, 0
    .data.l _SV0_LOT2_CNT
    .data.w 115, 51, 0, 4, 0, 3, 1, 0, 0, 0;
;SV0766
    .data.w 0, 0
    .data.l _SV0_PLAN_CNT
    .data.w 0, 0, 0, 4, 0, 1, 1, 0, 0, 0;
;SV0767
    .data.w 0, 0
    .data.l _SV_BAD_CNT
    .data.w 0, 0, 0, 4, 0, 2, 1, 0, 0, 0;
;SV0768
    .data.w 0, 0
    .data.l _SV0_WORKER_COD
    .data.w 0, 0, h'0080, 2, 0, 1, 1, 0, 0, 0;
;SV0769
    .data.w 0, 0
    .data.l _SV0_ORDER_COD
    .data.w 0, 0, h'0080, 4, 0, 1, 1, 0, 0, 0;
;SV0770
    .data.w 0, 0
    .data.l _SV0_PLAN_CNT
    .data.w 0, 0, 0, 4, 0, 1, 1, 0, 0, 0;
;SV0771
    .data.w 0, 0
    .data.l _SV_SRVPAR_BC
    .data.w 0, 0, 0, 4, 2, 2, 1, H'0001, 0, 0;
;SV0772
    .data.w 0, 0
    .data.l _SV_SRVPAR_BD
    .data.w 0, 0, 0, 4, 2, 4, 1, H'0001, 0, 0;
;SV0773
    .data.w 0, 0
    .data.l _SV_SRVPAR_BE
    .data.w 0, 0, 0, 4, 3, 6, 1, H'0001, 0, 0;
;SV0774
    .data.w 0, 0
    .data.l _SV_SRVPAR_BF
    .data.w 0, 0, 0, 4, 1, 8, 1, H'0001, 0, 0;
;SV0775
    .data.w 0, 0
    .data.l _SV_SRVPAR_BG
    .data.w 0, 0, 0, 4, 1, 10, 1, H'0001, 0, 0;
;SV0776
    .data.w 0, 0
    .data.l _SV_SRVPAR_BH
    .data.w 65, 0, 0, 4, 2, 12, 1, H'0001, 0, 0;
;SV0777
    .data.w 0, 0
    .data.l _SV_SRVPAR_BI
    .data.w 65, 0, 0, 4, 2, 14, 1, H'0001, 0, 0;
;SV0778
    .data.w 0, 0
    .data.l _SV_SRVPAR_BJ
    .data.w 65, 0, 0, 4, 2, 16, 1, H'0001, 0, 0;
;SV0779
    .data.w 0, 0
    .data.l _SV_SRVPAR_BK
    .data.w 65, 0, 0, 4, 2, 18, 1, H'0001, 0, 0;
;SV0780
    .data.w 0, 0
    .data.l _SV_SRVPAR_BL
    .data.w 65, 0, 0, 4, 0, 20, 1, H'0001, 0, 0;
;SV0781
    .data.w 0, 0
    .data.l _SV_SRVPAR_BM
    .data.w 65, 0, 0, 4, 0, 22, 1, H'0001, 0, 0;
;SV0782
    .data.w 0, 0
    .data.l _SV_SMPSTR_KAJ
    .data.w 0, 53, 0, 2, 0, 2, 1, H'0008, 0, 0;
;SV0783
    .data.w 0, 0
    .data.l _SV_SMPSTR_AGL
    .data.w 55, 0, H'0100, 2, 0, 3, 1, H'0008, 0, 0;
;SV0784
    .data.w 0, 0
    .data.l _SV_SMPSTR_SEH
    .data.w 0, 0, 0, 2, 0, 4, 1, H'0008, 0, 0;
;SV0785
    .data.w 0, 0
    .data.l _SV_SMPSTR_SQL
    .data.w 82, 0, 0, 2, 0, 4, 2, H'0008, 0, 0;
;SV0786
    .data.w 0, 0
    .data.l _SV_SMPMAX_CNT
    .data.w 91, 0, 0, 2, 0, 5, 1, H'0008, 0, 0;
;SV0787
    .data.w 0, 0
    .data.l _SV_SMPTRG_CNT
    .data.w 92, 0, 0, 2, 0, 6, 1, H'0008, 0, 0;
;SV0788
    .data.w 0, 0
    .data.l _SV_SMP_CNT
    .data.w 40, 0, 0, 2, 0, 1, 1, H'0008, 0, 0;
;SV0789
    .data.w 0, 0
    .data.l _SV_MOADR0_SQH
    .data.w 0, 0, 0, 2, 0, 7, 1, H'0001, 0, 0;
;SV0790
    .data.w 0, 0
    .data.l _SV_MOADR0_SQL
    .data.w 82, 0, 0, 2, 0, 7, 2, H'0001, 0, 0;
;SV0791
    .data.w 0, 0
    .data.l _SV_MOADR1_SQH
    .data.w 0, 0, 0, 2, 0, 9, 1, H'0001, 0, 0;
;SV0792
    .data.w 0, 0
    .data.l _SV_MOADR1_SQL
    .data.w 82, 0, 0, 2, 0, 9, 2, H'0001, 0, 0;
;SV0793
    .data.w 0, 0
    .data.l _SV_MOADR2_SQH
    .data.w 0, 0, 0, 2, 0, 11, 1, H'0001, 0, 0;
;SV0794
    .data.w 0, 0
    .data.l _SV_MOADR2_SQL
    .data.w 82, 0, 0, 2, 0, 11, 2, H'0001, 0, 0;
;SV0795
    .data.w 0, 0
    .data.l _SV_MOADR3_SQH
    .data.w 0, 0, 0, 2, 0, 13, 1, H'0001, 0, 0;
;SV0796
    .data.w 0, 0
    .data.l _SV_MOADR3_SQL
    .data.w 82, 0, 0, 2, 0, 13, 2, H'0001, 0, 0;
;SV0797
    .data.w 0, 0
    .data.l _SV_MOADR4_SQH
    .data.w 0, 0, 0, 2, 0, 8, 1, H'0001, 0, 0;
;SV0798
    .data.w 0, 0
    .data.l _SV_MOADR4_SQL
    .data.w 82, 0, 0, 2, 0, 8, 2, H'0001, 0, 0;
;SV0799
    .data.w 0, 0
    .data.l _SV_MOADR5_SQH
    .data.w 0, 0, 0, 2, 0, 10, 1, H'0001, 0, 0;
;SV0800
    .data.w 0, 0
    .data.l _SV_MOADR5_SQL
    .data.w 82, 0, 0, 2, 0, 10, 2, H'0001, 0, 0;
;SV0801
    .data.w 0, 0
    .data.l _SV_MOADR6_SQH
    .data.w 0, 0, 0, 2, 0, 12, 1, H'0001, 0, 0;
;SV0802
    .data.w 0, 0
    .data.l _SV_MOADR6_SQL
    .data.w 82, 0, 0, 2, 0, 12, 2, H'0001, 0, 0;
;SV0803
    .data.w 0, 0
    .data.l _SV_MOADR7_SQH
    .data.w 0, 0, 0, 2, 0, 14, 1, H'0001, 0, 0;
;SV0804
    .data.w 0, 0
    .data.l _SV_MOADR7_SQL
    .data.w 82, 0, 0, 2, 0, 14, 2, H'0001, 0, 0;
;SV0805
    .data.w 0, 0
    .data.l _SV_HAN_P
    .data.w 117, 143, 0, 2, 0, 31, 1, h'0004, 2, 0;
;SV0806
    .data.w 0, 0
    .data.l _SV_HAN_S
    .data.w 118, 143, 0, 2, 0, 32, 1, h'0004, 2, 0;
;SV0807
    .data.w 0, 0
    .data.l _SV_HAN_P
    .data.w 117, 0, 0, 2, 0, 31, 1, h'0004, 2, 0;
;SV0808
    .data.w 0, 0
    .data.l _SV_HAN_S
    .data.w 118, 0, 0, 2, 0, 32, 1, h'0004, 2, 0;
;SV0809
    .data.w 0, 0
    .data.l _SV_LANGUAGE
    .data.w 116, 0, 0, 2, 0, 1, 1, 0, 0, 0;
;SV0810
    .data.w 0, 0
    .data.l _SV_KATTCH_SPD
    .data.w 83, 125, 0, 2, 0, 7, 1, h'0004, 0, 0;
;SV0811
    .data.w 0, 0
    .data.l _SV_SPDDAN_B1
    .data.w 73, 0, 0, 2, 2, 5, 1, h'0004, 2, 0;
;SV0812
    .data.w 0, 0
    .data.l _SV_SPDDAN_B1
    .data.w 73, 0, 0, 2, 2, 11, 1, h'0004, 2, 0;
;SV0813
    .data.w 0, 0
    .data.l _SV_RNAORG_POS1
    .data.w 149, 0, 0, 4, 3, 1, 2, h'0100, 0, 0;
;SV0814
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT2
    .data.w 150, 0, 0, 4, 0, 2, 2, h'0001, 0, 0;
;SV0815
    .data.w 0, 0
    .data.l _SV_MACINE_SEL1
    .data.w 152, 0, 0, 2, 0, 4, 2, h'0001, 0, 0;
;SV0816
    .data.w 0, 0
    .data.l _SV_MAXHIZ_A24
    .data.w 153, 0, 0, 2, 0, 9, 2, h'010, 0, 0;
;SV0817
    .data.w 0, 0
    .data.l _SV_MAXHI3_A24
    .data.w 153, 0, 0, 2, 0, 9, 3, h'010, 0, 0;
;SV0818
    .data.w 0, 0
    .data.l _SV_MAXKAJ_A24
    .data.w 154, 53, 0, 2, 0, 10, 2, h'010, 0, 0;
;SV0819
    .data.w 0, 0
    .data.l _SV_MAXKA2_A24
    .data.w 154, 53, 0, 2, 0, 10, 3, h'018, 0, 0;
;SV0820
    .data.w 0, 0
    .data.l _SV_MAXKA3_A24
    .data.w 154, 53, 0, 2, 0, 10, 4, h'010, 0, 0;
;SV0821
    .data.w 0, 0
    .data.l _SV_KOUKAJ_A24
    .data.w 155, 53, 0, 2, 0, 11, 2, h'010, 0, 0;
;SV0822
    .data.w 0, 0
    .data.l _SV_KOUKA2_A24
    .data.w 156, 53, 0, 2, 0, 11, 3, h'010, 0, 0;
;SV0823
    .data.w 0, 0
    .data.l _SV_KOUKA3_A24
    .data.w 157, 53, 0, 2, 0, 11, 4, h'010, 0, 0;
;SV0824
    .data.w 0, 0
    .data.l _SV_KOUSEI_A24
    .data.w 0, 0, 0, 2, 0, 12, 1, h'010, 0, 0;
;SV0825
    .data.w 0, 0
    .data.l _SV_APARAD_A24
    .data.w 0, 0, 0, 2, 0, 13, 1, h'010, 0, 0;
;SV0826
    .data.w 0, 0
    .data.l 0; _SV_KAJOBJ_HAB
    .data.w 0, 0, 0, 2, 0, 27, 1, H'0004, 2, 0;
;SV0827
    .data.w 0, 0
    .data.l 0; _SV_KAJOBJ_HAB
    .data.w 0, 0, 0, 2, 0, 27, 1, H'0004, 2, 0;
;SV0828
    .data.w 0, 0
    .data.l _SMP_KAJ_MAX_SIN
    .data.w 0, 0, H'0040, 2, 0, 2, 1, 0, 0, 0;
;SV0829
    .data.w 0, 0
    .data.l _SMP_KAJ_MIN_SIN
    .data.w 0, 0, H'0040, 2, 0, 5, 1, 0, 0, 0;
;SV0830
    .data.w 0, 0
    .data.l _SMP_EP_MAX_SIN
    .data.w 0, 122, H'0040, 2, 0, 3, 1, 0, 0, 0;
;SV0831
    .data.w 0, 0
    .data.l _SMP_EP_MIN_SIN
    .data.w 0, 122, H'0040, 2, 0, 6, 1, 0, 0, 0;
;SV0832
    .data.w 0, 0
    .data.l _TRD_KAJ_MAX_SIN
    .data.w 0, 0, H'0040, 2, 0, 2, 1, 0, 0, 0;
;SV0833
    .data.w 0, 0
    .data.l _TRD_KAJ_MIN_SIN
    .data.w 0, 0, H'0040, 2, 0, 5, 1, 0, 0, 0;
;SV0834
    .data.w 0, 0
    .data.l _TRD_EP_MAX_SIN
    .data.w 0, 122, H'0040, 2, 0, 3, 1, 0, 0, 0;
;SV0835
    .data.w 0, 0
    .data.l _TRD_EP_MIN_SIN
    .data.w 0, 122, H'0040, 2, 0, 6, 1, 0, 0, 0;
;SV0836
    .data.w 0, 0
    .data.l _SV_KAJAREA_SNO
    .data.w 53, 0, 0, 2, 0, 4, 1, H'0008, 0, 0;
;SV0837
    .data.w 0, 0
    .data.l _SV_KAJAREA_SAG
    .data.w 55, 0, H'0100, 2, 0, 4, 2, H'0008, 0, 0;
;SV0838
    .data.w 0, 0
    .data.l _SV_KAJAREA_ENO
    .data.w 53, 0, 0, 2, 0, 4, 3, H'0008, 0, 0;
;SV0839
    .data.w 0, 0
    .data.l _SV_KAJAREA_EAG
    .data.w 55, 0, H'0100, 2, 0, 4, 4, H'0008, 0, 0;
;SV0840
    .data.w 0, 0
    .data.l _SV_KATTCH_SAG
    .data.w 55, 125, H'0100, 2, 0, 8, 1, H'0004, 0, 0;
;SV0841
    .data.w 0, 0
    .data.l _SV_KATTCH_EAG
    .data.w 55, 125, H'0100, 2, 0, 8, 2, H'0004, 0, 0;
;SV0842
    .data.w 0, 0
    .data.l _SV_SLPOS_DIR
    .data.w 60, 0, 0, 2, 0, 10, 1, h'0054, 0, 0;
;SV0843
    .data.w 0, 0
    .data.l _SV0_RELE_POS
    .data.w 129, 141, h'0400, 4, 2, 1, 1, 0, 0, 0;
;SV0844
    .data.w 0, 0
    .data.l _SV0_RELE_CAM
    .data.w 130, 137, 0, 2, 0, 1, 2, 0, 0, 0;
;SV0845
    .data.w 0, 0
    .data.l _SV0_SEND_POS
    .data.w 131, 141, h'0400, 4, 2, 2, 1, 0, 0, 0;
;SV0846
    .data.w 0, 0
    .data.l _SV0_SEND_CAM
    .data.w 132, 137, 0, 2, 0, 2, 2, 0, 0, 0;
;SV0847
    .data.w 0, 0
    .data.l _SV0_TIMING_CAM
    .data.w 133, 137, 0, 2, 0, 3, 1, 0, 0, 0;
;SV0848
    .data.w 0, 0
    .data.l _SV_INTLIM_SNO
    .data.w 134, 0, 0, 2, 0, 1, 1, h'0004, 0, 0;
;SV0849
    .data.w 0, 0
    .data.l _SV_INTLIM_AGL
    .data.w 135, 0, h'0100, 2, 0, 1, 2, h'0004, 0, 0;
;SV0850
    .data.w 0, 0
    .data.l _SV_INTLIM_POS
    .data.w 136, 140, h'0400, 4, 2, 1, 3, h'0004, 0, 0;
;SV0851
    .data.w 0, 0
    .data.l _SV_WTTIM_MAX
    .data.w 137, 0, 0, 2, 1, 2, 1, h'0004, 0, 0;
;SV0852
    .data.w 0, 0
    .data.l _SV_RCLSTA11_C17
    .data.w 53, 3, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0853
    .data.w 0, 0
    .data.l _SV_RCLS11_C17
    .data.w 5, 3, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0854
    .data.w 0, 0
    .data.l _SV_RCLSTP12_C17
    .data.w 53, 3, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0855
    .data.w 0, 0
    .data.l _SV_RCLS12_C17
    .data.w 5, 3, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV0856
    .data.w 0, 0
    .data.l _SV_RCSS11_C17
    .data.w 138, 38, 0, 2, 0, 1, 5, h'0020, 2, 0;
;SV0857
    .data.w 0, 0
    .data.l _SV_RCSS21_C17
    .data.w 139, 38, 0, 2, 0, 1, 5, h'0020, 2, 0;
;SV0858
    .data.w 0, 0
    .data.l _SV_RCSS31_C17
    .data.w 138, 38, 0, 2, 0, 1, 6, h'0020, 2, 0;
;SV0859
    .data.w 0, 0
    .data.l _SV_RCSS41_C17
    .data.w 139, 38, 0, 2, 0, 1, 6, h'0020, 2, 0;
;SV0860
    .data.w 0, 0
    .data.l _SV_RCLSTA21_C17
    .data.w 53, 4, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV0861
    .data.w 0, 0
    .data.l _SV_RCLS21_C17
    .data.w 5, 4, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV0862
    .data.w 0, 0
    .data.l _SV_RCLSTP22_C17
    .data.w 53, 4, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV0863
    .data.w 0, 0
    .data.l _SV_RCLS22_C17
    .data.w 5, 4, 0, 2, 0, 2, 4, h'0020, 2, 0;
;SV0864
    .data.w 0, 0
    .data.l _SV_RCSS12_C17
    .data.w 138, 38, 0, 2, 0, 2, 5, h'0020, 2, 0;
;SV0865
    .data.w 0, 0
    .data.l _SV_RCSS22_C17
    .data.w 139, 38, 0, 2, 0, 2, 5, h'0020, 2, 0;
;SV0866
    .data.w 0, 0
    .data.l _SV_RCSS32_C17
    .data.w 138, 38, 0, 2, 0, 2, 6, h'0020, 2, 0;
;SV0867
    .data.w 0, 0
    .data.l _SV_RCSS42_C17
    .data.w 139, 38, 0, 2, 0, 2, 6, h'0020, 2, 0;
;SV0868
    .data.w 0, 0
    .data.l _SV_RCLSTA31_C17
    .data.w 53, 5, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0869
    .data.w 0, 0
    .data.l _SV_RCLS31_C17
    .data.w 5, 5, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0870
    .data.w 0, 0
    .data.l _SV_RCLSTP32_C17
    .data.w 53, 5, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0871
    .data.w 0, 0
    .data.l _SV_RCLS32_C17
    .data.w 5, 5, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV0872
    .data.w 0, 0
    .data.l _SV_RCSS13_C17
    .data.w 138, 38, 0, 2, 0, 3, 5, h'0020, 2, 0;
;SV0873
    .data.w 0, 0
    .data.l _SV_RCSS23_C17
    .data.w 139, 38, 0, 2, 0, 3, 5, h'0020, 2, 0;
;SV0874
    .data.w 0, 0
    .data.l _SV_RCSS33_C17
    .data.w 138, 38, 0, 2, 0, 3, 6, h'0020, 2, 0;
;SV0875
    .data.w 0, 0
    .data.l _SV_RCSS43_C17
    .data.w 139, 38, 0, 2, 0, 3, 6, h'0020, 2, 0;
;SV0876
    .data.w 0, 0
    .data.l _SV_RCLSTA41_C17
    .data.w 53, 6, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV0877
    .data.w 0, 0
    .data.l _SV_RCLS41_C17
    .data.w 5, 6, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV0878
    .data.w 0, 0
    .data.l _SV_RCLSTP42_C17
    .data.w 53, 6, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV0879
    .data.w 0, 0
    .data.l _SV_RCLS42_C17
    .data.w 5, 6, 0, 2, 0, 4, 4, h'0020, 2, 0;
;SV0880
    .data.w 0, 0
    .data.l _SV_RCSS14_C17
    .data.w 138, 38, 0, 2, 0, 4, 5, h'0020, 2, 0;
;SV0881
    .data.w 0, 0
    .data.l _SV_RCSS24_C17
    .data.w 139, 38, 0, 2, 0, 4, 5, h'0020, 2, 0;
;SV0882
    .data.w 0, 0
    .data.l _SV_RCSS34_C17
    .data.w 138, 38, 0, 2, 0, 4, 6, h'0020, 2, 0;
;SV0883
    .data.w 0, 0
    .data.l _SV_RCSS44_C17
    .data.w 139, 38, 0, 2, 0, 4, 6, h'0020, 2, 0;
;SV0884
    .data.w 0, 0
    .data.l _SV_RCLSTA51_C18
    .data.w 53, 7, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0885
    .data.w 0, 0
    .data.l _SV_RCLS51_C18
    .data.w 5, 7, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0886
    .data.w 0, 0
    .data.l _SV_RCLSTP52_C18
    .data.w 53, 7, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0887
    .data.w 0, 0
    .data.l _SV_RCLS52_C18
    .data.w 5, 7, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV0888
    .data.w 0, 0
    .data.l _SV_RCSS11_C18
    .data.w 138, 39, 0, 2, 0, 5, 5, h'0020, 2, 0;
;SV0889
    .data.w 0, 0
    .data.l _SV_RCSS21_C18
    .data.w 139, 39, 0, 2, 0, 5, 5, h'0020, 2, 0;
;SV0890
    .data.w 0, 0
    .data.l _SV_RCSS31_C18
    .data.w 138, 39, 0, 2, 0, 5, 6, h'0020, 2, 0;
;SV0891
    .data.w 0, 0
    .data.l _SV_RCSS41_C18
    .data.w 139, 39, 0, 2, 0, 5, 6, h'0020, 2, 0;
;SV0892
    .data.w 0, 0
    .data.l _SV_RCLSTA61_C18
    .data.w 53, 8, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV0893
    .data.w 0, 0
    .data.l _SV_RCLS61_C18
    .data.w 5, 8, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV0894
    .data.w 0, 0
    .data.l _SV_RCLSTP62_C18
    .data.w 53, 8, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV0895
    .data.w 0, 0
    .data.l _SV_RCLS62_C18
    .data.w 5, 8, 0, 2, 0, 6, 4, h'0020, 2, 0;
;SV0896
    .data.w 0, 0
    .data.l _SV_RCSS12_C18
    .data.w 138, 39, 0, 2, 0, 6, 5, h'0020, 2, 0;
;SV0897
    .data.w 0, 0
    .data.l _SV_RCSS22_C18
    .data.w 139, 39, 0, 2, 0, 6, 5, h'0020, 2, 0;
;SV0898
    .data.w 0, 0
    .data.l _SV_RCSS32_C18
    .data.w 138, 39, 0, 2, 0, 6, 6, h'0020, 2, 0;
;SV0899
    .data.w 0, 0
    .data.l _SV_RCSS42_C18
    .data.w 139, 39, 0, 2, 0, 6, 6, h'0020, 2, 0;
;SV0900
    .data.w 0, 0
    .data.l _SV_RCLSTA71_C18
    .data.w 53, 9, 0, 2, 0, 7, 1, h'0020, 2, 0;
;SV0901
    .data.w 0, 0
    .data.l _SV_RCLS71_C18
    .data.w 5, 9, 0, 2, 0, 7, 2, h'0020, 2, 0;
;SV0902
    .data.w 0, 0
    .data.l _SV_RCLSTP72_C18
    .data.w 53, 9, 0, 2, 0, 7, 3, h'0020, 2, 0;
;SV0903
    .data.w 0, 0
    .data.l _SV_RCLS72_C18
    .data.w 5, 9, 0, 2, 0, 7, 4, h'0020, 2, 0;
;SV0904
    .data.w 0, 0
    .data.l _SV_RCSS13_C18
    .data.w 138, 39, 0, 2, 0, 7, 5, h'0020, 2, 0;
;SV0905
    .data.w 0, 0
    .data.l _SV_RCSS23_C18
    .data.w 139, 39, 0, 2, 0, 7, 5, h'0020, 2, 0;
;SV0906
    .data.w 0, 0
    .data.l _SV_RCSS33_C18
    .data.w 138, 39, 0, 2, 0, 7, 6, h'0020, 2, 0;
;SV0907
    .data.w 0, 0
    .data.l _SV_RCSS43_C18
    .data.w 139, 39, 0, 2, 0, 7, 6, h'0020, 2, 0;
;SV0908
    .data.w 0, 0
    .data.l _SV_RCLSTA81_C18
    .data.w 53, 10, 0, 2, 0, 8, 1, h'0020, 2, 0;
;SV0909
    .data.w 0, 0
    .data.l _SV_RCLS81_C18
    .data.w 5, 10, 0, 2, 0, 8, 2, h'0020, 2, 0;
;SV0910
    .data.w 0, 0
    .data.l _SV_RCLSTP82_C18
    .data.w 53, 10, 0, 2, 0, 8, 3, h'0020, 2, 0;
;SV0911
    .data.w 0, 0
    .data.l _SV_RCLS82_C18
    .data.w 5, 10, 0, 2, 0, 8, 4, h'0020, 2, 0;
;SV0912
    .data.w 0, 0
    .data.l _SV_RCSS14_C18
    .data.w 138, 39, 0, 2, 0, 8, 5, h'0020, 2, 0;
;SV0913
    .data.w 0, 0
    .data.l _SV_RCSS24_C18
    .data.w 139, 39, 0, 2, 0, 8, 5, h'0020, 2, 0;
;SV0914
    .data.w 0, 0
    .data.l _SV_RCSS34_C18
    .data.w 138, 39, 0, 2, 0, 8, 6, h'0020, 2, 0;
;SV0915
    .data.w 0, 0
    .data.l _SV_RCSS44_C18
    .data.w 139, 39, 0, 2, 0, 8, 6, h'0020, 2, 0;
;SV0916
    .data.w 0, 0
    .data.l _SV_RCLSTA11_C19
    .data.w 53, 11, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV0917
    .data.w 0, 0
    .data.l _SV_RCLS11_C19
    .data.w 5, 11, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV0918
    .data.w 0, 0
    .data.l _SV_RCLSTP12_C19
    .data.w 53, 11, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV0919
    .data.w 0, 0
    .data.l _SV_RCLS12_C19
    .data.w 5, 11, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV0920
    .data.w 0, 0
    .data.l _SV_RCSS11_C19
    .data.w 138, 40, 0, 2, 0, 1, 5, h'0020, 2, 0;
;SV0921
    .data.w 0, 0
    .data.l _SV_RCSS21_C19
    .data.w 139, 40, 0, 2, 0, 1, 5, h'0020, 2, 0;
;SV0922
    .data.w 0, 0
    .data.l _SV_RCSS31_C19
    .data.w 138, 40, 0, 2, 0, 1, 6, h'0020, 2, 0;
;SV0923
    .data.w 0, 0
    .data.l _SV_RCSS41_C19
    .data.w 139, 40, 0, 2, 0, 1, 6, h'0020, 2, 0;
;SV0924
    .data.w 0, 0
    .data.l _SV_RCLSTA21_C19
    .data.w 53, 12, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV0925
    .data.w 0, 0
    .data.l _SV_RCLS21_C19
    .data.w 5, 12, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV0926
    .data.w 0, 0
    .data.l _SV_RCLSTA22_C19
    .data.w 53, 12, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV0927
    .data.w 0, 0
    .data.l _SV_RCLS22_C19
    .data.w 5, 12, 0, 2, 0, 2, 4, h'0020, 2, 0;
;SV0928
    .data.w 0, 0
    .data.l _SV_RCSS12_C19
    .data.w 138, 40, 0, 2, 0, 2, 5, h'0020, 2, 0;
;SV0929
    .data.w 0, 0
    .data.l _SV_RCSS22_C19
    .data.w 139, 40, 0, 2, 0, 2, 5, h'0020, 2, 0;
;SV0930
    .data.w 0, 0
    .data.l _SV_RCSS32_C19
    .data.w 138, 40, 0, 2, 0, 2, 6, h'0020, 2, 0;
;SV0931
    .data.w 0, 0
    .data.l _SV_RCSS42_C19
    .data.w 139, 40, 0, 2, 0, 2, 6, h'0020, 2, 0;
;SV0932
    .data.w 0, 0
    .data.l _SV_RCLSTA31_C19
    .data.w 53, 13, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV0933
    .data.w 0, 0
    .data.l _SV_RCLS31_C19
    .data.w 5, 13, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV0934
    .data.w 0, 0
    .data.l _SV_RCLSTA32_C19
    .data.w 53, 13, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV0935
    .data.w 0, 0
    .data.l _SV_RCLS32_C19
    .data.w 5, 13, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV0936
    .data.w 0, 0
    .data.l _SV_RCSS13_C19
    .data.w 138, 40, 0, 2, 0, 3, 5, h'0020, 2, 0;
;SV0937
    .data.w 0, 0
    .data.l _SV_RCSS23_C19
    .data.w 139, 40, 0, 2, 0, 3, 5, h'0020, 2, 0;
;SV0938
    .data.w 0, 0
    .data.l _SV_RCSS33_C19
    .data.w 138, 40, 0, 2, 0, 3, 6, h'0020, 2, 0;
;SV0939
    .data.w 0, 0
    .data.l _SV_RCSS43_C19
    .data.w 139, 40, 0, 2, 0, 3, 6, h'0020, 2, 0;
;SV0940
    .data.w 0, 0
    .data.l _SV_RCLSTA41_C19
    .data.w 53, 14, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV0941
    .data.w 0, 0
    .data.l _SV_RCLS41_C19
    .data.w 5, 14, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV0942
    .data.w 0, 0
    .data.l _SV_RCLSTA42_C19
    .data.w 53, 14, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV0943
    .data.w 0, 0
    .data.l _SV_RCLS42_C19
    .data.w 5, 14, 0, 2, 0, 4, 4, h'0020, 2, 0;
;SV0944
    .data.w 0, 0
    .data.l _SV_RCSS14_C19
    .data.w 138, 40, 0, 2, 0, 4, 5, h'0020, 2, 0;
;SV0945
    .data.w 0, 0
    .data.l _SV_RCSS24_C19
    .data.w 139, 40, 0, 2, 0, 4, 5, h'0020, 2, 0;
;SV0946
    .data.w 0, 0
    .data.l _SV_RCSS34_C19
    .data.w 138, 40, 0, 2, 0, 4, 6, h'0020, 2, 0;
;SV0947
    .data.w 0, 0
    .data.l _SV_RCSS44_C19
    .data.w 139, 40, 0, 2, 0, 4, 6, h'0020, 2, 0;
;SV0948
    .data.w 0, 0
    .data.l _SV_RCLSTA51_C19
    .data.w 53, 15, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV0949
    .data.w 0, 0
    .data.l _SV_RCLS51_C20
    .data.w 5, 15, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV0950
    .data.w 0, 0
    .data.l _SV_RCLSTA52_C20
    .data.w 53, 15, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV0951
    .data.w 0, 0
    .data.l _SV_RCLS52_C20
    .data.w 5, 15, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV0952
    .data.w 0, 0
    .data.l _SV_RCSS11_C20
    .data.w 138, 41, 0, 2, 0, 5, 5, h'0020, 2, 0;
;SV0953
    .data.w 0, 0
    .data.l _SV_RCSS21_C20
    .data.w 139, 41, 0, 2, 0, 5, 5, h'0020, 2, 0;
;SV0954
    .data.w 0, 0
    .data.l _SV_RCSS31_C20
    .data.w 138, 41, 0, 2, 0, 5, 6, h'0020, 2, 0;
;SV0955
    .data.w 0, 0
    .data.l _SV_RCSS41_C20
    .data.w 139, 41, 0, 2, 0, 5, 6, h'0020, 2, 0;
;SV0956
    .data.w 0, 0
    .data.l _SV_RCLSTA61_C20
    .data.w 53, 16, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV0957
    .data.w 0, 0
    .data.l _SV_RCLS61_C20
    .data.w 5, 16, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV0958
    .data.w 0, 0
    .data.l _SV_RCLSTA62_C20
    .data.w 53, 16, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV0959
    .data.w 0, 0
    .data.l _SV_RCLS62_C20
    .data.w 5, 16, 0, 2, 0, 6, 4, h'0020, 2, 0;
;SV0960
    .data.w 0, 0
    .data.l _SV_RCSS12_C20
    .data.w 138, 41, 0, 2, 0, 6, 5, h'0020, 2, 0;
;SV0961
    .data.w 0, 0
    .data.l _SV_RCSS22_C20
    .data.w 139, 41, 0, 2, 0, 6, 5, h'0020, 2, 0;
;SV0962
    .data.w 0, 0
    .data.l _SV_RCSS32_C20
    .data.w 138, 41, 0, 2, 0, 6, 6, h'0020, 2, 0;
;SV0963
    .data.w 0, 0
    .data.l _SV_RCSS42_C20
    .data.w 139, 41, 0, 2, 0, 6, 6, h'0020, 2, 0;
;SV0964
    .data.w 0, 0
    .data.l _SV_RCLSTA71_C20
    .data.w 53, 17, 0, 2, 0, 7, 1, h'0020, 2, 0;
;SV0965
    .data.w 0, 0
    .data.l _SV_RCLS71_C20
    .data.w 5, 17, 0, 2, 0, 7, 2, h'0020, 2, 0;
;SV0966
    .data.w 0, 0
    .data.l _SV_RCLSTA72_C20
    .data.w 53, 17, 0, 2, 0, 7, 3, h'0020, 2, 0;
;SV0967
    .data.w 0, 0
    .data.l _SV_RCLS72_C20
    .data.w 5, 17, 0, 2, 0, 7, 4, h'0020, 2, 0;
;SV0968
    .data.w 0, 0
    .data.l _SV_RCSS13_C20
    .data.w 138, 41, 0, 2, 0, 7, 5, h'0020, 2, 0;
;SV0969
    .data.w 0, 0
    .data.l _SV_RCSS23_C20
    .data.w 139, 41, 0, 2, 0, 7, 5, h'0020, 2, 0;
;SV0970
    .data.w 0, 0
    .data.l _SV_RCSS33_C20
    .data.w 138, 41, 0, 2, 0, 7, 6, h'0020, 2, 0;
;SV0971
    .data.w 0, 0
    .data.l _SV_RCSS43_C20
    .data.w 139, 41, 0, 2, 0, 7, 6, h'0020, 2, 0;
;SV0972
    .data.w 0, 0
    .data.l _SV_RCLSTA81_C20
    .data.w 53, 18, 0, 2, 0, 8, 1, h'0020, 2, 0;
;SV0973
    .data.w 0, 0
    .data.l _SV_RCLS81_C20
    .data.w 5, 18, 0, 2, 0, 8, 2, h'0020, 2, 0;
;SV0974
    .data.w 0, 0
    .data.l _SV_RCLSTA82_C20
    .data.w 53, 18, 0, 2, 0, 8, 3, h'0020, 2, 0;
;SV0975
    .data.w 0, 0
    .data.l _SV_RCLS82_C20
    .data.w 5, 18, 0, 2, 0, 8, 4, h'0020, 2, 0;
;SV0976
    .data.w 0, 0
    .data.l _SV_RCSS14_C20
    .data.w 138, 41, 0, 2, 0, 8, 5, h'0020, 2, 0;
;SV0977
    .data.w 0, 0
    .data.l _SV_RCSS24_C20
    .data.w 139, 41, 0, 2, 0, 8, 5, h'0020, 2, 0;
;SV0978
    .data.w 0, 0
    .data.l _SV_RCSS34_C20
    .data.w 138, 41, 0, 2, 0, 8, 6, h'0020, 2, 0;
;SV0979
    .data.w 0, 0
    .data.l _SV_RCSS44_C20
    .data.w 139, 41, 0, 2, 0, 8, 6, h'0020, 2, 0;
;SV0980
    .data.w 0, 0
    .data.l _SV_SMPMAX_CNT2
    .data.w 140, 0, 0, 2, 0, 9, 2, H'0008, 0, 0;
;SV0981
    .data.w 0, 0
    .data.l _SV_SMPCYC_TIM2
    .data.w 103, 0, 0, 2, 0, 11, 2, H'0008, 0, 0;
;SV0982
    .data.w 0, 0
    .data.l _SV_MOTREP_STGS
    .data.w 141, 138, 0, 2, 0, 1, 1, h'0004, 0, 0;
;SV0983
    .data.w 0, 0
    .data.l _SV_MOTREP_STGE
    .data.w 142, 138, 0, 2, 0, 1, 2, h'0004, 0, 0;
;SV0984
    .data.w 0, 0
    .data.l _SV_MOTREP_SPD
    .data.w 70, 138, 0, 2, 1, 1, 3, h'0004, 0, 0;
;SV0985
    .data.w 0, 0
    .data.l _SV_MOTREP_CNT
    .data.w 143, 138, 0, 2, 0, 1, 4, h'0004, 0, 0;
;SV0986
    .data.w 0, 0
    .data.l _SV0_FIXARA_AGLS
    .data.w 144, 139, h'0100, 2, 0, 2, 1, 0, 0, 0;
;SV0987
    .data.w 0, 0
    .data.l _SV0_FIXARA_POSS
    .data.w 145, 139, h'0400, 4, 2, 2, 2, 0, 0, 0;
;SV0988
    .data.w 0, 0
    .data.l _SV0_FIXARA_SPDB
    .data.w 70, 139, 0, 2, 1, 3, 1, 0, 0, 0;
;SV0989
    .data.w 0, 0
    .data.l _SV0_FIXARA_SPDF
    .data.w 70, 139, 0, 2, 1, 3, 1, 0, 0, 0;
;SV0990
    .data.w 0, 0
    .data.l _SV0_FIXARA_AGLE
    .data.w 146, 139, h'0100, 2, 0, 4, 1, 0, 0, 0;
;SV0991
    .data.w 0, 0
    .data.l _SV0_FIXARA_POSE
    .data.w 147, 139, h'0400, 4, 2, 4, 2, 0, 0, 0;
;SV0992
    .data.w 0, 0
    .data.l _SV_KAJOBJ_HAB
    .data.w 0, 142, 0, 2, 0, 27, 1, H'0004, 2, 101;
;SV0993
    .data.w 0, 0
    .data.l _SV_KAJOBJ_HAB
    .data.w 0, 142, 0, 2, 0, 27, 1, H'0004, 2, 101;
;SV0994
    .data.w 0, 0
    .data.l _SV_ORGCAL_DAT1
    .data.w 151, 0, 0, 4, 0, 3, 2, h'0001, 0, 0;
;SV0995
    .data.w 0, 0
    .data.l _SV0_RNAORG_ENB1
    .data.w 60, 0, 0, 2, 0, 1, 1, 0, 0, 0;
;SV0996
    .data.w 0, 0
    .data.l _SV0_ORGCAL_ENB2
    .data.w 60, 0, 0, 2, 0, 2, 1, 0, 0, 0;
;SV0997
    .data.w 0, 0
    .data.l _SV0_ORGCAL_ENB1
    .data.w 60, 0, 0, 2, 0, 3, 1, 0, 0, 0;
;SV0998
    .data.w 0, 0
    .data.l _SV0_MACINE_ENB1
    .data.w 60, 0, 0, 2, 0, 4, 1, 0, 0, 0;
;SV0999
    .data.w 0, 0
    .data.l _SV0_OFSET_ENB
    .data.w 60, 0, 0, 2, 0, 7, 1, 0, 0, 0;
;SV1000
    .data.w 0, 0
    .data.l _SV0_KOUSEI_ENB
    .data.w 60, 0, 0, 2, 0, 8, 1, 0, 0, 0;
;SV1001
    .data.w 0, 0
    .data.l _SV0_MAXHIZ_ENB
    .data.w 60, 0, 0, 2, 0, 9, 1, 0, 0, 0;
;SV1002
    .data.w 0, 0
    .data.l _SV0_MAXKAJ_ENB
    .data.w 60, 0, 0, 2, 0, 10, 1, 0, 0, 0;
;SV1003
    .data.w 0, 0
    .data.l _SV0_KOUKAJ_ENB
    .data.w 60, 0, 0, 2, 0, 11, 1, 0, 0, 0;
;SV1004
    .data.w 0, 0
    .data.l _SV_LFEED_LNG1
    .data.w 0, 152, 0, 4, 2, 1, 1, h'0004, 0, 0;
;SV1005
    .data.w 0, 0
    .data.l _SV_LFEED_SPD1
    .data.w 0, 0, 0, 2, 0, 2, 1, h'0004, 0, 0;
;SV1006
    .data.w 0, 0
    .data.l _SV_LFEED_LNG1
    .data.w 0, 152, 0, 4, 2, 6, 1, h'0004, 0, 0;
;SV1007
    .data.w 0, 0
    .data.l _SV_LFEED_SPD1
    .data.w 2, 147, 0, 2, 0, 8, 1, h'0004, 0, 0;
;SV1008
    .data.w 0, 0
    .data.l _SV_LFEED_SPD2
    .data.w 161, 147, 0, 2, 0, 9, 1, h'0004, 0, 0;
;SV1009
    .data.w 0, 0
    .data.l _SV0_LFEED_HSIS
    .data.w 159, 147, H'0040, 2, 0, 10, 1, h'0004, 0, 0;
;SV1010
    .data.w 0, 0
    .data.l _SV_LFEED_HOSIN
    .data.w 159, 153, H'0020, 2, 2, 10, 2, h'0004, 0, 0;
;SV1011
    .data.w 0, 0
    .data.l _SV0_LFEED_HSOS
    .data.w 160, 147, H'0040, 2, 0, 10, 3, h'0004, 0, 0;
;SV1012
    .data.w 0, 0
    .data.l _SV_LFEED_HOSOT
    .data.w 160, 153, H'0020, 2, 2, 10, 4, h'0004, 0, 0;
;SV1013
    .data.w 0, 0
    .data.l _SV_LFEED_STRNO
    .data.w 53, 147, 0, 2, 0, 13, 1, h'0004, 0, 0;
;SV1014
    .data.w 0, 0
    .data.l _SV_LFEED_STRDEG
    .data.w 55, 148, h'0100, 2, 0, 13, 2, h'0004, 0, 0;
;SV1015
    .data.w 0, 0
    .data.l _SV_LFEED_STRPOS
    .data.w 162, 149, h'0400, 4, 2, 13, 3, h'0004, 0, 0;
;SV1016
    .data.w 0, 0
    .data.l _SV_LFEED_ENDNO
    .data.w 53, 147, 0, 2, 0, 14, 1, h'0004, 0, 0;
;SV1017
    .data.w 0, 0
    .data.l _SV_LFEED_ENDDEG
    .data.w 55, 150, h'0100, 2, 0, 14, 2, h'0004, 0, 0;
;SV1018
    .data.w 0, 0
    .data.l _SV_LFEED_ENDPOS
    .data.w 162, 151, h'0400, 4, 2, 14, 3, h'0004, 0, 0;
;SV1019
    .data.w 0, 0
    .data.l _SV_LFEED_SELNO
    .data.w 158, 147, 0, 2, 0, 5, 1, h'0004, 0, 0;
;SV1020
    .data.w 0, 0
    .data.l _SV_TAIKIKAKU_SRV
    .data.w 163, 0, h'0100, 2, 0, 1, 1, 0, 0, 0;
;SV1021
    .data.w 0, 0
    .data.l _SV_TAIKIPOS_SRV
    .data.w 164, 91, h'0400, 4, 2, 1, 2, 0, 0, 0;
;SV1022
    .data.w 0, 0
    .data.l _SV_MSSTAT_AGL
    .data.w 165, 0, h'0100, 2, 0, 2, 1, 0, 0, 0;
;SV1023
    .data.w 0, 0
    .data.l _SV_MSSTAT_POS
    .data.w 166, 155, h'0400, 4, 2, 2, 2, 0, 0, 0;
;SV1024
    .data.w 0, 0
    .data.l _SV_MSEND_AGL
    .data.w 167, 0, h'0100, 2, 0, 3, 1, 0, 0, 0;
;SV1025
    .data.w 0, 0
    .data.l _SV_MSEND_POS
    .data.w 168, 155, h'0400, 4, 2, 3, 2, 0, 0, 0;
;SV1026
    .data.w 0, 0
    .data.l _SV_MS_CNT
    .data.w 169, 0, 0, 2, 0, 4, 1, 0, 0, 0;
;SV1027
    .data.w 0, 0
    .data.l _SV_MSBAK_COR
    .data.w 170, 0, 0, 2, 0, 5, 1, 0, 0, 0;
;SV1028
    .data.w 0, 0
    .data.l _SV_MSSTD_SPD
    .data.w 171, 0, 0, 2, 1, 6, 1, 0, 0, 0;
;SV1029
    .data.w 0, 0
    .data.l _SV_RCLSTA11_C17T
    .data.w 53, 3, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV1030
    .data.w 0, 0
    .data.l _SV_RCLS11_C17T
    .data.w 5, 3, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV1031
    .data.w 0, 0
    .data.l _SV_RCLSTP12_C17T
    .data.w 53, 3, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV1032
    .data.w 0, 0
    .data.l _SV_RCLS12_C17T
    .data.w 172, 3, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV1033
    .data.w 0, 0
    .data.l _SV_RCLSTA21_C17T
    .data.w 53, 4, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV1034
    .data.w 0, 0
    .data.l _SV_RCLS21_C17T
    .data.w 5, 4, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV1035
    .data.w 0, 0
    .data.l _SV_RCLSTP22_C17T
    .data.w 53, 4, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV1036
    .data.w 0, 0
    .data.l _SV_RCLS22_C17T
    .data.w 172, 4, 0, 2, 0, 2, 4, h'0020, 2, 0;
;SV1037
    .data.w 0, 0
    .data.l _SV_RCLSTA31_C17T
    .data.w 53, 5, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV1038
    .data.w 0, 0
    .data.l _SV_RCLS31_C17T
    .data.w 5, 5, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV1039
    .data.w 0, 0
    .data.l _SV_RCLSTP32_C17T
    .data.w 53, 5, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV1040
    .data.w 0, 0
    .data.l _SV_RCLS32_C17T
    .data.w 172, 5, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV1041
    .data.w 0, 0
    .data.l _SV_RCLSTA41_C17T
    .data.w 53, 6, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV1042
    .data.w 0, 0
    .data.l _SV_RCLS41_C17T
    .data.w 5, 6, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV1043
    .data.w 0, 0
    .data.l _SV_RCLSTP42_C17T
    .data.w 53, 6, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV1044
    .data.w 0, 0
    .data.l _SV_RCLS42_C17T
    .data.w 172, 6, 0, 2, 0, 4, 4, h'0020, 2, 0;
;SV1045
    .data.w 0, 0
    .data.l _SV_RCLSTA51_C18T
    .data.w 53, 7, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV1046
    .data.w 0, 0
    .data.l _SV_RCLS51_C18T
    .data.w 5, 7, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV1047
    .data.w 0, 0
    .data.l _SV_RCLSTP52_C18T
    .data.w 53, 7, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV1048
    .data.w 0, 0
    .data.l _SV_RCLS52_C18T
    .data.w 172, 7, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV1049
    .data.w 0, 0
    .data.l _SV_RCLSTA61_C18T
    .data.w 53, 8, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV1050
    .data.w 0, 0
    .data.l _SV_RCLS61_C18T
    .data.w 5, 8, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV1051
    .data.w 0, 0
    .data.l _SV_RCLSTP62_C18T
    .data.w 53, 8, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV1052
    .data.w 0, 0
    .data.l _SV_RCLS62_C18T
    .data.w 172, 8, 0, 2, 0, 6, 4, h'0020, 2, 0;
;SV1053
    .data.w 0, 0
    .data.l _SV_RCLSTA71_C18T
    .data.w 53, 9, 0, 2, 0, 7, 1, h'0020, 2, 0;
;SV1054
    .data.w 0, 0
    .data.l _SV_RCLS71_C18T
    .data.w 5, 9, 0, 2, 0, 7, 2, h'0020, 2, 0;
;SV1055
    .data.w 0, 0
    .data.l _SV_RCLSTP72_C18T
    .data.w 53, 9, 0, 2, 0, 7, 3, h'0020, 2, 0;
;SV1056
    .data.w 0, 0
    .data.l _SV_RCLS72_C18T
    .data.w 172, 9, 0, 2, 0, 7, 4, h'0020, 2, 0;
;SV1057
    .data.w 0, 0
    .data.l _SV_RCLSTA81_C18T
    .data.w 53, 10, 0, 2, 0, 8, 1, h'0020, 2, 0;
;SV1058
    .data.w 0, 0
    .data.l _SV_RCLS81_C18T
    .data.w 5, 10, 0, 2, 0, 8, 2, h'0020, 2, 0;
;SV1059
    .data.w 0, 0
    .data.l _SV_RCLSTP82_C18T
    .data.w 53, 10, 0, 2, 0, 8, 3, h'0020, 2, 0;
;SV1060
    .data.w 0, 0
    .data.l _SV_RCLS82_C18T
    .data.w 172, 10, 0, 2, 0, 8, 4, h'0020, 2, 0;
;SV1061
    .data.w 0, 0
    .data.l _SV_RCLSTA11_C19T
    .data.w 53, 11, 0, 2, 0, 1, 1, h'0020, 2, 0;
;SV1062
    .data.w 0, 0
    .data.l _SV_RCLS11_C19T
    .data.w 5, 11, 0, 2, 0, 1, 2, h'0020, 2, 0;
;SV1063
    .data.w 0, 0
    .data.l _SV_RCLSTP12_C19T
    .data.w 53, 11, 0, 2, 0, 1, 3, h'0020, 2, 0;
;SV1064
    .data.w 0, 0
    .data.l _SV_RCLS12_C19T
    .data.w 172, 11, 0, 2, 0, 1, 4, h'0020, 2, 0;
;SV1065
    .data.w 0, 0
    .data.l _SV_RCLSTA21_C19T
    .data.w 53, 12, 0, 2, 0, 2, 1, h'0020, 2, 0;
;SV1066
    .data.w 0, 0
    .data.l _SV_RCLS21_C19T
    .data.w 5, 12, 0, 2, 0, 2, 2, h'0020, 2, 0;
;SV1067
    .data.w 0, 0
    .data.l _SV_RCLSTA22_C19T
    .data.w 53, 12, 0, 2, 0, 2, 3, h'0020, 2, 0;
;SV1068
    .data.w 0, 0
    .data.l _SV_RCLS22_C19T
    .data.w 172, 12, 0, 2, 0, 2, 4, h'0020, 2, 0;
;SV1069
    .data.w 0, 0
    .data.l _SV_RCLSTA31_C19T
    .data.w 53, 13, 0, 2, 0, 3, 1, h'0020, 2, 0;
;SV1070
    .data.w 0, 0
    .data.l _SV_RCLS31_C19T
    .data.w 5, 13, 0, 2, 0, 3, 2, h'0020, 2, 0;
;SV1071
    .data.w 0, 0
    .data.l _SV_RCLSTA32_C19T
    .data.w 53, 13, 0, 2, 0, 3, 3, h'0020, 2, 0;
;SV1072
    .data.w 0, 0
    .data.l _SV_RCLS32_C19T
    .data.w 172, 13, 0, 2, 0, 3, 4, h'0020, 2, 0;
;SV1073
    .data.w 0, 0
    .data.l _SV_RCLSTA41_C19T
    .data.w 53, 14, 0, 2, 0, 4, 1, h'0020, 2, 0;
;SV1074
    .data.w 0, 0
    .data.l _SV_RCLS41_C19T
    .data.w 5, 14, 0, 2, 0, 4, 2, h'0020, 2, 0;
;SV1075
    .data.w 0, 0
    .data.l _SV_RCLSTA42_C19T
    .data.w 53, 14, 0, 2, 0, 4, 3, h'0020, 2, 0;
;SV1076
    .data.w 0, 0
    .data.l _SV_RCLS42_C19T
    .data.w 172, 14, 0, 2, 0, 4, 4, h'0020, 2, 0;
;SV1077
    .data.w 0, 0
    .data.l _SV_RCLSTA51_C19T
    .data.w 53, 15, 0, 2, 0, 5, 1, h'0020, 2, 0;
;SV1078
    .data.w 0, 0
    .data.l _SV_RCLS51_C20T
    .data.w 5, 15, 0, 2, 0, 5, 2, h'0020, 2, 0;
;SV1079
    .data.w 0, 0
    .data.l _SV_RCLSTA52_C20T
    .data.w 53, 15, 0, 2, 0, 5, 3, h'0020, 2, 0;
;SV1080
    .data.w 0, 0
    .data.l _SV_RCLS52_C20T
    .data.w 172, 15, 0, 2, 0, 5, 4, h'0020, 2, 0;
;SV1081
    .data.w 0, 0
    .data.l _SV_RCLSTA61_C20T
    .data.w 53, 16, 0, 2, 0, 6, 1, h'0020, 2, 0;
;SV1082
    .data.w 0, 0
    .data.l _SV_RCLS61_C20T
    .data.w 5, 16, 0, 2, 0, 6, 2, h'0020, 2, 0;
;SV1083
    .data.w 0, 0
    .data.l _SV_RCLSTA62_C20T
    .data.w 53, 16, 0, 2, 0, 6, 3, h'0020, 2, 0;
;SV1084
    .data.w 0, 0
    .data.l _SV_RCLS62_C20T
    .data.w 172, 16, 0, 2, 0, 6, 4, h'0020, 2, 0;
;SV1085
    .data.w 0, 0
    .data.l _SV_RCLSTA71_C20T
    .data.w 53, 17, 0, 2, 0, 7, 1, h'0020, 2, 0;
;SV1086
    .data.w 0, 0
    .data.l _SV_RCLS71_C20T
    .data.w 5, 17, 0, 2, 0, 7, 2, h'0020, 2, 0;
;SV1087
    .data.w 0, 0
    .data.l _SV_RCLSTA72_C20T
    .data.w 53, 17, 0, 2, 0, 7, 3, h'0020, 2, 0;
;SV1088
    .data.w 0, 0
    .data.l _SV_RCLS72_C20T
    .data.w 172, 17, 0, 2, 0, 7, 4, h'0020, 2, 0;
;SV1089
    .data.w 0, 0
    .data.l _SV_RCLSTA81_C20T
    .data.w 53, 18, 0, 2, 0, 8, 1, h'0020, 2, 0;
;SV1090
    .data.w 0, 0
    .data.l _SV_RCLS81_C20T
    .data.w 5, 18, 0, 2, 0, 8, 2, h'0020, 2, 0;
;SV1091
    .data.w 0, 0
    .data.l _SV_RCLSTA82_C20T
    .data.w 53, 18, 0, 2, 0, 8, 3, h'0020, 2, 0;
;SV1092
    .data.w 0, 0
    .data.l _SV_RCLS82_C20T
    .data.w 172, 18, 0, 2, 0, 8, 4, h'0020, 2, 0;

