
; ***** 型データ関連アドレスマップ 外部参照定義 アセンブラ用 ****************
		.GLOBAL		_SEQ_016_SV_INI			; 初期回路設定シーケンス１６
		.GLOBAL		_SEQ_017_SV_INI			; 初期回路設定シーケンス１７
		.GLOBAL		_SEQ_018_SV_INI			; 初期回路設定シーケンス１８
		.GLOBAL		_SEQ_019_SV_INI			; 初期回路設定シーケンス１９
		.GLOBAL		_SEQ_020_SV_INI			; 初期回路設定シーケンス２０
		.GLOBAL		_SEQ_021_SV_INI			; 初期回路設定シーケンス２１
		.GLOBAL		_SEQ_022_SV_INI			; 初期回路設定シーケンス２２
		.GLOBAL		_SEQ_023_SV_INI			; 初期回路設定シーケンス２３
		.GLOBAL		_SEQ_024_SV_INI			; 初期回路設定シーケンス２４
		.GLOBAL		_SEQ_025_SV_INI			; 初期回路設定シーケンス２５
		.GLOBAL		_SEQ_026_SV_INI			; 初期回路設定シーケンス２６
		.GLOBAL		_SEQ_027_SV_INI			; 初期回路設定シーケンス２７
		.GLOBAL		_SEQ_028_SV_INI			; クラッチ初期設定シーケンス２８
		.GLOBAL		_SEQ_029_SV_INI			; クラッチ初期設定シーケンス２９
		.GLOBAL		_SEQ_030_SV_INI			; クラッチ初期設定シーケンス３０
		.GLOBAL		_SEQ_031_SV_INI			; 機能選択シーケンス３１
		.GLOBAL		_SEQ_032_SVB_INI		; 空き
		.GLOBAL		_SEQ_033_SVB_INI		; 空き
		.GLOBAL		_SEQ_034_SVB_INI		; 空き
		.GLOBAL		_SEQ_035_SVB_INI		; 空き
		.GLOBAL		_SEQ_036_SVB_INI		; 空き
		.GLOBAL		_SEQ_037_SVB_INI		; 空き
		.GLOBAL		_SEQ_038_SVB_INI		; 空き
		.GLOBAL		_SEQ_039_SVB_INI		; 空き
		.GLOBAL		_SEQ_040_SVB_INI		; 空き
		.GLOBAL		_SEQ_041_SVB_INI		; 空き
		.GLOBAL		_SEQ_042_SVB_INI		; 空き
		.GLOBAL		_SEQ_043_SVB_INI		; 空き
		.GLOBAL		_SEQ_044_SVB_INI		; 空き
		.GLOBAL		_SEQ_045_SVB_INI		; 空き
		.GLOBAL		_SEQ_046_SVB_INI		; 空き
		.GLOBAL		_SEQ_047_SVB_INI		; 空き
		.GLOBAL		_SEQ_048_SVB_INI		; 空き
		.GLOBAL		_SEQ_049_SVB_INI		; 空き
		.GLOBAL		_SEQ_050_SVB_INI		; 空き
		.GLOBAL		_SEQ_051_SVB_INI		; 空き
		.GLOBAL		_SEQ_052_SVB_INI		; 空き
		.GLOBAL		_SEQ_053_SVB_INI		; 空き
		.GLOBAL		_SEQ_054_SVB_INI		; 空き
		.GLOBAL		_SEQ_055_SVB_INI		; 空き
		.GLOBAL		_SEQ_056_SVB_INI		; 空き
		.GLOBAL		_SEQ_057_SVB_INI		; 空き
		.GLOBAL		_SEQ_058_SVB_INI		; 空き
		.GLOBAL		_SEQ_059_SVB_INI		; 空き
		.GLOBAL		_SEQ_060_SVB_INI		; 空き
		.GLOBAL		_SEQ_061_SVB_INI		; 空き
		.GLOBAL		_SEQ_062_SVB_INI		; 空き
		.GLOBAL		_SEQ_063_SVB_INI		; 空き
		.GLOBAL		_SEQ_064_SVB_INI		; 空き
		.GLOBAL		_SEQ_065_SVB_INI		; 空き
		.GLOBAL		_SEQ_066_SVB_INI		; 空き
		.GLOBAL		_SEQ_067_SVB_INI		; 空き
		.GLOBAL		_SEQ_068_SVB_INI		; 空き
		.GLOBAL		_SEQ_069_SVB_INI		; 空き
		.GLOBAL		_SEQ_070_SVB_INI		; 空き
		.GLOBAL		_SEQ_071_SVB_INI		; 空き
		.GLOBAL		_SEQ_072_SVB_INI		; 空き
		.GLOBAL		_SEQ_073_SVB_INI		; 空き
		.GLOBAL		_SEQ_074_SVB_INI		; 空き
		.GLOBAL		_SEQ_075_SVB_INI		; 空き
		.GLOBAL		_SEQ_076_SVB_INI		; 空き
		.GLOBAL		_SEQ_077_SVB_INI		; 空き
		.GLOBAL		_SEQ_078_SVB_INI		; 空き
		.GLOBAL		_SEQ_079_SVB_INI		; 空き
		.GLOBAL		_SEQ_DUMMY_01_INI		; ダミー
		.GLOBAL		_SV_SEQDT1_A91_INI		; シーケンスモニタ設定１
		.GLOBAL		_SV_SEQDT2_A91_INI		; シーケンスモニタ設定２
		.GLOBAL		_SV_SEQDT3_A91_INI		; シーケンスモニタ設定３
		.GLOBAL		_SV_SEQDT4_A91_INI		; シーケンスモニタ設定４
		.GLOBAL		_SV_DUMMY_A91_INI		; 空き
		.GLOBAL		_SV_POINT_A1_INI		; スライド調節　小数点位置
		.GLOBAL		_SV_KANDO_A21_INI		; スライド自動調節　感度
		.GLOBAL		_SV_UPDATA_A21_INI		; スライド自動調節　上限
		.GLOBAL		_SV_DNDATA_A21_INI		; スライド自動調節　下限
		.GLOBAL		_SV_GENITI_A21_INI		; スライド自動調節　現位置
		.GLOBAL		_SV_DNSTOP_A21_INI		; スライド自動調節　下降停止
		.GLOBAL		_SV_UPSTOP_A21_INI		; スライド自動調節　上昇停止
		.GLOBAL		_SV_MODORI_A21_INI		; スライド自動調節　戻り量
		.GLOBAL		_SV_SSEIDO_A21_INI		; スライド自動調節　制御精度
		.GLOBAL		_SV_DUMMY_A21_INI		; 空き
		.GLOBAL		_SV_MAXHIZ_A24_INI		; 荷重校正　最大歪１
		.GLOBAL		_SV_MAXKAJ_A24_INI		; 荷重校正　最大荷重１
		.GLOBAL		_SV_KOUKAJ_A24_INI		; 荷重校正　校正荷重１
		.GLOBAL		_SV_KOUSEI_A24_INI		; 荷重校正　校正精度
		.GLOBAL		_SV_MAXKA2_A24_INI		; 荷重校正　最大荷重２
		.GLOBAL		_SV_KOUKA2_A24_INI		; 荷重校正　校正荷重２
		.GLOBAL		_SV_MAXHI3_A24_INI		; 荷重校正　最大歪３
		.GLOBAL		_SV_MAXKA3_A24_INI		; 荷重校正　最大荷重３
		.GLOBAL		_SV_KOUKA3_A24_INI		; 荷重校正　校正荷重３
		.GLOBAL		_SV_APARAD_A24_INI		; 荷重校正　最低表示荷重
		.GLOBAL		_SV_COUNT1_A1_INI		; 内部カウンタ１
		.GLOBAL		_SV_COUNT2_A1_INI		; 内部カウンタ２
		.GLOBAL		_SV_COUNT3_A1_INI		; 内部カウンタ３
		.GLOBAL		_SV_TIMER1_A1_INI		; 内部タイマ１
		.GLOBAL		_SV_TIMER2_A1_INI		; 内部タイマ２
		.GLOBAL		_SV_TIMER3_A1_INI		; 内部タイマ３
		.GLOBAL		_SV_DUMMY_A1_INI		; 空き
		.GLOBAL		_SV_RCLSA1_A17_INI		; システムカムＡ　ＯＮ角度
		.GLOBAL		_SV_RCLSA2_A17_INI		; システムカムＡ　ＯＦＦ角度
		.GLOBAL		_SV_RCLSB1_A17_INI		; システムカムＢ　ＯＮ角度
		.GLOBAL		_SV_RCLSB2_A17_INI		; システムカムＢ　ＯＦＦ角度
		.GLOBAL		_SV_RCLSC1_A17_INI		; システムカムＣ　ＯＮ角度
		.GLOBAL		_SV_RCLSC2_A17_INI		; システムカムＣ　ＯＦＦ角度
		.GLOBAL		_SV_RCLSD1_A17_INI		; システムカムＤ　ＯＮ角度
		.GLOBAL		_SV_RCLSD2_A17_INI		; システムカムＤ　ＯＦＦ角度
		.GLOBAL		_SV_RCLSE1_A17_INI		; システムカムＥ　ＯＮ角度
		.GLOBAL		_SV_RCLSE2_A17_INI		; システムカムＥ　ＯＦＦ角度
		.GLOBAL		_SV_RCLSF1_A18_INI		; システムカムＦ　ＯＮ角度
		.GLOBAL		_SV_RCLSF2_A18_INI		; システムカムＦ　ＯＦＦ角度
		.GLOBAL		_SV_RCLSG1_A18_INI		; システムカムＧ　ＯＮ角度
		.GLOBAL		_SV_RCLSG2_A18_INI		; システムカムＧ　ＯＦＦ角度
		.GLOBAL		_SV_RCLSH1_A18_INI		; システムカムＨ　ＯＮ角度
		.GLOBAL		_SV_RCLSH2_A18_INI		; システムカムＨ　ＯＦＦ角度
		.GLOBAL		_SV_DUMMY_A18_INI		; 空き
		.GLOBAL		_SV_RNADIR_SEL1_INI		; ﾘﾆｱｾﾝｻ極性
		.GLOBAL		_SV_INCDIR_SEL1_INI		; PG極性
		.GLOBAL		_SV_INCPLS_1REV_INI		; PG1回転のﾊﾟﾙｽ選択
		.GLOBAL		_SV_INCPLS_HOSN_INI		; PG補正N　ﾓｰﾀN回
		.GLOBAL		_SV_INCPLS_HOSM_INI		; PG補正M　ｸﾗﾝｸ角度M
		.GLOBAL		_SV_MOTRPM_MAXM_INI		; ﾓｰﾀ最大回転数
		.GLOBAL		_SV_DNDINC_SPD1_INI		; 段取速度
		.GLOBAL		_SV_UPAREA_SPD1_INI		; 待機点復帰速度
		.GLOBAL		_SV_STDINC_SPD1_INI		; 寸動速度
		.GLOBAL		_SV_REVDAT_SPD1_INI		; 予備速度１
		.GLOBAL		_SV_REVDAT_SPD2_INI		; 予備速度２
		.GLOBAL		_SV_REVDAT_SPD3_INI		; 予備速度３
		.GLOBAL		_SV_TEPDAT_SPD1_INI		; 手動ﾊﾟﾙｻ速度
		.GLOBAL		_SV_TEPLAT_DAT1_INI		; 手動ﾊﾟﾙｻ低倍率
		.GLOBAL		_SV_TEPLAT_DAT2_INI		; 手動ﾊﾟﾙｻ高倍率
		.GLOBAL		_SV_INCPOS_KP01_INI		; PG位置比例ｹﾞｲﾝ
		.GLOBAL		_SV_RNAPOS_KP01_INI		; ﾘﾆｱ位置比例ｹﾞｲﾝ
		.GLOBAL		_SV_ACCLAT__TIM1_INI	; 加減速時間
		.GLOBAL		_SV_SSCURV_TIM1_INI		; Ｓ字時間
		.GLOBAL		_SV_UPAREA_INP1_INI		; 上死点ｲﾝﾎﾟｼﾞｼｮﾝ
		.GLOBAL		_SV_DNAREA_INP1_INI		; 下死点ｲﾝﾎﾟｼﾞｼｮﾝ
		.GLOBAL		_SV_OBJARA_INP1_INI		; 目標位置ｲﾝﾎﾟｼﾞｼｮﾝ
		.GLOBAL		_SV_INPPOS_TIM1_INI		; ｲﾝﾎﾟｼﾞｼｮﾝﾁｪｯｸ時間
		.GLOBAL		_SV_ARACHK_LNG1_INI		; 上／下死点通過判定量
		.GLOBAL		_SV_UPAREA_DIG1_INI		; 回転時待機点(上死点)
		.GLOBAL		_SV_DUMMY_A22_INI		; 空き
		.GLOBAL		_SV_UPAREA_JUDG_INI		; 上死点判定範囲
		.GLOBAL		_SV_DNAREA_JUDG_INI		; 反転設定不可範囲
		.GLOBAL		_SV_INCHEN_ELNG_INI		; PG偏差異常幅
		.GLOBAL		_SV_INCENC_ELNG_INI		; PG-ENC一致量
		.GLOBAL		_SV_INCRNA_ELNG_INI		; PG-ﾘﾆｱ一致量
		.GLOBAL		_SV_INCSTP_ELNG_INI		; PG停止異常量
		.GLOBAL		_SV_RNASTP_ELNG_INI		; ﾘﾆｱ停止異常量
		.GLOBAL		_SV_INCREV_ELNG_INI		; PG逆転異常量
		.GLOBAL		_SV_RNAREV_ELNG_INI		; ﾘﾆｱ逆転異常量
		.GLOBAL		_SV_DAIHAI_LNG1_INI		; ﾀﾞｲﾊｲﾄ補正比較値(小)
		.GLOBAL		_SV_DAIHAI_LNG2_INI		; ﾀﾞｲﾊｲﾄ補正比較値(中)
		.GLOBAL		_SV_DAIHAI_LNG3_INI		; ﾀﾞｲﾊｲﾄ補正比較値(大)
		.GLOBAL		_SV_AMPERR_VLT1_INI		; 過負荷電圧1
		.GLOBAL		_SV_AMPERR_TIM1_INI		; 過負荷時間1
		.GLOBAL		_SV_AMPERR_VLT2_INI		; 過負荷電圧2
		.GLOBAL		_SV_AMPERR_TIM2_INI		; 過負荷時間2
		.GLOBAL		_SV_AMPERR_VLT3_INI		; 過負荷電圧3
		.GLOBAL		_SV_AMPERR_TIM3_INI		; 過負荷時間3
		.GLOBAL		_SV_SERVO_44_INI		; サーボパラメータ４４
		.GLOBAL		_SV_SERVO_45_INI		; サーボパラメータ４５
		.GLOBAL		_SV_SERVO_46_INI		; サーボパラメータ４６
		.GLOBAL		_SV_SERVO_47_INI		; サーボパラメータ４７
		.GLOBAL		_SV_SERVO_48_INI		; サーボパラメータ４８
		.GLOBAL		_SV_SERVO_49_INI		; サーボパラメータ４９
		.GLOBAL		_SV_RNA_STLORK_INI		; ストローク設定
		.GLOBAL		_SV_OUTPLS_HOSA_INI		; 出力ﾊﾟﾙｽ補正A
		.GLOBAL		_SV_OUTPLS_HOSB_INI		; 出力ﾊﾟﾙｽ補正B
		.GLOBAL		_SV_UPHOLD_DIG_INI		; 上昇ﾎｰﾙﾄﾞ角度
		.GLOBAL		_SV_MACINE_SEL1_INI		; 予備（機種選択１）
		.GLOBAL		_SV_SERVO_56_INI		; サーボパラメータ５６
		.GLOBAL		_SV_SERVO_57_INI		; サーボパラメータ５７
		.GLOBAL		_SV_SERVO_58_INI		; サーボパラメータ５８
		.GLOBAL		_SV_SERVO_59_INI		; サーボパラメータ５９
		.GLOBAL		_SV_SERVO_60_INI		; サーボパラメータ６０
		.GLOBAL		_SV_SERVO_61_INI		; サーボパラメータ６１
		.GLOBAL		_SV_SERVO_62_INI		; サーボパラメータ６２
		.GLOBAL		_SV_SERVO_63_INI		; サーボパラメータ６３
		.GLOBAL		_SV_SERVO_64_INI		; サーボパラメータ６４
		.GLOBAL		_SV_SERVO_65_INI		; サーボパラメータ６５
		.GLOBAL		_SV_SERVO_66_INI		; サーボパラメータ６６
		.GLOBAL		_SV_SERVO_67_INI		; サーボパラメータ６７
		.GLOBAL		_SV_SERVO_68_INI		; サーボパラメータ６８
		.GLOBAL		_SV_SERVO_69_INI		; サーボパラメータ６９
		.GLOBAL		_SV_SERVO_70_INI		; サーボパラメータ７０
		.GLOBAL		_SV_DUMMY_18_INI		; 空き
		.GLOBAL		_SV_MOTMAX_FREQ_INI		; ﾓｰﾀ最大時指令周波数
		.GLOBAL		_SV_RNAORG_POS1_INI		; 機械原点入力
		.GLOBAL		_SV_RNAPOS_MAXP_INI		; 機械上限
		.GLOBAL		_SV_RNAPOS_MINP_INI		; 機械下限
		.GLOBAL		_SV_SERVO_80_INI		; サーボパラメータ８０
		.GLOBAL		_SV_SERVO_81_INI		; サーボパラメータ８１
		.GLOBAL		_SV_SERVO_82_INI		; サーボパラメータ８２
		.GLOBAL		_SV_SERVO_83_INI		; サーボパラメータ８３
		.GLOBAL		_SV_SERVO_84_INI		; サーボパラメータ８４
		.GLOBAL		_SV_SERVO_85_INI		; サーボパラメータ８５
		.GLOBAL		_SV_SERVO_86_INI		; サーボパラメータ８６
		.GLOBAL		_SV_SERVO_87_INI		; サーボパラメータ８７
		.GLOBAL		_SV_SERVO_88_INI		; サーボパラメータ８８
		.GLOBAL		_SV_SERVO_89_INI		; サーボパラメータ８９
		.GLOBAL		_SV_SERVO_90_INI		; サーボパラメータ９０
		.GLOBAL		_SV_SERVO_91_INI		; サーボパラメータ９１
		.GLOBAL		_SV_SERVO_92_INI		; サーボパラメータ９２
		.GLOBAL		_SV_SERVO_93_INI		; サーボパラメータ９３
		.GLOBAL		_SV_SERVO_94_INI		; サーボパラメータ９４
		.GLOBAL		_SV_SERVO_95_INI		; サーボパラメータ９５
		.GLOBAL		_SV_SERVO_96_INI		; サーボパラメータ９６
		.GLOBAL		_SV_SERVO_97_INI		; サーボパラメータ９７
		.GLOBAL		_SV_SERVO_98_INI		; サーボパラメータ９８
		.GLOBAL		_SV_SERVO_99_INI		; サーボパラメータ９９
		.GLOBAL		_SV_SERVO_100_INI		; サーボパラメータ１００
		.GLOBAL		_SV_DUMMY_101_INI		; 予備
		.GLOBAL		_SV_SPMSV1_A1_INI		; 検出速度１
		.GLOBAL		_SV_SPMSV2_A1_INI		; 検出速度２
		.GLOBAL		_SV_SPMSV3_A1_INI		; 検出速度３
		.GLOBAL		_SV_SPMSV4_A1_INI		; 段取速度１
		.GLOBAL		_SV_SPMSV5_A1_INI		; 段取速度２
		.GLOBAL		_SV_MAXSPM_A14_INI		; 機械最高速度設定
		.GLOBAL		_SV_RNZ100_A15_INI		; 待機点１連続　　１００％設定
		.GLOBAL		_SV_RNZ090_A15_INI		; 待機点１連続　　　９０％設定
		.GLOBAL		_SV_RNZ080_A15_INI		; 待機点１連続　　　８０％設定
		.GLOBAL		_SV_RNZ070_A15_INI		; 待機点１連続　　　７０％設定
		.GLOBAL		_SV_RNZ060_A15_INI		; 待機点１連続　　　６０％設定
		.GLOBAL		_SV_RNZ050_A15_INI		; 待機点１連続　　　５０％設定
		.GLOBAL		_SV_ITK100_A15_INI		; 待機点１一行程　１００％設定
		.GLOBAL		_SV_ITK090_A15_INI		; 待機点１一行程　　９０％設定
		.GLOBAL		_SV_ITK080_A15_INI		; 待機点１一行程　　８０％設定
		.GLOBAL		_SV_ITK070_A15_INI		; 待機点１一行程　　７０％設定
		.GLOBAL		_SV_ITK060_A15_INI		; 待機点１一行程　　６０％設定
		.GLOBAL		_SV_ITK050_A15_INI		; 待機点１一行程　　５０％設定
		.GLOBAL		_SV_RNZ100_A152_INI		; 待機点２連続　　１００％設定
		.GLOBAL		_SV_RNZ090_A152_INI		; 待機点２連続　　　９０％設定
		.GLOBAL		_SV_RNZ080_A152_INI		; 待機点２連続　　　８０％設定
		.GLOBAL		_SV_RNZ070_A152_INI		; 待機点２連続　　　７０％設定
		.GLOBAL		_SV_RNZ060_A152_INI		; 待機点２連続　　　６０％設定
		.GLOBAL		_SV_RNZ050_A152_INI		; 待機点２連続　　　５０％設定
		.GLOBAL		_SV_ITK100_A152_INI		; 待機点２一行程　１００％設定
		.GLOBAL		_SV_ITK090_A152_INI		; 待機点２一行程　　９０％設定
		.GLOBAL		_SV_ITK080_A152_INI		; 待機点２一行程　　８０％設定
		.GLOBAL		_SV_ITK070_A152_INI		; 待機点２一行程　　７０％設定
		.GLOBAL		_SV_ITK060_A152_INI		; 待機点２一行程　　６０％設定
		.GLOBAL		_SV_ITK050_A152_INI		; 待機点２一行程　　５０％設定
		.GLOBAL		_SV_RNZ100_A153_INI		; 待機点３連続　　１００％設定
		.GLOBAL		_SV_RNZ090_A153_INI		; 待機点３連続　　　９０％設定
		.GLOBAL		_SV_RNZ080_A153_INI		; 待機点３連続　　　８０％設定
		.GLOBAL		_SV_RNZ070_A153_INI		; 待機点３連続　　　７０％設定
		.GLOBAL		_SV_RNZ060_A153_INI		; 待機点３連続　　　６０％設定
		.GLOBAL		_SV_RNZ050_A153_INI		; 待機点３連続　　　５０％設定
		.GLOBAL		_SV_ITK100_A153_INI		; 待機点３一行程　１００％設定
		.GLOBAL		_SV_ITK090_A153_INI		; 待機点３一行程　　９０％設定
		.GLOBAL		_SV_ITK080_A153_INI		; 待機点３一行程　　８０％設定
		.GLOBAL		_SV_ITK070_A153_INI		; 待機点３一行程　　７０％設定
		.GLOBAL		_SV_ITK060_A153_INI		; 待機点３一行程　　６０％設定
		.GLOBAL		_SV_ITK050_A153_INI		; 待機点３一行程　　５０％設定
		.GLOBAL		_SV_KAGENS_A1_INI		; 加減速時間
		.GLOBAL		_SV_DUMMY_102_INI		; 空き
		.GLOBAL		_SV_DUMMY_103_INI		; 空き
		.GLOBAL		_SV_DUMMY_104_INI		; 空き
		.GLOBAL		_SV_DUMMY_105_INI		; 空き
		.GLOBAL		_SV_DUMMY_106_INI		; 空き
		.GLOBAL		_SV_DUMMY_107_INI		; 空き
		.GLOBAL		_SV_SPM001_A15_INI		; 最高速度設定の１００％演算値
		.GLOBAL		_SV_SPM002_A15_INI		; 最高速度設定の　９０％演算値
		.GLOBAL		_SV_SPM003_A15_INI		; 最高速度設定の　８０％演算値
		.GLOBAL		_SV_SPM004_A15_INI		; 最高速度設定の　７０％演算値
		.GLOBAL		_SV_SPM005_A15_INI		; 最高速度設定の　６０％演算値
		.GLOBAL		_SV_SPM006_A15_INI		; 最高速度設定の　５０％演算値
		.GLOBAL		_SV_SPM001_A152_INI		; 空き
		.GLOBAL		_SV_SPM002_A152_INI		; 空き
		.GLOBAL		_SV_SPM003_A152_INI		; 空き
		.GLOBAL		_SV_SPM004_A152_INI		; 空き
		.GLOBAL		_SV_SPM005_A152_INI		; 空き
		.GLOBAL		_SV_SPM006_A152_INI		; 空き
		.GLOBAL		_SV_SPM001_A153_INI		; 空き
		.GLOBAL		_SV_SPM002_A153_INI		; 空き
		.GLOBAL		_SV_SPM003_A153_INI		; 空き
		.GLOBAL		_SV_SPM004_A153_INI		; 空き
		.GLOBAL		_SV_SPM005_A153_INI		; 空き
		.GLOBAL		_SV_DUMMY_A153_INI		; 空き
		.GLOBAL		_SV_POINT_A47_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節左　小数点位置
		.GLOBAL		_SV_KANDO_A47_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節左　感度
		.GLOBAL		_SV_UPDATA_A47_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節左　上限
		.GLOBAL		_SV_DNDATA_A47_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節左　下限
		.GLOBAL		_SV_GENITI_A47_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節左　現位置
		.GLOBAL		_SV_DNSTOP_A47_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節左　下降停止
		.GLOBAL		_SV_UPSTOP_A47_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節左　上昇停止
		.GLOBAL		_SV_MODORI_A47_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節左　戻り量
		.GLOBAL		_SV_SSEIDO_A47_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節左　制御精度
		.GLOBAL		_SV_DUMMY_A17_INI		; 空き
		.GLOBAL		_SV_POINT_A48_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節右　小数点位置
		.GLOBAL		_SV_KANDO_A48_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節右　感度
		.GLOBAL		_SV_UPDATA_A48_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節右　上限
		.GLOBAL		_SV_DNDATA_A48_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節右　下限
		.GLOBAL		_SV_GENITI_A48_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節右　現位置
		.GLOBAL		_SV_DNSTOP_A48_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節右　下降停止
		.GLOBAL		_SV_UPSTOP_A48_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節右　上昇停止
		.GLOBAL		_SV_MODORI_A48_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節右　戻り量
		.GLOBAL		_SV_SSEIDO_A48_INI		; ﾀﾞｲｸｯｼｮﾝ自動調節右　制御精度
		.GLOBAL		_SV_BARAUP_A49_INI		; バランサ圧力調節　上限
		.GLOBAL		_SV_BARADN_A49_INI		; バランサ圧力調節　上限
		.GLOBAL		_SV_DAILUP_A49_INI		; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ左上限
		.GLOBAL		_SV_DAILDN_A49_INI		; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ左下限
		.GLOBAL		_SV_DAIRUP_A49_INI		; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ右上限
		.GLOBAL		_SV_DAIRDN_A49_INI		; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ右下限
		.GLOBAL		_SV_SYUMAX_A14_INI		; 仕様速度以下
		.GLOBAL		_SV_CLTIME_C1_INI		; クラッチタイム
		.GLOBAL		_SV_BRTIME_C1_INI		; ブレーキタイム 設定
		.GLOBAL		_SV_BRDIG_C1_INI		; ブレーキ角度 設定
		.GLOBAL		_SV_BARKIJ_A45_INI		; バランサ圧基準
		.GLOBAL		_SV_CILDN1_A50_INI		; コイルライン設定上限値１
		.GLOBAL		_SV_CILUP1_A50_INI		; コイルライン設定下限値１
		.GLOBAL		_SV_CILDN2_A50_INI		; コイルライン設定上限値２
		.GLOBAL		_SV_CILUP2_A50_INI		; コイルライン設定下限値２
		.GLOBAL		_SV_CILDN3_A50_INI		; コイルライン設定上限値３
		.GLOBAL		_SV_CILUP3_A50_INI		; コイルライン設定下限値３
		.GLOBAL		_SV_CILDN4_A50_INI		; コイルライン設定上限値４
		.GLOBAL		_SV_CILUP4_A50_INI		; コイルライン設定下限値４
		.GLOBAL		_SV_CILDN5_A50_INI		; コイルライン設定上限値５
		.GLOBAL		_SV_CILUP5_A50_INI		; コイルライン設定下限値５
		.GLOBAL		_SV_CILDN6_A50_INI		; コイルライン設定上限値６
		.GLOBAL		_SV_CILUP6_A50_INI		; コイルライン設定下限値６
		.GLOBAL		_SV_CILTN1_A50_INI		; コイルライン設定１小数点
		.GLOBAL		_SV_CILTN2_A50_INI		; コイルライン設定２小数点
		.GLOBAL		_SV_CILTN3_A50_INI		; コイルライン設定３小数点
		.GLOBAL		_SV_CILTN4_A50_INI		; コイルライン設定４小数点
		.GLOBAL		_SV_CILTN5_A50_INI		; コイルライン設定５小数点
		.GLOBAL		_SV_CILTN6_A50_INI		; コイルライン設定６小数点
		.GLOBAL		_SV_CILUMU_A50_INI		; コイルライン設定有無選択
		.GLOBAL		_SV_CILMAI_A50_INI		; コイルライン設定マイナス選択






		.GLOBAL		_SV_NEXTNO_D1_INI		; 自動金型用次期ファイル読み出し番号
		.GLOBAL		_SV_DUMMY_D1_INI		; 空き
		.GLOBAL		_FRAM_KAT_TOP_INI		; F-RAM領域の型データのトップラベル
		.GLOBAL		_SV_DUMMY_D2_INI		; 空き
		.GLOBAL		_SEQ_032_SV_INI			; トータル＆ロットカウンタ　入／切選択
		.GLOBAL		_SEQ_033_SV_INI			; 空き
		.GLOBAL		_SEQ_034_SV_INI			; エジェクタ１～６　入／切選択、カム／タイマ選択
		.GLOBAL		_SEQ_035_SV_INI			; 空き
		.GLOBAL		_SEQ_036_SV_INI			; ミスフィード１～４　入／切、即／連
		.GLOBAL		_SEQ_037_SV_INI			; ミスフィード１～４　N.O／Ｎ．Ｃ、接触／保持
		.GLOBAL		_SEQ_038_SV_INI			; ロータリカム１～１６　入／切選択
		.GLOBAL		_SEQ_039_SV_INI			; ロータリカム１７～２０　入／切選択
		.GLOBAL		_SEQ_040_SV_INI			; 空き
		.GLOBAL		_SEQ_041_SV_INI			; 上型クランパ、下型クランパ　内／全／外選択
		.GLOBAL		_SEQ_042_SV_INI			; ダイリフタ　内/全／外選択
		.GLOBAL		_SEQ_043_SV_INI			; 空き
		.GLOBAL		_SEQ_044_SV_INI			; ｽﾗｲﾄﾞ自動調節 生産／段取１／段取２選択
		.GLOBAL		_SEQ_045_SV_INI			; 空き
		.GLOBAL		_SEQ_046_SV_INI			; 空き
		.GLOBAL		_SEQ_047_SV_INI			; 空き
		.GLOBAL		_SEQ_048_SV_INI			; 空き
		.GLOBAL		_SEQ_049_SV_INI			; 空き
		.GLOBAL		_SEQ_050_SV_INI			; 空き
		.GLOBAL		_SEQ_051_SV_INI			; 空き
		.GLOBAL		_SEQ_052_SV_INI			; 空き
		.GLOBAL		_SEQ_053_SV_INI			; 空き
		.GLOBAL		_SEQ_054_SV_INI			; 空き
		.GLOBAL		_SEQ_055_SV_INI			; 空き
		.GLOBAL		_SEQ_056_SV_INI			; 空き
		.GLOBAL		_SEQ_057_SV_INI			; 空き
		.GLOBAL		_SEQ_058_SV_INI			; 空き
		.GLOBAL		_SEQ_059_SV_INI			; 空き
		.GLOBAL		_SEQ_060_SV_INI			; 空き
		.GLOBAL		_SEQ_061_SV_INI			; 空き
		.GLOBAL		_SEQ_062_SV_INI			; 空き
		.GLOBAL		_SEQ_063_SV_INI			; 空き
		.GLOBAL		_SEQ_064_SV_INI			; 空き
		.GLOBAL		_SEQ_065_SV_INI			; 空き
		.GLOBAL		_SEQ_066_SV_INI			; 空き
		.GLOBAL		_SEQ_067_SV_INI			; 空き
		.GLOBAL		_SEQ_068_SV_INI			; 空き
		.GLOBAL		_SEQ_069_SV_INI			; 空き
		.GLOBAL		_SEQ_070_SV_INI			; 空き
		.GLOBAL		_SEQ_071_SV_INI			; 空き
		.GLOBAL		_SEQ_072_SV_INI			; 空き
		.GLOBAL		_SEQ_073_SV_INI			; 空き
		.GLOBAL		_SEQ_074_SV_INI			; 空き
		.GLOBAL		_SEQ_075_SV_INI			; 空き
		.GLOBAL		_SEQ_076_SV_INI			; 空き
		.GLOBAL		_SEQ_077_SV_INI			; 空き
		.GLOBAL		_SEQ_078_SV_INI			; 空き
		.GLOBAL		_SEQ_079_SV_INI			; 空き
		.GLOBAL		_SV_PUR1SV_B4_INI		; ロットカウンタ１設定値
		.GLOBAL		_SV_PUR2SV_B41_INI		; ロットカウンタ２設定値
		.GLOBAL		_SV_TAIKIPOS0_SRV_INI	; 待機位置
		.GLOBAL		_SV_KAITEN0_SRV_INI		; 回転方式
		.GLOBAL		_SV_DANSUU0_SRV_INI		; 段数
		.GLOBAL		_SV_TAIKIKAKU0_SRV_INI	; 待機角
		.GLOBAL		_SV_TAIKSPD0_SRV_INI	; 基準速度
		.GLOBAL		_SV_DAIHAITO0_SRV_INI	; ダイハイト
		.GLOBAL		_SV_HOASEI0_SRV_INI		; 補正データ
		.GLOBAL		_SV_TAIKTIM0_SRV_INI	; 待機時間
		.GLOBAL		_SV_1DANDEG0_SRV_INI	; 1段目目標角度
		.GLOBAL		_SV_2DANDEG0_SRV_INI	; 2段目目標角度
		.GLOBAL		_SV_3DANDEG0_SRV_INI	; 3段目目標角度
		.GLOBAL		_SV_4DANDEG0_SRV_INI	; 4段目目標角度
		.GLOBAL		_SV_5DANDEG0_SRV_INI	; 5段目目標角度
		.GLOBAL		_SV_6DANDEG0_SRV_INI	; 6段目目標角度
		.GLOBAL		_SV_7DANDEG0_SRV_INI	; 7段目目標角度
		.GLOBAL		_SV_8DANDEG0_SRV_INI	; 8段目目標角度
		.GLOBAL		_SV_9DANDEG0_SRV_INI	; 9段目目標角度
		.GLOBAL		_SV_10DANDEG0_SRV_INI	; 10段目目標角度
		.GLOBAL		_SV_1DANPOS0_SRV_INI	; 1段目目標位置
		.GLOBAL		_SV_2DANPOS0_SRV_INI	; 2段目目標位置
		.GLOBAL		_SV_3DANPOS0_SRV_INI	; 3段目目標位置
		.GLOBAL		_SV_4DANPOS0_SRV_INI	; 4段目目標位置
		.GLOBAL		_SV_5DANPOS0_SRV_INI	; 5段目目標位置
		.GLOBAL		_SV_6DANPOS0_SRV_INI	; 6段目目標位置
		.GLOBAL		_SV_7DANPOS0_SRV_INI	; 7段目目標位置
		.GLOBAL		_SV_8DANPOS0_SRV_INI	; 8段目目標位置
		.GLOBAL		_SV_9DANPOS0_SRV_INI	; 9段目目標位置
		.GLOBAL		_SV_10DANPOS0_SRV_INI	; 10段目目標位置
		.GLOBAL		_SV_1DANSPD0_SRV_INI	; 1段目移動速度
		.GLOBAL		_SV_2DANSPD0_SRV_INI	; 2段目移動速度
		.GLOBAL		_SV_3DANSPD0_SRV_INI	; 3段目移動速度
		.GLOBAL		_SV_4DANSPD0_SRV_INI	; 4段目移動速度
		.GLOBAL		_SV_5DANSPD0_SRV_INI	; 5段目移動速度
		.GLOBAL		_SV_6DANSPD0_SRV_INI	; 6段目移動速度
		.GLOBAL		_SV_7DANSPD0_SRV_INI	; 7段目移動速度
		.GLOBAL		_SV_8DANSPD0_SRV_INI	; 8段目移動速度
		.GLOBAL		_SV_9DANSPD0_SRV_INI	; 9段目移動速度
		.GLOBAL		_SV_10DANSPD0_SRV_INI	; 10段目移動速度
		.GLOBAL		_SV_1DANTIM0_SRV_INI	; 1段目停止時間
		.GLOBAL		_SV_2DANTIM0_SRV_INI	; 2段目停止時間
		.GLOBAL		_SV_3DANTIM0_SRV_INI	; 3段目停止時間
		.GLOBAL		_SV_4DANTIM0_SRV_INI	; 4段目停止時間
		.GLOBAL		_SV_5DANTIM0_SRV_INI	; 5段目停止時間
		.GLOBAL		_SV_6DANTIM0_SRV_INI	; 6段目停止時間
		.GLOBAL		_SV_7DANTIM0_SRV_INI	; 7段目停止時間
		.GLOBAL		_SV_8DANTIM0_SRV_INI	; 8段目停止時間
		.GLOBAL		_SV_9DANTIM0_SRV_INI	; 9段目停止時間
		.GLOBAL		_SV_10DANTIM0_SRV_INI	; 10段目停止時間
		.GLOBAL		_SV_CYCTIM0_SRV_INI		; サイクルタイム
		.GLOBAL		_SV_TAIKAN0_SRV_INI		; 待機完了範囲
		.GLOBAL		_SV_MOKKAN0_SRV_INI		; 目標完了範囲
		.GLOBAL		_SV_DUMMY_B11_INI		; 空き
		.GLOBAL		_SV_EJESAT1_C4_INI		; エジェクタ１　ＯＮ工程　　　カム仕様
		.GLOBAL		_SV_EJEKK1_C4_INI		; エジェクタ１　ＯＮ角度　　　カム仕様
		.GLOBAL		_SV_EJESTP1_C4_INI		; エジェクタ１　ＯＦＦ工程　　　カム仕様
		.GLOBAL		_SV_EJEKK2_C4_INI		; エジェクタ１　ＯＦＦ角度　　カム仕様
		.GLOBAL		_SV_EJESAT1_C4A_INI		; エジェクタ２　ＯＮ工程　　　カム仕様
		.GLOBAL		_SV_EJEKK1_C4A_INI		; エジャクタ２　ＯＮ角度　　　カム仕様
		.GLOBAL		_SV_EJESTP1_C4A_INI		; エジェクタ２　ＯＦＦ工程　　　カム仕様
		.GLOBAL		_SV_EJEKK2_C4A_INI		; エジェクタ２　ＯＦＦ角度　　カム仕様
		.GLOBAL		_SV_EJESAT1_C4B_INI		; エジェクタ３　ＯＮ工程　　　カム仕様
		.GLOBAL		_SV_EJEKK1_C4B_INI		; エジャクタ３　ＯＮ角度　　　カム仕様
		.GLOBAL		_SV_EJESTP1_C4B_INI		; エジェクタ３　ＯＦＦ工程　　　カム仕様
		.GLOBAL		_SV_EJEKK2_C4B_INI		; エジェクタ３　ＯＦＦ角度　　カム仕様
		.GLOBAL		_SV_AUTSTA_C41_INI		; 自動化１　ＯＮ工程　　　カム仕様
		.GLOBAL		_SV_AUTKK1_C41_INI		; 自動化１　ＯＮ角度　　　カム仕様
		.GLOBAL		_SV_AUTSTP_C41_INI		; 自動化１　ＯFF工程　　　カム仕様
		.GLOBAL		_SV_AUTKK2_C41_INI		; 自動化１　ＯＦＦ角度　　　カム仕様
		.GLOBAL		_SV_AUTSTA_C41A_INI		; 自動化２　ＯＮ工程　　　カム仕様
		.GLOBAL		_SV_AUTKK1_C41A_INI		; 自動化２　ＯＮ角度　　　カム仕様
		.GLOBAL		_SV_AUTSTP_C41A_INI		; 自動化２　ＯFF工程　　　カム仕様
		.GLOBAL		_SV_AUTKK2_C41A_INI		; 自動化２　ＯＦＦ角度　　　カム仕様
		.GLOBAL		_SV_AUTSTA_C41B_INI		; 自動化３　ＯＮ工程　　　カム仕様
		.GLOBAL		_SV_AUTKK1_C41B_INI		; 自動化３　ＯＮ角度　　　カム仕様
		.GLOBAL		_SV_AUTSTP_C41B_INI		; 自動化３　ＯFF程　　　カム仕様
		.GLOBAL		_SV_AUTKK2_C41B_INI		; 自動化３　ＯＦＦ角度　　　カム仕様
		.GLOBAL		_SV_EJESTA_C5_INI		; エジェクタ１　ＯＮ工程　　　タイマ仕様
		.GLOBAL		_SV_EJEKK3_C5_INI		; エジェクタ１　ＯＮ角度　　　タイマ仕様
		.GLOBAL		_SV_EJESTP_C5_INI		; エジェクタ１　ＯＦＦ工程　　　タイマ仕様
		.GLOBAL		_SV_EJETIM_C5_INI		; エジェクタ１　ＯＦＦタイマ　タイマ仕様
		.GLOBAL		_SV_EJESTA_C5A_INI		; エジェクタ２　ＯＮ工程　　　タイマ仕様
		.GLOBAL		_SV_EJEKK3_C5A_INI		; エジェクタ２　ＯＮ角度　　　タイマ仕様
		.GLOBAL		_SV_EJESTP_C5A_INI		; エジェクタ２　ＯＦＦ工程　　　タイマ仕様
		.GLOBAL		_SV_EJETIM_C5A_INI		; エジェクタ２　ＯＦＦタイマ　タイマ仕様
		.GLOBAL		_SV_EJESTA_C5B_INI		; エジェクタ３　ＯＮ工程　　　タイマ仕様
		.GLOBAL		_SV_EJEKK3_C5B_INI		; エジェクタ３　ＯＮ角度　　　タイマ仕様
		.GLOBAL		_SV_EJESTP_C5B_INI		; エジェクタ２　ＯＦＦ工程　　　タイマ仕様
		.GLOBAL		_SV_EJETIM_C5B_INI		; エジェクタ３　ＯＦＦタイマ　タイマ仕様
		.GLOBAL		_SV_AUTSTA_C51_INI		; 自動化１　ＯＮ工程　　　タイマ仕様
		.GLOBAL		_SV_AUTKK3_C51_INI		; 自動化１　ＯＮ角度　　　　　タイマ仕様
		.GLOBAL		_SV_AUTSTP_C51_INI		; 自動化１　ＯFF工程　　　タイマ仕様
		.GLOBAL		_SV_AUTTIM_C51_INI		; 自動化１　ＯＦＦタイマ　　　タイマ仕様
		.GLOBAL		_SV_AUTSTA_C51A_INI		; 自動化２　ＯＮ工程　　　タイマ仕様
		.GLOBAL		_SV_AUTKK3_C51A_INI		; 自動化２　ＯＮ角度　　　　　タイマ仕様
		.GLOBAL		_SV_AUTSTP_C51A_INI		; 自動化２　ＯFF工程　　　タイマ仕様
		.GLOBAL		_SV_AUTTIM_C51A_INI		; 自動化２　ＯＦＦタイマ　　　タイマ仕様
		.GLOBAL		_SV_AUTSTA_C51B_INI		; 自動化３　ＯＮ工程　　　タイマ仕様
		.GLOBAL		_SV_AUTKK3_C51B_INI		; 自動化３　ＯＮ角度　　　　　タイマ仕様
		.GLOBAL		_SV_AUTSTP_C51B_INI		; 自動化３　ＯFF程　　　タイマ仕様
		.GLOBAL		_SV_AUTTIM_C51B_INI		; 自動化３　ＯＦＦタイマ　　　タイマ仕様
		.GLOBAL		_SV_MISSTA1_C9_INI		; ミスフィード１　ＯＮ工程
		.GLOBAL		_SV_MISSK1_C9_INI		; ミスフィード１　ＯＮ角度
		.GLOBAL		_SV_MISSTP1_C9_INI		; ミスフィード１　ＯＦＦ工程
		.GLOBAL		_SV_MISSK2_C9_INI		; ミスフィード１　ＯＦＦ角度
		.GLOBAL		_SV_MISSTA2_C9_INI		; ミスフィード２　ＯＮ工程
		.GLOBAL		_SV_MISSK3_C9_INI		; ミスフィード２　ＯＮ角度
		.GLOBAL		_SV_MISSTP2_C9_INI		; ミスフィード２　ＯＦＦ工程
		.GLOBAL		_SV_MISSK4_C9_INI		; ミスフィード２　ＯＦＦ角度
		.GLOBAL		_SV_MISSTA3_C9_INI		; ミスフィード３　ＯＮ工程
		.GLOBAL		_SV_MISSK5_C9_INI		; ミスフィード３　ＯＮ角度
		.GLOBAL		_SV_MISSTP3_C9_INI		; ミスフィード３　ＯＦＦ工程
		.GLOBAL		_SV_MISSK6_C9_INI		; ミスフィード３　ＯＦＦ角度
		.GLOBAL		_SV_MISSTA4_C9_INI		; ミスフィード４　ＯＮ工程
		.GLOBAL		_SV_MISSK7_C9_INI		; ミスフィード４　ＯＮ角度
		.GLOBAL		_SV_MISSTP4_C9_INI		; ミスフィード４　ＯＦＦ工程
		.GLOBAL		_SV_MISSK8_C9_INI		; ミスフィード４　ＯＦＦ角度
		.GLOBAL		_SV_MISSTA5_C10_INI		; ミスフィード５　ＯＮ工程
		.GLOBAL		_SV_MISSK1_C10_INI		; ミスフィード５　ＯＮ角度
		.GLOBAL		_SV_MISSTP5_C10_INI		; ミスフィード５　ＯＦＦ工程
		.GLOBAL		_SV_MISSK2_C10_INI		; ミスフィード５　ＯＦＦ角度
		.GLOBAL		_SV_MISSTA6_C10_INI		; ミスフィード６　ＯＮ工程
		.GLOBAL		_SV_MISSK3_C10_INI		; ミスフィード６　ＯＮ角度
		.GLOBAL		_SV_MISSTP6_C10_INI		; ミスフィード６　ＯＦＦ工程
		.GLOBAL		_SV_MISSK4_C10_INI		; ミスフィード６　ＯＦＦ角度
		.GLOBAL		_SV_MISSTA7_C10_INI		; ミスフィード７　ＯＮ工程
		.GLOBAL		_SV_MISSK5_C10_INI		; ミスフィード７　ＯＮ角度
		.GLOBAL		_SV_MISSTP7_C10_INI		; ミスフィード７　ＯＦＦ工程
		.GLOBAL		_SV_MISSK6_C10_INI		; ミスフィード７　ＯＦＦ角度
		.GLOBAL		_SV_MISSTA8_C10_INI		; ミスフィード８　ＯＮ工程
		.GLOBAL		_SV_MISSK7_C10_INI		; ミスフィード８　ＯＮ角度
		.GLOBAL		_SV_MISSTP8_C10_INI		; ミスフィード８　ＯＦＦ工程
		.GLOBAL		_SV_MISSK8_C10_INI		; ミスフィード８　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA11_C17_INI	; ロータリカム１　ＯＮ工程
		.GLOBAL		_SV_RCLS11_C17_INI		; ロータリカム１　ＯＮ角度
		.GLOBAL		_SV_RCLSTP12_C17_INI	; ロータリカム１　ＯＦＦ工程
		.GLOBAL		_SV_RCLS12_C17_INI		; ロータリカム１　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA21_C17_INI	; ロータリカム２　ＯＮ工程
		.GLOBAL		_SV_RCLS21_C17_INI		; ロータリカム２　ＯＮ角度
		.GLOBAL		_SV_RCLSTP22_C17_INI	; ロータリカム２　ＯＦＦ工程
		.GLOBAL		_SV_RCLS22_C17_INI		; ロータリカム２　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA31_C17_INI	; ロータリカム３　ＯＮ工程
		.GLOBAL		_SV_RCLS31_C17_INI		; ロータリカム３　ＯＮ角度
		.GLOBAL		_SV_RCLSTP32_C17_INI	; ロータリカム３　ＯＦＦ工程
		.GLOBAL		_SV_RCLS32_C17_INI		; ロータリカム３　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA41_C17_INI	; ロータリカム４　ＯＮ工程
		.GLOBAL		_SV_RCLS41_C17_INI		; ロータリカム４　ＯＮ角度
		.GLOBAL		_SV_RCLSTP42_C17_INI	; ロータリカム４　ＯＦＦ工程
		.GLOBAL		_SV_RCLS42_C17_INI		; ロータリカム４　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA51_C18_INI	; ロータリカム５　ＯＮ工程
		.GLOBAL		_SV_RCLS51_C18_INI		; ロータリカム５　ＯＮ角度
		.GLOBAL		_SV_RCLSTP52_C18_INI	; ロータリカム５　ＯＦＦ工程
		.GLOBAL		_SV_RCLS52_C18_INI		; ロータリカム５　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA61_C18_INI	; ロータリカム６　ＯＮ工程
		.GLOBAL		_SV_RCLS61_C18_INI		; ロータリカム６　ＯＮ角度
		.GLOBAL		_SV_RCLSTP62_C18_INI	; ロータリカム６　ＯＦＦ工程
		.GLOBAL		_SV_RCLS62_C18_INI		; ロータリカム６　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA71_C18_INI	; ロータリカム７　ＯＮ工程
		.GLOBAL		_SV_RCLS71_C18_INI		; ロータリカム７　ＯＮ角度
		.GLOBAL		_SV_RCLSTP72_C18_INI	; ロータリカム７　ＯＦＦ工程
		.GLOBAL		_SV_RCLS72_C18_INI		; ロータリカム７　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA81_C18_INI	; ロータリカム８　ＯＮ工程
		.GLOBAL		_SV_RCLS81_C18_INI		; ロータリカム８　ＯＮ角度
		.GLOBAL		_SV_RCLSTP82_C18_INI	; ロータリカム８　ＯＦＦ工程
		.GLOBAL		_SV_RCLS82_C18_INI		; ロータリカム８　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA11_C19_INI	; ロータリカム９　ＯＮ工程
		.GLOBAL		_SV_RCLS11_C19_INI		; ロータリカム９　ＯＮ角度
		.GLOBAL		_SV_RCLSTP12_C19_INI	; ロータリカム９　ＯＦＦ工程
		.GLOBAL		_SV_RCLS12_C19_INI		; ロータリカム９　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA21_C19_INI	; ロータリカム１０　ＯＮ工程
		.GLOBAL		_SV_RCLS21_C19_INI		; ロータリカム１０　ＯＮ角度
		.GLOBAL		_SV_RCLSTA22_C19_INI	; ロータリカム１０　ＯＦＦ工程
		.GLOBAL		_SV_RCLS22_C19_INI		; ロータリカム１０　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA31_C19_INI	; ロータリカム１１　ＯＮ工程
		.GLOBAL		_SV_RCLS31_C19_INI		; ロータリカム１１　ＯＮ角度
		.GLOBAL		_SV_RCLSTA32_C19_INI	; ロータリカム１１　ＯＦＦ工程
		.GLOBAL		_SV_RCLS32_C19_INI		; ロータリカム１１　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA41_C19_INI	; ロータリカム１２　ＯＮ工程
		.GLOBAL		_SV_RCLS41_C19_INI		; ロータリカム１２　ＯＮ角度
		.GLOBAL		_SV_RCLSTA42_C19_INI	; ロータリカム１２　ＯＦＦ工程
		.GLOBAL		_SV_RCLS42_C19_INI		; ロータリカム１２　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA51_C19_INI	; ロータリカム１３　ＯＮ工程
		.GLOBAL		_SV_RCLS51_C20_INI		; ロータリカム１３　ＯＮ角度
		.GLOBAL		_SV_RCLSTA52_C20_INI	; ロータリカム１３　ＯＦＦ工程
		.GLOBAL		_SV_RCLS52_C20_INI		; ロータリカム１３　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA61_C20_INI	; ロータリカム１４　ＯＮ工程
		.GLOBAL		_SV_RCLS61_C20_INI		; ロータリカム１４　ＯＮ角度
		.GLOBAL		_SV_RCLSTA62_C20_INI	; ロータリカム１４　ＯＦＦ工程
		.GLOBAL		_SV_RCLS62_C20_INI		; ロータリカム１４　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA71_C20_INI	; ロータリカム１５　ＯＮ工程
		.GLOBAL		_SV_RCLS71_C20_INI		; ロータリカム１５　ＯＮ角度
		.GLOBAL		_SV_RCLSTA72_C20_INI	; ロータリカム１５　ＯＦＦ工程
		.GLOBAL		_SV_RCLS72_C20_INI		; ロータリカム１５　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA81_C20_INI	; ロータリカム１６　ＯＮ工程
		.GLOBAL		_SV_RCLS81_C20_INI		; ロータリカム１６　ＯＮ角度
		.GLOBAL		_SV_RCLSTA82_C20_INI	; ロータリカム１６　ＯＦＦ工程
		.GLOBAL		_SV_RCLS82_C20_INI		; ロータリカム１６　ＯＦＦ角度
		.GLOBAL		_SV_RCLSTA11_C21_INI	; ロータリカム１７　ＯＮ工程
		.GLOBAL		_SV_RCLS11_C21_INI		; ロータリカム１７　ON角度
		.GLOBAL		_SV_RCLSTA12_C21_INI	; ロータリカム１７　ＯＦＦ工程
		.GLOBAL		_SV_RCLS12_C21_INI		; ロータリカム１７　OFF角度
		.GLOBAL		_SV_RCLSTA21_C21_INI	; ロータリカム１８　ＯＮ工程
		.GLOBAL		_SV_RCLS21_C21_INI		; ロータリカム１８　ON角度
		.GLOBAL		_SV_RCLSTA22_C21_INI	; ロータリカム１８　ＯＦＦ工程
		.GLOBAL		_SV_RCLS22_C21_INI		; ロータリカム１８　OFF角度
		.GLOBAL		_SV_RCLSTA31_C21_INI	; ロータリカム１９　ＯＮ工程
		.GLOBAL		_SV_RCLS31_C21_INI		; ロータリカム１９　ON角度
		.GLOBAL		_SV_RCLSTA32_C21_INI	; ロータリカム１９　ＯＦＦ工程
		.GLOBAL		_SV_RCLS32_C21_INI		; ロータリカム１９　OFF角度
		.GLOBAL		_SV_RCLSTA41_C21_INI	; ロータリカム２０　ＯＮ工程
		.GLOBAL		_SV_RCLS41_C21_INI		; ロータリカム２０　ON角度
		.GLOBAL		_SV_RCLSTA42_C21_INI	; ロータリカム２０　ＯＦＦ工程
		.GLOBAL		_SV_RCLS42_C21_INI		; ロータリカム２０　OFF角度

		.GLOBAL		_SV_ATUOSU_D9_INI		; スライド自動調節設定値（現在動作中）
		.GLOBAL		_SV_ATUOS0_D9_INI		; スライド自動調節　生産設定
		.GLOBAL		_SV_ATUOS1_D9_INI		; スライド自動調節　段取り１設定
		.GLOBAL		_SV_ATUOS2_D9_INI		; スライド自動調節　段取り２設定
		.GLOBAL		_SV_OVERE1_A26_INI		; 荷重計　オーバーロード１
		.GLOBAL		_SV_ROALM1_A26_INI		; 荷重計　ロアーリッミト１
		.GLOBAL		_SV_OVERE2_A26_INI		; 荷重計　オーバーロード２
		.GLOBAL		_SV_ROALM2_A26_INI		; 荷重計　ロアーリッミト２
		.GLOBAL		_SV_OVERE3_A26_INI		; 荷重計　オーバーロード３
		.GLOBAL		_SV_ROALM3_A26_INI		; 荷重計　ロアーリッミト３
		.GLOBAL		_SV_DUMMY_A26_INI		; 空き
		.GLOBAL		_SV_CAMNA0_C1_INI		; ロータリカム１汎用選択種別
		.GLOBAL		_SV_CAMNA1_C1_INI		; ロータリカム２汎用選択種別
		.GLOBAL		_SV_CAMNA2_C1_INI		; ロータリカム３汎用選択種別
		.GLOBAL		_SV_CAMNA3_C1_INI		; ロータリカム４汎用選択種別
		.GLOBAL		_SV_CAMNA4_C1_INI		; ロータリカム５汎用選択種別
		.GLOBAL		_SV_CAMNA5_C1_INI		; ロータリカム６汎用選択種別
		.GLOBAL		_SV_CAMNA6_C1_INI		; ロータリカム７汎用選択種別
		.GLOBAL		_SV_CAMNA7_C1_INI		; ロータリカム８汎用選択種別
		.GLOBAL		_SV_CAMNA8_C1_INI		; ロータリカム９汎用選択種別
		.GLOBAL		_SV_CAMNA9_C1_INI		; ロータリカム１０汎用選択種別
		.GLOBAL		_SV_CAMNAA_C1_INI		; ロータリカム１１汎用選択種別
		.GLOBAL		_SV_CAMNAB_C1_INI		; ロータリカム１２汎用選択種別
		.GLOBAL		_SV_CAMNAC_C1_INI		; ロータリカム１３汎用選択種別
		.GLOBAL		_SV_CAMNAD_C1_INI		; ロータリカム１４汎用選択種別
		.GLOBAL		_SV_CAMNAE_C1_INI		; ロータリカム１５汎用選択種別
		.GLOBAL		_SV_CAMNAF_C1_INI		; ロータリカム１６汎用選択種別
		.GLOBAL		_SV_SPDSET_B1_INI		; 生産速度設定値
		.GLOBAL		_SV_SPDDAN_B1_INI		; 段取速度設定値
		.GLOBAL		_SV_BARANS_C27_INI		; バランサ圧
		.GLOBAL		_SV_DAIKA1_C27_INI		; ダイクッション圧１
		.GLOBAL		_SV_DAIKA2_C27_INI		; ダイクッション圧２
		.GLOBAL		_SV_DAITY1_C27_INI		; ダイクッション調節１
		.GLOBAL		_SV_DAITY2_C27_INI		; ダイクッション調節２
		.GLOBAL		_SV_COILL1_C30_INI		; コイルライン設定１
		.GLOBAL		_SV_COILL2_C30_INI		; コイルライン設定２
		.GLOBAL		_SV_COILL3_C30_INI		; コイルライン設定３
		.GLOBAL		_SV_COILL4_C30_INI		; コイルライン設定４
		.GLOBAL		_SV_COILL5_C30_INI		; コイルライン設定５
		.GLOBAL		_SV_COILL6_C30_INI		; コイルライン設定６
		.GLOBAL		_SV_COIMAI_C30_INI		; コイルライン設定ﾏｲﾅｽ
		.GLOBAL		_SV_UPDANO_C28_INI		; 上型クランパ６選択　パターン入力データ

;2002-10-08:追加ｽﾀｰﾄ
		.GLOBAL		_SV_TAIKIPOS1_SRV_INI	; 待機位置
		.GLOBAL		_SV_KAITEN1_SRV_INI		; 回転方式
		.GLOBAL		_SV_DANSUU1_SRV_INI		; 段数
		.GLOBAL		_SV_TAIKIKAKU1_SRV_INI	; 待機角
		.GLOBAL		_SV_TAIKSPD1_SRV_INI	; 基準速度
		.GLOBAL		_SV_DAIHAITO1_SRV_INI	; ダイハイト
		.GLOBAL		_SV_HOASEI1_SRV_INI		; 補正データ
		.GLOBAL		_SV_TAIKTIM1_SRV_INI	; 待機時間
		.GLOBAL		_SV_1DANDEG1_SRV_INI	; 1段目目標角度
		.GLOBAL		_SV_2DANDEG1_SRV_INI	; 2段目目標角度
		.GLOBAL		_SV_3DANDEG1_SRV_INI	; 3段目目標角度
		.GLOBAL		_SV_4DANDEG1_SRV_INI	; 4段目目標角度
		.GLOBAL		_SV_5DANDEG1_SRV_INI	; 5段目目標角度
		.GLOBAL		_SV_6DANDEG1_SRV_INI	; 6段目目標角度
		.GLOBAL		_SV_7DANDEG1_SRV_INI	; 7段目目標角度
		.GLOBAL		_SV_8DANDEG1_SRV_INI	; 8段目目標角度
		.GLOBAL		_SV_9DANDEG1_SRV_INI	; 9段目目標角度
		.GLOBAL		_SV_10DANDEG1_SRV_INI	; 10段目目標角度
		.GLOBAL		_SV_1DANPOS1_SRV_INI	; 1段目目標位置
		.GLOBAL		_SV_2DANPOS1_SRV_INI	; 2段目目標位置
		.GLOBAL		_SV_3DANPOS1_SRV_INI	; 3段目目標位置
		.GLOBAL		_SV_4DANPOS1_SRV_INI	; 4段目目標位置
		.GLOBAL		_SV_5DANPOS1_SRV_INI	; 5段目目標位置
		.GLOBAL		_SV_6DANPOS1_SRV_INI	; 6段目目標位置
		.GLOBAL		_SV_7DANPOS1_SRV_INI	; 7段目目標位置
		.GLOBAL		_SV_8DANPOS1_SRV_INI	; 8段目目標位置
		.GLOBAL		_SV_9DANPOS1_SRV_INI	; 9段目目標位置
		.GLOBAL		_SV_10DANPOS1_SRV_INI	; 10段目目標位置
		.GLOBAL		_SV_1DANSPD1_SRV_INI	; 1段目移動速度
		.GLOBAL		_SV_2DANSPD1_SRV_INI	; 2段目移動速度
		.GLOBAL		_SV_3DANSPD1_SRV_INI	; 3段目移動速度
		.GLOBAL		_SV_4DANSPD1_SRV_INI	; 4段目移動速度
		.GLOBAL		_SV_5DANSPD1_SRV_INI	; 5段目移動速度
		.GLOBAL		_SV_6DANSPD1_SRV_INI	; 6段目移動速度
		.GLOBAL		_SV_7DANSPD1_SRV_INI	; 7段目移動速度
		.GLOBAL		_SV_8DANSPD1_SRV_INI	; 8段目移動速度
		.GLOBAL		_SV_9DANSPD1_SRV_INI	; 9段目移動速度
		.GLOBAL		_SV_10DANSPD1_SRV_INI	; 10段目移動速度
		.GLOBAL		_SV_1DANTIM1_SRV_INI	; 1段目停止時間
		.GLOBAL		_SV_2DANTIM1_SRV_INI	; 2段目停止時間
		.GLOBAL		_SV_3DANTIM1_SRV_INI	; 3段目停止時間
		.GLOBAL		_SV_4DANTIM1_SRV_INI	; 4段目停止時間
		.GLOBAL		_SV_5DANTIM1_SRV_INI	; 5段目停止時間
		.GLOBAL		_SV_6DANTIM1_SRV_INI	; 6段目停止時間
		.GLOBAL		_SV_7DANTIM1_SRV_INI	; 7段目停止時間
		.GLOBAL		_SV_8DANTIM1_SRV_INI	; 8段目停止時間
		.GLOBAL		_SV_9DANTIM1_SRV_INI	; 9段目停止時間
		.GLOBAL		_SV_10DANTIM1_SRV_INI	; 10段目停止時間
		.GLOBAL		_SV_MOKKAN1_SRV_INI		; 目標完了範囲
		.GLOBAL		_SV_TAIKIPOS2_SRV_INI	; 待機位置
		.GLOBAL		_SV_KAITEN2_SRV_INI		; 回転方式
		.GLOBAL		_SV_DANSUU2_SRV_INI		; 段数
		.GLOBAL		_SV_TAIKIKAKU2_SRV_INI	; 待機角
		.GLOBAL		_SV_TAIKSPD2_SRV_INI	; 基準速度
		.GLOBAL		_SV_DAIHAITO2_SRV_INI	; ダイハイト
		.GLOBAL		_SV_HOASEI2_SRV_INI		; 補正データ
		.GLOBAL		_SV_TAIKTIM2_SRV_INI	; 待機時間
		.GLOBAL		_SV_1DANDEG2_SRV_INI	; 1段目目標角度
		.GLOBAL		_SV_2DANDEG2_SRV_INI	; 2段目目標角度
		.GLOBAL		_SV_3DANDEG2_SRV_INI	; 3段目目標角度
		.GLOBAL		_SV_4DANDEG2_SRV_INI	; 4段目目標角度
		.GLOBAL		_SV_5DANDEG2_SRV_INI	; 5段目目標角度
		.GLOBAL		_SV_6DANDEG2_SRV_INI	; 6段目目標角度
		.GLOBAL		_SV_7DANDEG2_SRV_INI	; 7段目目標角度
		.GLOBAL		_SV_8DANDEG2_SRV_INI	; 8段目目標角度
		.GLOBAL		_SV_9DANDEG2_SRV_INI	; 9段目目標角度
		.GLOBAL		_SV_10DANDEG2_SRV_INI	; 10段目目標角度
		.GLOBAL		_SV_1DANPOS2_SRV_INI	; 1段目目標位置
		.GLOBAL		_SV_2DANPOS2_SRV_INI	; 2段目目標位置
		.GLOBAL		_SV_3DANPOS2_SRV_INI	; 3段目目標位置
		.GLOBAL		_SV_4DANPOS2_SRV_INI	; 4段目目標位置
		.GLOBAL		_SV_5DANPOS2_SRV_INI	; 5段目目標位置
		.GLOBAL		_SV_6DANPOS2_SRV_INI	; 6段目目標位置
		.GLOBAL		_SV_7DANPOS2_SRV_INI	; 7段目目標位置
		.GLOBAL		_SV_8DANPOS2_SRV_INI	; 8段目目標位置
		.GLOBAL		_SV_9DANPOS2_SRV_INI	; 9段目目標位置
		.GLOBAL		_SV_10DANPOS2_SRV_INI	; 10段目目標位置
		.GLOBAL		_SV_1DANSPD2_SRV_INI	; 1段目移動速度
		.GLOBAL		_SV_2DANSPD2_SRV_INI	; 2段目移動速度
		.GLOBAL		_SV_3DANSPD2_SRV_INI	; 3段目移動速度
		.GLOBAL		_SV_4DANSPD2_SRV_INI	; 4段目移動速度
		.GLOBAL		_SV_5DANSPD2_SRV_INI	; 5段目移動速度
		.GLOBAL		_SV_6DANSPD2_SRV_INI	; 6段目移動速度
		.GLOBAL		_SV_7DANSPD2_SRV_INI	; 7段目移動速度
		.GLOBAL		_SV_8DANSPD2_SRV_INI	; 8段目移動速度
		.GLOBAL		_SV_9DANSPD2_SRV_INI	; 9段目移動速度
		.GLOBAL		_SV_10DANSPD2_SRV_INI	; 10段目移動速度
		.GLOBAL		_SV_1DANTIM2_SRV_INI	; 1段目停止時間
		.GLOBAL		_SV_2DANTIM2_SRV_INI	; 2段目停止時間
		.GLOBAL		_SV_3DANTIM2_SRV_INI	; 3段目停止時間
		.GLOBAL		_SV_4DANTIM2_SRV_INI	; 4段目停止時間
		.GLOBAL		_SV_5DANTIM2_SRV_INI	; 5段目停止時間
		.GLOBAL		_SV_6DANTIM2_SRV_INI	; 6段目停止時間
		.GLOBAL		_SV_7DANTIM2_SRV_INI	; 7段目停止時間
		.GLOBAL		_SV_8DANTIM2_SRV_INI	; 8段目停止時間
		.GLOBAL		_SV_9DANTIM2_SRV_INI	; 9段目停止時間
		.GLOBAL		_SV_10DANTIM2_SRV_INI	; 10段目停止時間
		.GLOBAL		_SV_MOKKAN2_SRV_INI		; 目標完了範囲
		.GLOBAL		_SV_TAIKIPOS3_SRV_INI	; 待機位置
		.GLOBAL		_SV_KAITEN3_SRV_INI		; 回転方式
		.GLOBAL		_SV_DANSUU3_SRV_INI		; 段数
		.GLOBAL		_SV_TAIKIKAKU3_SRV_INI	; 待機角
		.GLOBAL		_SV_TAIKSPD3_SRV_INI	; 基準速度
		.GLOBAL		_SV_DAIHAITO3_SRV_INI	; ダイハイト
		.GLOBAL		_SV_HOASEI3_SRV_INI		; 補正データ
		.GLOBAL		_SV_TAIKTIM3_SRV_INI	; 待機時間
		.GLOBAL		_SV_1DANDEG3_SRV_INI	; 1段目目標角度
		.GLOBAL		_SV_2DANDEG3_SRV_INI	; 2段目目標角度
		.GLOBAL		_SV_3DANDEG3_SRV_INI	; 3段目目標角度
		.GLOBAL		_SV_4DANDEG3_SRV_INI	; 4段目目標角度
		.GLOBAL		_SV_5DANDEG3_SRV_INI	; 5段目目標角度
		.GLOBAL		_SV_6DANDEG3_SRV_INI	; 6段目目標角度
		.GLOBAL		_SV_7DANDEG3_SRV_INI	; 7段目目標角度
		.GLOBAL		_SV_8DANDEG3_SRV_INI	; 8段目目標角度
		.GLOBAL		_SV_9DANDEG3_SRV_INI	; 9段目目標角度
		.GLOBAL		_SV_10DANDEG3_SRV_INI	; 10段目目標角度
		.GLOBAL		_SV_1DANPOS3_SRV_INI	; 1段目目標位置
		.GLOBAL		_SV_2DANPOS3_SRV_INI	; 2段目目標位置
		.GLOBAL		_SV_3DANPOS3_SRV_INI	; 3段目目標位置
		.GLOBAL		_SV_4DANPOS3_SRV_INI	; 4段目目標位置
		.GLOBAL		_SV_5DANPOS3_SRV_INI	; 5段目目標位置
		.GLOBAL		_SV_6DANPOS3_SRV_INI	; 6段目目標位置
		.GLOBAL		_SV_7DANPOS3_SRV_INI	; 7段目目標位置
		.GLOBAL		_SV_8DANPOS3_SRV_INI	; 8段目目標位置
		.GLOBAL		_SV_9DANPOS3_SRV_INI	; 9段目目標位置
		.GLOBAL		_SV_10DANPOS3_SRV_INI	; 10段目目標位置
		.GLOBAL		_SV_1DANSPD3_SRV_INI	; 1段目移動速度
		.GLOBAL		_SV_2DANSPD3_SRV_INI	; 2段目移動速度
		.GLOBAL		_SV_3DANSPD3_SRV_INI	; 3段目移動速度
		.GLOBAL		_SV_4DANSPD3_SRV_INI	; 4段目移動速度
		.GLOBAL		_SV_5DANSPD3_SRV_INI	; 5段目移動速度
		.GLOBAL		_SV_6DANSPD3_SRV_INI	; 6段目移動速度
		.GLOBAL		_SV_7DANSPD3_SRV_INI	; 7段目移動速度
		.GLOBAL		_SV_8DANSPD3_SRV_INI	; 8段目移動速度
		.GLOBAL		_SV_9DANSPD3_SRV_INI	; 9段目移動速度
		.GLOBAL		_SV_10DANSPD3_SRV_INI	; 10段目移動速度
		.GLOBAL		_SV_1DANTIM3_SRV_INI	; 1段目停止時間
		.GLOBAL		_SV_2DANTIM3_SRV_INI	; 2段目停止時間
		.GLOBAL		_SV_3DANTIM3_SRV_INI	; 3段目停止時間
		.GLOBAL		_SV_4DANTIM3_SRV_INI	; 4段目停止時間
		.GLOBAL		_SV_5DANTIM3_SRV_INI	; 5段目停止時間
		.GLOBAL		_SV_6DANTIM3_SRV_INI	; 6段目停止時間
		.GLOBAL		_SV_7DANTIM3_SRV_INI	; 7段目停止時間
		.GLOBAL		_SV_8DANTIM3_SRV_INI	; 8段目停止時間
		.GLOBAL		_SV_9DANTIM3_SRV_INI	; 9段目停止時間
		.GLOBAL		_SV_10DANTIM3_SRV_INI	; 10段目停止時間
		.GLOBAL		_SV_MOKKAN3_SRV_INI		; 目標完了範囲
		.GLOBAL		_SV_DUMMY_C28_INI		; 空き／＊＊＊＊　未使用　＊＊＊＊／
;2002-10-08:追加ｴﾝﾄﾞ

		.GLOBAL		_SV_DUMMY_C29_INI		; 空き
		.GLOBAL		_PV_TOTLC1_B3_KAT_INI   ; トータルカウンタ１実測値
		.GLOBAL		_PV_LOTCT1_B4_KAT_INI   ; ロットカウンタ１実測値
		.GLOBAL		_PV_TOTLC2_B31_KAT_INI  ; 未使用
		.GLOBAL		_PV_LOTCT2_B41_KAT_INI  ; ロットカウンタ２実測値
		.GLOBAL		_SV_DUMMY_C30_INI		; 空き
		.GLOBAL		_FRAM_KAT_END_INI		; F-RAM領域の型データのエンドラベル
		.GLOBAL		_FRAM_KAT_SUM_INI		; 型データのチェックサム領域用
		.GLOBAL		_SV_DUMMY_C31_INI		; 調整用(次オフセット・アドレス：0x１０００)
		.GLOBAL		_KAT_NEXT_FLG_INI		; 次型データ有無ﾌﾗｸﾞ読み込み 1=有り
		.GLOBAL		_KT_MLDNO0_NF1_INI		; 次型金型名称
		.GLOBAL		_SV_DUMMY_NF1_INI		; 空き
		.GLOBAL		_PV_MLDNO1_F1_INI		; 現在の型番号
		.GLOBAL		_PV_MLDNO2_F1_INI		; 現在の型名称
		.GLOBAL		_KAT_NOW_NO_INI_INI		; 空き
		.GLOBAL		_PV_MLDNO3_F1_INI		; 空き（型名称画面の仮の名称）
		.GLOBAL		_SV_DUMMY_F1_INI		; 空き
		.GLOBAL		_SV_EJENAM01_C1_INI		; エジェクタ１名称
		.GLOBAL		_SV_EJENAM02_C1_INI		; エジェクタ１名称
		.GLOBAL		_SV_EJENAM03_C1_INI		; エジェクタ１名称
		.GLOBAL		_SV_EJENAM04_C1_INI		; エジェクタ１名称
		.GLOBAL		_SV_EJENAM05_C1_INI		; エジェクタ１名称
		.GLOBAL		_SV_EJENAM06_C1_INI		; エジェクタ１名称
		.GLOBAL		_SV_CAMNA01_C1_INI		; ロータリカム１名称
		.GLOBAL		_SV_CAMNA02_C1_INI		; ロータリカム２名称
		.GLOBAL		_SV_CAMNA03_C1_INI		; ロータリカム３名称
		.GLOBAL		_SV_CAMNA04_C1_INI		; ロータリカム４名称
		.GLOBAL		_SV_CAMNA05_C1_INI		; ロータリカム５名称
		.GLOBAL		_SV_CAMNA06_C1_INI		; ロータリカム６名称
		.GLOBAL		_SV_CAMNA07_C1_INI		; ロータリカム７名称
		.GLOBAL		_SV_CAMNA08_C1_INI		; ロータリカム８名称
		.GLOBAL		_SV_CAMNA09_C1_INI		; ロータリカム９名称
		.GLOBAL		_SV_CAMNA10_C1_INI		; ロータリカム１０名称
		.GLOBAL		_SV_CAMNA11_C1_INI		; ロータリカム１１名称
		.GLOBAL		_SV_CAMNA12_C1_INI		; ロータリカム１２名称
		.GLOBAL		_SV_CAMNA13_C1_INI		; ロータリカム１３名称
		.GLOBAL		_SV_CAMNA14_C1_INI		; ロータリカム１４名称
		.GLOBAL		_SV_CAMNA15_C1_INI		; ロータリカム１５名称
		.GLOBAL		_SV_CAMNA16_C1_INI		; ロータリカム１６名称
		.GLOBAL		_SV_CAMNA17_C1_INI		; ロータリカム１７名称
		.GLOBAL		_SV_CAMNA18_C1_INI		; ロータリカム１８名称
		.GLOBAL		_SV_CAMNA19_C1_INI		; ロータリカム１９名称
		.GLOBAL		_SV_CAMNA20_C1_INI		; ロータリカム２０名称
		.GLOBAL		_KAT_JIKI_TOP_INI		; 次期金型用型データ領域

		.GLOBAL		_PV_TOTLC1_B3_INI		; トータルカウンタ１実測値
		.GLOBAL		_PV_LOTCT1_B4_INI		; ロットカウンタ１実測値
		.GLOBAL		_PV_TOTLC2_B31_INI		; 未使用
		.GLOBAL		_PV_LOTCT2_B41_INI		; ロットカウンタ２実測値
		.GLOBAL		_PV_LIFE_COUNT_INI		; 機械総カウンタ

		.GLOBAL		_PV_LIFE_TIME_10_INI	; 機械総時間（10msecカウンタ）
		.GLOBAL		_PV_LIFE_TIME_INI		; 機械総時間（1secカウンタ）


		.GLOBAL		_SEQ_BAK_312_INI		; キープリレーバックアップ３１２
		.GLOBAL		_SEQ_BAK_313_INI		; キープリレーバックアップ３１３
		.GLOBAL		_SEQ_BAK_314_INI		; キープリレーバックアップ３１４
		.GLOBAL		_SEQ_BAK_315_INI		; キープリレーバックアップ３１５
		.GLOBAL		_SEQ_BAK_316_INI		; キープリレーバックアップ３１６
		.GLOBAL		_SEQ_BAK_317_INI		; キープリレーバックアップ３１７
		.GLOBAL		_SEQ_BAK_318_INI		; キープリレーバックアップ３１８
		.GLOBAL		_SEQ_BAK_319_INI		; キープリレーバックアップ３１９
		.GLOBAL		_SURA_CHG_LST_INI		; リザーブ

		.GLOBAL		_MCN_MENT_CNT1_INI		; メンテナンスカウンタ１
		.GLOBAL		_MCN_MENT_CNT2_INI		; メンテナンスカウンタ２
		.GLOBAL		_MCN_MENT_CNT3_INI		; メンテナンスカウンタ３
		.GLOBAL		_MCN_MENT_CNT4_INI		; メンテナンスカウンタ４
		.GLOBAL		_MCN_MENT_CNT5_INI		; メンテナンスカウンタ５
		.GLOBAL		_MCN_MENT_CNT6_INI		; メンテナンスカウンタ６
		.GLOBAL		_MCN_MENT_CNT7_INI		; メンテナンスカウンタ７
		.GLOBAL		_MCN_MENT_CNT8_INI		; メンテナンスカウンタ８
		.GLOBAL		_MCN_MENT_TIM1_INI		; メンテナンス時間１（1secカウンタ）
		.GLOBAL		_MCN_MENT_TIM1_10_INI   ; メンテナンス時間１（10msecカウンタ）
		.GLOBAL		_MCN_MENT_TIM2_INI		; メンテナンス時間２（1secカウンタ）
		.GLOBAL		_MCN_MENT_TIM2_10_INI   ; メンテナンス時間２（10msecカウンタ）
		.GLOBAL		_MCN_MENT_TIM3_INI		; メンテナンス時間３（1secカウンタ）
		.GLOBAL		_MCN_MENT_TIM3_10_INI   ; メンテナンス時間３（10msecカウンタ）

		.GLOBAL		_PV_GAIN_BAK1L_INI		; 最大歪み２０００左ゲイン
		.GLOBAL		_PV_GAIN_BAK1R_INI		; 最大歪み２０００右ゲイン
		.GLOBAL		_PV_GAIN_BAK2L_INI		; 最大歪み１５００左ゲイン
		.GLOBAL		_PV_GAIN_BAK2R_INI		; 最大歪み１５００右ゲイン
		.GLOBAL		_PV_GAIN_BAK3L_INI		; 最大歪み　８００左ゲイン
		.GLOBAL		_PV_GAIN_BAK3R_INI		; 最大歪み　８００右ゲイン
		.GLOBAL		_PV_GAIN_BAK4L_INI		; 最大歪み　４００左ゲイン
		.GLOBAL		_PV_GAIN_BAK4R_INI		; 最大歪み　４００右ゲイン
		.GLOBAL		_PV_GAIN_BAK5L_INI		; 最大歪み　２００左ゲイン
		.GLOBAL		_PV_GAIN_BAK5R_INI		; 最大歪み　２００右ゲイン
		.GLOBAL		_PV_OF_BAKL_INI			; オフセット値左
		.GLOBAL		_PV_OF_BAKR_INI			; オフセット値右
		.GLOBAL		_PV_OF_AVE_BAKL_INI		; オフセット補正左
		.GLOBAL		_PV_OF_AVE_BAKR_INI		; オフセット補正右
		.GLOBAL		_PV_OF_AVE_BAKT_INI		; オフセット補正合計

		.GLOBAL		_PV_GENITI_B2_INI		; 現位置データ

		.GLOBAL		_SUM_CHK_INI_INI		; 設定値サムチェックコード
		.GLOBAL		_SUM_CHK_KAT_INI		; 型ﾃﾞｰﾀ 名称＆メモ サムチェックコード

		.GLOBAL		_PV_SEQDT1_A91_INI		; シーケンスチェック１
		.GLOBAL		_PV_SEQDT2_A91_INI		; シーケンスチェック２
		.GLOBAL		_PV_SEQDT3_A91_INI		; シーケンスチェック３
		.GLOBAL		_PV_SEQDT4_A91_INI		; シーケンスチェック４
		.GLOBAL		_PV_CB1_MAXSPD_INI		; 仕様最高速設定時のＡＤ値
		.GLOBAL		_PV_CB2_MAXSPD_INI		; 未使用
		.GLOBAL		_SV_EUPL_SYS_INI		; 未使用
		.GLOBAL		_SV_CBRPM1_SYS_INI		; 未使用
		.GLOBAL		_SV_CBRPM2_SYS_INI		; 未使用
		.GLOBAL		_SV_CBRPM3_SYS_INI		; 未使用
		.GLOBAL		_SV_HOSTIM_A12_INI		; 起動補償時間設定値
		.GLOBAL		_SV_TAIKI1_A12_INI		; 待機点１データ設定値
		.GLOBAL		_SV_TAIKI2_A12_INI		; 待機点２データ設定値
		.GLOBAL		_SV_TAIKI3_A12_INI		; 待機点３データ設定値
		.GLOBAL		_SV_RNZRPM_A12_INI		; 連続回転設定値
		.GLOBAL		_SV_RNZTIM_A12_INI		; 連続タイマ設定値



		.GLOBAL		_KIDO_FLG_SV_INI		; 輝度データ読込＆格納
		.GLOBAL		_KIDO_CNT_INI_INI		; 輝度調整設定値
		.GLOBAL		_SV_PSDIMD_A1_INI		; ＰＳＤＩ選択番号
		.GLOBAL		_SV_CAMNA_C1_INI		; ロータリカム１７～２０用ダミー領域
		.GLOBAL		_PV_SEARCH_C15_INI		; 型番号検索ナンバー読込
		.GLOBAL		_SV_RS4SEL_SYS_INI		; ＲＳ４２２仕様の有無
		.GLOBAL		_SV_RS4BPS_SYS_INI		; ぼーれいと設定
		.GLOBAL		_SV_RS4DTL_SYS_INI		; データ長
		.GLOBAL		_SV_RS4STP_SYS_INI		; ストップビット
		.GLOBAL		_SV_RS4PAR_SYS_INI		; パリティ設定
		.GLOBAL		_SV_RS4KNO_SYS_INI		; 局番
		.GLOBAL		_SV_OUTADR_SYS_INI		; 拡張出力領域アドレス
		.GLOBAL		_SV_OUTCNT_SYS_INI		; 拡張出力領域カウンタ
		.GLOBAL		_SV_UPDANO_MAX_INI		; 上型クランパ６選択パターン入力MAX

		.GLOBAL		_KAT_NAME_01_INI		; 型データ名称１
		.GLOBAL		_KAT_MEMO_01_INI		; 型データメモ１
		.GLOBAL		_KAT_NAME_02_INI		; 型データ名称２
		.GLOBAL		_KAT_MEMO_02_INI		; 型データメモ２
		.GLOBAL		_KAT_NAME_03_INI		; 型データ名称３
		.GLOBAL		_KAT_MEMO_03_INI		; 型データメモ３
		.GLOBAL		_KAT_NAME_04_INI		; 型データ名称４
		.GLOBAL		_KAT_MEMO_04_INI		; 型データメモ４
		.GLOBAL		_KAT_NAME_05_INI		; 型データ名称５
		.GLOBAL		_KAT_MEMO_05_INI		; 型データメモ５
		.GLOBAL		_KAT_NAME_06_INI		; 型データ名称６
		.GLOBAL		_KAT_MEMO_06_INI		; 型データメモ６
		.GLOBAL		_KAT_NAME_07_INI		; 型データ名称７
		.GLOBAL		_KAT_MEMO_07_INI		; 型データメモ７
		.GLOBAL		_KAT_NAME_08_INI		; 型データ名称８
		.GLOBAL		_KAT_MEMO_08_INI		; 型データメモ８
		.GLOBAL		_KAT_NAME_09_INI		; 型データ名称９
		.GLOBAL		_KAT_MEMO_09_INI		; 型データメモ９
		.GLOBAL		_KAT_NAME_10_INI		; 型データ名称1０
		.GLOBAL		_KAT_MEMO_10_INI		; 型データメモ1０
		.GLOBAL		_KAT_NAME_11_INI		; 型データ名称１１
		.GLOBAL		_KAT_MEMO_11_INI		; 型データメモ１１
		.GLOBAL		_KAT_NAME_12_INI		; 型データ名称１２
		.GLOBAL		_KAT_MEMO_12_INI		; 型データメモ１２
		.GLOBAL		_KAT_NAME_13_INI		; 型データ名称１３
		.GLOBAL		_KAT_MEMO_13_INI		; 型データメモ１３
		.GLOBAL		_KAT_NAME_14_INI		; 型データ名称１４
		.GLOBAL		_KAT_MEMO_14_INI		; 型データメモ１４
		.GLOBAL		_KAT_NAME_15_INI		; 型データ名称１５
		.GLOBAL		_KAT_MEMO_15_INI		; 型データメモ１５
		.GLOBAL		_KAT_NAME_16_INI		; 型データ名称１６
		.GLOBAL		_KAT_MEMO_16_INI		; 型データメモ１６
		.GLOBAL		_KAT_NAME_17_INI		; 型データ名称１７
		.GLOBAL		_KAT_MEMO_17_INI		; 型データメモ１７
		.GLOBAL		_KAT_NAME_18_INI		; 型データ名称１８
		.GLOBAL		_KAT_MEMO_18_INI		; 型データメモ１８
		.GLOBAL		_KAT_NAME_19_INI		; 型データ名称１９
		.GLOBAL		_KAT_MEMO_19_INI		; 型データメモ１９
		.GLOBAL		_KAT_NAME_20_INI		; 型データ名称２０
		.GLOBAL		_KAT_MEMO_20_INI		; 型データメモ２０
		.GLOBAL		_KAT_NAME_21_INI		; 型データ名称２１
		.GLOBAL		_KAT_MEMO_21_INI		; 型データメモ２１
		.GLOBAL		_KAT_NAME_22_INI		; 型データ名称２２
		.GLOBAL		_KAT_MEMO_22_INI		; 型データメモ２２
		.GLOBAL		_KAT_NAME_23_INI		; 型データ名称２３
		.GLOBAL		_KAT_MEMO_23_INI		; 型データメモ２３
		.GLOBAL		_KAT_NAME_24_INI		; 型データ名称２４
		.GLOBAL		_KAT_MEMO_24_INI		; 型データメモ２４
		.GLOBAL		_KAT_NAME_25_INI		; 型データ名称２５
		.GLOBAL		_KAT_MEMO_25_INI		; 型データメモ２５
		.GLOBAL		_KAT_NAME_26_INI		; 型データ名称２６
		.GLOBAL		_KAT_MEMO_26_INI		; 型データメモ２６
		.GLOBAL		_KAT_NAME_27_INI		; 型データ名称２７
		.GLOBAL		_KAT_MEMO_27_INI		; 型データメモ２７
		.GLOBAL		_KAT_NAME_28_INI		; 型データ名称２８
		.GLOBAL		_KAT_MEMO_28_INI		; 型データメモ２８
		.GLOBAL		_KAT_NAME_29_INI		; 型データ名称２９
		.GLOBAL		_KAT_MEMO_29_INI		; 型データメモ２９
		.GLOBAL		_KAT_NAME_30_INI		; 型データ名称３０
		.GLOBAL		_KAT_MEMO_30_INI		; 型データメモ３０
		.GLOBAL		_KAT_NAME_31_INI		; 型データ名称３１
		.GLOBAL		_KAT_MEMO_31_INI		; 型データメモ３１
		.GLOBAL		_KAT_NAME_32_INI		; 型データ名称３２
		.GLOBAL		_KAT_MEMO_32_INI		; 型データメモ３２
		.GLOBAL		_KAT_NAME_33_INI		; 型データ名称３３
		.GLOBAL		_KAT_MEMO_33_INI		; 型データメモ３３
		.GLOBAL		_KAT_NAME_34_INI		; 型データ名称３４
		.GLOBAL		_KAT_MEMO_34_INI		; 型データメモ３４
		.GLOBAL		_KAT_NAME_35_INI		; 型データ名称３５
		.GLOBAL		_KAT_MEMO_35_INI		; 型データメモ３５
		.GLOBAL		_KAT_NAME_36_INI		; 型データ名称３６
		.GLOBAL		_KAT_MEMO_36_INI		; 型データメモ３６
		.GLOBAL		_KAT_NAME_37_INI		; 型データ名称３７
		.GLOBAL		_KAT_MEMO_37_INI		; 型データメモ３７
		.GLOBAL		_KAT_NAME_38_INI		; 型データ名称３８
		.GLOBAL		_KAT_MEMO_38_INI		; 型データメモ３８
		.GLOBAL		_KAT_NAME_39_INI		; 型データ名称３９
		.GLOBAL		_KAT_MEMO_39_INI		; 型データメモ３９
		.GLOBAL		_KAT_NAME_40_INI		; 型データ名称４０
		.GLOBAL		_KAT_MEMO_40_INI		; 型データメモ４０
		.GLOBAL		_KAT_NAME_41_INI		; 型データ名称４１
		.GLOBAL		_KAT_MEMO_41_INI		; 型データメモ４１
		.GLOBAL		_KAT_NAME_42_INI		; 型データ名称４２
		.GLOBAL		_KAT_MEMO_42_INI		; 型データメモ４２
		.GLOBAL		_KAT_NAME_43_INI		; 型データ名称４３
		.GLOBAL		_KAT_MEMO_43_INI		; 型データメモ４３
		.GLOBAL		_KAT_NAME_44_INI		; 型データ名称４４
		.GLOBAL		_KAT_MEMO_44_INI		; 型データメモ４４
		.GLOBAL		_KAT_NAME_45_INI		; 型データ名称４５
		.GLOBAL		_KAT_MEMO_45_INI		; 型データメモ４５
		.GLOBAL		_KAT_NAME_46_INI		; 型データ名称４６
		.GLOBAL		_KAT_MEMO_46_INI		; 型データメモ４６
		.GLOBAL		_KAT_NAME_47_INI		; 型データ名称４７
		.GLOBAL		_KAT_MEMO_47_INI		; 型データメモ４７
		.GLOBAL		_KAT_NAME_48_INI		; 型データ名称４８
		.GLOBAL		_KAT_MEMO_48_INI		; 型データメモ４８
		.GLOBAL		_KAT_NAME_49_INI		; 型データ名称４９
		.GLOBAL		_KAT_MEMO_49_INI		; 型データメモ４９
		.GLOBAL		_KAT_NAME_50_INI		; 型データ名称５０
		.GLOBAL		_KAT_MEMO_50_INI		; 型データメモ５０
		.GLOBAL		_KAT_NAME_51_INI		; 型データ名称５１
		.GLOBAL		_KAT_MEMO_51_INI		; 型データメモ５１
		.GLOBAL		_KAT_NAME_52_INI		; 型データ名称５２
		.GLOBAL		_KAT_MEMO_52_INI		; 型データメモ５２
		.GLOBAL		_KAT_NAME_53_INI		; 型データ名称５３
		.GLOBAL		_KAT_MEMO_53_INI		; 型データメモ５３
		.GLOBAL		_KAT_NAME_54_INI		; 型データ名称５４
		.GLOBAL		_KAT_MEMO_54_INI		; 型データメモ５４
		.GLOBAL		_KAT_NAME_55_INI		; 型データ名称５５
		.GLOBAL		_KAT_MEMO_55_INI		; 型データメモ５５
		.GLOBAL		_KAT_NAME_56_INI		; 型データ名称５６
		.GLOBAL		_KAT_MEMO_56_INI		; 型データメモ５６
		.GLOBAL		_KAT_NAME_57_INI		; 型データ名称５７
		.GLOBAL		_KAT_MEMO_57_INI		; 型データメモ５７
		.GLOBAL		_KAT_NAME_58_INI		; 型データ名称５８
		.GLOBAL		_KAT_MEMO_58_INI		; 型データメモ５８
		.GLOBAL		_KAT_NAME_59_INI		; 型データ名称５９
		.GLOBAL		_KAT_MEMO_59_INI		; 型データメモ５９
		.GLOBAL		_KAT_NAME_60_INI		; 型データ名称６０
		.GLOBAL		_KAT_MEMO_60_INI		; 型データメモ６０
		.GLOBAL		_KAT_NAME_61_INI		; 型データ名称６１
		.GLOBAL		_KAT_MEMO_61_INI		; 型データメモ６１
		.GLOBAL		_KAT_NAME_62_INI		; 型データ名称６２
		.GLOBAL		_KAT_MEMO_62_INI		; 型データメモ６２
		.GLOBAL		_KAT_NAME_63_INI		; 型データ名称６３
		.GLOBAL		_KAT_MEMO_63_INI		; 型データメモ６３
		.GLOBAL		_KAT_NAME_64_INI		; 型データ名称６４
		.GLOBAL		_KAT_MEMO_64_INI		; 型データメモ６４
		.GLOBAL		_KAT_NAME_65_INI		; 型データ名称６５
		.GLOBAL		_KAT_MEMO_65_INI		; 型データメモ６５
		.GLOBAL		_KAT_NAME_66_INI		; 型データ名称６６
		.GLOBAL		_KAT_MEMO_66_INI		; 型データメモ６６
		.GLOBAL		_KAT_NAME_67_INI		; 型データ名称６７
		.GLOBAL		_KAT_MEMO_67_INI		; 型データメモ６７
		.GLOBAL		_KAT_NAME_68_INI		; 型データ名称６８
		.GLOBAL		_KAT_MEMO_68_INI		; 型データメモ６８
		.GLOBAL		_KAT_NAME_69_INI		; 型データ名称６９
		.GLOBAL		_KAT_MEMO_69_INI		; 型データメモ６９
		.GLOBAL		_KAT_NAME_70_INI		; 型データ名称７０
		.GLOBAL		_KAT_MEMO_70_INI		; 型データメモ７０
		.GLOBAL		_KAT_NAME_71_INI		; 型データ名称７１
		.GLOBAL		_KAT_MEMO_71_INI		; 型データメモ７１
		.GLOBAL		_KAT_NAME_72_INI		; 型データ名称７２
		.GLOBAL		_KAT_MEMO_72_INI		; 型データメモ７２
		.GLOBAL		_KAT_NAME_73_INI		; 型データ名称７３
		.GLOBAL		_KAT_MEMO_73_INI		; 型データメモ７３
		.GLOBAL		_KAT_NAME_74_INI		; 型データ名称７４
		.GLOBAL		_KAT_MEMO_74_INI		; 型データメモ７４
		.GLOBAL		_KAT_NAME_75_INI		; 型データ名称７５
		.GLOBAL		_KAT_MEMO_75_INI		; 型データメモ７５
		.GLOBAL		_KAT_NAME_76_INI		; 型データ名称７６
		.GLOBAL		_KAT_MEMO_76_INI		; 型データメモ７６
		.GLOBAL		_KAT_NAME_77_INI		; 型データ名称７７
		.GLOBAL		_KAT_MEMO_77_INI		; 型データメモ７７
		.GLOBAL		_KAT_NAME_78_INI		; 型データ名称７８
		.GLOBAL		_KAT_MEMO_78_INI		; 型データメモ７８
		.GLOBAL		_KAT_NAME_79_INI		; 型データ名称７９
		.GLOBAL		_KAT_MEMO_79_INI		; 型データメモ７９
		.GLOBAL		_KAT_NAME_80_INI		; 型データ名称８０
		.GLOBAL		_KAT_MEMO_80_INI		; 型データメモ８０
		.GLOBAL		_KAT_NAME_81_INI		; 型データ名称８１
		.GLOBAL		_KAT_MEMO_81_INI		; 型データメモ８１
		.GLOBAL		_KAT_NAME_82_INI		; 型データ名称８２
		.GLOBAL		_KAT_MEMO_82_INI		; 型データメモ８２
		.GLOBAL		_KAT_NAME_83_INI		; 型データ名称８３
		.GLOBAL		_KAT_MEMO_83_INI		; 型データメモ８３
		.GLOBAL		_KAT_NAME_84_INI		; 型データ名称８４
		.GLOBAL		_KAT_MEMO_84_INI		; 型データメモ８４
		.GLOBAL		_KAT_NAME_85_INI		; 型データ名称８５
		.GLOBAL		_KAT_MEMO_85_INI		; 型データメモ８５
		.GLOBAL		_KAT_NAME_86_INI		; 型データ名称８６
		.GLOBAL		_KAT_MEMO_86_INI		; 型データメモ８６
		.GLOBAL		_KAT_NAME_87_INI		; 型データ名称８７
		.GLOBAL		_KAT_MEMO_87_INI		; 型データメモ８７
		.GLOBAL		_KAT_NAME_88_INI		; 型データ名称８８
		.GLOBAL		_KAT_MEMO_88_INI		; 型データメモ８８
		.GLOBAL		_KAT_NAME_89_INI		; 型データ名称８９
		.GLOBAL		_KAT_MEMO_89_INI		; 型データメモ８９
		.GLOBAL		_KAT_NAME_90_INI		; 型データ名称９０
		.GLOBAL		_KAT_MEMO_90_INI		; 型データメモ９０
		.GLOBAL		_KAT_NAME_91_INI		; 型データ名称９１
		.GLOBAL		_KAT_MEMO_91_INI		; 型データメモ９１
		.GLOBAL		_KAT_NAME_92_INI		; 型データ名称９２
		.GLOBAL		_KAT_MEMO_92_INI		; 型データメモ９２
		.GLOBAL		_KAT_NAME_93_INI		; 型データ名称９３
		.GLOBAL		_KAT_MEMO_93_INI		; 型データメモ９３
		.GLOBAL		_KAT_NAME_94_INI		; 型データ名称９４
		.GLOBAL		_KAT_MEMO_94_INI		; 型データメモ９４
		.GLOBAL		_KAT_NAME_95_INI		; 型データ名称９５
		.GLOBAL		_KAT_MEMO_95_INI		; 型データメモ９５
		.GLOBAL		_KAT_NAME_96_INI		; 型データ名称９６
		.GLOBAL		_KAT_MEMO_96_INI		; 型データメモ９６
		.GLOBAL		_KAT_NAME_97_INI		; 型データ名称９７
		.GLOBAL		_KAT_MEMO_97_INI		; 型データメモ９７
		.GLOBAL		_KAT_NAME_98_INI		; 型データ名称９８
		.GLOBAL		_KAT_MEMO_98_INI		; 型データメモ９８
		.GLOBAL		_KAT_NAME_99_INI		; 型データ名称９９
		.GLOBAL		_KAT_MEMO_99_INI		; 型データメモ９９
		.GLOBAL		_KAT_NAME_100_INI		; 型データ名称１００
		.GLOBAL		_KAT_MEMO_100_INI		; 型データメモ１００
		.GLOBAL		_KAT_NAME_END_INI		; 空き(型データ　名称＆メモ終了ｱﾄﾞﾚｽ)

; END