
; ***** 型データ関連アドレスマップ データ定義 ******************************
_SEQ_016_SV         .SRES        2           ; 初期回路設定シーケンス１６
_SEQ_017_SV         .SRES        2           ; 初期回路設定シーケンス１７
_SEQ_018_SV         .SRES        2           ; 初期回路設定シーケンス１８
_SEQ_019_SV         .SRES        2           ; 初期回路設定シーケンス１９
_SEQ_020_SV         .SRES        2           ; 初期回路設定シーケンス２０
_SEQ_021_SV         .SRES        2           ; 初期回路設定シーケンス２１
_SEQ_022_SV         .SRES        2           ; 初期回路設定シーケンス２２
_SEQ_023_SV         .SRES        2           ; 初期回路設定シーケンス２３
_SEQ_024_SV         .SRES        2           ; 初期回路設定シーケンス２４
_SEQ_025_SV         .SRES        2           ; 初期回路設定シーケンス２５
_SEQ_026_SV         .SRES        2           ; 初期回路設定シーケンス２６
_SEQ_027_SV         .SRES        2           ; 初期回路設定シーケンス２７
_SEQ_028_SV         .SRES        2           ; クラッチ初期設定シーケンス２８
_SEQ_029_SV         .SRES        2           ; クラッチ初期設定シーケンス２９
_SEQ_030_SV         .SRES        2           ; クラッチ初期設定シーケンス３０
_SEQ_031_SV         .SRES        2           ; 機能選択シーケンス３１
_SEQ_032_SVB        .SRES        2           ; 空き
_SEQ_033_SVB        .SRES        2           ; 空き
_SEQ_034_SVB        .SRES        2           ; 空き
_SEQ_035_SVB        .SRES        2           ; 空き
_SEQ_036_SVB        .SRES        2           ; 空き
_SEQ_037_SVB        .SRES        2           ; 空き
_SEQ_038_SVB        .SRES        2           ; 空き
_SEQ_039_SVB        .SRES        2           ; 空き
_SEQ_040_SVB        .SRES        2           ; 空き
_SEQ_041_SVB        .SRES        2           ; 空き
_SEQ_042_SVB        .SRES        2           ; 空き
_SEQ_043_SVB        .SRES        2           ; 空き
_SEQ_044_SVB        .SRES        2           ; 空き
_SEQ_045_SVB        .SRES        2           ; 空き
_SEQ_046_SVB        .SRES        2           ; 空き
_SEQ_047_SVB        .SRES        2           ; 空き
_SEQ_048_SVB        .SRES        2           ; 空き
_SEQ_049_SVB        .SRES        2           ; 空き
_SEQ_050_SVB        .SRES        2           ; 空き
_SEQ_051_SVB        .SRES        2           ; 空き
_SEQ_052_SVB        .SRES        2           ; 空き
_SEQ_053_SVB        .SRES        2           ; 空き
_SEQ_054_SVB        .SRES        2           ; 空き
_SEQ_055_SVB        .SRES        2           ; 空き
_SEQ_056_SVB        .SRES        2           ; 空き
_SEQ_057_SVB        .SRES        2           ; 空き
_SEQ_058_SVB        .SRES        2           ; 空き
_SEQ_059_SVB        .SRES        2           ; 空き
_SEQ_060_SVB        .SRES        2           ; 空き
_SEQ_061_SVB        .SRES        2           ; 空き
_SEQ_062_SVB        .SRES        2           ; 空き
_SEQ_063_SVB        .SRES        2           ; 空き
_SEQ_064_SVB        .SRES        2           ; 空き
_SEQ_065_SVB        .SRES        2           ; 空き
_SEQ_066_SVB        .SRES        2           ; 空き
_SEQ_067_SVB        .SRES        2           ; 空き
_SEQ_068_SVB        .SRES        2           ; 空き
_SEQ_069_SVB        .SRES        2           ; 空き
_SEQ_070_SVB        .SRES        2           ; 空き
_SEQ_071_SVB        .SRES        2           ; 空き
_SEQ_072_SVB        .SRES        2           ; 空き
_SEQ_073_SVB        .SRES        2           ; 空き
_SEQ_074_SVB        .SRES        2           ; 空き
_SEQ_075_SVB        .SRES        2           ; 空き
_SEQ_076_SVB        .SRES        2           ; 空き
_SEQ_077_SVB        .SRES        2           ; 空き
_SEQ_078_SVB        .SRES        2           ; 空き
_SEQ_079_SVB        .SRES        2           ; 空き
_SEQ_DUMMY_01       .SRES        32          ; ダミー
_SV_SEQDT1_A91      .SRES        2           ; シーケンスモニタ設定１
_SV_SEQDT2_A91      .SRES        2           ; シーケンスモニタ設定２
_SV_SEQDT3_A91      .SRES        2           ; シーケンスモニタ設定３
_SV_SEQDT4_A91      .SRES        2           ; シーケンスモニタ設定４
_SV_DUMMY_A91       .SRES        22          ; 空き
_SV_POINT_A1        .SRES        2           ; スライド調節　小数点位置
_SV_KANDO_A21       .SRES        4           ; スライド自動調節　感度
_SV_UPDATA_A21      .SRES        4           ; スライド自動調節　上限
_SV_DNDATA_A21      .SRES        4           ; スライド自動調節　下限
_SV_GENITI_A21      .SRES        4           ; スライド自動調節　現位置
_SV_DNSTOP_A21      .SRES        2           ; スライド自動調節　下降停止
_SV_UPSTOP_A21      .SRES        2           ; スライド自動調節　上昇停止
_SV_MODORI_A21      .SRES        2           ; スライド自動調節　戻り量
_SV_SSEIDO_A21      .SRES        2           ; スライド自動調節　制御精度
_SV_DUMMY_A21       .SRES        20          ; 空き
_SV_MAXHIZ_A24      .SRES        2           ; 荷重校正　最大歪１
_SV_MAXKAJ_A24      .SRES        2           ; 荷重校正　最大荷重１
_SV_KOUKAJ_A24      .SRES        2           ; 荷重校正　校正荷重１
_SV_KOUSEI_A24      .SRES        2           ; 荷重校正　校正精度
_SV_MAXKA2_A24      .SRES        2           ; 荷重校正　最大荷重２
_SV_KOUKA2_A24      .SRES        2           ; 荷重校正　校正荷重２
_SV_MAXHI3_A24      .SRES        2           ; 荷重校正　最大歪３
_SV_MAXKA3_A24      .SRES        2           ; 荷重校正　最大荷重３
_SV_KOUKA3_A24      .SRES        2           ; 荷重校正　校正荷重３
_SV_APARAD_A24      .SRES        2           ; 荷重校正　最低表示荷重
_SV_COUNT1_A1       .SRES        2           ; 内部カウンタ１
_SV_COUNT2_A1       .SRES        2           ; 内部カウンタ２
_SV_COUNT3_A1       .SRES        2           ; 内部カウンタ３
_SV_TIMER1_A1       .SRES        2           ; 内部タイマ１
_SV_TIMER2_A1       .SRES        2           ; 内部タイマ２
_SV_TIMER3_A1       .SRES        2           ; 内部タイマ３
_SV_DUMMY_A1        .SRES        10          ; 空き
_SV_RCLSA1_A17      .SRES        2           ; システムカムＡ　ＯＮ角度
_SV_RCLSA2_A17      .SRES        2           ; システムカムＡ　ＯＦＦ角度
_SV_RCLSB1_A17      .SRES        2           ; システムカムＢ　ＯＮ角度
_SV_RCLSB2_A17      .SRES        2           ; システムカムＢ　ＯＦＦ角度
_SV_RCLSC1_A17      .SRES        2           ; システムカムＣ　ＯＮ角度
_SV_RCLSC2_A17      .SRES        2           ; システムカムＣ　ＯＦＦ角度
_SV_RCLSD1_A17      .SRES        2           ; システムカムＤ　ＯＮ角度
_SV_RCLSD2_A17      .SRES        2           ; システムカムＤ　ＯＦＦ角度
_SV_RCLSE1_A17      .SRES        2           ; システムカムＥ　ＯＮ角度
_SV_RCLSE2_A17      .SRES        2           ; システムカムＥ　ＯＦＦ角度
_SV_RCLSF1_A18      .SRES        2           ; システムカムＦ　ＯＮ角度
_SV_RCLSF2_A18      .SRES        2           ; システムカムＦ　ＯＦＦ角度
_SV_RCLSG1_A18      .SRES        2           ; システムカムＧ　ＯＮ角度
_SV_RCLSG2_A18      .SRES        2           ; システムカムＧ　ＯＦＦ角度
_SV_RCLSH1_A18      .SRES        2           ; システムカムＨ　ＯＮ角度
_SV_RCLSH2_A18      .SRES        2           ; システムカムＨ　ＯＦＦ角度
_SV_DUMMY_A18       .SRES        10          ; 空き
_SV_RNADIR_SEL1     .SRES        2           ; ﾘﾆｱｾﾝｻ極性
_SV_INCDIR_SEL1     .SRES        2           ; PG極性
_SV_INCPLS_1REV     .SRES        2           ; PG1回転のﾊﾟﾙｽ選択
_SV_INCPLS_HOSN     .SRES        2           ; PG補正N　ﾓｰﾀN回
_SV_INCPLS_HOSM     .SRES        2           ; PG補正M　ｸﾗﾝｸ角度M
_SV_MOTRPM_MAXM     .SRES        2           ; ﾓｰﾀ最大回転数
_SV_DNDINC_SPD1     .SRES        2           ; 段取速度
_SV_UPAREA_SPD1     .SRES        2           ; 待機点復帰速度
_SV_STDINC_SPD1     .SRES        2           ; 寸動速度
_SV_REVDAT_SPD1     .SRES        2           ; 予備速度１
_SV_REVDAT_SPD2     .SRES        2           ; 予備速度２
_SV_REVDAT_SPD3     .SRES        2           ; 予備速度３
_SV_TEPDAT_SPD1     .SRES        2           ; 手動ﾊﾟﾙｻ速度
_SV_TEPLAT_DAT1     .SRES        2           ; 手動ﾊﾟﾙｻ低倍率
_SV_TEPLAT_DAT2     .SRES        2           ; 手動ﾊﾟﾙｻ高倍率
_SV_INCPOS_KP01     .SRES        2           ; PG位置比例ｹﾞｲﾝ
_SV_RNAPOS_KP01     .SRES        2           ; ﾘﾆｱ位置比例ｹﾞｲﾝ
_SV_ACCLAT__TIM1    .SRES        2           ; 加減速時間
_SV_SSCURV_TIM1     .SRES        2           ; Ｓ字時間
_SV_UPAREA_INP1     .SRES        2           ; 上死点ｲﾝﾎﾟｼﾞｼｮﾝ
_SV_DNAREA_INP1     .SRES        2           ; 下死点ｲﾝﾎﾟｼﾞｼｮﾝ
_SV_OBJARA_INP1     .SRES        2           ; 目標位置ｲﾝﾎﾟｼﾞｼｮﾝ
_SV_INPPOS_TIM1     .SRES        2           ; ｲﾝﾎﾟｼﾞｼｮﾝﾁｪｯｸ時間
_SV_ARACHK_LNG1     .SRES        2           ; 上／下死点通過判定量
_SV_UPAREA_DIG1     .SRES        2           ; 回転時待機点(上死点)
_SV_DUMMY_A22       .SRES        2           ; 空き
_SV_UPAREA_JUDG     .SRES        4           ; 上死点判定範囲
_SV_DNAREA_JUDG     .SRES        4           ; 反転設定不可範囲
_SV_INCHEN_ELNG     .SRES        2           ; PG偏差異常幅
_SV_INCENC_ELNG     .SRES        2           ; PG-ENC一致量
_SV_INCRNA_ELNG     .SRES        2           ; PG-ﾘﾆｱ一致量
_SV_INCSTP_ELNG     .SRES        2           ; PG停止異常量
_SV_RNASTP_ELNG     .SRES        2           ; ﾘﾆｱ停止異常量
_SV_INCREV_ELNG     .SRES        2           ; PG逆転異常量
_SV_RNAREV_ELNG     .SRES        2           ; ﾘﾆｱ逆転異常量
_SV_DAIHAI_LNG1     .SRES        2           ; ﾀﾞｲﾊｲﾄ補正比較値(小)
_SV_DAIHAI_LNG2     .SRES        2           ; ﾀﾞｲﾊｲﾄ補正比較値(中)
_SV_DAIHAI_LNG3     .SRES        2           ; ﾀﾞｲﾊｲﾄ補正比較値(大)
_SV_AMPERR_VLT1     .SRES        2           ; 過負荷電圧1
_SV_AMPERR_TIM1     .SRES        2           ; 過負荷時間1
_SV_AMPERR_VLT2     .SRES        2           ; 過負荷電圧2
_SV_AMPERR_TIM2     .SRES        2           ; 過負荷時間2
_SV_AMPERR_VLT3     .SRES        2           ; 過負荷電圧3
_SV_AMPERR_TIM3     .SRES        2           ; 過負荷時間3
_SV_ORGRUP_DEG      .SRES        2           ; 原点復帰：原点右区間上 (COP2)
_SV_ORGRDN_DEG      .SRES        2           ; 原点復帰：原点右区間下 (COP2)
_SV_ORGLUP_DEG      .SRES        2           ; 原点復帰：原点左区間上 (COP2)
_SV_ORGLDN_DEG      .SRES        2           ; 原点復帰：原点左区間下 (COP2)
_SV_ORGMEM_DEG1     .SRES        2           ; 原点記憶調整：角度1軸 (COP2)
_SV_ORGMEM_DEG2     .SRES        2           ; 原点記憶調整：角度2軸 (COP2)
_SV_RNA_STLORK      .SRES        4           ; ストローク設定
_SV_OUTPLS_HOSA     .SRES        2           ; 出力ﾊﾟﾙｽ補正A
_SV_OUTPLS_HOSB     .SRES        2           ; 出力ﾊﾟﾙｽ補正B
_SV_UPHOLD_DIG      .SRES        2           ; 上昇ﾎｰﾙﾄﾞ角度
_SV_MACINE_SEL1     .SRES        2           ; 予備（機種選択１）
_SV_AMP100P_VLT     .SRES        2           ; AMP100%相当の電圧  V00m(2003/01/27)
_SV_RNAORG_SIN      .SRES        2           ; ﾊﾞｯｸｱｯﾌﾟ原点ﾃﾞｰﾀ符号  V00m(2003/01/27)
_SV_LSAABN_AGL1     .SRES        4           ; LSA異常検知の角度1　　V01v（2006/07/11）
_SV_LSAABN_AGL2     .SRES        4           ; LSA異常検知の角度2　　V01v（2006/07/11）
_SV_PLSALO_PLS      .SRES        2           ; パルサ倍率低　　V01v（2006/07/11）
_SV_PLSAHI_PLS      .SRES        2           ; パルサ倍率高　　V01v（2006/07/11）
_SV_HOSRAG_PLS1     .SRES        2           ; 原点記憶調整：軸間補正範囲1 (COP2)
_SV_HOSRAG_PLS2     .SRES        2           ; 原点記憶調整：軸間補正範囲2 (COP2)
_SV_HOSEI_SPD       .SRES        2           ; 原点記憶調整：補正速度 (COP2)
_SV_MANSAM_LEN      .SRES        2           ; 異常・補正：手動時同期 (COP2)
_SV_DANSAM_LEN      .SRES        2           ; 異常・補正：段取時同期 (COP2)
_SV_RUNSAMER_LEN1   .SRES        2           ; 異常・補正：運転同期異常１ (COP2)
_SV_RUNSAMER_LEN2   .SRES        2           ; 異常・補正：運転同期異常２ (COP2)
_SV_MANSAMER_PLS    .SRES        2           ; 異常・補正：手動同期異常 (COP2)
_SV_RUNSAMER_PLS    .SRES        2           ; 異常・補正：運転同期異常 (COP2)
_SV_ORGMEM_SW       .SRES        2           ; 原点記憶調整：SW関係 (COP2)
_SV_ORGMEM_DEGS1    .SRES        2           ; 原点記憶調整：角度1軸選択　(COP2)
_SV_ORGMEM_DEGS2    .SRES        2           ; 原点記憶調整：角度2軸選択　(COP2)
_SV_ORGMPL_SEL1     .SRES        2           ; 原点記憶調整：手ﾊﾟﾙｻ選択1軸選択　(COP2)
_SV_ORGMPL_SEL2     .SRES        2           ; 原点記憶調整：手ﾊﾟﾙｻ選択2軸選択　(COP2)
_SV_MOTMAX_FREQ     .SRES        4           ; ﾓｰﾀ最大時指令周波数
_SV_RNAORG_POS1     .SRES        4           ; 機械原点入力
_SV_RNAPOS_MAXP     .SRES        4           ; 機械上限
_SV_RNAPOS_MINP     .SRES        4           ; 機械下限
_SV_NEG_OFS_LNG     .SRES        4           ; 反転下限距離  V00m(2003/01/27)
_SV_RNAORG_PLS      .SRES        4           ; ﾊﾞｯｸｱｯﾌﾟ原点ﾃﾞｰﾀABS値  V00m(2003/01/27)
_SV_ORGSOK_PLS      .SRES        4           ; 原点復帰：原点測定ﾊﾟﾙｽ (COP2)
_SV_ORGCAL_DAT1     .SRES        4           ; 原点復帰：演算係数１ (COP2)→機種ｺｰﾄﾞ
_SV_ORGCAL_DAT2     .SRES        4           ; 原点復帰：演算係数２ (COP2)→機種番号
_SV_ORGCAL_DAT3     .SRES        4           ; 原点復帰：演算係数３ (COP2)
_SV_ORGCAL_DAT4     .SRES        4           ; 原点復帰：演算係数４ (COP2)
_SV_ORGCAL_DAT5     .SRES        4           ; 原点復帰：演算係数５ (COP2)
_SV_ORGCAL_DAT6     .SRES        4           ; 原点復帰：演算係数６ (COP2)
_SV_ORGSTRK_LEN1    .SRES        4           ; 原点復帰：ｽﾄﾛｰｸ1 (COP2)
_SV_ORGSTRK_LEN2    .SRES        4           ; 原点復帰：ｽﾄﾛｰｸ2 (COP2)
_SV_RNAORGMEM_LEG1  .SRES        4           ; 原点記憶調整：ﾘﾆｱ原点1軸記憶 (COP2)
_SV_RNAORGMEM_LEG2  .SRES        4           ; 原点記憶調整：ﾘﾆｱ原点2軸記憶 (COP2)
_SV_RNAORG_PLS1     .SRES        4           ; 原点記憶調整：機械原点1ﾊﾞｯｸｱｯﾌﾟ原点ﾃﾞｰﾀ (COP2)
_SV_RNAORG_PLS2     .SRES        4           ; 原点記憶調整：機械原点2ﾊﾞｯｸｱｯﾌﾟ原点ﾃﾞｰﾀ (COP2)
_SV_ORGMEM_DEG1A    .SRES        4           ; 原点記憶調整：角度1軸選択　(COP2)
_SV_ORGMEM_DEG2A    .SRES        4           ; 原点記憶調整：角度2軸選択　(COP2)
_SV_SERVO_97        .SRES        4           ; サーボパラメータ９７
_SV_SERVO_98        .SRES        4           ; サーボパラメータ９８
_SV_RNAORG_SIN1     .SRES        2           ; 原点記憶調整：機械原点1ﾊﾞｯｸｱｯﾌﾟ符号 (COP2)
_SV_RNAORG_SIN2     .SRES        2           ; 原点記憶調整：機械原点2ﾊﾞｯｸｱｯﾌﾟ符号 (COP2)
_SV_MOADR0_SQH      .SRES        2           ; モニタアドレス０　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR0_SQL      .SRES        2           ; モニタアドレス０　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADR1_SQH      .SRES        2           ; モニタアドレス１　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR1_SQL      .SRES        2           ; モニタアドレス１　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADR2_SQH      .SRES        2           ; モニタアドレス２　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR2_SQL      .SRES        2           ; モニタアドレス２　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADR3_SQH      .SRES        2           ; モニタアドレス３　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR3_SQL      .SRES        2           ; モニタアドレス３　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADR4_SQH      .SRES        2           ; モニタアドレス４　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR4_SQL      .SRES        2           ; モニタアドレス４　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADR5_SQH      .SRES        2           ; モニタアドレス５　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR5_SQL      .SRES        2           ; モニタアドレス５　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADR6_SQH      .SRES        2           ; モニタアドレス６　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR6_SQL      .SRES        2           ; モニタアドレス６　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADR7_SQH      .SRES        2           ; モニタアドレス７　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR7_SQL      .SRES        2           ; モニタアドレス７　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADR8_SQH      .SRES        2           ; モニタアドレス８　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR8_SQL      .SRES        2           ; モニタアドレス８　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADR9_SQH      .SRES        2           ; モニタアドレス９　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADR9_SQL      .SRES        2           ; モニタアドレス９　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADRA_SQH      .SRES        2           ; モニタアドレス１０　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADRA_SQL      .SRES        2           ; モニタアドレス１０　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADRB_SQH      .SRES        2           ; モニタアドレス１１　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADRB_SQL      .SRES        2           ; モニタアドレス１１　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADRC_SQH      .SRES        2           ; モニタアドレス１２　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADRC_SQL      .SRES        2           ; モニタアドレス１２　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADRD_SQH      .SRES        2           ; モニタアドレス１３　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADRD_SQL      .SRES        2           ; モニタアドレス１３　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADRE_SQH      .SRES        2           ; モニタアドレス１４　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADRE_SQL      .SRES        2           ; モニタアドレス１４　ｼｰｹﾝｽ下位　V01v　060713
_SV_MOADRF_SQH      .SRES        2           ; モニタアドレス１５　ｼｰｹﾝｽ上位　V01v　060713
_SV_MOADRF_SQL      .SRES        2           ; モニタアドレス１５　ｼｰｹﾝｽ下位　V01v　060713
_SV_SPMSV1_A1       .SRES        2           ; 検出速度１
_SV_SPMSV2_A1       .SRES        2           ; 検出速度２
_SV_SPMSV3_A1       .SRES        2           ; 検出速度３
_SV_SPMSV4_A1       .SRES        2           ; 段取速度１
_SV_SPMSV5_A1       .SRES        2           ; 段取速度２
_SV_MAXSPM_A14      .SRES        2           ; 機械最高速度設定
_SV_RNZ100_A15      .SRES        2           ; 待機点１連続　　１００％設定
_SV_RNZ090_A15      .SRES        2           ; 待機点１連続　　　９０％設定
_SV_RNZ080_A15      .SRES        2           ; 待機点１連続　　　８０％設定
_SV_RNZ070_A15      .SRES        2           ; 待機点１連続　　　７０％設定
_SV_RNZ060_A15      .SRES        2           ; 待機点１連続　　　６０％設定
_SV_RNZ050_A15      .SRES        2           ; 待機点１連続　　　５０％設定
_SV_ITK100_A15      .SRES        2           ; 待機点１一行程　１００％設定
_SV_ITK090_A15      .SRES        2           ; 待機点１一行程　　９０％設定
_SV_ITK080_A15      .SRES        2           ; 待機点１一行程　　８０％設定
_SV_ITK070_A15      .SRES        2           ; 待機点１一行程　　７０％設定
_SV_ITK060_A15      .SRES        2           ; 待機点１一行程　　６０％設定
_SV_ITK050_A15      .SRES        2           ; 待機点１一行程　　５０％設定
_SV_RNZ100_A152     .SRES        2           ; 待機点２連続　　１００％設定
_SV_RNZ090_A152     .SRES        2           ; 待機点２連続　　　９０％設定
_SV_RNZ080_A152     .SRES        2           ; 待機点２連続　　　８０％設定
_SV_RNZ070_A152     .SRES        2           ; 待機点２連続　　　７０％設定
_SV_RNZ060_A152     .SRES        2           ; 待機点２連続　　　６０％設定
_SV_RNZ050_A152     .SRES        2           ; 待機点２連続　　　５０％設定
_SV_ITK100_A152     .SRES        2           ; 待機点２一行程　１００％設定
_SV_ITK090_A152     .SRES        2           ; 待機点２一行程　　９０％設定
_SV_ITK080_A152     .SRES        2           ; 待機点２一行程　　８０％設定
_SV_ITK070_A152     .SRES        2           ; 待機点２一行程　　７０％設定
_SV_ITK060_A152     .SRES        2           ; 待機点２一行程　　６０％設定
_SV_ITK050_A152     .SRES        2           ; 待機点２一行程　　５０％設定
_SV_RNZ100_A153     .SRES        2           ; 待機点３連続　　１００％設定
_SV_RNZ090_A153     .SRES        2           ; 待機点３連続　　　９０％設定
_SV_RNZ080_A153     .SRES        2           ; 待機点３連続　　　８０％設定
_SV_RNZ070_A153     .SRES        2           ; 待機点３連続　　　７０％設定
_SV_RNZ060_A153     .SRES        2           ; 待機点３連続　　　６０％設定
_SV_RNZ050_A153     .SRES        2           ; 待機点３連続　　　５０％設定
_SV_ITK100_A153     .SRES        2           ; 待機点３一行程　１００％設定
_SV_ITK090_A153     .SRES        2           ; 待機点３一行程　　９０％設定
_SV_ITK080_A153     .SRES        2           ; 待機点３一行程　　８０％設定
_SV_ITK070_A153     .SRES        2           ; 待機点３一行程　　７０％設定
_SV_ITK060_A153     .SRES        2           ; 待機点３一行程　　６０％設定
_SV_ITK050_A153     .SRES        2           ; 待機点３一行程　　５０％設定
_SV_KAGENS_A1       .SRES        2           ; 加減速時間
_SV_DUMMY_102       .SRES        2           ; 空き
_SV_DUMMY_103       .SRES        2           ; 空き
_SV_DUMMY_104       .SRES        2           ; 空き
_SV_DUMMY_105       .SRES        2           ; 空き
_SV_DUMMY_106       .SRES        2           ; 空き
_SV_DUMMY_107       .SRES        2           ; 空き
_SV_SPM001_A15      .SRES        2           ; 最高速度設定の１００％演算値
_SV_SPM002_A15      .SRES        2           ; 最高速度設定の　９０％演算値
_SV_SPM003_A15      .SRES        2           ; 最高速度設定の　８０％演算値
_SV_SPM004_A15      .SRES        2           ; 最高速度設定の　７０％演算値
_SV_SPM005_A15      .SRES        2           ; 最高速度設定の　６０％演算値
_SV_SPM006_A15      .SRES        2           ; 最高速度設定の　５０％演算値
_SV_SPM001_A152     .SRES        2           ; 空き
_SV_SPM002_A152     .SRES        2           ; 空き
_SV_SPM003_A152     .SRES        2           ; 空き
_SV_SPM004_A152     .SRES        2           ; 空き
_SV_SPM005_A152     .SRES        2           ; 空き
_SV_SPM006_A152     .SRES        2           ; 空き
_SV_SPM001_A153     .SRES        2           ; 空き
_SV_SPM002_A153     .SRES        2           ; 空き
_SV_SPM003_A153     .SRES        2           ; 空き
_SV_SPM004_A153     .SRES        2           ; 空き
_SV_SPM005_A153     .SRES        2           ; 空き
_SV_DUMMY_A153      .SRES        2           ; 空き
_SV_POINT_A47       .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　小数点位置
_SV_KANDO_A47       .SRES        4           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　感度
_SV_UPDATA_A47      .SRES        4           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　上限
_SV_DNDATA_A47      .SRES        4           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　下限
_SV_GENITI_A47      .SRES        4           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　現位置
_SV_DNSTOP_A47      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　下降停止
_SV_UPSTOP_A47      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　上昇停止
_SV_MODORI_A47      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　戻り量
_SV_SSEIDO_A47      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　制御精度
_SV_DUMMY_A17       .SRES        2           ; 空き
_SV_POINT_A48       .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　小数点位置
_SV_KANDO_A48       .SRES        4           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　感度
_SV_UPDATA_A48      .SRES        4           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　上限
_SV_DNDATA_A48      .SRES        4           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　下限
_SV_GENITI_A48      .SRES        4           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　現位置
_SV_DNSTOP_A48      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　下降停止
_SV_UPSTOP_A48      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　上昇停止
_SV_MODORI_A48      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　戻り量
_SV_SSEIDO_A48      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　制御精度
_SV_BARAUP_A49      .SRES        2           ; バランサ圧力調節　上限
_SV_BARADN_A49      .SRES        2           ; バランサ圧力調節　上限
_SV_DAILUP_A49      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ左上限
_SV_DAILDN_A49      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ左下限
_SV_DAIRUP_A49      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ右上限
_SV_DAIRDN_A49      .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ右下限
_SV_SYUMAX_A14      .SRES        2           ; 仕様速度以下
_SV_CLTIME_C1       .SRES        2           ; クラッチタイム
_SV_BRTIME_C1       .SRES        2           ; ブレーキタイム 設定
_SV_BRDIG_C1        .SRES        2           ; ブレーキ角度 設定
_SV_BARKIJ_A45      .SRES        2           ; バランサ圧基準
_SV_CILDN1_A50      .SRES        2           ; コイルライン設定上限値１
_SV_CILUP1_A50      .SRES        2           ; コイルライン設定下限値１
_SV_CILDN2_A50      .SRES        2           ; コイルライン設定上限値２
_SV_CILUP2_A50      .SRES        2           ; コイルライン設定下限値２
_SV_CILDN3_A50      .SRES        2           ; コイルライン設定上限値３
_SV_CILUP3_A50      .SRES        2           ; コイルライン設定下限値３
_SV_CILDN4_A50      .SRES        2           ; コイルライン設定上限値４
_SV_CILUP4_A50      .SRES        2           ; コイルライン設定下限値４
_SV_CILDN5_A50      .SRES        2           ; コイルライン設定上限値５
_SV_CILUP5_A50      .SRES        2           ; コイルライン設定下限値５
_SV_CILDN6_A50      .SRES        2           ; コイルライン設定上限値６
_SV_CILUP6_A50      .SRES        2           ; コイルライン設定下限値６
_SV_CILTN1_A50      .SRES        2           ; コイルライン設定１小数点
_SV_CILTN2_A50      .SRES        2           ; コイルライン設定２小数点
_SV_CILTN3_A50      .SRES        2           ; コイルライン設定３小数点
_SV_CILTN4_A50      .SRES        2           ; コイルライン設定４小数点
_SV_CILTN5_A50      .SRES        2           ; コイルライン設定５小数点
_SV_CILTN6_A50      .SRES        2           ; コイルライン設定６小数点
_SV_CILUMU_A50      .SRES        2           ; コイルライン設定有無選択
_SV_CILMAI_A50      .SRES        2           ; コイルライン設定マイナス選択
                    .SRES        2           ; バランサ圧力上限
                    .SRES        2           ; バランサ圧力上限
                    .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ左上限
                    .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ左下限
                    .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ右上限
                    .SRES        2           ; ﾀﾞｲｸｯｼｮﾝ右下限
_SV_NEXTNO_D1       .SRES        2           ; 自動金型用次期ファイル読み出し番号
_SV_RNADIR_SEL2     .SRES        2           ; ﾘﾆｱｾﾝｻ2軸目の極性 (COP2)
_SV_FCLS_STR_DEG    .SRES        2           ; ﾌﾙｸﾛ開始角度 (COP2)
_SV_FCLS_STR_HENS   .SRES        2           ; ﾌﾙｸﾛ開始偏差 (COP2)
_SV_FCLS_ZIKI_SPD1  .SRES        2           ; ﾌﾙｸﾛ自起動速度1 (COP2)
_SV_FCLS_ZIKI_SPD2  .SRES        2           ; ﾌﾙｸﾛ自起動速度2 (COP2)
_SV_SYNC_ERR_DEGA   .SRES        2           ; 同期異常領域角度A (COP2)
_SV_SYNC_ERR_DEGB   .SRES        2           ; 同期異常領域角度B (COP2)
_SV_SYNC_ERR_DEGC   .SRES        2           ; 同期異常領域角度C (COP2)
_SV_SYNC_ERR_DEGD   .SRES        2           ; 同期異常領域角度D (COP2)
_SV_SYNC_ERR_RNAA   .SRES        2           ; ﾘﾆｱ同期異常A (COP2)
_SV_SYNC_ERR_RNAB   .SRES        2           ; ﾘﾆｱ同期異常B (COP2)
_SV_SYNC_ERR_RNAC   .SRES        2           ; ﾘﾆｱ同期異常C (COP2)
_SV_SYNC_ERR_RNAD   .SRES        2           ; ﾘﾆｱ同期異常D (COP2)
_SV_SYNC_ERR_PGA    .SRES        2           ; PG同期異常A (COP2)
_SV_SYNC_ERR_PGB    .SRES        2           ; PG同期異常B (COP2)
_SV_SYNC_ERR_PGC    .SRES        2           ; PG同期異常C (COP2)
_SV_SYNC_ERR_PGD    .SRES        2           ; PG同期異常D (COP2)
_SV_IPS_ADR0        .SRES        2           ; IPｱﾄﾞﾚｽ　（2007/11/17）
_SV_IPS_ADR1        .SRES        2           ; IPｱﾄﾞﾚｽ　（2007/11/17）
_SV_IPS_ADR2        .SRES        2           ; IPｱﾄﾞﾚｽ　（2007/11/17）
_SV_IPS_ADR3        .SRES        2           ; IPｱﾄﾞﾚｽ　（2007/11/17）
_SV_SUB_NET0        .SRES        2           ; ｻﾌﾞﾈｯﾄﾏｽｸ　（2007/11/17）
_SV_SUB_NET1        .SRES        2           ; ｻﾌﾞﾈｯﾄﾏｽｸ　（2007/11/17）
_SV_SUB_NET2        .SRES        2           ; ｻﾌﾞﾈｯﾄﾏｽｸ　（2007/11/17）
_SV_SUB_NET3        .SRES        2           ; ｻﾌﾞﾈｯﾄﾏｽｸ　（2007/11/17）
_SV_DEF_GAT0        .SRES        2           ; ﾃﾞﾌｫﾙﾄｹﾞｰﾄｳｪｲ　（2007/11/17）
_SV_DEF_GAT1        .SRES        2           ; ﾃﾞﾌｫﾙﾄｹﾞｰﾄｳｪｲ　（2007/11/17）
_SV_DEF_GAT2        .SRES        2           ; ﾃﾞﾌｫﾙﾄｹﾞｰﾄｳｪｲ　（2007/11/17）
_SV_DEF_GAT3        .SRES        2           ; ﾃﾞﾌｫﾙﾄｹﾞｰﾄｳｪｲ　（2007/11/17）
                    .SRES        2           ; 空き(ALIGN)
_SV_WAVE_SCL1U      .SRES        4           ; ｽﾗｲﾄﾞ位置ｽｹｰﾙ上限(ｻﾝﾌﾟﾘﾝｸﾞ画面)
_SV_WAVE_SCL1D      .SRES        4           ; ｽﾗｲﾄﾞ位置ｽｹｰﾙ下限(ｻﾝﾌﾟﾘﾝｸﾞ画面)
_SV_WAVE_SCL2U      .SRES        2           ; 荷重ｽｹｰﾙ上限(ｻﾝﾌﾟﾘﾝｸﾞ画面)
_SV_WAVE_SCL2D      .SRES        2           ; 荷重ｽｹｰﾙ下限(ｻﾝﾌﾟﾘﾝｸﾞ画面)
_SV_WAVE_SCL3U      .SRES        4           ; ｽﾗｲﾄﾞ位置ｽｹｰﾙ上限(ﾄﾚﾝﾄﾞ画面)
_SV_WAVE_SCL3D      .SRES        4           ; ｽﾗｲﾄﾞ位置ｽｹｰﾙ下限(ﾄﾚﾝﾄﾞ画面)
_SV_WAVE_SCL4U      .SRES        2           ; 荷重ｽｹｰﾙ上限(ﾄﾚﾝﾄﾞ画面)
_SV_WAVE_SCL4D      .SRES        2           ; 荷重ｽｹｰﾙ下限(ﾄﾚﾝﾄﾞ画面)
_SV_WAVE_PAGE       .SRES        2           ; ﾍﾟｰｼﾞ(ﾄﾚﾝﾄﾞ画面)
_SV_SMPTRG_CNT1     .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞSITﾌﾟﾘﾄﾘｶﾞ個数
_SV_TRDCSR_RNAU     .SRES        4           ; ｽﾗｲﾄﾞ位置上限検出位置
_SV_TRDCSR_RNAD     .SRES        4           ; ｽﾗｲﾄﾞ位置下限検出位置
_SV_BRDIG_C2        .SRES        2           ; ﾌﾞﾚｰｷ角度2(%)　　V05r（2010/08/11）
_SV_BRTIME_C2       .SRES        2           ; ﾌﾞﾚｰｷﾀｲﾑ2(%)　　V05r（2010/08/11）
_SV_INTER_TIM       .SRES        2           ; 制動性能試験ｲﾝﾀｰﾊﾞﾙﾀｲﾏ　　V05r（2010/08/11）
_IDOU_2_4BYTE1      .SRES        2           ; 電力ﾓﾆﾀ棒ｸﾞﾗﾌ最大　　V06 （2010/09/07）
_IDOU_2_4BYTE2      .SRES        2           ; 電力ﾓﾆﾀ折れ線ｸﾞﾗﾌ最大　　V06 （2010/09/07）
_SV_EPMCSR_TIM      .SRES        2           ; 電力ﾓﾆﾀ単位時間　　V06 （2010/09/07）
_SV_SRVPAR_B0       .SRES        2           ; サーボパラメータB0　　電力用ｵﾌｾｯﾄ
_SV_SRVPAR_B1       .SRES        2           ; サーボパラメータB1　　電力用最大値
_SV_SRVPAR_B2       .SRES        2           ; サーボパラメータB2　　電力用ﾄﾙｸ値
_SV_SRVPAR_B3       .SRES        2           ; サーボパラメータB3　　ﾄﾙｸ側遅れ時間
_SV_SRVPAR_B4       .SRES        2           ; サーボパラメータB4　　調整係数A
_SV_SRVPAR_B5       .SRES        2           ; サーボパラメータB5　　調整係数B
_SV_SRVPAR_B6       .SRES        2           ; サーボパラメータB6　　調整電力符号
_SV_SRVPAR_B7       .SRES        2           ; サーボパラメータB7　　調整電力
_SV_WAVE_SCL5U      .SRES        4           ; 瞬時電力最大(ｻﾝﾌﾟﾘﾝｸﾞ画面)
_SV_WAVE_SCL5D      .SRES        4           ; 瞬時電力最小(ｻﾝﾌﾟﾘﾝｸﾞ画面)
_SV_WAVE_SCL6U      .SRES        4           ; 1サイクルの電力量最大(ｻﾝﾌﾟﾘﾝｸﾞ画面)
_SV_WAVE_SCL6D      .SRES        4           ; 1サイクルの電力量最小(ｻﾝﾌﾟﾘﾝｸﾞ画面)
_SV_SRVPAR_B8       .SRES        2           ; サーボパラメータB8　　エコメータ基準値
_SV_SRVPAR_B9       .SRES        2           ; サーボパラメータB9　　エコメータスケール
_SV_MOTRPM_MAXP     .SRES        2           ; BA.モータ最大回転数
_SV_ACCLAT__TIMP    .SRES        2           ; BB.加減速時間
_SV_EPMGRP_MXL      .SRES        4           ; 電力ﾓﾆﾀ棒ｸﾞﾗﾌ最大　　V06 （2010/09/07）
_SV_EPMGRP_MXR      .SRES        4           ; 電力ﾓﾆﾀ折れ線ｸﾞﾗﾌ最大　　V06 （2010/09/07）
_SV_ONESTR_SPD2     .SRES        2           ; サーボパラメータ29　反転時自起動速度　　V06b（2010/12/06）
_SV_WORKER_COD      .SRES        2           ; 作業者ｺｰﾄﾞ　　V06c（2011/1/2）
_SV_WORKER_ENT_FLG  .SRES        2           ; 作業者ｺｰﾄﾞ登録ﾌﾗｸﾞ　　V06c（2011/1/2）
                    .SRES        2           ; 空き
_SV_ORDER_COD       .SRES        4           ; 注番ｺｰﾄﾞ　　V06c（2011/1/2）
_SV_PLAN_CNT        .SRES        4           ; 計画数　　V06c（2011/1/2）
_SV_BAD_CNT         .SRES        4           ; 不良数　　V06c（2011/1/2）
_SV_SRVPAR_BC       .SRES        4           ; サーボパラメータBC　ﾎﾞﾙｽﾀL　　　　V06d（2011/3/18）
_SV_SRVPAR_BD       .SRES        4           ; サーボパラメータBD　ｽﾗｲﾄﾞS　　　　V06d（2011/3/18）
_SV_SRVPAR_BE       .SRES        4           ; サーボパラメータBE　半径　　　　　　V06d（2011/3/18）
_SV_SRVPAR_BF       .SRES        4           ; サーボパラメータBF　原点逆転　　　V06d（2011/3/18）
_SV_SRVPAR_BG       .SRES        4           ; サーボパラメータBG　原点正転　　　V06d（2011/3/18）
_SV_SRVPAR_BH       .SRES        4           ; サーボパラメータBH　　　　　V06d（2011/3/18）
_SV_SRVPAR_BI       .SRES        4           ; サーボパラメータBI　　　　　V06d（2011/3/18）
_SV_SRVPAR_BJ       .SRES        4           ; サーボパラメータBJ　　　　　V06d（2011/3/18）
_SV_SRVPAR_BK       .SRES        4           ; サーボパラメータBK　　　　　V06d（2011/3/18）
_SV_SRVPAR_BL       .SRES        4           ; サーボパラメータBL　　　　　V06d（2011/3/18）
_SV_SRVPAR_BM       .SRES        4           ; サーボパラメータBM　　　　　V06d（2011/3/18）
_SV_LANGUAGE        .SRES        2           ; 言語設定
_SV_KATTCH_SPD      .SRES        2           ; タッチ位置検出速度
_SV_KAJAREA_SNO     .SRES        2           ; 荷重測定範囲　開始工程No.
_SV_KAJAREA_SAG     .SRES        2           ; 荷重測定範囲　開始角度
_SV_KAJAREA_ENO     .SRES        2           ; 荷重測定範囲　終了工程No.
_SV_KAJAREA_EAG     .SRES        2           ; 荷重測定範囲　終了角度
_SV_KAJAREA_SEL     .SRES        2           ; 記録荷重選択
_SV_KATTCH_SAG      .SRES        2           ; タッチ位置検出開始角度
_SV_KATTCH_EAG      .SRES        2           ; タッチ位置検出終了角度
_SV_SLPOS_DIR       .SRES        2           ; スライド自動調節　位置決め方向
_SV_SPM_LIM         .SRES        2           ; 制限速度（ﾒｶﾌﾟﾚｽ）　　2014/09/15
_SV_PASSWORD        .SRES        2           ; パスワード　2017/11/06
_SV_DUMMY_D1        .SRES        132         ; 空き
_FRAM_KAT_TOP       .SRES        2           ; F-RAM領域の型データのトップラベル
_SV_DUMMY_D2        .SRES        14          ; 空き
_SEQ_032_SV         .SRES        2           ; トータル＆ロットカウンタ　入／切選択
_SEQ_033_SV         .SRES        2           ; 空き
_SEQ_034_SV         .SRES        2           ; エジェクタ１～６　入／切選択、カム／タイマ選択
_SEQ_035_SV         .SRES        2           ; 空き
_SEQ_036_SV         .SRES        2           ; ミスフィード１～４　入／切、即／連
_SEQ_037_SV         .SRES        2           ; ミスフィード１～４　N.O／Ｎ．Ｃ、接触／保持
_SEQ_038_SV         .SRES        2           ; ロータリカム１～１６　入／切選択
_SEQ_039_SV         .SRES        2           ; ロータリカム１７～２０　入／切選択
_SEQ_040_SV         .SRES        2           ; 空き
_SEQ_041_SV         .SRES        2           ; 上型クランパ、下型クランパ　内／全／外選択
_SEQ_042_SV         .SRES        2           ; ダイリフタ　内/全／外選択
_SEQ_043_SV         .SRES        2           ; 空き
_SEQ_044_SV         .SRES        2           ; ｽﾗｲﾄﾞ自動調節 生産／段取１／段取２選択
_SEQ_045_SV         .SRES        2           ; 空き
_SEQ_046_SV         .SRES        2           ; 空き
_SEQ_047_SV         .SRES        2           ; 空き
_SEQ_048_SV         .SRES        2           ; 空き
_SEQ_049_SV         .SRES        2           ; 空き
_SEQ_050_SV         .SRES        2           ; 空き
_SEQ_051_SV         .SRES        2           ; 空き
_SEQ_052_SV         .SRES        2           ; 空き
_SEQ_053_SV         .SRES        2           ; 空き
_SEQ_054_SV         .SRES        2           ; 空き
_SEQ_055_SV         .SRES        2           ; 空き
_SEQ_056_SV         .SRES        2           ; 空き
_SEQ_057_SV         .SRES        2           ; 空き
_SEQ_058_SV         .SRES        2           ; 空き
_SEQ_059_SV         .SRES        2           ; 空き
_SEQ_060_SV         .SRES        2           ; 空き
_SEQ_061_SV         .SRES        2           ; 空き
_SEQ_062_SV         .SRES        2           ; 空き
_SEQ_063_SV         .SRES        2           ; 空き
_SEQ_064_SV         .SRES        2           ; 空き
_SEQ_065_SV         .SRES        2           ; 空き
_SEQ_066_SV         .SRES        2           ; 空き
_SEQ_067_SV         .SRES        2           ; 空き
_SEQ_068_SV         .SRES        2           ; 空き
_SEQ_069_SV         .SRES        2           ; 空き
_SEQ_070_SV         .SRES        2           ; 空き
_SEQ_071_SV         .SRES        2           ; 空き
_SEQ_072_SV         .SRES        2           ; 空き
_SEQ_073_SV         .SRES        2           ; 空き
_SEQ_074_SV         .SRES        2           ; 空き
_SEQ_075_SV         .SRES        2           ; 空き
_SEQ_076_SV         .SRES        2           ; 空き
_SEQ_077_SV         .SRES        2           ; 空き
_SEQ_078_SV         .SRES        2           ; 空き
_SEQ_079_SV         .SRES        2           ; 空き
_SV_PUR1SV_B4       .SRES        4           ; ロットカウンタ１設定値
_SV_PUR2SV_B41      .SRES        4           ; ロットカウンタ２設定値
_SV_TAIKIPOS0_SRV   .SRES        4           ; 待機位置
_SV_KAITEN0_SRV     .SRES        2           ; 回転方式
_SV_DANSUU0_SRV     .SRES        2           ; 段数
_SV_TAIKIKAKU0_SRV  .SRES        2           ; 待機角
_SV_TAIKSPD0_SRV    .SRES        2           ; 基準速度
_SV_DAIHAITO0_SRV   .SRES        4           ; ダイハイト
_SV_HOASEI0_SRV     .SRES        2           ; 補正データ
_SV_TAIKTIM0_SRV    .SRES        2           ; 待機時間
_SV_1DANDEG0_SRV    .SRES        2           ; 1段目目標角度
_SV_2DANDEG0_SRV    .SRES        2           ; 2段目目標角度
_SV_3DANDEG0_SRV    .SRES        2           ; 3段目目標角度
_SV_4DANDEG0_SRV    .SRES        2           ; 4段目目標角度
_SV_5DANDEG0_SRV    .SRES        2           ; 5段目目標角度
_SV_6DANDEG0_SRV    .SRES        2           ; 6段目目標角度
_SV_7DANDEG0_SRV    .SRES        2           ; 7段目目標角度
_SV_8DANDEG0_SRV    .SRES        2           ; 8段目目標角度
_SV_9DANDEG0_SRV    .SRES        2           ; 9段目目標角度
_SV_10DANDEG0_SRV   .SRES        2           ; 10段目目標角度
_SV_1DANPOS0_SRV    .SRES        4           ; 1段目目標位置
_SV_2DANPOS0_SRV    .SRES        4           ; 2段目目標位置
_SV_3DANPOS0_SRV    .SRES        4           ; 3段目目標位置
_SV_4DANPOS0_SRV    .SRES        4           ; 4段目目標位置
_SV_5DANPOS0_SRV    .SRES        4           ; 5段目目標位置
_SV_6DANPOS0_SRV    .SRES        4           ; 6段目目標位置
_SV_7DANPOS0_SRV    .SRES        4           ; 7段目目標位置
_SV_8DANPOS0_SRV    .SRES        4           ; 8段目目標位置
_SV_9DANPOS0_SRV    .SRES        4           ; 9段目目標位置
_SV_10DANPOS0_SRV   .SRES        4           ; 10段目目標位置
_SV_1DANSPD0_SRV    .SRES        2           ; 1段目移動速度
_SV_2DANSPD0_SRV    .SRES        2           ; 2段目移動速度
_SV_3DANSPD0_SRV    .SRES        2           ; 3段目移動速度
_SV_4DANSPD0_SRV    .SRES        2           ; 4段目移動速度
_SV_5DANSPD0_SRV    .SRES        2           ; 5段目移動速度
_SV_6DANSPD0_SRV    .SRES        2           ; 6段目移動速度
_SV_7DANSPD0_SRV    .SRES        2           ; 7段目移動速度
_SV_8DANSPD0_SRV    .SRES        2           ; 8段目移動速度
_SV_9DANSPD0_SRV    .SRES        2           ; 9段目移動速度
_SV_10DANSPD0_SRV   .SRES        2           ; 10段目移動速度
_SV_1DANTIM0_SRV    .SRES        2           ; 1段目停止時間
_SV_2DANTIM0_SRV    .SRES        2           ; 2段目停止時間
_SV_3DANTIM0_SRV    .SRES        2           ; 3段目停止時間
_SV_4DANTIM0_SRV    .SRES        2           ; 4段目停止時間
_SV_5DANTIM0_SRV    .SRES        2           ; 5段目停止時間
_SV_6DANTIM0_SRV    .SRES        2           ; 6段目停止時間
_SV_7DANTIM0_SRV    .SRES        2           ; 7段目停止時間
_SV_8DANTIM0_SRV    .SRES        2           ; 8段目停止時間
_SV_9DANTIM0_SRV    .SRES        2           ; 9段目停止時間
_SV_10DANTIM0_SRV   .SRES        2           ; 10段目停止時間
_SV_CYCTIM0_SRV     .SRES        2           ; サイクルタイム
_SV_TAIKAN0_SRV     .SRES        2           ; 待機完了範囲
_SV_MOKKAN0_SRV     .SRES        2           ; 目標完了範囲
_SV_KAJYUU_PRS0     .SRES        2           ; 荷重補正
_SV_KAJYUU_OBJP0    .SRES        2           ; 荷重目標
_SV_DUMMY_B11       .SRES        6           ; 空き
_SV_EJESAT1_C4      .SRES        2           ; エジェクタ１　ＯＮ工程　　　カム仕様
_SV_EJEKK1_C4       .SRES        2           ; エジェクタ１　ＯＮ角度　　　カム仕様
_SV_EJESTP1_C4      .SRES        2           ; エジェクタ１　ＯＦＦ工程　　　カム仕様
_SV_EJEKK2_C4       .SRES        2           ; エジェクタ１　ＯＦＦ角度　　カム仕様
_SV_EJESAT1_C4A     .SRES        2           ; エジェクタ２　ＯＮ工程　　　カム仕様
_SV_EJEKK1_C4A      .SRES        2           ; エジャクタ２　ＯＮ角度　　　カム仕様
_SV_EJESTP1_C4A     .SRES        2           ; エジェクタ２　ＯＦＦ工程　　　カム仕様
_SV_EJEKK2_C4A      .SRES        2           ; エジェクタ２　ＯＦＦ角度　　カム仕様
_SV_EJESAT1_C4B     .SRES        2           ; エジェクタ３　ＯＮ工程　　　カム仕様
_SV_EJEKK1_C4B      .SRES        2           ; エジャクタ３　ＯＮ角度　　　カム仕様
_SV_EJESTP1_C4B     .SRES        2           ; エジェクタ３　ＯＦＦ工程　　　カム仕様
_SV_EJEKK2_C4B      .SRES        2           ; エジェクタ３　ＯＦＦ角度　　カム仕様
_SV_AUTSTA_C41      .SRES        2           ; 自動化１　ＯＮ工程　　　カム仕様
_SV_AUTKK1_C41      .SRES        2           ; 自動化１　ＯＮ角度　　　カム仕様
_SV_AUTSTP_C41      .SRES        2           ; 自動化１　ＯFF工程　　　カム仕様
_SV_AUTKK2_C41      .SRES        2           ; 自動化１　ＯＦＦ角度　　　カム仕様
_SV_AUTSTA_C41A     .SRES        2           ; 自動化２　ＯＮ工程　　　カム仕様
_SV_AUTKK1_C41A     .SRES        2           ; 自動化２　ＯＮ角度　　　カム仕様
_SV_AUTSTP_C41A     .SRES        2           ; 自動化２　ＯFF工程　　　カム仕様
_SV_AUTKK2_C41A     .SRES        2           ; 自動化２　ＯＦＦ角度　　　カム仕様
_SV_AUTSTA_C41B     .SRES        2           ; 自動化３　ＯＮ工程　　　カム仕様
_SV_AUTKK1_C41B     .SRES        2           ; 自動化３　ＯＮ角度　　　カム仕様
_SV_AUTSTP_C41B     .SRES        2           ; 自動化３　ＯFF程　　　カム仕様
_SV_AUTKK2_C41B     .SRES        2           ; 自動化３　ＯＦＦ角度　　　カム仕様
_SV_EJESTA_C5       .SRES        2           ; エジェクタ１　ＯＮ工程　　　タイマ仕様
_SV_EJEKK3_C5       .SRES        2           ; エジェクタ１　ＯＮ角度　　　タイマ仕様
_SV_EJESTP_C5       .SRES        2           ; エジェクタ１　ＯＦＦ工程　　　タイマ仕様
_SV_EJETIM_C5       .SRES        2           ; エジェクタ１　ＯＦＦタイマ　タイマ仕様
_SV_EJESTA_C5A      .SRES        2           ; エジェクタ２　ＯＮ工程　　　タイマ仕様
_SV_EJEKK3_C5A      .SRES        2           ; エジェクタ２　ＯＮ角度　　　タイマ仕様
_SV_EJESTP_C5A      .SRES        2           ; エジェクタ２　ＯＦＦ工程　　　タイマ仕様
_SV_EJETIM_C5A      .SRES        2           ; エジェクタ２　ＯＦＦタイマ　タイマ仕様
_SV_EJESTA_C5B      .SRES        2           ; エジェクタ３　ＯＮ工程　　　タイマ仕様
_SV_EJEKK3_C5B      .SRES        2           ; エジェクタ３　ＯＮ角度　　　タイマ仕様
_SV_EJESTP_C5B      .SRES        2           ; エジェクタ２　ＯＦＦ工程　　　タイマ仕様
_SV_EJETIM_C5B      .SRES        2           ; エジェクタ３　ＯＦＦタイマ　タイマ仕様
_SV_AUTSTA_C51      .SRES        2           ; 自動化１　ＯＮ工程　　　タイマ仕様
_SV_AUTKK3_C51      .SRES        2           ; 自動化１　ＯＮ角度　　　　　タイマ仕様
_SV_AUTSTP_C51      .SRES        2           ; 自動化１　ＯFF工程　　　タイマ仕様
_SV_AUTTIM_C51      .SRES        2           ; 自動化１　ＯＦＦタイマ　　　タイマ仕様
_SV_AUTSTA_C51A     .SRES        2           ; 自動化２　ＯＮ工程　　　タイマ仕様
_SV_AUTKK3_C51A     .SRES        2           ; 自動化２　ＯＮ角度　　　　　タイマ仕様
_SV_AUTSTP_C51A     .SRES        2           ; 自動化２　ＯFF工程　　　タイマ仕様
_SV_AUTTIM_C51A     .SRES        2           ; 自動化２　ＯＦＦタイマ　　　タイマ仕様
_SV_AUTSTA_C51B     .SRES        2           ; 自動化３　ＯＮ工程　　　タイマ仕様
_SV_AUTKK3_C51B     .SRES        2           ; 自動化３　ＯＮ角度　　　　　タイマ仕様
_SV_AUTSTP_C51B     .SRES        2           ; 自動化３　ＯFF程　　　タイマ仕様
_SV_AUTTIM_C51B     .SRES        2           ; 自動化３　ＯＦＦタイマ　　　タイマ仕様
_SV_MISSTA1_C9      .SRES        2           ; ミスフィード１　ＯＮ工程
_SV_MISSK1_C9       .SRES        2           ; ミスフィード１　ＯＮ角度
_SV_MISSTP1_C9      .SRES        2           ; ミスフィード１　ＯＦＦ工程
_SV_MISSK2_C9       .SRES        2           ; ミスフィード１　ＯＦＦ角度
_SV_MISSTA2_C9      .SRES        2           ; ミスフィード２　ＯＮ工程
_SV_MISSK3_C9       .SRES        2           ; ミスフィード２　ＯＮ角度
_SV_MISSTP2_C9      .SRES        2           ; ミスフィード２　ＯＦＦ工程
_SV_MISSK4_C9       .SRES        2           ; ミスフィード２　ＯＦＦ角度
_SV_MISSTA3_C9      .SRES        2           ; ミスフィード３　ＯＮ工程
_SV_MISSK5_C9       .SRES        2           ; ミスフィード３　ＯＮ角度
_SV_MISSTP3_C9      .SRES        2           ; ミスフィード３　ＯＦＦ工程
_SV_MISSK6_C9       .SRES        2           ; ミスフィード３　ＯＦＦ角度
_SV_MISSTA4_C9      .SRES        2           ; ミスフィード４　ＯＮ工程
_SV_MISSK7_C9       .SRES        2           ; ミスフィード４　ＯＮ角度
_SV_MISSTP4_C9      .SRES        2           ; ミスフィード４　ＯＦＦ工程
_SV_MISSK8_C9       .SRES        2           ; ミスフィード４　ＯＦＦ角度
_SV_MISSTA5_C10     .SRES        2           ; ミスフィード５　ＯＮ工程
_SV_MISSK1_C10      .SRES        2           ; ミスフィード５　ＯＮ角度
_SV_MISSTP5_C10     .SRES        2           ; ミスフィード５　ＯＦＦ工程
_SV_MISSK2_C10      .SRES        2           ; ミスフィード５　ＯＦＦ角度
_SV_MISSTA6_C10     .SRES        2           ; ミスフィード６　ＯＮ工程
_SV_MISSK3_C10      .SRES        2           ; ミスフィード６　ＯＮ角度
_SV_MISSTP6_C10     .SRES        2           ; ミスフィード６　ＯＦＦ工程
_SV_MISSK4_C10      .SRES        2           ; ミスフィード６　ＯＦＦ角度
_SV_MISSTA7_C10     .SRES        2           ; ミスフィード７　ＯＮ工程
_SV_MISSK5_C10      .SRES        2           ; ミスフィード７　ＯＮ角度
_SV_MISSTP7_C10     .SRES        2           ; ミスフィード７　ＯＦＦ工程
_SV_MISSK6_C10      .SRES        2           ; ミスフィード７　ＯＦＦ角度
_SV_MISSTA8_C10     .SRES        2           ; ミスフィード８　ＯＮ工程
_SV_MISSK7_C10      .SRES        2           ; ミスフィード８　ＯＮ角度
_SV_MISSTP8_C10     .SRES        2           ; ミスフィード８　ＯＦＦ工程
_SV_MISSK8_C10      .SRES        2           ; ミスフィード８　ＯＦＦ角度
_SV_RCLSTA11_C17    .SRES        2           ; ロータリカム１　ＯＮ工程
_SV_RCLS11_C17      .SRES        2           ; ロータリカム１　ＯＮ角度
_SV_RCLSTP12_C17    .SRES        2           ; ロータリカム１　ＯＦＦ工程
_SV_RCLS12_C17      .SRES        2           ; ロータリカム１　ＯＦＦ角度
_SV_RCLSTA21_C17    .SRES        2           ; ロータリカム２　ＯＮ工程
_SV_RCLS21_C17      .SRES        2           ; ロータリカム２　ＯＮ角度
_SV_RCLSTP22_C17    .SRES        2           ; ロータリカム２　ＯＦＦ工程
_SV_RCLS22_C17      .SRES        2           ; ロータリカム２　ＯＦＦ角度
_SV_RCLSTA31_C17    .SRES        2           ; ロータリカム３　ＯＮ工程
_SV_RCLS31_C17      .SRES        2           ; ロータリカム３　ＯＮ角度
_SV_RCLSTP32_C17    .SRES        2           ; ロータリカム３　ＯＦＦ工程
_SV_RCLS32_C17      .SRES        2           ; ロータリカム３　ＯＦＦ角度
_SV_RCLSTA41_C17    .SRES        2           ; ロータリカム４　ＯＮ工程
_SV_RCLS41_C17      .SRES        2           ; ロータリカム４　ＯＮ角度
_SV_RCLSTP42_C17    .SRES        2           ; ロータリカム４　ＯＦＦ工程
_SV_RCLS42_C17      .SRES        2           ; ロータリカム４　ＯＦＦ角度
_SV_RCLSTA51_C18    .SRES        2           ; ロータリカム５　ＯＮ工程
_SV_RCLS51_C18      .SRES        2           ; ロータリカム５　ＯＮ角度
_SV_RCLSTP52_C18    .SRES        2           ; ロータリカム５　ＯＦＦ工程
_SV_RCLS52_C18      .SRES        2           ; ロータリカム５　ＯＦＦ角度
_SV_RCLSTA61_C18    .SRES        2           ; ロータリカム６　ＯＮ工程
_SV_RCLS61_C18      .SRES        2           ; ロータリカム６　ＯＮ角度
_SV_RCLSTP62_C18    .SRES        2           ; ロータリカム６　ＯＦＦ工程
_SV_RCLS62_C18      .SRES        2           ; ロータリカム６　ＯＦＦ角度
_SV_RCLSTA71_C18    .SRES        2           ; ロータリカム７　ＯＮ工程
_SV_RCLS71_C18      .SRES        2           ; ロータリカム７　ＯＮ角度
_SV_RCLSTP72_C18    .SRES        2           ; ロータリカム７　ＯＦＦ工程
_SV_RCLS72_C18      .SRES        2           ; ロータリカム７　ＯＦＦ角度
_SV_RCLSTA81_C18    .SRES        2           ; ロータリカム８　ＯＮ工程
_SV_RCLS81_C18      .SRES        2           ; ロータリカム８　ＯＮ角度
_SV_RCLSTP82_C18    .SRES        2           ; ロータリカム８　ＯＦＦ工程
_SV_RCLS82_C18      .SRES        2           ; ロータリカム８　ＯＦＦ角度
_SV_RCLSTA11_C19    .SRES        2           ; ロータリカム９　ＯＮ工程
_SV_RCLS11_C19      .SRES        2           ; ロータリカム９　ＯＮ角度
_SV_RCLSTP12_C19    .SRES        2           ; ロータリカム９　ＯＦＦ工程
_SV_RCLS12_C19      .SRES        2           ; ロータリカム９　ＯＦＦ角度
_SV_RCLSTA21_C19    .SRES        2           ; ロータリカム１０　ＯＮ工程
_SV_RCLS21_C19      .SRES        2           ; ロータリカム１０　ＯＮ角度
_SV_RCLSTA22_C19    .SRES        2           ; ロータリカム１０　ＯＦＦ工程
_SV_RCLS22_C19      .SRES        2           ; ロータリカム１０　ＯＦＦ角度
_SV_RCLSTA31_C19    .SRES        2           ; ロータリカム１１　ＯＮ工程
_SV_RCLS31_C19      .SRES        2           ; ロータリカム１１　ＯＮ角度
_SV_RCLSTA32_C19    .SRES        2           ; ロータリカム１１　ＯＦＦ工程
_SV_RCLS32_C19      .SRES        2           ; ロータリカム１１　ＯＦＦ角度
_SV_RCLSTA41_C19    .SRES        2           ; ロータリカム１２　ＯＮ工程
_SV_RCLS41_C19      .SRES        2           ; ロータリカム１２　ＯＮ角度
_SV_RCLSTA42_C19    .SRES        2           ; ロータリカム１２　ＯＦＦ工程
_SV_RCLS42_C19      .SRES        2           ; ロータリカム１２　ＯＦＦ角度
_SV_RCLSTA51_C19    .SRES        2           ; ロータリカム１３　ＯＮ工程
_SV_RCLS51_C20      .SRES        2           ; ロータリカム１３　ＯＮ角度
_SV_RCLSTA52_C20    .SRES        2           ; ロータリカム１３　ＯＦＦ工程
_SV_RCLS52_C20      .SRES        2           ; ロータリカム１３　ＯＦＦ角度
_SV_RCLSTA61_C20    .SRES        2           ; ロータリカム１４　ＯＮ工程
_SV_RCLS61_C20      .SRES        2           ; ロータリカム１４　ＯＮ角度
_SV_RCLSTA62_C20    .SRES        2           ; ロータリカム１４　ＯＦＦ工程
_SV_RCLS62_C20      .SRES        2           ; ロータリカム１４　ＯＦＦ角度
_SV_RCLSTA71_C20    .SRES        2           ; ロータリカム１５　ＯＮ工程
_SV_RCLS71_C20      .SRES        2           ; ロータリカム１５　ＯＮ角度
_SV_RCLSTA72_C20    .SRES        2           ; ロータリカム１５　ＯＦＦ工程
_SV_RCLS72_C20      .SRES        2           ; ロータリカム１５　ＯＦＦ角度
_SV_RCLSTA81_C20    .SRES        2           ; ロータリカム１６　ＯＮ工程
_SV_RCLS81_C20      .SRES        2           ; ロータリカム１６　ＯＮ角度
_SV_RCLSTA82_C20    .SRES        2           ; ロータリカム１６　ＯＦＦ工程
_SV_RCLS82_C20      .SRES        2           ; ロータリカム１６　ＯＦＦ角度
_SV_RCLSTA11_C21    .SRES        2           ; ロータリカム１７　ＯＮ工程
_SV_RCLS11_C21      .SRES        2           ; ロータリカム１７　ON角度
_SV_RCLSTA12_C21    .SRES        2           ; ロータリカム１７　ＯＦＦ工程
_SV_RCLS12_C21      .SRES        2           ; ロータリカム１７　OFF角度
_SV_RCLSTA21_C21    .SRES        2           ; ロータリカム１８　ＯＮ工程
_SV_RCLS21_C21      .SRES        2           ; ロータリカム１８　ON角度
_SV_RCLSTA22_C21    .SRES        2           ; ロータリカム１８　ＯＦＦ工程
_SV_RCLS22_C21      .SRES        2           ; ロータリカム１８　OFF角度
_SV_RCLSTA31_C21    .SRES        2           ; ロータリカム１９　ＯＮ工程
_SV_RCLS31_C21      .SRES        2           ; ロータリカム１９　ON角度
_SV_RCLSTA32_C21    .SRES        2           ; ロータリカム１９　ＯＦＦ工程
_SV_RCLS32_C21      .SRES        2           ; ロータリカム１９　OFF角度
_SV_RCLSTA41_C21    .SRES        2           ; ロータリカム２０　ＯＮ工程
_SV_RCLS41_C21      .SRES        2           ; ロータリカム２０　ON角度
_SV_RCLSTA42_C21    .SRES        2           ; ロータリカム２０　ＯＦＦ工程
_SV_RCLS42_C21      .SRES        2           ; ロータリカム２０　OFF角度
_SV_PC_KNO          .SRES        2           ; PC側型番号　　　2016/09/17
                    .SRES        6           ; 空き
_SV_ATUOSU_D9       .SRES        4           ; スライド自動調節設定値（現在動作中）
_SV_ATUOS0_D9       .SRES        4           ; スライド自動調節　生産設定
_SV_ATUOS1_D9       .SRES        4           ; スライド自動調節　段取り１設定
_SV_ATUOS2_D9       .SRES        4           ; スライド自動調節　段取り２設定
_SV_OVERE1_A26      .SRES        2           ; 荷重計　オーバーロード１
_SV_ROALM1_A26      .SRES        2           ; 荷重計　ロアーリッミト１
_SV_OVERE2_A26      .SRES        2           ; 荷重計　オーバーロード２
_SV_ROALM2_A26      .SRES        2           ; 荷重計　ロアーリッミト２
_SV_OVERE3_A26      .SRES        2           ; 荷重計　オーバーロード３
_SV_ROALM3_A26      .SRES        2           ; 荷重計　ロアーリッミト３
_SV_DUMMY_A26       .SRES        2           ; 空き
_SV_CAMNA0_C1       .SRES        2           ; ロータリカム１汎用選択種別
_SV_CAMNA1_C1       .SRES        2           ; ロータリカム２汎用選択種別
_SV_CAMNA2_C1       .SRES        2           ; ロータリカム３汎用選択種別
_SV_CAMNA3_C1       .SRES        2           ; ロータリカム４汎用選択種別
_SV_CAMNA4_C1       .SRES        2           ; ロータリカム５汎用選択種別
_SV_CAMNA5_C1       .SRES        2           ; ロータリカム６汎用選択種別
_SV_CAMNA6_C1       .SRES        2           ; ロータリカム７汎用選択種別
_SV_CAMNA7_C1       .SRES        2           ; ロータリカム８汎用選択種別
_SV_CAMNA8_C1       .SRES        2           ; ロータリカム９汎用選択種別
_SV_CAMNA9_C1       .SRES        2           ; ロータリカム１０汎用選択種別
_SV_CAMNAA_C1       .SRES        2           ; ロータリカム１１汎用選択種別
_SV_CAMNAB_C1       .SRES        2           ; ロータリカム１２汎用選択種別
_SV_CAMNAC_C1       .SRES        2           ; ロータリカム１３汎用選択種別
_SV_CAMNAD_C1       .SRES        2           ; ロータリカム１４汎用選択種別
_SV_CAMNAE_C1       .SRES        2           ; ロータリカム１５汎用選択種別
_SV_CAMNAF_C1       .SRES        2           ; ロータリカム１６汎用選択種別
_SV_SPDSET_B1       .SRES        2           ; 生産速度設定値
_SV_SPDDAN_B1       .SRES        2           ; 段取速度設定値　(V01 復活2003/07/08)
_SV_BARANS_C27      .SRES        2           ; バランサ圧
                    .SRES        2           ; ダイクッション圧１
                    .SRES        2           ; ダイクッション圧２
_SV_DAITY1_C27      .SRES        2           ; ダイクッション調節１　→　圧力１
_SV_DAITY2_C27      .SRES        2           ; ダイクッション調節２　→　圧力１
_SV_COILL1_C30      .SRES        2           ; コイルライン設定１
_SV_COILL2_C30      .SRES        2           ; コイルライン設定２
_SV_COILL3_C30      .SRES        2           ; コイルライン設定３
_SV_COILL4_C30      .SRES        2           ; コイルライン設定４
_SV_COILL5_C30      .SRES        2           ; コイルライン設定５
_SV_COILL6_C30      .SRES        2           ; コイルライン設定６
_SV_COIMAI_C30      .SRES        2           ; コイルライン設定ﾏｲﾅｽ
_SV_UPDANO_C28      .SRES        2           ; 上型クランパ６選択　パターン入力データ
_SV_DAIKA1_C27      .SRES        4           ; ダイクッション圧１ →　調節１
_SV_DAIKA2_C27      .SRES        4           ; ダイクッション圧２ →　調節２
                    .SRES        4           ; 空き
_SV_TAIKIPOS1_SRV   .SRES        4           ; 待機位置
_SV_KAITEN1_SRV     .SRES        2           ; 回転方式
_SV_DANSUU1_SRV     .SRES        2           ; 段数
_SV_TAIKIKAKU1_SRV  .SRES        2           ; 待機角
_SV_TAIKSPD1_SRV    .SRES        2           ; 基準速度
_SV_DAIHAITO1_SRV   .SRES        4           ; ダイハイト
_SV_HOASEI1_SRV     .SRES        2           ; 補正データ
_SV_TAIKTIM1_SRV    .SRES        2           ; 待機時間
_SV_1DANDEG1_SRV    .SRES        2           ; 1段目目標角度
_SV_2DANDEG1_SRV    .SRES        2           ; 2段目目標角度
_SV_3DANDEG1_SRV    .SRES        2           ; 3段目目標角度
_SV_4DANDEG1_SRV    .SRES        2           ; 4段目目標角度
_SV_5DANDEG1_SRV    .SRES        2           ; 5段目目標角度
_SV_6DANDEG1_SRV    .SRES        2           ; 6段目目標角度
_SV_7DANDEG1_SRV    .SRES        2           ; 7段目目標角度
_SV_8DANDEG1_SRV    .SRES        2           ; 8段目目標角度
_SV_9DANDEG1_SRV    .SRES        2           ; 9段目目標角度
_SV_10DANDEG1_SRV   .SRES        2           ; 10段目目標角度
_SV_1DANPOS1_SRV    .SRES        4           ; 1段目目標位置
_SV_2DANPOS1_SRV    .SRES        4           ; 2段目目標位置
_SV_3DANPOS1_SRV    .SRES        4           ; 3段目目標位置
_SV_4DANPOS1_SRV    .SRES        4           ; 4段目目標位置
_SV_5DANPOS1_SRV    .SRES        4           ; 5段目目標位置
_SV_6DANPOS1_SRV    .SRES        4           ; 6段目目標位置
_SV_7DANPOS1_SRV    .SRES        4           ; 7段目目標位置
_SV_8DANPOS1_SRV    .SRES        4           ; 8段目目標位置
_SV_9DANPOS1_SRV    .SRES        4           ; 9段目目標位置
_SV_10DANPOS1_SRV   .SRES        4           ; 10段目目標位置
_SV_1DANSPD1_SRV    .SRES        2           ; 1段目移動速度
_SV_2DANSPD1_SRV    .SRES        2           ; 2段目移動速度
_SV_3DANSPD1_SRV    .SRES        2           ; 3段目移動速度
_SV_4DANSPD1_SRV    .SRES        2           ; 4段目移動速度
_SV_5DANSPD1_SRV    .SRES        2           ; 5段目移動速度
_SV_6DANSPD1_SRV    .SRES        2           ; 6段目移動速度
_SV_7DANSPD1_SRV    .SRES        2           ; 7段目移動速度
_SV_8DANSPD1_SRV    .SRES        2           ; 8段目移動速度
_SV_9DANSPD1_SRV    .SRES        2           ; 9段目移動速度
_SV_10DANSPD1_SRV   .SRES        2           ; 10段目移動速度
_SV_1DANTIM1_SRV    .SRES        2           ; 1段目停止時間
_SV_2DANTIM1_SRV    .SRES        2           ; 2段目停止時間
_SV_3DANTIM1_SRV    .SRES        2           ; 3段目停止時間
_SV_4DANTIM1_SRV    .SRES        2           ; 4段目停止時間
_SV_5DANTIM1_SRV    .SRES        2           ; 5段目停止時間
_SV_6DANTIM1_SRV    .SRES        2           ; 6段目停止時間
_SV_7DANTIM1_SRV    .SRES        2           ; 7段目停止時間
_SV_8DANTIM1_SRV    .SRES        2           ; 8段目停止時間
_SV_9DANTIM1_SRV    .SRES        2           ; 9段目停止時間
_SV_10DANTIM1_SRV   .SRES        2           ; 10段目停止時間
                    .SRES        2           ; 空き
                    .SRES        2           ; 空き
_SV_MOKKAN1_SRV     .SRES        2           ; 目標完了範囲
_SV_KAJYUU_PRS1     .SRES        2           ; 荷重補正
_SV_KAJYUU_OBJP1    .SRES        2           ; 荷重目標
                    .SRES        6           ; 空き
_SV_TAIKIPOS2_SRV   .SRES        4           ; 待機位置
_SV_KAITEN2_SRV     .SRES        2           ; 回転方式
_SV_DANSUU2_SRV     .SRES        2           ; 段数
_SV_TAIKIKAKU2_SRV  .SRES        2           ; 待機角
_SV_TAIKSPD2_SRV    .SRES        2           ; 基準速度
_SV_DAIHAITO2_SRV   .SRES        4           ; ダイハイト
_SV_HOASEI2_SRV     .SRES        2           ; 補正データ
_SV_TAIKTIM2_SRV    .SRES        2           ; 待機時間
_SV_1DANDEG2_SRV    .SRES        2           ; 1段目目標角度
_SV_2DANDEG2_SRV    .SRES        2           ; 2段目目標角度
_SV_3DANDEG2_SRV    .SRES        2           ; 3段目目標角度
_SV_4DANDEG2_SRV    .SRES        2           ; 4段目目標角度
_SV_5DANDEG2_SRV    .SRES        2           ; 5段目目標角度
_SV_6DANDEG2_SRV    .SRES        2           ; 6段目目標角度
_SV_7DANDEG2_SRV    .SRES        2           ; 7段目目標角度
_SV_8DANDEG2_SRV    .SRES        2           ; 8段目目標角度
_SV_9DANDEG2_SRV    .SRES        2           ; 9段目目標角度
_SV_10DANDEG2_SRV   .SRES        2           ; 10段目目標角度
_SV_1DANPOS2_SRV    .SRES        4           ; 1段目目標位置
_SV_2DANPOS2_SRV    .SRES        4           ; 2段目目標位置
_SV_3DANPOS2_SRV    .SRES        4           ; 3段目目標位置
_SV_4DANPOS2_SRV    .SRES        4           ; 4段目目標位置
_SV_5DANPOS2_SRV    .SRES        4           ; 5段目目標位置
_SV_6DANPOS2_SRV    .SRES        4           ; 6段目目標位置
_SV_7DANPOS2_SRV    .SRES        4           ; 7段目目標位置
_SV_8DANPOS2_SRV    .SRES        4           ; 8段目目標位置
_SV_9DANPOS2_SRV    .SRES        4           ; 9段目目標位置
_SV_10DANPOS2_SRV   .SRES        4           ; 10段目目標位置
_SV_1DANSPD2_SRV    .SRES        2           ; 1段目移動速度
_SV_2DANSPD2_SRV    .SRES        2           ; 2段目移動速度
_SV_3DANSPD2_SRV    .SRES        2           ; 3段目移動速度
_SV_4DANSPD2_SRV    .SRES        2           ; 4段目移動速度
_SV_5DANSPD2_SRV    .SRES        2           ; 5段目移動速度
_SV_6DANSPD2_SRV    .SRES        2           ; 6段目移動速度
_SV_7DANSPD2_SRV    .SRES        2           ; 7段目移動速度
_SV_8DANSPD2_SRV    .SRES        2           ; 8段目移動速度
_SV_9DANSPD2_SRV    .SRES        2           ; 9段目移動速度
_SV_10DANSPD2_SRV   .SRES        2           ; 10段目移動速度
_SV_1DANTIM2_SRV    .SRES        2           ; 1段目停止時間
_SV_2DANTIM2_SRV    .SRES        2           ; 2段目停止時間
_SV_3DANTIM2_SRV    .SRES        2           ; 3段目停止時間
_SV_4DANTIM2_SRV    .SRES        2           ; 4段目停止時間
_SV_5DANTIM2_SRV    .SRES        2           ; 5段目停止時間
_SV_6DANTIM2_SRV    .SRES        2           ; 6段目停止時間
_SV_7DANTIM2_SRV    .SRES        2           ; 7段目停止時間
_SV_8DANTIM2_SRV    .SRES        2           ; 8段目停止時間
_SV_9DANTIM2_SRV    .SRES        2           ; 9段目停止時間
_SV_10DANTIM2_SRV   .SRES        2           ; 10段目停止時間
                    .SRES        2           ; 空き
                    .SRES        2           ; 空き
_SV_MOKKAN2_SRV     .SRES        2           ; 目標完了範囲
_SV_KAJYUU_PRS2     .SRES        2           ; 荷重補正
_SV_KAJYUU_OBJP2    .SRES        2           ; 荷重目標
                    .SRES        6           ; 空き
_SV_TAIKIPOS3_SRV   .SRES        4           ; 待機位置
_SV_KAITEN3_SRV     .SRES        2           ; 回転方式
_SV_DANSUU3_SRV     .SRES        2           ; 段数
_SV_TAIKIKAKU3_SRV  .SRES        2           ; 待機角
_SV_TAIKSPD3_SRV    .SRES        2           ; 基準速度
_SV_DAIHAITO3_SRV   .SRES        4           ; ダイハイト
_SV_HOASEI3_SRV     .SRES        2           ; 補正データ
_SV_TAIKTIM3_SRV    .SRES        2           ; 待機時間
_SV_1DANDEG3_SRV    .SRES        2           ; 1段目目標角度
_SV_2DANDEG3_SRV    .SRES        2           ; 2段目目標角度
_SV_3DANDEG3_SRV    .SRES        2           ; 3段目目標角度
_SV_4DANDEG3_SRV    .SRES        2           ; 4段目目標角度
_SV_5DANDEG3_SRV    .SRES        2           ; 5段目目標角度
_SV_6DANDEG3_SRV    .SRES        2           ; 6段目目標角度
_SV_7DANDEG3_SRV    .SRES        2           ; 7段目目標角度
_SV_8DANDEG3_SRV    .SRES        2           ; 8段目目標角度
_SV_9DANDEG3_SRV    .SRES        2           ; 9段目目標角度
_SV_10DANDEG3_SRV   .SRES        2           ; 10段目目標角度
_SV_1DANPOS3_SRV    .SRES        4           ; 1段目目標位置
_SV_2DANPOS3_SRV    .SRES        4           ; 2段目目標位置
_SV_3DANPOS3_SRV    .SRES        4           ; 3段目目標位置
_SV_4DANPOS3_SRV    .SRES        4           ; 4段目目標位置
_SV_5DANPOS3_SRV    .SRES        4           ; 5段目目標位置
_SV_6DANPOS3_SRV    .SRES        4           ; 6段目目標位置
_SV_7DANPOS3_SRV    .SRES        4           ; 7段目目標位置
_SV_8DANPOS3_SRV    .SRES        4           ; 8段目目標位置
_SV_9DANPOS3_SRV    .SRES        4           ; 9段目目標位置
_SV_10DANPOS3_SRV   .SRES        4           ; 10段目目標位置
_SV_1DANSPD3_SRV    .SRES        2           ; 1段目移動速度
_SV_2DANSPD3_SRV    .SRES        2           ; 2段目移動速度
_SV_3DANSPD3_SRV    .SRES        2           ; 3段目移動速度
_SV_4DANSPD3_SRV    .SRES        2           ; 4段目移動速度
_SV_5DANSPD3_SRV    .SRES        2           ; 5段目移動速度
_SV_6DANSPD3_SRV    .SRES        2           ; 6段目移動速度
_SV_7DANSPD3_SRV    .SRES        2           ; 7段目移動速度
_SV_8DANSPD3_SRV    .SRES        2           ; 8段目移動速度
_SV_9DANSPD3_SRV    .SRES        2           ; 9段目移動速度
_SV_10DANSPD3_SRV   .SRES        2           ; 10段目移動速度
_SV_1DANTIM3_SRV    .SRES        2           ; 1段目停止時間
_SV_2DANTIM3_SRV    .SRES        2           ; 2段目停止時間
_SV_3DANTIM3_SRV    .SRES        2           ; 3段目停止時間
_SV_4DANTIM3_SRV    .SRES        2           ; 4段目停止時間
_SV_5DANTIM3_SRV    .SRES        2           ; 5段目停止時間
_SV_6DANTIM3_SRV    .SRES        2           ; 6段目停止時間
_SV_7DANTIM3_SRV    .SRES        2           ; 7段目停止時間
_SV_8DANTIM3_SRV    .SRES        2           ; 8段目停止時間
_SV_9DANTIM3_SRV    .SRES        2           ; 9段目停止時間
_SV_10DANTIM3_SRV   .SRES        2           ; 10段目停止時間
                    .SRES        2           ; 空き
                    .SRES        2           ; 空き
_SV_MOKKAN3_SRV     .SRES        2           ; 目標完了範囲
_SV_KAJYUU_PRS3     .SRES        2           ; 荷重補正
_SV_KAJYUU_OBJP3    .SRES        2           ; 荷重目標
_SV_OVERLIDE_COF    .SRES        2           ; ｵｰﾊﾞﾗｲﾄﾞ比率   V01w(060725)
_SV_DND_STOPDIG1    .SRES        2           ; 段取停止角度   V01w(060725)
_SV_KJSTR_STEP1     .SRES        2           ; 荷重測定の開始行程
_SV_KJSTR_DIG1      .SRES        2           ; 荷重測定の開始角度
_SV_KJEND_STEP1     .SRES        2           ; 荷重測定の終了行程
_SV_KJEND_DIG1      .SRES        2           ; 荷重測定の終了角度
_PV0_KAJYUHOS_BAK   .SRES        2           ; 荷重補正前回値
_PV0_KAGENHOS_BAK   .SRES        4           ; 下限補正前回値
_SV_DUMMY_C28       .SRES        44          ; 空き
_SV_RCSS11_C17      .SRES        2           ; ロータリカム１　ＯＮ進角　（角度）
_SV_RCSS21_C17      .SRES        2           ; ロータリカム１　ＯＮ進角　（時間）
_SV_RCSS31_C17      .SRES        2           ; ロータリカム１　ＯＦＦ進角　（角度）
_SV_RCSS41_C17      .SRES        2           ; ロータリカム１　ＯＦＦ進角　（時間）
_SV_RCSS12_C17      .SRES        2           ; ロータリカム２　ＯＮ進角　（角度）
_SV_RCSS22_C17      .SRES        2           ; ロータリカム２　ＯＮ進角　（時間）
_SV_RCSS32_C17      .SRES        2           ; ロータリカム２　ＯＦＦ進角　（角度）
_SV_RCSS42_C17      .SRES        2           ; ロータリカム２　ＯＦＦ進角　（時間）
_SV_RCSS13_C17      .SRES        2           ; ロータリカム３　ＯＮ進角　（角度）
_SV_RCSS23_C17      .SRES        2           ; ロータリカム３　ＯＮ進角　（時間）
_SV_RCSS33_C17      .SRES        2           ; ロータリカム３　ＯＦＦ進角　（角度）
_SV_RCSS43_C17      .SRES        2           ; ロータリカム３　ＯＦＦ進角　（時間）
_SV_RCSS14_C17      .SRES        2           ; ロータリカム４　ＯＮ進角　（角度）
_SV_RCSS24_C17      .SRES        2           ; ロータリカム４　ＯＮ進角　（時間）
_SV_RCSS34_C17      .SRES        2           ; ロータリカム４　ＯＦＦ進角　（角度）
_SV_RCSS44_C17      .SRES        2           ; ロータリカム４　ＯＦＦ進角　（時間）
_SV_RCSS11_C18      .SRES        2           ; ロータリカム５　ＯＮ進角　（角度）
_SV_RCSS21_C18      .SRES        2           ; ロータリカム５　ＯＮ進角　（時間）
_SV_RCSS31_C18      .SRES        2           ; ロータリカム５　ＯＦＦ進角　（角度）
_SV_RCSS41_C18      .SRES        2           ; ロータリカム５　ＯＦＦ進角　（時間）
_SV_RCSS12_C18      .SRES        2           ; ロータリカム６　ＯＮ進角　（角度）
_SV_RCSS22_C18      .SRES        2           ; ロータリカム６　ＯＮ進角　（時間）
_SV_RCSS32_C18      .SRES        2           ; ロータリカム６　ＯＦＦ進角　（角度）
_SV_RCSS42_C18      .SRES        2           ; ロータリカム６　ＯＦＦ進角　（時間）
_SV_RCSS13_C18      .SRES        2           ; ロータリカム７　ＯＮ進角　（角度）
_SV_RCSS23_C18      .SRES        2           ; ロータリカム７　ＯＮ進角　（時間）
_SV_RCSS33_C18      .SRES        2           ; ロータリカム７　ＯＦＦ進角　（角度）
_SV_RCSS43_C18      .SRES        2           ; ロータリカム７　ＯＦＦ進角　（時間）
_SV_RCSS14_C18      .SRES        2           ; ロータリカム８　ＯＮ進角　（角度）
_SV_RCSS24_C18      .SRES        2           ; ロータリカム８　ＯＮ進角　（時間）
_SV_RCSS34_C18      .SRES        2           ; ロータリカム８　ＯＦＦ進角　（角度）
_SV_RCSS44_C18      .SRES        2           ; ロータリカム８　ＯＦＦ進角　（時間）
_SV_RCSS11_C19      .SRES        2           ; ロータリカム９　ＯＮ進角　（角度）
_SV_RCSS21_C19      .SRES        2           ; ロータリカム９　ＯＮ進角　（時間）
_SV_RCSS31_C19      .SRES        2           ; ロータリカム９　ＯＦＦ進角　（角度）
_SV_RCSS41_C19      .SRES        2           ; ロータリカム９　ＯＦＦ進角　（時間）
_SV_RCSS12_C19      .SRES        2           ; ロータリカム１０　ＯＮ進角　（角度）
_SV_RCSS22_C19      .SRES        2           ; ロータリカム１０　ＯＮ進角　（時間）
_SV_RCSS32_C19      .SRES        2           ; ロータリカム１０　ＯＦＦ進角　（角度）
_SV_RCSS42_C19      .SRES        2           ; ロータリカム１０　ＯＦＦ進角　（時間）
_SV_RCSS13_C19      .SRES        2           ; ロータリカム１１　ＯＮ進角　（角度）
_SV_RCSS23_C19      .SRES        2           ; ロータリカム１１　ＯＮ進角　（時間）
_SV_RCSS33_C19      .SRES        2           ; ロータリカム１１　ＯＦＦ進角　（角度）
_SV_RCSS43_C19      .SRES        2           ; ロータリカム１１　ＯＦＦ進角　（時間）
_SV_RCSS14_C19      .SRES        2           ; ロータリカム１２　ＯＮ進角　（角度）
_SV_RCSS24_C19      .SRES        2           ; ロータリカム１２　ＯＮ進角　（時間）
_SV_RCSS34_C19      .SRES        2           ; ロータリカム１２　ＯＦＦ進角　（角度）
_SV_RCSS44_C19      .SRES        2           ; ロータリカム１２　ＯＦＦ進角　（時間）
_SV_RCSS11_C20      .SRES        2           ; ロータリカム１３　ＯＮ進角　（角度）
_SV_RCSS21_C20      .SRES        2           ; ロータリカム１３　ＯＮ進角　（時間）
_SV_RCSS31_C20      .SRES        2           ; ロータリカム１３　ＯＦＦ進角　（角度）
_SV_RCSS41_C20      .SRES        2           ; ロータリカム１３　ＯＦＦ進角　（時間）
_SV_RCSS12_C20      .SRES        2           ; ロータリカム１４　ＯＮ進角　（角度）
_SV_RCSS22_C20      .SRES        2           ; ロータリカム１４　ＯＮ進角　（時間）
_SV_RCSS32_C20      .SRES        2           ; ロータリカム１４　ＯＦＦ進角　（角度）
_SV_RCSS42_C20      .SRES        2           ; ロータリカム１４　ＯＦＦ進角　（時間）
_SV_RCSS13_C20      .SRES        2           ; ロータリカム１５　ＯＮ進角　（角度）
_SV_RCSS23_C20      .SRES        2           ; ロータリカム１５　ＯＮ進角　（時間）
_SV_RCSS33_C20      .SRES        2           ; ロータリカム１５　ＯＦＦ進角　（角度）
_SV_RCSS43_C20      .SRES        2           ; ロータリカム１５　ＯＦＦ進角　（時間）
_SV_RCSS14_C20      .SRES        2           ; ロータリカム１６　ＯＮ進角　（角度）
_SV_RCSS24_C20      .SRES        2           ; ロータリカム１６　ＯＮ進角　（時間）
_SV_RCSS34_C20      .SRES        2           ; ロータリカム１６　ＯＦＦ進角　（角度）
_SV_RCSS44_C20      .SRES        2           ; ロータリカム１６　ＯＦＦ進角　（時間）
                    .SRES        32          ; 空き
_SV_EJE1S1_C1       .SRES        2           ; エジェクタ１　ＯＮ進角
_SV_EJE1S2_C1       .SRES        2           ; エジェクタ１　ＯＮ進角
_SV_EJE1S3_C1       .SRES        2           ; エジェクタ１　ＯＦＦ進角
_SV_EJE1S4_C1       .SRES        2           ; エジェクタ１　ＯＦＦ進角
_SV_EJE2S1_C1       .SRES        2           ; エジェクタ２　ＯＮ進角
_SV_EJE2S2_C1       .SRES        2           ; エジェクタ２　ＯＮ進角
_SV_EJE2S3_C1       .SRES        2           ; エジェクタ２　ＯＦＦ進角
_SV_EJE2S4_C1       .SRES        2           ; エジェクタ２　ＯＦＦ進角
_SV_EJE3S1_C1       .SRES        2           ; エジェクタ３　ＯＮ進角
_SV_EJE3S2_C1       .SRES        2           ; エジェクタ３　ＯＮ進角
_SV_EJE3S3_C1       .SRES        2           ; エジェクタ３　ＯＦＦ進角
_SV_EJE3S4_C1       .SRES        2           ; エジェクタ３　ＯＦＦ進角
_SV_EJE4S1_C1       .SRES        2           ; エジェクタ４　ＯＮ進角
_SV_EJE4S2_C1       .SRES        2           ; エジェクタ４　ＯＮ進角
_SV_EJE4S3_C1       .SRES        2           ; エジェクタ４　ＯＦＦ進角
_SV_EJE4S4_C1       .SRES        2           ; エジェクタ４　ＯＦＦ進角
_SV_EJE5S1_C1       .SRES        2           ; エジェクタ５　ＯＮ進角
_SV_EJE5S2_C1       .SRES        2           ; エジェクタ５　ＯＮ進角
_SV_EJE5S3_C1       .SRES        2           ; エジェクタ５　ＯＦＦ進角
_SV_EJE5S4_C1       .SRES        2           ; エジェクタ５　ＯＦＦ進角
_SV_EJE6S1_C1       .SRES        2           ; エジェクタ６　ＯＮ進角
_SV_EJE6S2_C1       .SRES        2           ; エジェクタ６　ＯＮ進角
_SV_EJE6S3_C1       .SRES        2           ; エジェクタ６　ＯＦＦ進角
_SV_EJE6S4_C1       .SRES        2           ; エジェクタ６　ＯＦＦ進角
_SV_DUMMY_C29       .SRES        32          ; 空き
_SV_1DANPRS0_SRV    .SRES        2           ; 1段目目標荷重　（回転モード）
_SV_2DANPRS0_SRV    .SRES        2           ; 2段目目標荷重　（回転モード）
_SV_3DANPRS0_SRV    .SRES        2           ; 3段目目標荷重　（回転モード）
_SV_4DANPRS0_SRV    .SRES        2           ; 4段目目標荷重　（回転モード）
_SV_5DANPRS0_SRV    .SRES        2           ; 5段目目標荷重　（回転モード）
_SV_6DANPRS0_SRV    .SRES        2           ; 6段目目標荷重　（回転モード）
_SV_7DANPRS0_SRV    .SRES        2           ; 7段目目標荷重　（回転モード）
_SV_8DANPRS0_SRV    .SRES        2           ; 8段目目標荷重　（回転モード）
_SV_9DANPRS0_SRV    .SRES        2           ; 9段目目標荷重　（回転モード）
_SV_10DANPRS0_SRV   .SRES        2           ; 10段目目標荷重　（回転モード）
_SV_1DANPRS1_SRV    .SRES        2           ; 1段目目標荷重　（反転モード）
_SV_2DANPRS1_SRV    .SRES        2           ; 2段目目標荷重　（反転モード）
_SV_3DANPRS1_SRV    .SRES        2           ; 3段目目標荷重　（反転モード）
_SV_4DANPRS1_SRV    .SRES        2           ; 4段目目標荷重　（反転モード）
_SV_5DANPRS1_SRV    .SRES        2           ; 5段目目標荷重　（反転モード）
_SV_6DANPRS1_SRV    .SRES        2           ; 6段目目標荷重　（反転モード）
_SV_7DANPRS1_SRV    .SRES        2           ; 7段目目標荷重　（反転モード）
_SV_8DANPRS1_SRV    .SRES        2           ; 8段目目標荷重　（反転モード）
_SV_9DANPRS1_SRV    .SRES        2           ; 9段目目標荷重　（反転モード）
_SV_10DANPRS1_SRV   .SRES        2           ; 10段目目標荷重　（反転モード）
_SV_1DANPRS2_SRV    .SRES        2           ; 1段目目標荷重　（下往復モード）
_SV_2DANPRS2_SRV    .SRES        2           ; 2段目目標荷重　（下往復モード）
_SV_3DANPRS2_SRV    .SRES        2           ; 3段目目標荷重　（下往復モード）
_SV_4DANPRS2_SRV    .SRES        2           ; 4段目目標荷重　（下往復モード）
_SV_5DANPRS2_SRV    .SRES        2           ; 5段目目標荷重　（下往復モード）
_SV_6DANPRS2_SRV    .SRES        2           ; 6段目目標荷重　（下往復モード）
_SV_7DANPRS2_SRV    .SRES        2           ; 7段目目標荷重　（下往復モード）
_SV_8DANPRS2_SRV    .SRES        2           ; 8段目目標荷重　（下往復モード）
_SV_9DANPRS2_SRV    .SRES        2           ; 9段目目標荷重　（下往復モード）
_SV_10DANPRS2_SRV   .SRES        2           ; 10段目目標荷重　（下往復モード）
_SV_1DANPRS3_SRV    .SRES        2           ; 1段目目標荷重　（上往復モード）
_SV_2DANPRS3_SRV    .SRES        2           ; 2段目目標荷重　（上往復モード）
_SV_3DANPRS3_SRV    .SRES        2           ; 3段目目標荷重　（上往復モード）
_SV_4DANPRS3_SRV    .SRES        2           ; 4段目目標荷重　（上往復モード）
_SV_5DANPRS3_SRV    .SRES        2           ; 5段目目標荷重　（上往復モード）
_SV_6DANPRS3_SRV    .SRES        2           ; 6段目目標荷重　（上往復モード）
_SV_7DANPRS3_SRV    .SRES        2           ; 7段目目標荷重　（上往復モード）
_SV_8DANPRS3_SRV    .SRES        2           ; 8段目目標荷重　（上往復モード）
_SV_9DANPRS3_SRV    .SRES        2           ; 9段目目標荷重　（上往復モード）
_SV_10DANPRS3_SRV   .SRES        2           ; 10段目目標荷重　（上往復モード）
_SV_MOTOBJ_INF0     .SRES        2           ; 目標位置／荷重切替BIT情報　（回転モード）
_SV_MOTOBJ_INF1     .SRES        2           ; 目標位置／荷重切替BIT情報　（反転モード）
_SV_MOTOBJ_INF2     .SRES        2           ; 目標位置／荷重切替BIT情報　（下往復モード）
_SV_MOTOBJ_INF3     .SRES        2           ; 目標位置／荷重切替BIT情報　（上往復モード）
_SV_TIMER4_A1       .SRES        2           ; 外部ﾀｲﾏ　　　　V05r（2010/08/11）
_SV_KASIN_KAJ       .SRES        2           ; 加振実行荷重　　　V05r（2010/08/30）
_SV_HAN_P           .SRES        2           ; 反転ﾓｰﾄﾞP
_SV_HAN_S           .SRES        2           ; 反転ﾓｰﾄﾞS
_SV_KAJOBJ0_HAB     .SRES        2           ; 荷重完了範囲
_SV_KAJOBJ1_HAB     .SRES        2           ; 荷重完了範囲
_SV_KAJOBJ2_HAB     .SRES        2           ; 荷重完了範囲
_SV_KAJOBJ3_HAB     .SRES        2           ; 荷重完了範囲
_SV_OVERE1_A27      .SRES        2           ; 荷重計　オーバーロード１ 　（最小値）
_SV_ROALM1_A27      .SRES        2           ; 荷重計　ロアーリッミト１  　（最小値）
_SV_OVERE2_A27      .SRES        2           ; 荷重計　オーバーロード２  　（最小値）
_SV_ROALM2_A27      .SRES        2           ; 荷重計　ロアーリッミト２  　（最小値）
_SV_OVERE3_A27      .SRES        2           ; 荷重計　オーバーロード３  　（最小値）
_SV_ROALM3_A27      .SRES        2           ; 荷重計　ロアーリッミト３  　（最小値）
_SV_OVERE1_A28      .SRES        2           ; 荷重計　オーバーロード１ 　（振幅）
_SV_ROALM1_A28      .SRES        2           ; 荷重計　ロアーリッミト１  　（振幅）
_SV_OVERE2_A28      .SRES        2           ; 荷重計　オーバーロード２  　（振幅）
_SV_ROALM2_A28      .SRES        2           ; 荷重計　ロアーリッミト２  　（振幅）
_SV_OVERE3_A28      .SRES        2           ; 荷重計　オーバーロード３  　（振幅）
_SV_ROALM3_A28      .SRES        2           ; 荷重計　ロアーリッミト３  　（振幅）
_SV_OVLD_SEL        .SRES        2           ; 荷重計　オーバーロード選択（0:最大値／1:最小値／2振幅）
_SV_LWLM_SEL        .SRES        2           ; 荷重計　ロアーリミット選択（0:最大値／1:最小値／2振幅）
_SV_INTLIM_SNO      .SRES        2           ; 干渉限界位置　行程
_SV_INTLIM_AGL      .SRES        2           ; 干渉限界位置　角度
_SV_INTLIM_POS      .SRES        4           ; 干渉限界位置　位置
_SV_WTTIM_MAX       .SRES        2           ; 待機時間上限　時間
_SV_MOTREP_STGS     .SRES        2           ; 繰り返し開始行程
_SV_MOTREP_STGE     .SRES        2           ; 繰り返し終了行程
_SV_MOTREP_SPD      .SRES        2           ; 繰り返し戻り速度
_SV_MOTREP_CNT      .SRES        2           ; 繰り返し回数
_SV_ROTCAM_ONR      .SRES        2           ; ﾛｰﾀﾘｶﾑ ON行程 ﾘﾋﾟｰﾄ戻り
_SV_ROTCAM_OFR      .SRES        2           ; ﾛｰﾀﾘｶﾑ OFF行程 ﾘﾋﾟｰﾄ戻り
_SV_EJECAM_ONR      .SRES        2           ; ｴｼﾞｪｸﾀ ON行程 ﾘﾋﾟｰﾄ戻り
_SV_EJECAM_OFR      .SRES        2           ; ｴｼﾞｪｸﾀ OFF行程 ﾘﾋﾟｰﾄ戻り
_SV_MISCAM_ONR      .SRES        2           ; ﾐｽﾌｨｰﾄﾞ  ON行程 ﾘﾋﾟｰﾄ戻り
_SV_MISCAM_OFR      .SRES        2           ; ﾐｽﾌｨｰﾄﾞ  OFF行程 ﾘﾋﾟｰﾄ戻り
_SV_MOT_FIX         .SRES        2           ; 一定速領域行程（BIT情報）
_SV_DUMMY_C30       .SRES        236         ; 空き
_KAT_NAME_CHR       .SRES        16          ; 型データ名称
_KAT_MEMO_CHR       .SRES        16          ; 型データメモ
_SV_DUMMY_C300      .SRES        16          ; 空き
_PV_TOTLC1_B3_KAT   .SRES        4           ; トータルカウンタ１実測値
_PV_LOTCT1_B4_KAT   .SRES        4           ; ロットカウンタ１実測値
_PV_TOTLC2_B31_KAT  .SRES        4           ; 未使用
_PV_LOTCT2_B41_KAT  .SRES        4           ; ロットカウンタ２実測値
_SV_DUMMY_C301      .SRES        172         ; 空き
_SV_KAT_MM_INCH     .SRES        2           ; 型ﾃﾞｰﾀ内単位（mm/inch）情報
_FRAM_KAT_END       .SRES        2           ; F-RAM領域の型データのエンドラベル
_FRAM_KAT_SUM       .SRES        16          ; 型データのチェックサム領域用
_SV_DUMMY_C31       .SRES        768         ; 調整用(次オフセット・アドレス：0x１０００)
_KAT_NEXT_FLG       .SRES        2           ; 次型データ有無ﾌﾗｸﾞ読み込み 1=有り
_KT_MLDNO0_NF1      .SRES        16          ; 次型金型名称
_SV_DUMMY_NF1       .SRES        14          ; 空き
_PV_MLDNO1_F1       .SRES        2           ; 現在の型番号
_PV_MLDNO2_F1       .SRES        16          ; 現在の型名称
_KAT_NOW_NO         .SRES        2           ; 空き
_PV_MLDNO3_F1       .SRES        16          ; 空き（型名称画面の仮の名称）
_SV_DUMMY_F1        .SRES        30          ; 空き
_SV_EJENAM01_C1     .SRES        8           ; エジェクタ１名称
_SV_EJENAM02_C1     .SRES        8           ; エジェクタ１名称
_SV_EJENAM03_C1     .SRES        8           ; エジェクタ１名称
_SV_EJENAM04_C1     .SRES        8           ; エジェクタ１名称
_SV_EJENAM05_C1     .SRES        8           ; エジェクタ１名称
_SV_EJENAM06_C1     .SRES        8           ; エジェクタ１名称
_SV_CAMNA01_C1      .SRES        8           ; ロータリカム１名称
_SV_CAMNA02_C1      .SRES        8           ; ロータリカム２名称
_SV_CAMNA03_C1      .SRES        8           ; ロータリカム３名称
_SV_CAMNA04_C1      .SRES        8           ; ロータリカム４名称
_SV_CAMNA05_C1      .SRES        8           ; ロータリカム５名称
_SV_CAMNA06_C1      .SRES        8           ; ロータリカム６名称
_SV_CAMNA07_C1      .SRES        8           ; ロータリカム７名称
_SV_CAMNA08_C1      .SRES        8           ; ロータリカム８名称
_SV_CAMNA09_C1      .SRES        8           ; ロータリカム９名称
_SV_CAMNA10_C1      .SRES        8           ; ロータリカム１０名称
_SV_CAMNA11_C1      .SRES        8           ; ロータリカム１１名称
_SV_CAMNA12_C1      .SRES        8           ; ロータリカム１２名称
_SV_CAMNA13_C1      .SRES        8           ; ロータリカム１３名称
_SV_CAMNA14_C1      .SRES        8           ; ロータリカム１４名称
_SV_CAMNA15_C1      .SRES        8           ; ロータリカム１５名称
_SV_CAMNA16_C1      .SRES        8           ; ロータリカム１６名称
_SV_CAMNA17_C1      .SRES        8           ; ロータリカム１７名称
_SV_CAMNA18_C1      .SRES        8           ; ロータリカム１８名称
_SV_CAMNA19_C1      .SRES        8           ; ロータリカム１９名称
_SV_CAMNA20_C1      .SRES        8           ; ロータリカム２０名称
_KAT_JIKI_TOP       .SRES        512         ; 次期金型用型データ領域
                    .SRES        206         ; 空き
_PV_TOTLC1_B3       .SRES        4           ; トータルカウンタ１実測値
_PV_LOTCT1_B4       .SRES        4           ; ロットカウンタ１実測値
_PV_TOTLC2_B31      .SRES        4           ; 未使用
_PV_LOTCT2_B41      .SRES        4           ; ロットカウンタ２実測値
_PV_LIFE_COUNT      .SRES        6           ; 機械総カウンタ
                    .SRES        2           ; 空き
_PV_LIFE_TIME_10    .SRES        4           ; 機械総時間（10msecカウンタ）
_PV_LIFE_TIME       .SRES        4           ; 機械総時間（1secカウンタ）
                    .SRES        4           ; 空き
                    .SRES        2           ; 空き
_SEQ_BAK_312        .SRES        2           ; キープリレーバックアップ３１２
_SEQ_BAK_313        .SRES        2           ; キープリレーバックアップ３１３
_SEQ_BAK_314        .SRES        2           ; キープリレーバックアップ３１４
_SEQ_BAK_315        .SRES        2           ; キープリレーバックアップ３１５
_SEQ_BAK_316        .SRES        2           ; キープリレーバックアップ３１６
_SEQ_BAK_317        .SRES        2           ; キープリレーバックアップ３１７
_SEQ_BAK_318        .SRES        2           ; キープリレーバックアップ３１８
_SEQ_BAK_319        .SRES        2           ; キープリレーバックアップ３１９
_SURA_CHG_LST       .SRES        2           ; リザーブ
                    .SRES        8           ; 空き
_MCN_MENT_CNT1      .SRES        4           ; メンテナンスカウンタ１
_MCN_MENT_CNT2      .SRES        4           ; メンテナンスカウンタ２
_MCN_MENT_CNT3      .SRES        4           ; メンテナンスカウンタ３
_MCN_MENT_CNT4      .SRES        4           ; メンテナンスカウンタ４
_MCN_MENT_CNT5      .SRES        4           ; メンテナンスカウンタ５
_MCN_MENT_CNT6      .SRES        4           ; メンテナンスカウンタ６
_MCN_MENT_CNT7      .SRES        4           ; メンテナンスカウンタ７
_MCN_MENT_CNT8      .SRES        4           ; メンテナンスカウンタ８
_MCN_MENT_TIM1      .SRES        4           ; メンテナンス時間１（1secカウンタ）
_MCN_MENT_TIM1_10   .SRES        4           ; メンテナンス時間１（10msecカウンタ）
_MCN_MENT_TIM2      .SRES        4           ; メンテナンス時間２（1secカウンタ）
_MCN_MENT_TIM2_10   .SRES        4           ; メンテナンス時間２（10msecカウンタ）
_MCN_MENT_TIM3      .SRES        4           ; メンテナンス時間３（1secカウンタ）
_MCN_MENT_TIM3_10   .SRES        4           ; メンテナンス時間３（10msecカウンタ）
                    .SRES        8           ; 空き
_PV_GAIN_BAK1L      .SRES        2           ; 最大歪み２０００左ゲイン
_PV_GAIN_BAK1R      .SRES        2           ; 最大歪み２０００右ゲイン
_PV_GAIN_BAK2L      .SRES        2           ; 最大歪み１５００左ゲイン
_PV_GAIN_BAK2R      .SRES        2           ; 最大歪み１５００右ゲイン
_PV_GAIN_BAK3L      .SRES        2           ; 最大歪み　８００左ゲイン
_PV_GAIN_BAK3R      .SRES        2           ; 最大歪み　８００右ゲイン
_PV_GAIN_BAK4L      .SRES        2           ; 最大歪み　４００左ゲイン
_PV_GAIN_BAK4R      .SRES        2           ; 最大歪み　４００右ゲイン
_PV_GAIN_BAK5L      .SRES        2           ; 最大歪み　２００左ゲイン
_PV_GAIN_BAK5R      .SRES        2           ; 最大歪み　２００右ゲイン
_PV_OF_BAKL         .SRES        2           ; オフセット値左
_PV_OF_BAKR         .SRES        2           ; オフセット値右
_PV_OF_AVE_BAKL     .SRES        2           ; オフセット補正左
_PV_OF_AVE_BAKR     .SRES        2           ; オフセット補正右
_PV_OF_AVE_BAKT     .SRES        2           ; オフセット補正合計
                    .SRES        2           ; 空き
_PV_GENITI_B2       .SRES        4           ; 現位置データ
_SV_GENITI_CHK      .SRES        4           ; 現位置データ(?)
_PV_INTER_TIM       .SRES        2           ; 制動性能試験インターバールタイマ実測
                    .SRES        22          ; 
_SUM_CHK            .SRES        4           ; 設定値サムチェックコード
_SUM_CHK_KAT        .SRES        2           ; 型ﾃﾞｰﾀ 名称＆メモ サムチェックコード
                    .SRES        60          ; 空き
_PV_SEQDT1_A91      .SRES        2           ; シーケンスチェック１
_PV_SEQDT2_A91      .SRES        2           ; シーケンスチェック２
_PV_SEQDT3_A91      .SRES        2           ; シーケンスチェック３
_PV_SEQDT4_A91      .SRES        2           ; シーケンスチェック４
_PV_CB1_MAXSPD      .SRES        2           ; 仕様最高速設定時のＡＤ値
_PV_CB2_MAXSPD      .SRES        2           ; 未使用
_SV_EUPL_SYS        .SRES        2           ; 未使用
_SV_CBRPM1_SYS      .SRES        2           ; 未使用
_SV_CBRPM2_SYS      .SRES        2           ; 未使用
_SV_CBRPM3_SYS      .SRES        2           ; 未使用
_SV_HOSTIM_A12      .SRES        2           ; 起動補償時間設定値
_SV_TAIKI1_A12      .SRES        2           ; 待機点１データ設定値
_SV_TAIKI2_A12      .SRES        2           ; 待機点２データ設定値
_SV_TAIKI3_A12      .SRES        2           ; 待機点３データ設定値
_SV_RNZRPM_A12      .SRES        2           ; 連続回転設定値
_SV_RNZTIM_A12      .SRES        2           ; 連続タイマ設定値
                    .SRES        2           ; クラッチ定数１  シーケンス２８．０～２８．１５
                    .SRES        2           ; クラッチ定数２  シーケンス２９．０～２９．１５
                    .SRES        2           ; クラッチ定数３  シーケンス３０．０～３０．１５
_KIDO_FLG_SV        .SRES        2           ; 輝度データ読込＆格納
_KIDO_CNT           .SRES        2           ; 輝度調整設定値
_SV_PSDIMD_A1       .SRES        2           ; ＰＳＤＩ選択番号
_SV_CAMNA_C1        .SRES        2           ; ロータリカム１７～２０用ダミー領域
_PV_SEARCH_C15      .SRES        2           ; 型番号検索ナンバー読込
_SV_RS4SEL_SYS      .SRES        2           ; ＲＳ４２２仕様の有無
_SV_RS4BPS_SYS      .SRES        2           ; ぼーれいと設定
_SV_RS4DTL_SYS      .SRES        2           ; データ長
_SV_RS4STP_SYS      .SRES        2           ; ストップビット
_SV_RS4PAR_SYS      .SRES        2           ; パリティ設定
_SV_RS4KNO_SYS      .SRES        2           ; 局番
_SV_OUTADR_SYS      .SRES        2           ; 拡張出力領域アドレス
_SV_OUTCNT_SYS      .SRES        2           ; 拡張出力領域カウンタ
_SV_UPDANO_MAX      .SRES        2           ; 上型クランパ６選択パターン入力MAX
                    .SRES        194         ; 空き
_KAT_NAME_01        .SRES        16          ; 型データ名称１
_KAT_MEMO_01        .SRES        16          ; 型データメモ１
_KAT_NAME_02        .SRES        16          ; 型データ名称２
_KAT_MEMO_02        .SRES        16          ; 型データメモ２
_KAT_NAME_03        .SRES        16          ; 型データ名称３
_KAT_MEMO_03        .SRES        16          ; 型データメモ３
_KAT_NAME_04        .SRES        16          ; 型データ名称４
_KAT_MEMO_04        .SRES        16          ; 型データメモ４
_KAT_NAME_05        .SRES        16          ; 型データ名称５
_KAT_MEMO_05        .SRES        16          ; 型データメモ５
_KAT_NAME_06        .SRES        16          ; 型データ名称６
_KAT_MEMO_06        .SRES        16          ; 型データメモ６
_KAT_NAME_07        .SRES        16          ; 型データ名称７
_KAT_MEMO_07        .SRES        16          ; 型データメモ７
_KAT_NAME_08        .SRES        16          ; 型データ名称８
_KAT_MEMO_08        .SRES        16          ; 型データメモ８
_KAT_NAME_09        .SRES        16          ; 型データ名称９
_KAT_MEMO_09        .SRES        16          ; 型データメモ９
_KAT_NAME_10        .SRES        16          ; 型データ名称1０
_KAT_MEMO_10        .SRES        16          ; 型データメモ1０
_KAT_NAME_11        .SRES        16          ; 型データ名称１１
_KAT_MEMO_11        .SRES        16          ; 型データメモ１１
_KAT_NAME_12        .SRES        16          ; 型データ名称１２
_KAT_MEMO_12        .SRES        16          ; 型データメモ１２
_KAT_NAME_13        .SRES        16          ; 型データ名称１３
_KAT_MEMO_13        .SRES        16          ; 型データメモ１３
_KAT_NAME_14        .SRES        16          ; 型データ名称１４
_KAT_MEMO_14        .SRES        16          ; 型データメモ１４
_KAT_NAME_15        .SRES        16          ; 型データ名称１５
_KAT_MEMO_15        .SRES        16          ; 型データメモ１５
_KAT_NAME_16        .SRES        16          ; 型データ名称１６
_KAT_MEMO_16        .SRES        16          ; 型データメモ１６
_KAT_NAME_17        .SRES        16          ; 型データ名称１７
_KAT_MEMO_17        .SRES        16          ; 型データメモ１７
_KAT_NAME_18        .SRES        16          ; 型データ名称１８
_KAT_MEMO_18        .SRES        16          ; 型データメモ１８
_KAT_NAME_19        .SRES        16          ; 型データ名称１９
_KAT_MEMO_19        .SRES        16          ; 型データメモ１９
_KAT_NAME_20        .SRES        16          ; 型データ名称２０
_KAT_MEMO_20        .SRES        16          ; 型データメモ２０
_KAT_NAME_21        .SRES        16          ; 型データ名称２１
_KAT_MEMO_21        .SRES        16          ; 型データメモ２１
_KAT_NAME_22        .SRES        16          ; 型データ名称２２
_KAT_MEMO_22        .SRES        16          ; 型データメモ２２
_KAT_NAME_23        .SRES        16          ; 型データ名称２３
_KAT_MEMO_23        .SRES        16          ; 型データメモ２３
_KAT_NAME_24        .SRES        16          ; 型データ名称２４
_KAT_MEMO_24        .SRES        16          ; 型データメモ２４
_KAT_NAME_25        .SRES        16          ; 型データ名称２５
_KAT_MEMO_25        .SRES        16          ; 型データメモ２５
_KAT_NAME_26        .SRES        16          ; 型データ名称２６
_KAT_MEMO_26        .SRES        16          ; 型データメモ２６
_KAT_NAME_27        .SRES        16          ; 型データ名称２７
_KAT_MEMO_27        .SRES        16          ; 型データメモ２７
_KAT_NAME_28        .SRES        16          ; 型データ名称２８
_KAT_MEMO_28        .SRES        16          ; 型データメモ２８
_KAT_NAME_29        .SRES        16          ; 型データ名称２９
_KAT_MEMO_29        .SRES        16          ; 型データメモ２９
_KAT_NAME_30        .SRES        16          ; 型データ名称３０
_KAT_MEMO_30        .SRES        16          ; 型データメモ３０
_KAT_NAME_31        .SRES        16          ; 型データ名称３１
_KAT_MEMO_31        .SRES        16          ; 型データメモ３１
_KAT_NAME_32        .SRES        16          ; 型データ名称３２
_KAT_MEMO_32        .SRES        16          ; 型データメモ３２
_KAT_NAME_33        .SRES        16          ; 型データ名称３３
_KAT_MEMO_33        .SRES        16          ; 型データメモ３３
_KAT_NAME_34        .SRES        16          ; 型データ名称３４
_KAT_MEMO_34        .SRES        16          ; 型データメモ３４
_KAT_NAME_35        .SRES        16          ; 型データ名称３５
_KAT_MEMO_35        .SRES        16          ; 型データメモ３５
_KAT_NAME_36        .SRES        16          ; 型データ名称３６
_KAT_MEMO_36        .SRES        16          ; 型データメモ３６
_KAT_NAME_37        .SRES        16          ; 型データ名称３７
_KAT_MEMO_37        .SRES        16          ; 型データメモ３７
_KAT_NAME_38        .SRES        16          ; 型データ名称３８
_KAT_MEMO_38        .SRES        16          ; 型データメモ３８
_KAT_NAME_39        .SRES        16          ; 型データ名称３９
_KAT_MEMO_39        .SRES        16          ; 型データメモ３９
_KAT_NAME_40        .SRES        16          ; 型データ名称４０
_KAT_MEMO_40        .SRES        16          ; 型データメモ４０
_KAT_NAME_41        .SRES        16          ; 型データ名称４１
_KAT_MEMO_41        .SRES        16          ; 型データメモ４１
_KAT_NAME_42        .SRES        16          ; 型データ名称４２
_KAT_MEMO_42        .SRES        16          ; 型データメモ４２
_KAT_NAME_43        .SRES        16          ; 型データ名称４３
_KAT_MEMO_43        .SRES        16          ; 型データメモ４３
_KAT_NAME_44        .SRES        16          ; 型データ名称４４
_KAT_MEMO_44        .SRES        16          ; 型データメモ４４
_KAT_NAME_45        .SRES        16          ; 型データ名称４５
_KAT_MEMO_45        .SRES        16          ; 型データメモ４５
_KAT_NAME_46        .SRES        16          ; 型データ名称４６
_KAT_MEMO_46        .SRES        16          ; 型データメモ４６
_KAT_NAME_47        .SRES        16          ; 型データ名称４７
_KAT_MEMO_47        .SRES        16          ; 型データメモ４７
_KAT_NAME_48        .SRES        16          ; 型データ名称４８
_KAT_MEMO_48        .SRES        16          ; 型データメモ４８
_KAT_NAME_49        .SRES        16          ; 型データ名称４９
_KAT_MEMO_49        .SRES        16          ; 型データメモ４９
_KAT_NAME_50        .SRES        16          ; 型データ名称５０
_KAT_MEMO_50        .SRES        16          ; 型データメモ５０
_KAT_NAME_51        .SRES        16          ; 型データ名称５１
_KAT_MEMO_51        .SRES        16          ; 型データメモ５１
_KAT_NAME_52        .SRES        16          ; 型データ名称５２
_KAT_MEMO_52        .SRES        16          ; 型データメモ５２
_KAT_NAME_53        .SRES        16          ; 型データ名称５３
_KAT_MEMO_53        .SRES        16          ; 型データメモ５３
_KAT_NAME_54        .SRES        16          ; 型データ名称５４
_KAT_MEMO_54        .SRES        16          ; 型データメモ５４
_KAT_NAME_55        .SRES        16          ; 型データ名称５５
_KAT_MEMO_55        .SRES        16          ; 型データメモ５５
_KAT_NAME_56        .SRES        16          ; 型データ名称５６
_KAT_MEMO_56        .SRES        16          ; 型データメモ５６
_KAT_NAME_57        .SRES        16          ; 型データ名称５７
_KAT_MEMO_57        .SRES        16          ; 型データメモ５７
_KAT_NAME_58        .SRES        16          ; 型データ名称５８
_KAT_MEMO_58        .SRES        16          ; 型データメモ５８
_KAT_NAME_59        .SRES        16          ; 型データ名称５９
_KAT_MEMO_59        .SRES        16          ; 型データメモ５９
_KAT_NAME_60        .SRES        16          ; 型データ名称６０
_KAT_MEMO_60        .SRES        16          ; 型データメモ６０
_KAT_NAME_61        .SRES        16          ; 型データ名称６１
_KAT_MEMO_61        .SRES        16          ; 型データメモ６１
_KAT_NAME_62        .SRES        16          ; 型データ名称６２
_KAT_MEMO_62        .SRES        16          ; 型データメモ６２
_KAT_NAME_63        .SRES        16          ; 型データ名称６３
_KAT_MEMO_63        .SRES        16          ; 型データメモ６３
_KAT_NAME_64        .SRES        16          ; 型データ名称６４
_KAT_MEMO_64        .SRES        16          ; 型データメモ６４
_KAT_NAME_65        .SRES        16          ; 型データ名称６５
_KAT_MEMO_65        .SRES        16          ; 型データメモ６５
_KAT_NAME_66        .SRES        16          ; 型データ名称６６
_KAT_MEMO_66        .SRES        16          ; 型データメモ６６
_KAT_NAME_67        .SRES        16          ; 型データ名称６７
_KAT_MEMO_67        .SRES        16          ; 型データメモ６７
_KAT_NAME_68        .SRES        16          ; 型データ名称６８
_KAT_MEMO_68        .SRES        16          ; 型データメモ６８
_KAT_NAME_69        .SRES        16          ; 型データ名称６９
_KAT_MEMO_69        .SRES        16          ; 型データメモ６９
_KAT_NAME_70        .SRES        16          ; 型データ名称７０
_KAT_MEMO_70        .SRES        16          ; 型データメモ７０
_KAT_NAME_71        .SRES        16          ; 型データ名称７１
_KAT_MEMO_71        .SRES        16          ; 型データメモ７１
_KAT_NAME_72        .SRES        16          ; 型データ名称７２
_KAT_MEMO_72        .SRES        16          ; 型データメモ７２
_KAT_NAME_73        .SRES        16          ; 型データ名称７３
_KAT_MEMO_73        .SRES        16          ; 型データメモ７３
_KAT_NAME_74        .SRES        16          ; 型データ名称７４
_KAT_MEMO_74        .SRES        16          ; 型データメモ７４
_KAT_NAME_75        .SRES        16          ; 型データ名称７５
_KAT_MEMO_75        .SRES        16          ; 型データメモ７５
_KAT_NAME_76        .SRES        16          ; 型データ名称７６
_KAT_MEMO_76        .SRES        16          ; 型データメモ７６
_KAT_NAME_77        .SRES        16          ; 型データ名称７７
_KAT_MEMO_77        .SRES        16          ; 型データメモ７７
_KAT_NAME_78        .SRES        16          ; 型データ名称７８
_KAT_MEMO_78        .SRES        16          ; 型データメモ７８
_KAT_NAME_79        .SRES        16          ; 型データ名称７９
_KAT_MEMO_79        .SRES        16          ; 型データメモ７９
_KAT_NAME_80        .SRES        16          ; 型データ名称８０
_KAT_MEMO_80        .SRES        16          ; 型データメモ８０
_KAT_NAME_81        .SRES        16          ; 型データ名称８１
_KAT_MEMO_81        .SRES        16          ; 型データメモ８１
_KAT_NAME_82        .SRES        16          ; 型データ名称８２
_KAT_MEMO_82        .SRES        16          ; 型データメモ８２
_KAT_NAME_83        .SRES        16          ; 型データ名称８３
_KAT_MEMO_83        .SRES        16          ; 型データメモ８３
_KAT_NAME_84        .SRES        16          ; 型データ名称８４
_KAT_MEMO_84        .SRES        16          ; 型データメモ８４
_KAT_NAME_85        .SRES        16          ; 型データ名称８５
_KAT_MEMO_85        .SRES        16          ; 型データメモ８５
_KAT_NAME_86        .SRES        16          ; 型データ名称８６
_KAT_MEMO_86        .SRES        16          ; 型データメモ８６
_KAT_NAME_87        .SRES        16          ; 型データ名称８７
_KAT_MEMO_87        .SRES        16          ; 型データメモ８７
_KAT_NAME_88        .SRES        16          ; 型データ名称８８
_KAT_MEMO_88        .SRES        16          ; 型データメモ８８
_KAT_NAME_89        .SRES        16          ; 型データ名称８９
_KAT_MEMO_89        .SRES        16          ; 型データメモ８９
_KAT_NAME_90        .SRES        16          ; 型データ名称９０
_KAT_MEMO_90        .SRES        16          ; 型データメモ９０
_KAT_NAME_91        .SRES        16          ; 型データ名称９１
_KAT_MEMO_91        .SRES        16          ; 型データメモ９１
_KAT_NAME_92        .SRES        16          ; 型データ名称９２
_KAT_MEMO_92        .SRES        16          ; 型データメモ９２
_KAT_NAME_93        .SRES        16          ; 型データ名称９３
_KAT_MEMO_93        .SRES        16          ; 型データメモ９３
_KAT_NAME_94        .SRES        16          ; 型データ名称９４
_KAT_MEMO_94        .SRES        16          ; 型データメモ９４
_KAT_NAME_95        .SRES        16          ; 型データ名称９５
_KAT_MEMO_95        .SRES        16          ; 型データメモ９５
_KAT_NAME_96        .SRES        16          ; 型データ名称９６
_KAT_MEMO_96        .SRES        16          ; 型データメモ９６
_KAT_NAME_97        .SRES        16          ; 型データ名称９７
_KAT_MEMO_97        .SRES        16          ; 型データメモ９７
_KAT_NAME_98        .SRES        16          ; 型データ名称９８
_KAT_MEMO_98        .SRES        16          ; 型データメモ９８
_KAT_NAME_99        .SRES        16          ; 型データ名称９９
_KAT_MEMO_99        .SRES        16          ; 型データメモ９９
_KAT_NAME_100       .SRES        16          ; 型データ名称１００
_KAT_MEMO_100       .SRES        16          ; 型データメモ１００
_KAT_NAME_END       .SRES        130         ; 空き(型データ　名称＆メモ終了ｱﾄﾞﾚｽ)
_PV_ENCOD_BCD       .SRES        2           ; エンコーダ角度
_PV_CYCLE_TIME      .SRES        2           ; サイクルタイム
_PV_NOW_POS         .SRES        4           ; 現在位置
_PV_MOKU_POS        .SRES        4           ; 目標現在位置
_PV_MOKUTAI_POS     .SRES        4           ; 目標位置
_PV_DAIHAITO_POS    .SRES        4           ; ダイハイト位置
_PV_DAIHAI_B5       .SRES        4           ; ダイハイト実測値
_PV_MOKUTAI_KAKU    .SRES        2           ; 目標角
_PV_TAIKI_TIME      .SRES        2           ; 待機タイマ実測値
_PV_1DANSTOP_TIME   .SRES        2           ; 停止タイマ実測値１工程
_PV_2DANSTOP_TIME   .SRES        2           ; 停止タイマ実測値2工程
_PV_3DANSTOP_TIME   .SRES        2           ; 停止タイマ実測値3工程
_PV_4DANSTOP_TIME   .SRES        2           ; 停止タイマ実測値4工程
_PV_5DANSTOP_TIME   .SRES        2           ; 停止タイマ実測値5工程
_PV_6DANSTOP_TIME   .SRES        2           ; 停止タイマ実測値6工程
_PV_7DANSTOP_TIME   .SRES        2           ; 停止タイマ実測値7工程
_PV_8DANSTOP_TIME   .SRES        2           ; 停止タイマ実測値8工程
_PV_9DANSTOP_TIME   .SRES        2           ; 停止タイマ実測値9工程
_PV_10DANSTOP_TIME  .SRES        2           ; 停止タイマ実測値10工程
_PV_STOP_TIME       .SRES        2           ; ストッピングタイム
_PV_SEQSCAN_TIME    .SRES        2           ; シーケンススキャン
_PV_RNAORG_PLS1     .SRES        4           ; ﾘﾆｱ基準位置ﾊﾟﾙｽ
_PV_AMPDAT_A23      .SRES        2           ; オフセット調整合計
_PV_LAMPDT_A23      .SRES        2           ; オフセット調整左
_PV_RAMPDT_A23      .SRES        2           ; オフセット調整右
_PV_KAJYU1_A24      .SRES        2           ; 荷重左
_PV_KAJYU2_A24      .SRES        2           ; 荷重合計
_PV_KAJYU3_A24      .SRES        2           ; 荷重右
_PV_BAKORG_PLS1     .SRES        4           ; 原点記憶調整：機械原点1ﾊﾞｯｸｱｯﾌﾟ原点ﾃﾞｰﾀ (COP2)
_PV_BAKORG_PLS2     .SRES        4           ; 原点記憶調整：機械原点2ﾊﾞｯｸｱｯﾌﾟ原点ﾃﾞｰﾀ (COP2)
_PV_RENIA_BUP1      .SRES        4           ; リニアスケールバックアップ１
_PV_RENIA_BUP2      .SRES        4           ; リニアスケールバックアップ２
_PV_RENIA_BUP3      .SRES        4           ; リニアスケールバックアップ３
_PV_RENIA_BUP4      .SRES        4           ; リニアスケールバックアップ４
_PV_ARA1_KAJ_T2     .SRES        2           ; 荷重実測平均
                    .SRES        166         ; 空き
_PV_CMP_ERR         .SRES        2           ; シーケンスコンパイル異常フラグ
_PV_SEQ_ERR         .SRES        2           ; シーケンスコンパイル異常領域フラグ
_PV_COMPILE         .SRES        2           ; 未使用
_PV_COM_ADR         .SRES        2           ; シーケンスコンパイル異常アドレス
_PV_IO_ERR          .SRES        2           ; リモートI/O異常フラグ
_PV_CPUA_ERR        .SRES        2           ; 未使用
_PV_WDTA_ERR        .SRES        2           ; 未使用
_PV_CPUB_ERR        .SRES        2           ; 未使用
_PV_WDTB_ERR        .SRES        2           ; 未使用
_PV_SCAN_TM         .SRES        2           ; シーケンススキャンタイム
_CB1_VERNO_PV       .SRES        6           ; 未使用
_CB1_MAXSPD_PV      .SRES        2           ; ＣＰＵ－Ａ　ＡＤ値
_CB1_DIGDAT_PV      .SRES        2           ; ＣＰＵ－Ａ　角度ﾃﾞｰﾀ
_CB1_SPMDAT_PV      .SRES        2           ; ＣＰＵ－Ａ　ＳＰＭﾃﾞｰﾀ
_CB1_STPTIM_PV      .SRES        2           ; ＣＰＵ－Ａ　ストッピングタイム
_CB1_SUBERI_PV      .SRES        2           ; ＣＰＵ－Ａ　スベリ量
_CB1_STTIME_PV      .SRES        2           ; ＣＰＵ－Ａ　スタートタイム（未使用）
_CB1_STPPOS_PV      .SRES        2           ; ＣＰＵ－Ａ　停止指令位置（未使用）
                    .SRES        126         ; 空き
                    .SRES        126         ; 空き
                    .SRES        2           ; オフセット調整合計
                    .SRES        2           ; オフセット調整左
                    .SRES        2           ; オフセット調整右
                    .SRES        2           ; 荷重左
                    .SRES        2           ; 荷重合計
                    .SRES        2           ; 荷重右
                    .SRES        4           ; ダイハイト実測値
_PV_CBAVER_A1       .SRES        6           ; ＣＰＵ－Ａ　バージョン
_PV_CBASEL_A1       .SRES        6           ; 未使用
_PV_GMNVER_A1       .SRES        6           ; 画面　バージョン
_PV_OPCVER_A1       .SRES        6           ; オプション　バージョン
_PV_CBBVER_A1       .SRES        6           ; ＣＰＵ－Ｂ　バージョン
_PV_SYSVER_A1       .SRES        2           ; シスパラ　バージョン
_PV_LOTCT1_B1       .SRES        4           ; ロットカウンタ１（増減対応実測値）
_PV_LOTCT2_B1       .SRES        4           ; ロットカウンタ２（増減対応実測値）
_PV_SPDSET_B1       .SRES        2           ; 未使用
_PV_SPDSET_B11      .SRES        2           ; 現在の速度設定値データ
_PV_BARANS_C27      .SRES        2           ; バランサ圧 実測値
                    .SRES        2           ; 空き
_PV_DAIKA1_C27      .SRES        4           ; ダイクッション圧１→調節１ 　実測値
_PV_DAIKA2_C27      .SRES        4           ; ダイクッション圧２→調節２ 　実測値
_PV_DAITY1_C27      .SRES        2           ; ダイクッション調節１→圧力１　実測値
_PV_DAITY2_C27      .SRES        2           ; ダイクッション調節２→圧力２　実測値
_PV_CAMNAM_C1       .SRES        10          ; カム名称入力画面用データ領域
_PV_CAMNAM_C2       .SRES        10          ; カム名称入力画面用データ領域
_SEQ_165_PV         .SRES        2           ; 上型クランパ６段表示用
                    .SRES        2           ; 空き
_PV_ET1VER_A1       .SRES        6           ; オプションET1バージョン
                    .SRES        12          ; 空き
                    .SRES        10          ; 空き
_LNG_MM             .SRES        4           ; 単位(距離mm)
_LNG_INCH           .SRES        4           ; 単位(距離inch)
_CAR_LNG_AREA       .SRES        4           ; 単位切替(距離)
_CAR_KAJ_AREA       .SRES        4           ; 単位切替(荷重)
_CAR_ATU_AREA       .SRES        4           ; 単位切替(重さ)
_SYO_LNG_CNT        .SRES        2           ; 小数点位置(距離)
_SYO_KAJ_CNT        .SRES        2           ; 小数点位置(荷重)
_SYO_ATU_CNT        .SRES        2           ; 小数点位置(重さ)
_SYOD_LNG_CNT       .SRES        2           ; 小数点位置(距離)
_SYOD_ATU_CNT       .SRES        2           ; 小数点位置(重さ)
_KAT_DATCHG_FLG     .SRES        2           ; 型データ変更フラグ　（V01u追加2005/12/08）
_SV_DEB_ADR0        .SRES        4           ; デバッグ画面相対ｱﾄﾞﾚｽ0
_SV_DEB_ADR1        .SRES        4           ; デバッグ画面相対ｱﾄﾞﾚｽ1
_SV_DEB_ADR2        .SRES        4           ; デバッグ画面相対ｱﾄﾞﾚｽ2
_SV_DEB_ADR3        .SRES        4           ; デバッグ画面相対ｱﾄﾞﾚｽ3
_SV_DEB_ADR4        .SRES        4           ; デバッグ画面相対ｱﾄﾞﾚｽ4
_SV_DEB_SEL0        .SRES        2           ; デバッグ画面領域選択0
_SV_DEB_SEL1        .SRES        2           ; デバッグ画面領域選択1
_SV_DEB_SEL2        .SRES        2           ; デバッグ画面領域選択2
_SV_DEB_SEL3        .SRES        2           ; デバッグ画面領域選択3
_SV_DEB_SEL4        .SRES        2           ; デバッグ画面領域選択4
                    .SRES        2           ; 空き
_PV_DYHITO_POS      .SRES        4           ; 下限位置　(V01 追加2003/07/08）
_PV_SLIDE_POS       .SRES        4           ; 生産下限位置　(V01 追加2003/07/08）
_SV_MONALM_S01      .SRES        2           ; 異常履歴No.S1　(V01 追加2003/07/08）
_SV_MONALM_S02      .SRES        2           ; 異常履歴No.S2　(V01 追加2003/07/08）
_SV_MONALM_S03      .SRES        2           ; 異常履歴No.S3　(V01 追加2003/07/08）
_SV_MONALM_S04      .SRES        2           ; 異常履歴No.S4　(V01 追加2003/07/08）
_PV_DEB_WORD_WK1    .SRES        2           ; デバッグ用（機械原点設定回数） 050207
_PV_DEB_WORD_WK2    .SRES        2           ; デバッグ用（ﾘﾆｱ位置ﾊﾞｯｸｱｯﾌﾟ回数） 050207
_PV_DEB_WORD_WK3    .SRES        2           ; デバッグ用（ｽﾗｲﾄﾞ自動調節登録回数） 050207
_PV_DEB_WORD_WK4    .SRES        2           ; デバッグ用
_PV_DEB_WORD_WK5    .SRES        2           ; デバッグ用
_PV_DEB_WORD_WK6    .SRES        2           ; デバッグ用
_PV_DEB_WORD_WK7    .SRES        2           ; デバッグ用
_PV_DEB_WORD_WK8    .SRES        2           ; デバッグ用
_PV_DEB_WORD_WK9    .SRES        2           ; デバッグ用
_PV_DEB_WORD_WK10   .SRES        2           ; デバッグ用
_PV_DEB_WORD_WK11   .SRES        2           ; デバッグ用(cpubのVUP時算出SUM上位）　061226
_PV_DEB_WORD_WK12   .SRES        2           ; デバッグ用(cpubのVUP時算出SUM下位）　061226
_PV_DEB_WORD_WK13   .SRES        2           ; デバッグ用
_PV_DEB_WORD_WK14   .SRES        2           ; デバッグ用(cpub最大ｽﾀｯｸﾎﾟｲﾝﾀﾌﾗｸﾞ）　061226
_PV_DEB_WORD_WK15   .SRES        2           ; デバッグ用(cpub最大ｽﾀｯｸﾎﾟｲﾝﾀ上位ｱﾄﾞﾚｽ)　061226
_PV_DEB_WORD_WK16   .SRES        2           ; デバッグ用(cpub最大ｽﾀｯｸﾎﾟｲﾝﾀ下位ｱﾄﾞﾚｽ)　061226
_SV_SMPSTR_KAJ      .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　ﾄﾘｶﾞ荷重
_SV_SMPSTR_AGL      .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　ﾄﾘｶﾞ角度
_SV_SMPSTR_FUK      .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　ﾄﾘｶﾞ負荷率
_SV_SMPSTR_SEH      .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　ﾄﾘｶﾞｼｰｹﾝｽ（上位ｱﾄﾞﾚｽ）
_SV_SMPSTR_SQL      .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　ﾄﾘｶﾞｼｰｹﾝｽ（下位ｱﾄﾞﾚｽ）
_SV_SMPMAX_CNT      .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　最大個数
_SV_SMPTRG_CNT      .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　ﾌﾟﾘﾄﾘｶﾞ個数
_SV_SMPCYC_TIM      .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　周期
_SV_SMP_CNT         .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　収集形式毎
_SV_TRD_CNT         .SRES        2           ; ﾄﾚﾝﾄﾞ　収集形式毎
_SV_ATCOL_CYC       .SRES        2           ; 自動収集条件　周期
_SV_ATCOL_STNO      .SRES        2           ; 自動収集条件　収集範囲　開始行程
_SV_ATCOL_STAG      .SRES        2           ; 自動収集条件　収集範囲　開始角度
_SV_ATCOL_SPNO      .SRES        2           ; 自動収集条件　収集範囲　終了行程
_SV_ATCOL_SPAG      .SRES        2           ; 自動収集条件　収集範囲　終了角度
_SV_SMPMAX_CNT2     .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　最大個数(SIT)
_SV_SMPCYC_TIM2     .SRES        2           ; ｻﾝﾌﾟﾘﾝｸﾞ　周期(SIT)
                    .SRES        2334        ; 予備
_SV_SPD1_CHK        .SRES        16          ; ﾓｰｼｮﾝ1段目速度100%チェック用
_SV_SUM_TEST        .SRES        4           ; ｻﾑ異常網掛け有効ｺｰﾄﾞ
                    .SRES        4           ; 予備
                    .SRES        4           ; 予備
                    .SRES        4           ; 予備
_SV_SUM_TEST_DAT    .SRES        128         ; ｻﾑ異常ﾃﾞｰﾀ
_KAT_NAME_101       .SRES        16          ; 型データ名称１０１
_KAT_MEMO_101       .SRES        16          ; 型データメモ１０１
_KAT_NAME_102       .SRES        16          ; 型データ名称１０２
_KAT_MEMO_102       .SRES        16          ; 型データメモ１０２
_KAT_NAME_103       .SRES        16          ; 型データ名称１０３
_KAT_MEMO_103       .SRES        16          ; 型データメモ１０３
_KAT_NAME_104       .SRES        16          ; 型データ名称１０４
_KAT_MEMO_104       .SRES        16          ; 型データメモ１０４
_KAT_NAME_105       .SRES        16          ; 型データ名称１０５
_KAT_MEMO_105       .SRES        16          ; 型データメモ１０５
_KAT_NAME_106       .SRES        16          ; 型データ名称１０６
_KAT_MEMO_106       .SRES        16          ; 型データメモ１０６
_KAT_NAME_107       .SRES        16          ; 型データ名称１０７
_KAT_MEMO_107       .SRES        16          ; 型データメモ１０７
_KAT_NAME_108       .SRES        16          ; 型データ名称１０８
_KAT_MEMO_108       .SRES        16          ; 型データメモ１０８
_KAT_NAME_109       .SRES        16          ; 型データ名称１０９
_KAT_MEMO_109       .SRES        16          ; 型データメモ１０９
_KAT_NAME_110       .SRES        16          ; 型データ名称１１０
_KAT_MEMO_110       .SRES        16          ; 型データメモ１１０
_KAT_NAME_111       .SRES        16          ; 型データ名称１１１
_KAT_MEMO_111       .SRES        16          ; 型データメモ１１１
_KAT_NAME_112       .SRES        16          ; 型データ名称１１２
_KAT_MEMO_112       .SRES        16          ; 型データメモ１１２
_KAT_NAME_113       .SRES        16          ; 型データ名称１１３
_KAT_MEMO_113       .SRES        16          ; 型データメモ１１３
_KAT_NAME_114       .SRES        16          ; 型データ名称１１４
_KAT_MEMO_114       .SRES        16          ; 型データメモ１１４
_KAT_NAME_115       .SRES        16          ; 型データ名称１１５
_KAT_MEMO_115       .SRES        16          ; 型データメモ１１５
_KAT_NAME_116       .SRES        16          ; 型データ名称１１６
_KAT_MEMO_116       .SRES        16          ; 型データメモ１１６
_KAT_NAME_117       .SRES        16          ; 型データ名称１１７
_KAT_MEMO_117       .SRES        16          ; 型データメモ１１７
_KAT_NAME_118       .SRES        16          ; 型データ名称１１８
_KAT_MEMO_118       .SRES        16          ; 型データメモ１１８
_KAT_NAME_119       .SRES        16          ; 型データ名称１１９
_KAT_MEMO_119       .SRES        16          ; 型データメモ１１９
_KAT_NAME_120       .SRES        16          ; 型データ名称１２０
_KAT_MEMO_120       .SRES        16          ; 型データメモ１２０
_KAT_NAME_121       .SRES        16          ; 型データ名称１２１
_KAT_MEMO_121       .SRES        16          ; 型データメモ１２１
_KAT_NAME_122       .SRES        16          ; 型データ名称１２２
_KAT_MEMO_122       .SRES        16          ; 型データメモ１２２
_KAT_NAME_123       .SRES        16          ; 型データ名称１２３
_KAT_MEMO_123       .SRES        16          ; 型データメモ１２３
_KAT_NAME_124       .SRES        16          ; 型データ名称１２４
_KAT_MEMO_124       .SRES        16          ; 型データメモ１２４
_KAT_NAME_125       .SRES        16          ; 型データ名称１２５
_KAT_MEMO_125       .SRES        16          ; 型データメモ１２５
_KAT_NAME_126       .SRES        16          ; 型データ名称１２６
_KAT_MEMO_126       .SRES        16          ; 型データメモ１２６
_KAT_NAME_127       .SRES        16          ; 型データ名称１２７
_KAT_MEMO_127       .SRES        16          ; 型データメモ１２７
_KAT_NAME_128       .SRES        16          ; 型データ名称１２８
_KAT_MEMO_128       .SRES        16          ; 型データメモ１２８
_KAT_NAME_129       .SRES        16          ; 型データ名称１２９
_KAT_MEMO_129       .SRES        16          ; 型データメモ１２９
_KAT_NAME_130       .SRES        16          ; 型データ名称１３０
_KAT_MEMO_130       .SRES        16          ; 型データメモ１３０
_KAT_NAME_131       .SRES        16          ; 型データ名称１３１
_KAT_MEMO_131       .SRES        16          ; 型データメモ１３１
_KAT_NAME_132       .SRES        16          ; 型データ名称１３２
_KAT_MEMO_132       .SRES        16          ; 型データメモ１３２
_KAT_NAME_133       .SRES        16          ; 型データ名称１３３
_KAT_MEMO_133       .SRES        16          ; 型データメモ１３３
_KAT_NAME_134       .SRES        16          ; 型データ名称１３４
_KAT_MEMO_134       .SRES        16          ; 型データメモ１３４
_KAT_NAME_135       .SRES        16          ; 型データ名称１３５
_KAT_MEMO_135       .SRES        16          ; 型データメモ１３５
_KAT_NAME_136       .SRES        16          ; 型データ名称１３６
_KAT_MEMO_136       .SRES        16          ; 型データメモ１３６
_KAT_NAME_137       .SRES        16          ; 型データ名称１３７
_KAT_MEMO_137       .SRES        16          ; 型データメモ１３７
_KAT_NAME_138       .SRES        16          ; 型データ名称１３８
_KAT_MEMO_138       .SRES        16          ; 型データメモ１３８
_KAT_NAME_139       .SRES        16          ; 型データ名称１３９
_KAT_MEMO_139       .SRES        16          ; 型データメモ１３９
_KAT_NAME_140       .SRES        16          ; 型データ名称１４０
_KAT_MEMO_140       .SRES        16          ; 型データメモ１４０
_KAT_NAME_141       .SRES        16          ; 型データ名称１４１
_KAT_MEMO_141       .SRES        16          ; 型データメモ１４１
_KAT_NAME_142       .SRES        16          ; 型データ名称１４２
_KAT_MEMO_142       .SRES        16          ; 型データメモ１４２
_KAT_NAME_143       .SRES        16          ; 型データ名称１４３
_KAT_MEMO_143       .SRES        16          ; 型データメモ１４３
_KAT_NAME_144       .SRES        16          ; 型データ名称１４４
_KAT_MEMO_144       .SRES        16          ; 型データメモ１４４
_KAT_NAME_145       .SRES        16          ; 型データ名称１４５
_KAT_MEMO_145       .SRES        16          ; 型データメモ１４５
_KAT_NAME_146       .SRES        16          ; 型データ名称１４６
_KAT_MEMO_146       .SRES        16          ; 型データメモ１４６
_KAT_NAME_147       .SRES        16          ; 型データ名称１４７
_KAT_MEMO_147       .SRES        16          ; 型データメモ１４７
_KAT_NAME_148       .SRES        16          ; 型データ名称１４８
_KAT_MEMO_148       .SRES        16          ; 型データメモ１４８
_KAT_NAME_149       .SRES        16          ; 型データ名称１４９
_KAT_MEMO_149       .SRES        16          ; 型データメモ１４９
_KAT_NAME_150       .SRES        16          ; 型データ名称１５０
_KAT_MEMO_150       .SRES        16          ; 型データメモ１５０
_KAT_NAME_151       .SRES        16          ; 型データ名称１５１
_KAT_MEMO_151       .SRES        16          ; 型データメモ１５１
_KAT_NAME_152       .SRES        16          ; 型データ名称１５２
_KAT_MEMO_152       .SRES        16          ; 型データメモ１５２
_KAT_NAME_153       .SRES        16          ; 型データ名称１５３
_KAT_MEMO_153       .SRES        16          ; 型データメモ１５３
_KAT_NAME_154       .SRES        16          ; 型データ名称１５４
_KAT_MEMO_154       .SRES        16          ; 型データメモ１５４
_KAT_NAME_155       .SRES        16          ; 型データ名称１５５
_KAT_MEMO_155       .SRES        16          ; 型データメモ１５５
_KAT_NAME_156       .SRES        16          ; 型データ名称１５６
_KAT_MEMO_156       .SRES        16          ; 型データメモ１５６
_KAT_NAME_157       .SRES        16          ; 型データ名称１５７
_KAT_MEMO_157       .SRES        16          ; 型データメモ１５７
_KAT_NAME_158       .SRES        16          ; 型データ名称１５８
_KAT_MEMO_158       .SRES        16          ; 型データメモ１５８
_KAT_NAME_159       .SRES        16          ; 型データ名称１５９
_KAT_MEMO_159       .SRES        16          ; 型データメモ１５９
_KAT_NAME_160       .SRES        16          ; 型データ名称１６０
_KAT_MEMO_160       .SRES        16          ; 型データメモ１６０
_KAT_NAME_161       .SRES        16          ; 型データ名称１６１
_KAT_MEMO_161       .SRES        16          ; 型データメモ１６１
_KAT_NAME_162       .SRES        16          ; 型データ名称１６２
_KAT_MEMO_162       .SRES        16          ; 型データメモ１６２
_KAT_NAME_163       .SRES        16          ; 型データ名称１６３
_KAT_MEMO_163       .SRES        16          ; 型データメモ１６３
_KAT_NAME_164       .SRES        16          ; 型データ名称１６４
_KAT_MEMO_164       .SRES        16          ; 型データメモ１６４
_KAT_NAME_165       .SRES        16          ; 型データ名称１６５
_KAT_MEMO_165       .SRES        16          ; 型データメモ１６５
_KAT_NAME_166       .SRES        16          ; 型データ名称１６６
_KAT_MEMO_166       .SRES        16          ; 型データメモ１６６
_KAT_NAME_167       .SRES        16          ; 型データ名称１６７
_KAT_MEMO_167       .SRES        16          ; 型データメモ１６７
_KAT_NAME_168       .SRES        16          ; 型データ名称１６８
_KAT_MEMO_168       .SRES        16          ; 型データメモ１６８
_KAT_NAME_169       .SRES        16          ; 型データ名称１６９
_KAT_MEMO_169       .SRES        16          ; 型データメモ１６９
_KAT_NAME_170       .SRES        16          ; 型データ名称１７０
_KAT_MEMO_170       .SRES        16          ; 型データメモ１７０
_KAT_NAME_171       .SRES        16          ; 型データ名称１７１
_KAT_MEMO_171       .SRES        16          ; 型データメモ１７１
_KAT_NAME_172       .SRES        16          ; 型データ名称１７２
_KAT_MEMO_172       .SRES        16          ; 型データメモ１７２
_KAT_NAME_173       .SRES        16          ; 型データ名称１７３
_KAT_MEMO_173       .SRES        16          ; 型データメモ１７３
_KAT_NAME_174       .SRES        16          ; 型データ名称１７４
_KAT_MEMO_174       .SRES        16          ; 型データメモ１７４
_KAT_NAME_175       .SRES        16          ; 型データ名称１７５
_KAT_MEMO_175       .SRES        16          ; 型データメモ１７５
_KAT_NAME_176       .SRES        16          ; 型データ名称１７６
_KAT_MEMO_176       .SRES        16          ; 型データメモ１７６
_KAT_NAME_177       .SRES        16          ; 型データ名称１７７
_KAT_MEMO_177       .SRES        16          ; 型データメモ１７７
_KAT_NAME_178       .SRES        16          ; 型データ名称１７８
_KAT_MEMO_178       .SRES        16          ; 型データメモ１７８
_KAT_NAME_179       .SRES        16          ; 型データ名称１７９
_KAT_MEMO_179       .SRES        16          ; 型データメモ１７９
_KAT_NAME_180       .SRES        16          ; 型データ名称１８０
_KAT_MEMO_180       .SRES        16          ; 型データメモ１８０
_KAT_NAME_181       .SRES        16          ; 型データ名称１８１
_KAT_MEMO_181       .SRES        16          ; 型データメモ１８１
_KAT_NAME_182       .SRES        16          ; 型データ名称１８２
_KAT_MEMO_182       .SRES        16          ; 型データメモ１８２
_KAT_NAME_183       .SRES        16          ; 型データ名称１８３
_KAT_MEMO_183       .SRES        16          ; 型データメモ１８３
_KAT_NAME_184       .SRES        16          ; 型データ名称１８４
_KAT_MEMO_184       .SRES        16          ; 型データメモ１８４
_KAT_NAME_185       .SRES        16          ; 型データ名称１８５
_KAT_MEMO_185       .SRES        16          ; 型データメモ１８５
_KAT_NAME_186       .SRES        16          ; 型データ名称１８６
_KAT_MEMO_186       .SRES        16          ; 型データメモ１８６
_KAT_NAME_187       .SRES        16          ; 型データ名称１８７
_KAT_MEMO_187       .SRES        16          ; 型データメモ１８７
_KAT_NAME_188       .SRES        16          ; 型データ名称１８８
_KAT_MEMO_188       .SRES        16          ; 型データメモ１８８
_KAT_NAME_189       .SRES        16          ; 型データ名称１８９
_KAT_MEMO_189       .SRES        16          ; 型データメモ１８９
_KAT_NAME_190       .SRES        16          ; 型データ名称１９０
_KAT_MEMO_190       .SRES        16          ; 型データメモ１９０
_KAT_NAME_191       .SRES        16          ; 型データ名称１９１
_KAT_MEMO_191       .SRES        16          ; 型データメモ１９１
_KAT_NAME_192       .SRES        16          ; 型データ名称１９２
_KAT_MEMO_192       .SRES        16          ; 型データメモ１９２
_KAT_NAME_193       .SRES        16          ; 型データ名称１９３
_KAT_MEMO_193       .SRES        16          ; 型データメモ１９３
_KAT_NAME_194       .SRES        16          ; 型データ名称１９４
_KAT_MEMO_194       .SRES        16          ; 型データメモ１９４
_KAT_NAME_195       .SRES        16          ; 型データ名称１９５
_KAT_MEMO_195       .SRES        16          ; 型データメモ１９５
_KAT_NAME_196       .SRES        16          ; 型データ名称１９６
_KAT_MEMO_196       .SRES        16          ; 型データメモ１９６
_KAT_NAME_197       .SRES        16          ; 型データ名称１９７
_KAT_MEMO_197       .SRES        16          ; 型データメモ１９７
_KAT_NAME_198       .SRES        16          ; 型データ名称１９８
_KAT_MEMO_198       .SRES        16          ; 型データメモ１９８
_KAT_NAME_199       .SRES        16          ; 型データ名称１９９
_KAT_MEMO_199       .SRES        16          ; 型データメモ１９９
_KAT_NAME_200       .SRES        16          ; 型データ名称２００
_KAT_MEMO_200       .SRES        16          ; 型データメモ２００
_KAT_NAME_201       .SRES        16          ; 型データ名称２０１
_KAT_MEMO_201       .SRES        16          ; 型データメモ２０１
_KAT_NAME_202       .SRES        16          ; 型データ名称２０２
_KAT_MEMO_202       .SRES        16          ; 型データメモ２０２
_KAT_NAME_203       .SRES        16          ; 型データ名称２０３
_KAT_MEMO_203       .SRES        16          ; 型データメモ２０３
_KAT_NAME_204       .SRES        16          ; 型データ名称２０４
_KAT_MEMO_204       .SRES        16          ; 型データメモ２０４
_KAT_NAME_205       .SRES        16          ; 型データ名称２０５
_KAT_MEMO_205       .SRES        16          ; 型データメモ２０５
_KAT_NAME_206       .SRES        16          ; 型データ名称２０６
_KAT_MEMO_206       .SRES        16          ; 型データメモ２０６
_KAT_NAME_207       .SRES        16          ; 型データ名称２０７
_KAT_MEMO_207       .SRES        16          ; 型データメモ２０７
_KAT_NAME_208       .SRES        16          ; 型データ名称２０８
_KAT_MEMO_208       .SRES        16          ; 型データメモ２０８
_KAT_NAME_209       .SRES        16          ; 型データ名称２０９
_KAT_MEMO_209       .SRES        16          ; 型データメモ２０９
_KAT_NAME_210       .SRES        16          ; 型データ名称２１０
_KAT_MEMO_210       .SRES        16          ; 型データメモ２１０
_KAT_NAME_211       .SRES        16          ; 型データ名称２１１
_KAT_MEMO_211       .SRES        16          ; 型データメモ２１１
_KAT_NAME_212       .SRES        16          ; 型データ名称２１２
_KAT_MEMO_212       .SRES        16          ; 型データメモ２１２
_KAT_NAME_213       .SRES        16          ; 型データ名称２１３
_KAT_MEMO_213       .SRES        16          ; 型データメモ２１３
_KAT_NAME_214       .SRES        16          ; 型データ名称２１４
_KAT_MEMO_214       .SRES        16          ; 型データメモ２１４
_KAT_NAME_215       .SRES        16          ; 型データ名称２１５
_KAT_MEMO_215       .SRES        16          ; 型データメモ２１５
_KAT_NAME_216       .SRES        16          ; 型データ名称２１６
_KAT_MEMO_216       .SRES        16          ; 型データメモ２１６
_KAT_NAME_217       .SRES        16          ; 型データ名称２１７
_KAT_MEMO_217       .SRES        16          ; 型データメモ２１７
_KAT_NAME_218       .SRES        16          ; 型データ名称２１８
_KAT_MEMO_218       .SRES        16          ; 型データメモ２１８
_KAT_NAME_219       .SRES        16          ; 型データ名称２１９
_KAT_MEMO_219       .SRES        16          ; 型データメモ２１９
_KAT_NAME_220       .SRES        16          ; 型データ名称２２０
_KAT_MEMO_220       .SRES        16          ; 型データメモ２２０
_KAT_NAME_END2      .SRES        256         ; 予備
_KJ_CHK_CNT0        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ0
_KJ_CHK_CNT1        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ1
_KJ_CHK_CNT2        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ2
_KJ_CHK_CNT3        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ3
_KJ_CHK_CNT4        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ4
_KJ_CHK_CNT5        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ5
_KJ_CHK_CNT6        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ6
_KJ_CHK_CNT7        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ7
_KJ_CHK_CNT8        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ8
_KJ_CHK_CNT9        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ9
_KJ_CHK_CNT10       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ10
_KJ_CHK_CNT11       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ11
_KJ_CHK_CNT12       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ12
_KJ_CHK_CNT13       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ13
_KJ_CHK_CNT14       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ14
_KJ_CHK_CNT15       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ｶｳﾝﾀ15
_KJ_CHK_DAT0        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ0
_KJ_CHK_DAT1        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ1
_KJ_CHK_DAT2        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ2
_KJ_CHK_DAT3        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ3
_KJ_CHK_DAT4        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ4
_KJ_CHK_DAT5        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ5
_KJ_CHK_DAT6        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ6
_KJ_CHK_DAT7        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ7
_KJ_CHK_DAT8        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ8
_KJ_CHK_DAT9        .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ9
_KJ_CHK_DAT10       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ10
_KJ_CHK_DAT11       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ11
_KJ_CHK_DAT12       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ12
_KJ_CHK_DAT13       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ13
_KJ_CHK_DAT14       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ14
_KJ_CHK_DAT15       .SRES        2           ; 荷重計ﾊﾞｯｸｱｱﾌﾟﾃﾞｰﾀ化け調査ﾃﾞｰﾀ15
_PV_GAIN_BAK1L_X    .SRES        2           ; 最大歪み２０００左ゲイン
_PV_GAIN_BAK1R_X    .SRES        2           ; 最大歪み２０００右ゲイン
_PV_GAIN_BAK2L_X    .SRES        2           ; 最大歪み１５００左ゲイン
_PV_GAIN_BAK2R_X    .SRES        2           ; 最大歪み１５００右ゲイン
_PV_GAIN_BAK3L_X    .SRES        2           ; 最大歪み　８００左ゲイン
_PV_GAIN_BAK3R_X    .SRES        2           ; 最大歪み　８００右ゲイン
_PV_GAIN_BAK4L_X    .SRES        2           ; 最大歪み　４００左ゲイン
_PV_GAIN_BAK4R_X    .SRES        2           ; 最大歪み　４００右ゲイン
_PV_GAIN_BAK5L_X    .SRES        2           ; 最大歪み　２００左ゲイン
_PV_GAIN_BAK5R_X    .SRES        2           ; 最大歪み　２００右ゲイン
_PV_OF_BAKL_X       .SRES        2           ; オフセット値左
_PV_OF_BAKR_X       .SRES        2           ; オフセット値右
_PV_OF_AVE_BAKL_X   .SRES        2           ; オフセット補正左
_PV_OF_AVE_BAKR_X   .SRES        2           ; オフセット補正右
_PV_OF_AVE_BAKT_X   .SRES        2           ; オフセット補正合計
                    .SRES        1954        ; 
_SV_BACK_AREA       .SRES        5120        ; FRAMサム対象エリア
_SV_BACK_SUM        .SRES        4           ; 

; END
