/***********************************************************************/
/*                                                                     */
/*  FILE        :initsct.c                                             */
/*  DATE        :Sun, Jul 16, 2006                                     */
/*  DESCRIPTION :Initialize of RAM Data                                */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  
#pragma	section	hwsetup1


/*SH-3DSP*/
extern int *_D_ROM, *_B_BGN, *_B_END, *_D_BGN, *_D_END;
extern void _INITSCT( )
{
char *p, *q;
	/*zero clear*/
	for( p = (char *)_B_BGN; p < (char *)_B_END; p++)
		*p = 0;                      
	/*ROM to RAM*/
	for(p = (char *)_D_BGN, q = (char *)_D_ROM; p < (char *)_D_END; p++, q++)
		*p = *q;
}

// Remove the following comment when you use __call_init and __call_end
// See resetprg.src and dbsct.src
//extern void (**_PRE_BGN)();
//extern void (**_PRE_END)();
//extern void (**_POST_BGN)();
//extern void (**_POST_END)();

//extern void _call_init();
//extern void _call_end();

//void _call_init()
//{
//    void (**ppf)();
//    for( ppf = _PRE_BGN; ppf < _PRE_END; ppf++)
//        (*ppf)();
//}

//void _call_end()
//{
//    void (**ppf)();
//    for( ppf = _POST_BGN; ppf < _POST_END; ppf++)
//        (*ppf)();
//}
