/***********************************************************************/
/*                                                                     */
/*  FILE        :cpua.c                                                */
/*  DATE        :Mon, Jun 24, 2002                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7750                                                */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  


#ifdef __cplusplus
//#include <ios>					// Remove the comment when you use ios                  
//int ios_base::Init::init_cnt;		// Remove the comment when you use ios
#endif
#ifdef __cplusplus
extern "C" {
#endif
void main(void);
#ifdef __cplusplus
}
#endif


#include	"cm_equ1.h" 
#include	"ssc_wram.h"


extern	void INT_EI(void);		// hwsetup.src

extern	void SR_INIT_SET(void);		// p4a_com1.src(共通演算)
extern	void SR_MAIN_SET(void);		// p4a_com1.src(共通演算)

//

extern	void ASM_DMK1_SOFT_INIT(void);//p4a_k.src
extern	void ASM_DMY1_SOFT_INIT(void);//p4a_y.src
//extern	void c_dmk1_soft_init(void);//p4c_k.c(割込解除前にする)
//extern	void c_dmy1_soft_init(void);//p4c_y.c(割込解除前にする)

//extern	void c_dmk1_data_main(void);	//ssc_k.c
//extern	void c_dmy1_data_main(void);	//ssc_y.c
//extern	void c_k1_ctrl_main(void);	//ssc_k.c
//extern	void c_y1_ctrl_main(void);	//ssc_y.c

extern	void ASM_VUP_MAIN();	//メインスキャン
extern	void ASM_Y1_CTRL_MAIN();	//メインスキャン
extern	void ASM_DMK1_DATA_INIT();

extern	void SEQ_INIT(void);		//ssa_seqm.src

extern	void IOGA_OUT_INIT(void);	//ssa_dio.src
extern	void IOGA_DI_LOAD(void);	//ssa_dio.src
//extern	void SEQ_CB_WKINRAM_SET(void);	//ssa_dio.src

extern	void POS_LSI_START(void);	//ssa_dio.src
extern	void POS_LSI_LATCH(void);	//ssa_dio.src

extern	void SEQ_RUN_MAIN(void);	//ｼｰｹﾝｽ処理
//extern	void SEQ_CB_DP_WR(void);	//クラッチで使用しているデータをDPRAMへ転送

extern	void RM_RDENB_ON(void);		//ssa_dio.src リモート RDENB ON
extern	void ROM_SYSPAR_CMP_CHK(void);	//ssa_erry.inc シスパラ比較

extern	void draw_smple(void);

//	2002-12-17
extern	U2b	CPUBA_HD_INDT1;
extern	void CPUBA_HAND_INPORT_LOAD(void);

//	2008-08-01
extern	REMOTE_INDT_READ(void);		//; リモート入力読み込み(元々有り)
extern	SQ_CARD_IN_REF1(void);		//2008-08-01




//	2013-12-11 [mc]
extern	void CPUD_START_CHK(void);
extern	U2b CPUD_START_OK;
extern	U2b SPL_ERR_INIT_WAIT_TIM;//5秒 2015-02-07




void data_init1(void)
{
	ASM_DMK1_DATA_INIT();		//ｼｽﾊﾟﾗ/設定/ﾃﾞｰﾀ転送:ﾏｽﾀのみの処理
	ASM_DMY1_DATA_INIT();		//


//	c_dmk1_data_init();		//ssc_k.c:位置決めのｲﾆｼｬﾙ処理(ﾏｽﾀ/OPTION同一):ｱﾄﾞﾚｽ設定
//	c_dmy1_data_init();		//ssc_y.c
}

#define		init_wt2_tim	50	//2ms*50=100ms

void data_init2(void)
{

	SEQ_INIT();				//ssa_seqm.src

	data_init2_timer = init_wt2_tim;	//

	while(data_init2_timer){
		WDT_Rifresh();			//

		REMOTE_INDT_READ();		//; リモート入力読み込み
		SQ_CARD_IN_REF1();		//2008-08-01

		IOGA_DI_LOAD();			//ssa_dio.src
		SEQ_CB_WKINRAM_SET();		//ssa_dio.src
		POS_LSI_START();		//ssa_dio.src
		POS_LSI_LATCH();		//ssa_dio.src
	}

	SPL_ERR_INIT_WAIT_TIM=5000;//5秒 2015-02-07

	RM_RDENB_ON();				//ssa_dio.src リモート RDENB ON
//	ROM_SYSPAR_CMP_CHK();		//ssa_erry.inc シスパラ比較



}


extern	ASM_K1_CTRL_MAIN(void);


extern	S2b	CMP_ERR_STSA_INF4;

void main(void)
{
//;	*******************************************
//;	***	割込み許可前1回処理		***
//;	*******************************************

	IOGA_OUT_INIT();		//ssa_dio.src

//"FIRST"
	ASM_DMK1_SOFT_INIT();		//cb_src\k_src\ssa_k.src
	ASM_DMY1_SOFT_INIT();		//cb_src\y_src\ssa_y.src


//	c_dmk1_soft_init();		//cb_src\k_src\ssc_k.c(割込解除前にする)
//	c_dmy1_soft_init();		//cb_src\y_src\ssc_y.c(割込解除前にする)

	SR_INIT_SET();			//cb_src\comon\ssa_com1.src

	INT_EI();

//	=============================================== //
//	===	タイムアウト付	2002-12-17 ﾊﾝﾄﾞｼｪｲｸ待ち		//
//	==============================================  //
	data_init2_timer =30000;//30.000*2=60秒
	while(data_init2_timer){
		WDT_Rifresh();		//2002-12-17

		CPUBA_HAND_INPORT_LOAD();//CPUBA_HD_INDT1;<=
		CPUD_START_CHK();
		if(CPUD_START_OK){//CPUD 移動
			if(CPUBA_HD_INDT1&cBIT15){//CPUB起動[dpram参照ok]
				data_init2_timer =0;
			}
		}

		//2013-12 mc CPUBA_HAND_INPORT_LOAD();//CPUBA_HD_INDT1;<=
		//2013-12 mc if(CPUBA_HD_INDT1&cBIT15){//"H" END
		//2013-12 mc 	data_init2_timer =0;
		//2013-12 mc }
	}





//;	*******************************************
//;	***	割込み許可後1回処理		***
//;	*******************************************
	data_init1();			//ｲﾆｼｬﾙﾃﾞｰﾀｾｯﾄ

//;	*******************************************
//;	***	SH2からの動作許可後処理		***
//;	*******************************************
	SR_MAIN_SET();			//cb_src\comon\ssa_com1.src

	data_init2();			//ｲﾆｼｬﾙﾃﾞｰﾀｾｯﾄ


//;	*******************************************
//;	***	MAINｽｷｬﾝ処理			***
//;	*******************************************
	while(1){
	
		WDT_Rifresh();		//

///////		IOGA_DI_LOAD();			//ssa_dio.src
///////		SEQ_CB_WKINRAM_SET();		//ssa_dio.src

//		c_dmk1_data_main();		//ssc_k.c
//		c_dmy1_data_main();		//ssc_y.c
		ASM_K1_CTRL_MAIN();
////		c_k1_ctrl_main();		//ssc_k.c
//		c_y1_ctrl_main();		//ssc_y.c

		ASM_Y1_CTRL_MAIN();		//メインスキャン

///////		SEQ_CB_DP_WR();			//クラッチで使用しているデータをDPRAMへ転送

		ASM_VUP_MAIN();
	}

}

void abort(void)
{
	
}