/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.c                                                */
/*  DATE        :Mon, Jun 24, 2002                                     */
/*  DESCRIPTION :Program of sbrk                                       */
/*  CPU TYPE    :SH7750                                                */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
                  


#include <stddef.h>
#include <stdio.h>
#include "sbrk.h"

extern char *_s1ptr;
extern void srand(unsigned int);

static  union  {
		long  dummy ;        /* Dummy for 4-byte boundary          */
		char heap[HEAPSIZE]; /* Declaration of the area managed   */
                             /*                           by sbrk */
 }heap_area ;

static  char  *brk=(char *)&heap_area;/* End address of area assigned     */

/**************************************************************************/
/*     sbrk:Data write							  						  */
/*	    Return value:Start address of the assigned area (Pass)	  		  */
/*	                 -1				    (Failure)	  					  */
/**************************************************************************/
char  *sbrk(unsigned long size)		   /* Assigned area size	  */
{
      char  *p;

      if(brk+size>heap_area.heap+HEAPSIZE) /* Empty area size		  */
	   return (char *)-1 ;

      p=brk ;				   /* Area assignment		  */
      brk += size ;			   /* End address update	  */
      return p ;
}

/****************************************************************************/
/* _INIT_OTHERLIB                                                           */
/*	Initialize C library Functions, if necessary.			    */
/*	Define OTHERLIB on Assembler Option.				    */
/****************************************************************************/

void _INIT_OTHERLIB(void)
{
	errno=0;
	srand(1);
	_s1ptr=NULL;
}
