
; ***** 型データ関連アドレスマップ データ定義 ******************************

_SEQ_016_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス１６
_SEQ_017_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス１７
_SEQ_018_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス１８
_SEQ_019_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス１９
_SEQ_020_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス２０
_SEQ_021_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス２１
_SEQ_022_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス２２
_SEQ_023_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス２３
_SEQ_024_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス２４
_SEQ_025_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス２５
_SEQ_026_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス２６
_SEQ_027_SV_INI        .DATA.W	H'0000           ; 初期回路設定シーケンス２７
_SEQ_028_SV_INI        .DATA.W	H'0000           ; クラッチ初期設定シーケンス２８
_SEQ_029_SV_INI        .DATA.W	H'0000           ; クラッチ初期設定シーケンス２９
_SEQ_030_SV_INI        .DATA.W	H'0000           ; クラッチ初期設定シーケンス３０
_SEQ_031_SV_INI        .DATA.W	H'0000           ; 機能選択シーケンス３１
_SEQ_032_SVB_INI       .DATA.W	H'0000           ; 空き	／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_033_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_034_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_035_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_036_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_037_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_038_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_039_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_040_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_041_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_042_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_043_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_044_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_045_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_046_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_047_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_048_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_049_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_050_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_051_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_052_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_053_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_054_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_055_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_056_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_057_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_058_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_059_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_060_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_061_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_062_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_063_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_064_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_065_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_066_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_067_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_068_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_069_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_070_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_071_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_072_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_073_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_074_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_075_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_076_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_077_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_078_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_079_SVB_INI       .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_DUMMY_01_INI      .SRES        32          ; ダミー／＊＊＊＊　未使用　＊＊＊＊／
_SV_SEQDT1_A91_INI     .DATA.W	H'0000           ; シーケンスモニタ設定１
_SV_SEQDT2_A91_INI     .DATA.W	H'0000           ; シーケンスモニタ設定２
_SV_SEQDT3_A91_INI     .DATA.W	H'0000           ; シーケンスモニタ設定３
_SV_SEQDT4_A91_INI     .DATA.W	H'0000           ; シーケンスモニタ設定４
_SV_DUMMY_A91_INI      .SRES        22          ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_POINT_A1_INI       .DATA.W	D'0000           ; スライド調節　小数点位置／＊＊＊＊　未使用　＊＊＊＊／
_SV_KANDO_A21_INI      .DATA.L	D'00000000       ; スライド自動調節　感度／＊＊＊＊　未使用　＊＊＊＊／
_SV_UPDATA_A21_INI     .DATA.L	D'00000000       ; スライド自動調節　上限／＊＊＊＊　未使用　＊＊＊＊／
_SV_DNDATA_A21_INI     .DATA.L	D'00000000       ; スライド自動調節　下限／＊＊＊＊　未使用　＊＊＊＊／
_SV_GENITI_A21_INI     .DATA.L	D'00000000       ; スライド自動調節　現位置／＊＊＊＊　未使用　＊＊＊＊／
_SV_DNSTOP_A21_INI     .DATA.W	D'0000           ; スライド自動調節　下降停止
_SV_UPSTOP_A21_INI     .DATA.W	D'0000           ; スライド自動調節　上昇停止
_SV_MODORI_A21_INI     .DATA.W	D'0000           ; スライド自動調節　戻り量
_SV_SSEIDO_A21_INI     .DATA.W	D'0000           ; スライド自動調節　制御精度
_SV_DUMMY_A21_INI      .SRES        20          ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_MAXHIZ_A24_INI     .DATA.W	D'0000           ; 荷重校正　最大歪１
_SV_MAXKAJ_A24_INI     .DATA.W	D'0000           ; 荷重校正　最大荷重１
_SV_KOUKAJ_A24_INI     .DATA.W	D'0000           ; 荷重校正　校正荷重１
_SV_KOUSEI_A24_INI     .DATA.W	D'0000           ; 荷重校正　校正精度
_SV_MAXKA2_A24_INI     .DATA.W	D'0000           ; 荷重校正　最大荷重２
_SV_KOUKA2_A24_INI     .DATA.W	D'0000           ; 荷重校正　校正荷重２
_SV_MAXHI3_A24_INI     .DATA.W	D'0000           ; 荷重校正　最大歪３
_SV_MAXKA3_A24_INI     .DATA.W	D'0000           ; 荷重校正　最大荷重３
_SV_KOUKA3_A24_INI     .DATA.W	D'0000           ; 荷重校正　校正荷重３
_SV_APARAD_A24_INI     .DATA.W	D'0000           ; 荷重校正　最低表示荷重
_SV_COUNT1_A1_INI      .DATA.W	D'0000           ; 内部カウンタ１
_SV_COUNT2_A1_INI      .DATA.W	D'0000           ; 内部カウンタ２
_SV_COUNT3_A1_INI      .DATA.W	D'0000           ; 内部カウンタ３
_SV_TIMER1_A1_INI      .DATA.W	D'0000           ; 内部タイマ１
_SV_TIMER2_A1_INI      .DATA.W	D'0000           ; 内部タイマ２
_SV_TIMER3_A1_INI      .DATA.W	D'0000           ; 内部タイマ３
_SV_DUMMY_A1_INI       .SRES        10          ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLSA1_A17_INI     .DATA.W	D'0000           ; システムカムＡ　ＯＮ角度
_SV_RCLSA2_A17_INI     .DATA.W	D'0000           ; システムカムＡ　ＯＦＦ角度
_SV_RCLSB1_A17_INI     .DATA.W	D'0000           ; システムカムＢ　ＯＮ角度
_SV_RCLSB2_A17_INI     .DATA.W	D'0000           ; システムカムＢ　ＯＦＦ角度
_SV_RCLSC1_A17_INI     .DATA.W	D'0000           ; システムカムＣ　ＯＮ角度
_SV_RCLSC2_A17_INI     .DATA.W	D'0000           ; システムカムＣ　ＯＦＦ角度
_SV_RCLSD1_A17_INI     .DATA.W	D'0000           ; システムカムＤ　ＯＮ角度
_SV_RCLSD2_A17_INI     .DATA.W	D'0000           ; システムカムＤ　ＯＦＦ角度
_SV_RCLSE1_A17_INI     .DATA.W	D'0000           ; システムカムＥ　ＯＮ角度
_SV_RCLSE2_A17_INI     .DATA.W	D'0000           ; システムカムＥ　ＯＦＦ角度
_SV_RCLSF1_A18_INI     .DATA.W	D'0000           ; システムカムＦ　ＯＮ角度
_SV_RCLSF2_A18_INI     .DATA.W	D'0000           ; システムカムＦ　ＯＦＦ角度
_SV_RCLSG1_A18_INI     .DATA.W	D'0000           ; システムカムＧ　ＯＮ角度
_SV_RCLSG2_A18_INI     .DATA.W	D'0000           ; システムカムＧ　ＯＦＦ角度
_SV_RCLSH1_A18_INI     .DATA.W	D'0000           ; システムカムＨ　ＯＮ角度
_SV_RCLSH2_A18_INI     .DATA.W	D'0000           ; システムカムＨ　ＯＦＦ角度
_SV_DUMMY_A18_INI      .SRES        10          ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNADIR_SEL1_INI    .DATA.W	D'0000           ; ﾘﾆｱｾﾝｻ極性
_SV_INCDIR_SEL1_INI    .DATA.W	D'0000           ; PG極性
_SV_INCPLS_1REV_INI    .DATA.W	D'0000           ; PG1回転のﾊﾟﾙｽ選択
_SV_INCPLS_HOSN_INI    .DATA.W	D'0000           ; PG補正N　ﾓｰﾀN回
_SV_INCPLS_HOSM_INI    .DATA.W	D'0000           ; PG補正M　ｸﾗﾝｸ角度M
_SV_MOTRPM_MAXM_INI    .DATA.W	D'0000           ; ﾓｰﾀ最大回転数
_SV_DNDINC_SPD1_INI    .DATA.W	D'0000           ; 段取速度
_SV_UPAREA_SPD1_INI    .DATA.W	D'0000           ; 待機点復帰速度
_SV_STDINC_SPD1_INI    .DATA.W	D'0000           ; 寸動速度
_SV_REVDAT_SPD1_INI    .DATA.W	D'0000           ; 予備速度１
_SV_REVDAT_SPD2_INI    .DATA.W	D'0000           ; 予備速度２
_SV_REVDAT_SPD3_INI    .DATA.W	D'0000           ; 予備速度３
_SV_TEPDAT_SPD1_INI    .DATA.W	D'0000           ; 手動ﾊﾟﾙｻ速度
_SV_TEPLAT_DAT1_INI    .DATA.W	D'0000           ; 手動ﾊﾟﾙｻ低倍率
_SV_TEPLAT_DAT2_INI    .DATA.W	D'0000           ; 手動ﾊﾟﾙｻ高倍率
_SV_INCPOS_KP01_INI    .DATA.W	D'0000           ; PG位置比例ｹﾞｲﾝ
_SV_RNAPOS_KP01_INI    .DATA.W	D'0000           ; ﾘﾆｱ位置比例ｹﾞｲﾝ
_SV_ACCLAT__TIM1_INI   .DATA.W	D'0000           ; 加減速時間
_SV_SSCURV_TIM1_INI    .DATA.W	D'0000           ; Ｓ字時間
_SV_UPAREA_INP1_INI    .DATA.W	D'0000           ; 上死点ｲﾝﾎﾟｼﾞｼｮﾝ
_SV_DNAREA_INP1_INI    .DATA.W	D'0000           ; 下死点ｲﾝﾎﾟｼﾞｼｮﾝ
_SV_OBJARA_INP1_INI    .DATA.W	D'0000           ; 目標位置ｲﾝﾎﾟｼﾞｼｮﾝ
_SV_INPPOS_TIM1_INI    .DATA.W	D'0000           ; ｲﾝﾎﾟｼﾞｼｮﾝﾁｪｯｸ時間
_SV_ARACHK_LNG1_INI    .DATA.W	D'0000           ; 上／下死点通過判定量
_SV_UPAREA_DIG1_INI    .DATA.W	D'0000           ; 回転時待機点(上死点)
_SV_DUMMY_A22_INI      .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_UPAREA_JUDG_INI    .DATA.L	D'00000000       ; 上死点判定範囲
_SV_DNAREA_JUDG_INI    .DATA.L	D'00000000       ; 反転設定不可範囲
_SV_INCHEN_ELNG_INI    .DATA.W	D'0000           ; PG偏差異常幅
_SV_INCENC_ELNG_INI    .DATA.W	D'0000           ; PG-ENC一致量
_SV_INCRNA_ELNG_INI    .DATA.W	D'0000           ; PG-ﾘﾆｱ一致量
_SV_INCSTP_ELNG_INI    .DATA.W	D'0000           ; PG停止異常量
_SV_RNASTP_ELNG_INI    .DATA.W	D'0000           ; ﾘﾆｱ停止異常量
_SV_INCREV_ELNG_INI    .DATA.W	D'0000           ; PG逆転異常量
_SV_RNAREV_ELNG_INI    .DATA.W	D'0000           ; ﾘﾆｱ逆転異常量
_SV_DAIHAI_LNG1_INI    .DATA.W	D'0000           ; ﾀﾞｲﾊｲﾄ補正比較値(小)
_SV_DAIHAI_LNG2_INI    .DATA.W	D'0000           ; ﾀﾞｲﾊｲﾄ補正比較値(中)
_SV_DAIHAI_LNG3_INI    .DATA.W	D'0000           ; ﾀﾞｲﾊｲﾄ補正比較値(大)
_SV_AMPERR_VLT1_INI    .DATA.W	D'0000           ; 過負荷電圧1
_SV_AMPERR_TIM1_INI    .DATA.W	D'0000           ; 過負荷時間1
_SV_AMPERR_VLT2_INI    .DATA.W	D'0000           ; 過負荷電圧2
_SV_AMPERR_TIM2_INI    .DATA.W	D'0000           ; 過負荷時間2
_SV_AMPERR_VLT3_INI    .DATA.W	D'0000           ; 過負荷電圧3
_SV_AMPERR_TIM3_INI    .DATA.W	D'0000           ; 過負荷時間3
_SV_SERVO_44_INI       .DATA.W	D'0000           ; サーボパラメータ４４／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_45_INI       .DATA.W	D'0000           ; サーボパラメータ４５／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_46_INI       .DATA.W	D'0000           ; サーボパラメータ４６／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_47_INI       .DATA.W	D'0000           ; サーボパラメータ４７／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_48_INI       .DATA.W	D'0000           ; サーボパラメータ４８／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_49_INI       .DATA.W	D'0000           ; サーボパラメータ４９／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNA_STLORK_INI     .DATA.L	D'00000000       ; ストローク設定
_SV_OUTPLS_HOSA_INI    .DATA.W	D'0000           ; 出力ﾊﾟﾙｽ補正A
_SV_OUTPLS_HOSB_INI    .DATA.W	D'0000           ; 出力ﾊﾟﾙｽ補正B
_SV_UPHOLD_DIG_INI     .DATA.W	D'0000           ; 上昇ﾎｰﾙﾄﾞ角度
_SV_MACINE_SEL1_INI    .DATA.W	D'0000           ; 予備（機種選択１）
_SV_SERVO_56_INI       .DATA.W	D'0000           ; サーボパラメータ５６／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_57_INI       .DATA.W	D'0000           ; サーボパラメータ５７／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_58_INI       .DATA.W	D'0000           ; サーボパラメータ５８／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_59_INI       .DATA.W	D'0000           ; サーボパラメータ５９／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_60_INI       .DATA.W	D'0000           ; サーボパラメータ６０／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_61_INI       .DATA.W	D'0000           ; サーボパラメータ６１／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_62_INI       .DATA.W	D'0000           ; サーボパラメータ６２／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_63_INI       .DATA.W	D'0000           ; サーボパラメータ６３／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_64_INI       .DATA.W	D'0000           ; サーボパラメータ６４／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_65_INI       .DATA.W	D'0000           ; サーボパラメータ６５／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_66_INI       .DATA.W	D'0000           ; サーボパラメータ６６／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_67_INI       .DATA.W	D'0000           ; サーボパラメータ６７／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_68_INI       .DATA.W	D'0000           ; サーボパラメータ６８／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_69_INI       .DATA.W	D'0000           ; サーボパラメータ６９／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_70_INI       .DATA.W	D'0000           ; サーボパラメータ７０／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_18_INI       .SRES        14          ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_MOTMAX_FREQ_INI    .DATA.L	D'00000000       ; ﾓｰﾀ最大時指令周波数
_SV_RNAORG_POS1_INI    .DATA.L	D'00000000       ; 機械原点入力
_SV_RNAPOS_MAXP_INI    .DATA.L	D'00000000       ; 機械上限
_SV_RNAPOS_MINP_INI    .DATA.L	D'00000000       ; 機械下限
_SV_SERVO_80_INI       .DATA.L	D'00000000       ; サーボパラメータ８０／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_81_INI       .DATA.L	D'00000000       ; サーボパラメータ８１／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_82_INI       .DATA.L	D'00000000       ; サーボパラメータ８２／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_83_INI       .DATA.L	D'00000000       ; サーボパラメータ８３／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_84_INI       .DATA.L	D'00000000       ; サーボパラメータ８４／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_85_INI       .DATA.L	D'00000000       ; サーボパラメータ８５／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_86_INI       .DATA.L	D'00000000       ; サーボパラメータ８６／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_87_INI       .DATA.L	D'00000000       ; サーボパラメータ８７／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_88_INI       .DATA.L	D'00000000       ; サーボパラメータ８８／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_89_INI       .DATA.L	D'00000000       ; サーボパラメータ８９／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_90_INI       .DATA.L	D'00000000       ; サーボパラメータ９０／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_91_INI       .DATA.L	D'00000000       ; サーボパラメータ９１／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_92_INI       .DATA.L	D'00000000       ; サーボパラメータ９２／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_93_INI       .DATA.L	D'00000000       ; サーボパラメータ９３／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_94_INI       .DATA.L	D'00000000       ; サーボパラメータ９４／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_95_INI       .DATA.L	D'00000000       ; サーボパラメータ９５／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_96_INI       .DATA.L	D'00000000       ; サーボパラメータ９６／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_97_INI       .DATA.L	D'00000000       ; サーボパラメータ９７／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_98_INI       .DATA.L	D'00000000       ; サーボパラメータ９８／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_99_INI       .DATA.L	D'00000000       ; サーボパラメータ９９／＊＊＊＊　未使用　＊＊＊＊／
_SV_SERVO_100_INI      .DATA.L	D'00000000       ; サーボパラメータ１００／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_101_INI      .SRES        60          ; 予備／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPMSV1_A1_INI      .DATA.W	D'0000           ; 検出速度１
_SV_SPMSV2_A1_INI      .DATA.W	D'0000           ; 検出速度２
_SV_SPMSV3_A1_INI      .DATA.W	D'0000           ; 検出速度３
_SV_SPMSV4_A1_INI      .DATA.W	D'0000           ; 段取速度１
_SV_SPMSV5_A1_INI      .DATA.W	D'0000           ; 段取速度２
_SV_MAXSPM_A14_INI     .DATA.W	D'0000           ; 機械最高速度設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ100_A15_INI     .DATA.W	D'0000           ; 待機点１連続　　１００％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ090_A15_INI     .DATA.W	D'0000           ; 待機点１連続　　　９０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ080_A15_INI     .DATA.W	D'0000           ; 待機点１連続　　　８０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ070_A15_INI     .DATA.W	D'0000           ; 待機点１連続　　　７０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ060_A15_INI     .DATA.W	D'0000           ; 待機点１連続　　　６０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ050_A15_INI     .DATA.W	D'0000           ; 待機点１連続　　　５０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK100_A15_INI     .DATA.W	D'0000           ; 待機点１一行程　１００％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK090_A15_INI     .DATA.W	D'0000           ; 待機点１一行程　　９０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK080_A15_INI     .DATA.W	D'0000           ; 待機点１一行程　　８０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK070_A15_INI     .DATA.W	D'0000           ; 待機点１一行程　　７０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK060_A15_INI     .DATA.W	D'0000           ; 待機点１一行程　　６０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK050_A15_INI     .DATA.W	D'0000           ; 待機点１一行程　　５０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ100_A152_INI    .DATA.W	D'0000           ; 待機点２連続　　１００％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ090_A152_INI    .DATA.W	D'0000           ; 待機点２連続　　　９０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ080_A152_INI    .DATA.W	D'0000           ; 待機点２連続　　　８０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ070_A152_INI    .DATA.W	D'0000           ; 待機点２連続　　　７０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ060_A152_INI    .DATA.W	D'0000           ; 待機点２連続　　　６０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ050_A152_INI    .DATA.W	D'0000           ; 待機点２連続　　　５０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK100_A152_INI    .DATA.W	D'0000           ; 待機点２一行程　１００％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK090_A152_INI    .DATA.W	D'0000           ; 待機点２一行程　　９０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK080_A152_INI    .DATA.W	D'0000           ; 待機点２一行程　　８０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK070_A152_INI    .DATA.W	D'0000           ; 待機点２一行程　　７０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK060_A152_INI    .DATA.W	D'0000           ; 待機点２一行程　　６０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK050_A152_INI    .DATA.W	D'0000           ; 待機点２一行程　　５０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ100_A153_INI    .DATA.W	D'0000           ; 待機点３連続　　１００％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ090_A153_INI    .DATA.W	D'0000           ; 待機点３連続　　　９０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ080_A153_INI    .DATA.W	D'0000           ; 待機点３連続　　　８０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ070_A153_INI    .DATA.W	D'0000           ; 待機点３連続　　　７０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ060_A153_INI    .DATA.W	D'0000           ; 待機点３連続　　　６０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZ050_A153_INI    .DATA.W	D'0000           ; 待機点３連続　　　５０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK100_A153_INI    .DATA.W	D'0000           ; 待機点３一行程　１００％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK090_A153_INI    .DATA.W	D'0000           ; 待機点３一行程　　９０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK080_A153_INI    .DATA.W	D'0000           ; 待機点３一行程　　８０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK070_A153_INI    .DATA.W	D'0000           ; 待機点３一行程　　７０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK060_A153_INI    .DATA.W	D'0000           ; 待機点３一行程　　６０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_ITK050_A153_INI    .DATA.W	D'0000           ; 待機点３一行程　　５０％設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_KAGENS_A1_INI      .DATA.W	D'0000           ; 加減速時間／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_102_INI      .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_103_INI      .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_104_INI      .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_105_INI      .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_106_INI      .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_107_INI      .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM001_A15_INI     .DATA.W	D'0000           ; 最高速度設定の１００％演算値／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM002_A15_INI     .DATA.W	D'0000           ; 最高速度設定の　９０％演算値／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM003_A15_INI     .DATA.W	D'0000           ; 最高速度設定の　８０％演算値／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM004_A15_INI     .DATA.W	D'0000           ; 最高速度設定の　７０％演算値／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM005_A15_INI     .DATA.W	D'0000           ; 最高速度設定の　６０％演算値／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM006_A15_INI     .DATA.W	D'0000           ; 最高速度設定の　５０％演算値／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM001_A152_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM002_A152_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM003_A152_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM004_A152_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM005_A152_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM006_A152_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM001_A153_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM002_A153_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM003_A153_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM004_A153_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_SPM005_A153_INI    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_A153_INI     .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_POINT_A47_INI      .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　小数点位置／＊＊＊＊　未使用　＊＊＊＊／
_SV_KANDO_A47_INI      .DATA.L	D'00000000       ; ﾀﾞｲｸｯｼｮﾝ自動調節左　感度／＊＊＊＊　未使用　＊＊＊＊／
_SV_UPDATA_A47_INI     .DATA.L	D'00000000       ; ﾀﾞｲｸｯｼｮﾝ自動調節左　上限／＊＊＊＊　未使用　＊＊＊＊／
_SV_DNDATA_A47_INI     .DATA.L	D'00000000       ; ﾀﾞｲｸｯｼｮﾝ自動調節左　下限／＊＊＊＊　未使用　＊＊＊＊／
_SV_GENITI_A47_INI     .DATA.L	D'00000000       ; ﾀﾞｲｸｯｼｮﾝ自動調節左　現位置／＊＊＊＊　未使用　＊＊＊＊／
_SV_DNSTOP_A47_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　下降停止／＊＊＊＊　未使用　＊＊＊＊／
_SV_UPSTOP_A47_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　上昇停止／＊＊＊＊　未使用　＊＊＊＊／
_SV_MODORI_A47_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　戻り量／＊＊＊＊　未使用　＊＊＊＊／
_SV_SSEIDO_A47_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節左　制御精度／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_A17_INI      .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_POINT_A48_INI      .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　小数点位置／＊＊＊＊　未使用　＊＊＊＊／
_SV_KANDO_A48_INI      .DATA.L	D'00000000       ; ﾀﾞｲｸｯｼｮﾝ自動調節右　感度／＊＊＊＊　未使用　＊＊＊＊／
_SV_UPDATA_A48_INI     .DATA.L	D'00000000       ; ﾀﾞｲｸｯｼｮﾝ自動調節右　上限／＊＊＊＊　未使用　＊＊＊＊／
_SV_DNDATA_A48_INI     .DATA.L	D'00000000       ; ﾀﾞｲｸｯｼｮﾝ自動調節右　下限／＊＊＊＊　未使用　＊＊＊＊／
_SV_GENITI_A48_INI     .DATA.L	D'00000000       ; ﾀﾞｲｸｯｼｮﾝ自動調節右　現位置／＊＊＊＊　未使用　＊＊＊＊／
_SV_DNSTOP_A48_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　下降停止／＊＊＊＊　未使用　＊＊＊＊／
_SV_UPSTOP_A48_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　上昇停止／＊＊＊＊　未使用　＊＊＊＊／
_SV_MODORI_A48_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　戻り量／＊＊＊＊　未使用　＊＊＊＊／
_SV_SSEIDO_A48_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ自動調節右　制御精度／＊＊＊＊　未使用　＊＊＊＊／
_SV_BARAUP_A49_INI     .DATA.W	D'0000           ; バランサ圧力調節　上限／＊＊＊＊　未使用　＊＊＊＊／
_SV_BARADN_A49_INI     .DATA.W	D'0000           ; バランサ圧力調節　上限／＊＊＊＊　未使用　＊＊＊＊／
_SV_DAILUP_A49_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ左上限／＊＊＊＊　未使用　＊＊＊＊／
_SV_DAILDN_A49_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ左下限／＊＊＊＊　未使用　＊＊＊＊／
_SV_DAIRUP_A49_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ右上限／＊＊＊＊　未使用　＊＊＊＊／
_SV_DAIRDN_A49_INI     .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ圧力調節　ﾀﾞｲｸｯｼｮﾝ右下限／＊＊＊＊　未使用　＊＊＊＊／
_SV_SYUMAX_A14_INI     .DATA.W	D'0000           ; 仕様速度以下／＊＊＊＊　未使用　＊＊＊＊／
_SV_CLTIME_C1_INI      .DATA.W	D'0000           ; クラッチタイム／＊＊＊＊　未使用　＊＊＊＊／
_SV_BRTIME_C1_INI      .DATA.W	D'0000           ; ブレーキタイム 設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_BRDIG_C1_INI       .DATA.W	D'0000           ; ブレーキ角度 設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_BARKIJ_A45_INI     .DATA.W	D'0000           ; バランサ圧基準／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILDN1_A50_INI     .DATA.W	D'0000           ; コイルライン設定上限値１／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILUP1_A50_INI     .DATA.W	D'0000           ; コイルライン設定下限値１／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILDN2_A50_INI     .DATA.W	D'0000           ; コイルライン設定上限値２／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILUP2_A50_INI     .DATA.W	D'0000           ; コイルライン設定下限値２／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILDN3_A50_INI     .DATA.W	D'0000           ; コイルライン設定上限値３／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILUP3_A50_INI     .DATA.W	D'0000           ; コイルライン設定下限値３／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILDN4_A50_INI     .DATA.W	D'0000           ; コイルライン設定上限値４／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILUP4_A50_INI     .DATA.W	D'0000           ; コイルライン設定下限値４／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILDN5_A50_INI     .DATA.W	D'0000           ; コイルライン設定上限値５／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILUP5_A50_INI     .DATA.W	D'0000           ; コイルライン設定下限値５／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILDN6_A50_INI     .DATA.W	D'0000           ; コイルライン設定上限値６／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILUP6_A50_INI     .DATA.W	D'0000           ; コイルライン設定下限値６／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILTN1_A50_INI     .DATA.W	D'0000           ; コイルライン設定１小数点／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILTN2_A50_INI     .DATA.W	D'0000           ; コイルライン設定２小数点／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILTN3_A50_INI     .DATA.W	D'0000           ; コイルライン設定３小数点／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILTN4_A50_INI     .DATA.W	D'0000           ; コイルライン設定４小数点／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILTN5_A50_INI     .DATA.W	D'0000           ; コイルライン設定５小数点／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILTN6_A50_INI     .DATA.W	D'0000           ; コイルライン設定６小数点／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILUMU_A50_INI     .DATA.W	D'0000           ; コイルライン設定有無選択／＊＊＊＊　未使用　＊＊＊＊／
_SV_CILMAI_A50_INI     .DATA.W	D'0000           ; コイルライン設定マイナス選択／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.W	D'0000           ; バランサ圧力上限／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.W	D'0000           ; バランサ圧力上限／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ左上限／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ左下限／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ右上限／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.W	D'0000           ; ﾀﾞｲｸｯｼｮﾝ右下限／＊＊＊＊　未使用　＊＊＊＊／
_SV_NEXTNO_D1_INI      .DATA.W	D'0000           ; 自動金型用次期ファイル読み出し番号／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_D1_INI       .SRES        376         ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_FRAM_KAT_TOP_INI      .DATA.W	D'0000           ; F-RAM領域の型データのトップラベル
_SV_DUMMY_D2_INI       .SRES        14          ; 空き
_SEQ_032_SV_INI        .DATA.W	H'0000           ; トータル＆ロットカウンタ　入／切選択
_SEQ_033_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_034_SV_INI        .DATA.W	H'0000           ; エジェクタ１～６　入／切選択、カム／タイマ選択
_SEQ_035_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_036_SV_INI        .DATA.W	H'0000           ; ミスフィード１～４　入／切、即／連
_SEQ_037_SV_INI        .DATA.W	H'0000           ; ミスフィード１～４　N.O／Ｎ．Ｃ、接触／保持
_SEQ_038_SV_INI        .DATA.W	H'0000           ; ロータリカム１～１６　入／切選択
_SEQ_039_SV_INI        .DATA.W	H'0000           ; ロータリカム１７～２０　入／切選択
_SEQ_040_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_041_SV_INI        .DATA.W	H'0000           ; 上型クランパ、下型クランパ　内／全／外選択
_SEQ_042_SV_INI        .DATA.W	H'0000           ; ダイリフタ　内/全／外選択
_SEQ_043_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_044_SV_INI        .DATA.W	H'0000           ; ｽﾗｲﾄﾞ自動調節 生産／段取１／段取２選択
_SEQ_045_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_046_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_047_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_048_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_049_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_050_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_051_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_052_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_053_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_054_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_055_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_056_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_057_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_058_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_059_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_060_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_061_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_062_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_063_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_064_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_065_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_066_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_067_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_068_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_069_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_070_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_071_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_072_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_073_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_074_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_075_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_076_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_077_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_078_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_079_SV_INI        .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_PUR1SV_B4_INI      .DATA.L	D'00000000       ; ロットカウンタ１設定値
_SV_PUR2SV_B41_INI     .DATA.L	D'00000000       ; ロットカウンタ２設定値
_SV_TAIKIPOS_SRV_INI   .DATA.L	D'00000000       ; 待機位置
_SV_KAITEN_SRV_INI     .DATA.W	D'0000           ; 回転方式
_SV_DANSUU_SRV_INI     .DATA.W	D'0000           ; 段数
_SV_TAIKIKAKU_SRV_INI  .DATA.W	D'0000           ; 待機角
_SV_TAIKSPD_SRV_INI    .DATA.W	D'0000           ; 基準速度
_SV_DAIHAITO_SRV_INI   .DATA.L	D'00000000       ; ダイハイト
_SV_HOASEI_SRV_INI     .DATA.W	D'0000           ; 補正データ
_SV_TAIKTIM_SRV_INI    .DATA.W	D'0000           ; 待機時間
_SV_1DANDEG_SRV_INI    .DATA.W	D'0000           ; 1段目目標角度
_SV_2DANDEG_SRV_INI    .DATA.W	D'0000           ; 2段目目標角度
_SV_3DANDEG_SRV_INI    .DATA.W	D'0000           ; 3段目目標角度
_SV_4DANDEG_SRV_INI    .DATA.W	D'0000           ; 4段目目標角度
_SV_5DANDEG_SRV_INI    .DATA.W	D'0000           ; 5段目目標角度
_SV_6DANDEG_SRV_INI    .DATA.W	D'0000           ; 6段目目標角度
_SV_7DANDEG_SRV_INI    .DATA.W	D'0000           ; 7段目目標角度
_SV_8DANDEG_SRV_INI    .DATA.W	D'0000           ; 8段目目標角度
_SV_9DANDEG_SRV_INI    .DATA.W	D'0000           ; 9段目目標角度
_SV_10DANDEG_SRV_INI   .DATA.W	D'0000           ; 10段目目標角度
_SV_1DANPOS_SRV_INI    .DATA.L	D'00000000       ; 1段目目標位置
_SV_2DANPOS_SRV_INI    .DATA.L	D'00000000       ; 2段目目標位置
_SV_3DANPOS_SRV_INI    .DATA.L	D'00000000       ; 3段目目標位置
_SV_4DANPOS_SRV_INI    .DATA.L	D'00000000       ; 4段目目標位置
_SV_5DANPOS_SRV_INI    .DATA.L	D'00000000       ; 5段目目標位置
_SV_6DANPOS_SRV_INI    .DATA.L	D'00000000       ; 6段目目標位置
_SV_7DANPOS_SRV_INI    .DATA.L	D'00000000       ; 7段目目標位置
_SV_8DANPOS_SRV_INI    .DATA.L	D'00000000       ; 8段目目標位置
_SV_9DANPOS_SRV_INI    .DATA.L	D'00000000       ; 9段目目標位置
_SV_10DANPOS_SRV_INI   .DATA.L	D'00000000       ; 10段目目標位置
_SV_1DANSPD_SRV_INI    .DATA.W	D'0000           ; 1段目移動速度
_SV_2DANSPD_SRV_INI    .DATA.W	D'0000           ; 2段目移動速度
_SV_3DANSPD_SRV_INI    .DATA.W	D'0000           ; 3段目移動速度
_SV_4DANSPD_SRV_INI    .DATA.W	D'0000           ; 4段目移動速度
_SV_5DANSPD_SRV_INI    .DATA.W	D'0000           ; 5段目移動速度
_SV_6DANSPD_SRV_INI    .DATA.W	D'0000           ; 6段目移動速度
_SV_7DANSPD_SRV_INI    .DATA.W	D'0000           ; 7段目移動速度
_SV_8DANSPD_SRV_INI    .DATA.W	D'0000           ; 8段目移動速度
_SV_9DANSPD_SRV_INI    .DATA.W	D'0000           ; 9段目移動速度
_SV_10DANSPD_SRV_INI   .DATA.W	D'0000           ; 10段目移動速度
_SV_1DANTIM_SRV_INI    .DATA.W	D'0000           ; 1段目停止時間
_SV_2DANTIM_SRV_INI    .DATA.W	D'0000           ; 2段目停止時間
_SV_3DANTIM_SRV_INI    .DATA.W	D'0000           ; 3段目停止時間
_SV_4DANTIM_SRV_INI    .DATA.W	D'0000           ; 4段目停止時間
_SV_5DANTIM_SRV_INI    .DATA.W	D'0000           ; 5段目停止時間
_SV_6DANTIM_SRV_INI    .DATA.W	D'0000           ; 6段目停止時間
_SV_7DANTIM_SRV_INI    .DATA.W	D'0000           ; 7段目停止時間
_SV_8DANTIM_SRV_INI    .DATA.W	D'0000           ; 8段目停止時間
_SV_9DANTIM_SRV_INI    .DATA.W	D'0000           ; 9段目停止時間
_SV_10DANTIM_SRV_INI   .DATA.W	D'0000           ; 10段目停止時間
_SV_CYCTIM_SRV_INI     .DATA.W	D'0000           ; サイクルタイム
_SV_TAIKAN_SRV_INI     .DATA.W	D'0000           ; 待機完了範囲
_SV_MOKKAN_SRV_INI     .DATA.W	D'0000           ; 目標完了範囲
_SV_DUMMY_B11_INI      .SRES        10          ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_EJESAT1_C4_INI     .DATA.W	D'0000           ; エジェクタ１　ＯＮ工程　　　カム仕様
_SV_EJEKK1_C4_INI      .DATA.W	D'0000           ; エジェクタ１　ＯＮ角度　　　カム仕様
_SV_EJESTP1_C4_INI     .DATA.W	D'0000           ; エジェクタ１　ＯＦＦ工程　　　カム仕様
_SV_EJEKK2_C4_INI      .DATA.W	D'0000           ; エジェクタ１　ＯＦＦ角度　　カム仕様
_SV_EJESAT1_C4A_INI    .DATA.W	D'0000           ; エジェクタ２　ＯＮ工程　　　カム仕様
_SV_EJEKK1_C4A_INI     .DATA.W	D'0000           ; エジャクタ２　ＯＮ角度　　　カム仕様
_SV_EJESTP1_C4A_INI    .DATA.W	D'0000           ; エジェクタ２　ＯＦＦ工程　　　カム仕様
_SV_EJEKK2_C4A_INI     .DATA.W	D'0000           ; エジェクタ２　ＯＦＦ角度　　カム仕様
_SV_EJESAT1_C4B_INI    .DATA.W	D'0000           ; エジェクタ３　ＯＮ工程　　　カム仕様
_SV_EJEKK1_C4B_INI     .DATA.W	D'0000           ; エジャクタ３　ＯＮ角度　　　カム仕様
_SV_EJESTP1_C4B_INI    .DATA.W	D'0000           ; エジェクタ３　ＯＦＦ工程　　　カム仕様
_SV_EJEKK2_C4B_INI     .DATA.W	D'0000           ; エジェクタ３　ＯＦＦ角度　　カム仕様
_SV_AUTSTA_C41_INI     .DATA.W	D'0000           ; 自動化１　ＯＮ工程　　　カム仕様
_SV_AUTKK1_C41_INI     .DATA.W	D'0000           ; 自動化１　ＯＮ角度　　　カム仕様
_SV_AUTSTP_C41_INI     .DATA.W	D'0000           ; 自動化１　ＯFF工程　　　カム仕様
_SV_AUTKK2_C41_INI     .DATA.W	D'0000           ; 自動化１　ＯＦＦ角度　　　カム仕様
_SV_AUTSTA_C41A_INI    .DATA.W	D'0000           ; 自動化２　ＯＮ工程　　　カム仕様
_SV_AUTKK1_C41A_INI    .DATA.W	D'0000           ; 自動化２　ＯＮ角度　　　カム仕様
_SV_AUTSTP_C41A_INI    .DATA.W	D'0000           ; 自動化２　ＯFF工程　　　カム仕様
_SV_AUTKK2_C41A_INI    .DATA.W	D'0000           ; 自動化２　ＯＦＦ角度　　　カム仕様
_SV_AUTSTA_C41B_INI    .DATA.W	D'0000           ; 自動化３　ＯＮ工程　　　カム仕様
_SV_AUTKK1_C41B_INI    .DATA.W	D'0000           ; 自動化３　ＯＮ角度　　　カム仕様
_SV_AUTSTP_C41B_INI    .DATA.W	D'0000           ; 自動化３　ＯFF程　　　カム仕様
_SV_AUTKK2_C41B_INI    .DATA.W	D'0000           ; 自動化３　ＯＦＦ角度　　　カム仕様
_SV_EJESTA_C5_INI      .DATA.W	D'0000           ; エジェクタ１　ＯＮ工程　　　タイマ仕様
_SV_EJEKK3_C5_INI      .DATA.W	D'0000           ; エジェクタ１　ＯＮ角度　　　タイマ仕様
_SV_EJESTP_C5_INI      .DATA.W	D'0000           ; エジェクタ１　ＯＦＦ工程　　　タイマ仕様
_SV_EJETIM_C5_INI      .DATA.W	D'0000           ; エジェクタ１　ＯＦＦタイマ　タイマ仕様
_SV_EJESTA_C5A_INI     .DATA.W	D'0000           ; エジェクタ２　ＯＮ工程　　　タイマ仕様
_SV_EJEKK3_C5A_INI     .DATA.W	D'0000           ; エジェクタ２　ＯＮ角度　　　タイマ仕様
_SV_EJESTP_C5A_INI     .DATA.W	D'0000           ; エジェクタ２　ＯＦＦ工程　　　タイマ仕様
_SV_EJETIM_C5A_INI     .DATA.W	D'0000           ; エジェクタ２　ＯＦＦタイマ　タイマ仕様
_SV_EJESTA_C5B_INI     .DATA.W	D'0000           ; エジェクタ３　ＯＮ工程　　　タイマ仕様
_SV_EJEKK3_C5B_INI     .DATA.W	D'0000           ; エジェクタ３　ＯＮ角度　　　タイマ仕様
_SV_EJESTP_C5B_INI     .DATA.W	D'0000           ; エジェクタ２　ＯＦＦ工程　　　タイマ仕様
_SV_EJETIM_C5B_INI     .DATA.W	D'0000           ; エジェクタ３　ＯＦＦタイマ　タイマ仕様
_SV_AUTSTA_C51_INI     .DATA.W	D'0000           ; 自動化１　ＯＮ工程　　　タイマ仕様
_SV_AUTKK3_C51_INI     .DATA.W	D'0000           ; 自動化１　ＯＮ角度　　　　　タイマ仕様
_SV_AUTSTP_C51_INI     .DATA.W	D'0000           ; 自動化１　ＯFF工程　　　タイマ仕様
_SV_AUTTIM_C51_INI     .DATA.W	D'0000           ; 自動化１　ＯＦＦタイマ　　　タイマ仕様
_SV_AUTSTA_C51A_INI    .DATA.W	D'0000           ; 自動化２　ＯＮ工程　　　タイマ仕様
_SV_AUTKK3_C51A_INI    .DATA.W	D'0000           ; 自動化２　ＯＮ角度　　　　　タイマ仕様
_SV_AUTSTP_C51A_INI    .DATA.W	D'0000           ; 自動化２　ＯFF工程　　　タイマ仕様
_SV_AUTTIM_C51A_INI    .DATA.W	D'0000           ; 自動化２　ＯＦＦタイマ　　　タイマ仕様
_SV_AUTSTA_C51B_INI    .DATA.W	D'0000           ; 自動化３　ＯＮ工程　　　タイマ仕様
_SV_AUTKK3_C51B_INI    .DATA.W	D'0000           ; 自動化３　ＯＮ角度　　　　　タイマ仕様
_SV_AUTSTP_C51B_INI    .DATA.W	D'0000           ; 自動化３　ＯFF程　　　タイマ仕様
_SV_AUTTIM_C51B_INI    .DATA.W	D'0000           ; 自動化３　ＯＦＦタイマ　　　タイマ仕様
_SV_MISSTA1_C9_INI     .DATA.W	D'0000           ; ミスフィード１　ＯＮ工程
_SV_MISSK1_C9_INI      .DATA.W	D'0000           ; ミスフィード１　ＯＮ角度
_SV_MISSTP1_C9_INI     .DATA.W	D'0000           ; ミスフィード１　ＯＦＦ工程
_SV_MISSK2_C9_INI      .DATA.W	D'0000           ; ミスフィード１　ＯＦＦ角度
_SV_MISSTA2_C9_INI     .DATA.W	D'0000           ; ミスフィード２　ＯＮ工程
_SV_MISSK3_C9_INI      .DATA.W	D'0000           ; ミスフィード２　ＯＮ角度
_SV_MISSTP2_C9_INI     .DATA.W	D'0000           ; ミスフィード２　ＯＦＦ工程
_SV_MISSK4_C9_INI      .DATA.W	D'0000           ; ミスフィード２　ＯＦＦ角度
_SV_MISSTA3_C9_INI     .DATA.W	D'0000           ; ミスフィード３　ＯＮ工程
_SV_MISSK5_C9_INI      .DATA.W	D'0000           ; ミスフィード３　ＯＮ角度
_SV_MISSTP3_C9_INI     .DATA.W	D'0000           ; ミスフィード３　ＯＦＦ工程
_SV_MISSK6_C9_INI      .DATA.W	D'0000           ; ミスフィード３　ＯＦＦ角度
_SV_MISSTA4_C9_INI     .DATA.W	D'0000           ; ミスフィード４　ＯＮ工程
_SV_MISSK7_C9_INI      .DATA.W	D'0000           ; ミスフィード４　ＯＮ角度
_SV_MISSTP4_C9_INI     .DATA.W	D'0000           ; ミスフィード４　ＯＦＦ工程
_SV_MISSK8_C9_INI      .DATA.W	D'0000           ; ミスフィード４　ＯＦＦ角度
_SV_MISSTA5_C10_INI    .DATA.W	D'0000           ; ミスフィード５　ＯＮ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSK1_C10_INI     .DATA.W	D'0000           ; ミスフィード５　ＯＮ角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSTP5_C10_INI    .DATA.W	D'0000           ; ミスフィード５　ＯＦＦ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSK2_C10_INI     .DATA.W	D'0000           ; ミスフィード５　ＯＦＦ角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSTA6_C10_INI    .DATA.W	D'0000           ; ミスフィード６　ＯＮ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSK3_C10_INI     .DATA.W	D'0000           ; ミスフィード６　ＯＮ角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSTP6_C10_INI    .DATA.W	D'0000           ; ミスフィード６　ＯＦＦ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSK4_C10_INI     .DATA.W	D'0000           ; ミスフィード６　ＯＦＦ角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSTA7_C10_INI    .DATA.W	D'0000           ; ミスフィード７　ＯＮ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSK5_C10_INI     .DATA.W	D'0000           ; ミスフィード７　ＯＮ角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSTP7_C10_INI    .DATA.W	D'0000           ; ミスフィード７　ＯＦＦ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSK6_C10_INI     .DATA.W	D'0000           ; ミスフィード７　ＯＦＦ角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSTA8_C10_INI    .DATA.W	D'0000           ; ミスフィード８　ＯＮ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSK7_C10_INI     .DATA.W	D'0000           ; ミスフィード８　ＯＮ角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSTP8_C10_INI    .DATA.W	D'0000           ; ミスフィード８　ＯＦＦ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_MISSK8_C10_INI     .DATA.W	D'0000           ; ミスフィード８　ＯＦＦ角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLSTA11_C17_INI   .DATA.W	D'0000           ; ロータリカム１　ＯＮ工程
_SV_RCLS11_C17_INI     .DATA.W	D'0000           ; ロータリカム１　ＯＮ角度
_SV_RCLSTP12_C17_INI   .DATA.W	D'0000           ; ロータリカム１　ＯＦＦ工程
_SV_RCLS12_C17_INI     .DATA.W	D'0000           ; ロータリカム１　ＯＦＦ角度
_SV_RCLSTA21_C17_INI   .DATA.W	D'0000           ; ロータリカム２　ＯＮ工程
_SV_RCLS21_C17_INI     .DATA.W	D'0000           ; ロータリカム２　ＯＮ角度
_SV_RCLSTP22_C17_INI   .DATA.W	D'0000           ; ロータリカム２　ＯＦＦ工程
_SV_RCLS22_C17_INI     .DATA.W	D'0000           ; ロータリカム２　ＯＦＦ角度
_SV_RCLSTA31_C17_INI   .DATA.W	D'0000           ; ロータリカム３　ＯＮ工程
_SV_RCLS31_C17_INI     .DATA.W	D'0000           ; ロータリカム３　ＯＮ角度
_SV_RCLSTP32_C17_INI   .DATA.W	D'0000           ; ロータリカム３　ＯＦＦ工程
_SV_RCLS32_C17_INI     .DATA.W	D'0000           ; ロータリカム３　ＯＦＦ角度
_SV_RCLSTA41_C17_INI   .DATA.W	D'0000           ; ロータリカム４　ＯＮ工程
_SV_RCLS41_C17_INI     .DATA.W	D'0000           ; ロータリカム４　ＯＮ角度
_SV_RCLSTP42_C17_INI   .DATA.W	D'0000           ; ロータリカム４　ＯＦＦ工程
_SV_RCLS42_C17_INI     .DATA.W	D'0000           ; ロータリカム４　ＯＦＦ角度
_SV_RCLSTA51_C18_INI   .DATA.W	D'0000           ; ロータリカム５　ＯＮ工程
_SV_RCLS51_C18_INI     .DATA.W	D'0000           ; ロータリカム５　ＯＮ角度
_SV_RCLSTP52_C18_INI   .DATA.W	D'0000           ; ロータリカム５　ＯＦＦ工程
_SV_RCLS52_C18_INI     .DATA.W	D'0000           ; ロータリカム５　ＯＦＦ角度
_SV_RCLSTA61_C18_INI   .DATA.W	D'0000           ; ロータリカム６　ＯＮ工程
_SV_RCLS61_C18_INI     .DATA.W	D'0000           ; ロータリカム６　ＯＮ角度
_SV_RCLSTP62_C18_INI   .DATA.W	D'0000           ; ロータリカム６　ＯＦＦ工程
_SV_RCLS62_C18_INI     .DATA.W	D'0000           ; ロータリカム６　ＯＦＦ角度
_SV_RCLSTA71_C18_INI   .DATA.W	D'0000           ; ロータリカム７　ＯＮ工程
_SV_RCLS71_C18_INI     .DATA.W	D'0000           ; ロータリカム７　ＯＮ角度
_SV_RCLSTP72_C18_INI   .DATA.W	D'0000           ; ロータリカム７　ＯＦＦ工程
_SV_RCLS72_C18_INI     .DATA.W	D'0000           ; ロータリカム７　ＯＦＦ角度
_SV_RCLSTA81_C18_INI   .DATA.W	D'0000           ; ロータリカム８　ＯＮ工程
_SV_RCLS81_C18_INI     .DATA.W	D'0000           ; ロータリカム８　ＯＮ角度
_SV_RCLSTP82_C18_INI   .DATA.W	D'0000           ; ロータリカム８　ＯＦＦ工程
_SV_RCLS82_C18_INI     .DATA.W	D'0000           ; ロータリカム８　ＯＦＦ角度
_SV_RCLSTA11_C19_INI   .DATA.W	D'0000           ; ロータリカム９　ＯＮ工程
_SV_RCLS11_C19_INI     .DATA.W	D'0000           ; ロータリカム９　ＯＮ角度
_SV_RCLSTP12_C19_INI   .DATA.W	D'0000           ; ロータリカム９　ＯＦＦ工程
_SV_RCLS12_C19_INI     .DATA.W	D'0000           ; ロータリカム９　ＯＦＦ角度
_SV_RCLSTA21_C19_INI   .DATA.W	D'0000           ; ロータリカム１０　ＯＮ工程
_SV_RCLS21_C19_INI     .DATA.W	D'0000           ; ロータリカム１０　ＯＮ角度
_SV_RCLSTA22_C19_INI   .DATA.W	D'0000           ; ロータリカム１０　ＯＦＦ工程
_SV_RCLS22_C19_INI     .DATA.W	D'0000           ; ロータリカム１０　ＯＦＦ角度
_SV_RCLSTA31_C19_INI   .DATA.W	D'0000           ; ロータリカム１１　ＯＮ工程
_SV_RCLS31_C19_INI     .DATA.W	D'0000           ; ロータリカム１１　ＯＮ角度
_SV_RCLSTA32_C19_INI   .DATA.W	D'0000           ; ロータリカム１１　ＯＦＦ工程
_SV_RCLS32_C19_INI     .DATA.W	D'0000           ; ロータリカム１１　ＯＦＦ角度
_SV_RCLSTA41_C19_INI   .DATA.W	D'0000           ; ロータリカム１２　ＯＮ工程
_SV_RCLS41_C19_INI     .DATA.W	D'0000           ; ロータリカム１２　ＯＮ角度
_SV_RCLSTA42_C19_INI   .DATA.W	D'0000           ; ロータリカム１２　ＯＦＦ工程
_SV_RCLS42_C19_INI     .DATA.W	D'0000           ; ロータリカム１２　ＯＦＦ角度
_SV_RCLSTA51_C19_INI   .DATA.W	D'0000           ; ロータリカム１３　ＯＮ工程
_SV_RCLS51_C20_INI     .DATA.W	D'0000           ; ロータリカム１３　ＯＮ角度
_SV_RCLSTA52_C20_INI   .DATA.W	D'0000           ; ロータリカム１３　ＯＦＦ工程
_SV_RCLS52_C20_INI     .DATA.W	D'0000           ; ロータリカム１３　ＯＦＦ角度
_SV_RCLSTA61_C20_INI   .DATA.W	D'0000           ; ロータリカム１４　ＯＮ工程
_SV_RCLS61_C20_INI     .DATA.W	D'0000           ; ロータリカム１４　ＯＮ角度
_SV_RCLSTA62_C20_INI   .DATA.W	D'0000           ; ロータリカム１４　ＯＦＦ工程
_SV_RCLS62_C20_INI     .DATA.W	D'0000           ; ロータリカム１４　ＯＦＦ角度
_SV_RCLSTA71_C20_INI   .DATA.W	D'0000           ; ロータリカム１５　ＯＮ工程
_SV_RCLS71_C20_INI     .DATA.W	D'0000           ; ロータリカム１５　ＯＮ角度
_SV_RCLSTA72_C20_INI   .DATA.W	D'0000           ; ロータリカム１５　ＯＦＦ工程
_SV_RCLS72_C20_INI     .DATA.W	D'0000           ; ロータリカム１５　ＯＦＦ角度
_SV_RCLSTA81_C20_INI   .DATA.W	D'0000           ; ロータリカム１６　ＯＮ工程
_SV_RCLS81_C20_INI     .DATA.W	D'0000           ; ロータリカム１６　ＯＮ角度
_SV_RCLSTA82_C20_INI   .DATA.W	D'0000           ; ロータリカム１６　ＯＦＦ工程
_SV_RCLS82_C20_INI     .DATA.W	D'0000           ; ロータリカム１６　ＯＦＦ角度
_SV_RCLSTA11_C21_INI   .DATA.W	D'0000           ; ロータリカム１７　ＯＮ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLS11_C21_INI     .DATA.W	D'0000           ; ロータリカム１７　ON角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLSTA12_C21_INI   .DATA.W	D'0000           ; ロータリカム１７　ＯＦＦ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLS12_C21_INI     .DATA.W	D'0000           ; ロータリカム１７　OFF角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLSTA21_C21_INI   .DATA.W	D'0000           ; ロータリカム１８　ＯＮ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLS21_C21_INI     .DATA.W	D'0000           ; ロータリカム１８　ON角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLSTA22_C21_INI   .DATA.W	D'0000           ; ロータリカム１８　ＯＦＦ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLS22_C21_INI     .DATA.W	D'0000           ; ロータリカム１８　OFF角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLSTA31_C21_INI   .DATA.W	D'0000           ; ロータリカム１９　ＯＮ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLS31_C21_INI     .DATA.W	D'0000           ; ロータリカム１９　ON角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLSTA32_C21_INI   .DATA.W	D'0000           ; ロータリカム１９　ＯＦＦ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLS32_C21_INI     .DATA.W	D'0000           ; ロータリカム１９　OFF角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLSTA41_C21_INI   .DATA.W	D'0000           ; ロータリカム２０　ＯＮ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLS41_C21_INI     .DATA.W	D'0000           ; ロータリカム２０　ON角度／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLSTA42_C21_INI   .DATA.W	D'0000           ; ロータリカム２０　ＯＦＦ工程／＊＊＊＊　未使用　＊＊＊＊／
_SV_RCLS42_C21_INI     .DATA.W	D'0000           ; ロータリカム２０　OFF角度／＊＊＊＊　未使用　＊＊＊＊／
                    .SRES        8           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_ATUOSU_D9_INI      .DATA.L	D'00000000       ; スライド自動調節設定値（現在動作中）
_SV_ATUOS0_D9_INI      .DATA.L	D'00000000       ; スライド自動調節　生産設定
_SV_ATUOS1_D9_INI      .DATA.L	D'00000000       ; スライド自動調節　段取り１設定
_SV_ATUOS2_D9_INI      .DATA.L	D'00000000       ; スライド自動調節　段取り２設定
_SV_OVERE1_A26_INI     .DATA.W	D'0000           ; 荷重計　オーバーロード１
_SV_ROALM1_A26_INI     .DATA.W	D'0000           ; 荷重計　ロアーリッミト１
_SV_OVERE2_A26_INI     .DATA.W	D'0000           ; 荷重計　オーバーロード２
_SV_ROALM2_A26_INI     .DATA.W	D'0000           ; 荷重計　ロアーリッミト２
_SV_OVERE3_A26_INI     .DATA.W	D'0000           ; 荷重計　オーバーロード３
_SV_ROALM3_A26_INI     .DATA.W	D'0000           ; 荷重計　ロアーリッミト３
_SV_DUMMY_A26_INI      .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_CAMNA0_C1_INI      .DATA.W	H'0001           ; ロータリカム１汎用選択種別
_SV_CAMNA1_C1_INI      .DATA.W	H'0001           ; ロータリカム２汎用選択種別
_SV_CAMNA2_C1_INI      .DATA.W	H'0001           ; ロータリカム３汎用選択種別
_SV_CAMNA3_C1_INI      .DATA.W	H'0001           ; ロータリカム４汎用選択種別
_SV_CAMNA4_C1_INI      .DATA.W	H'0001           ; ロータリカム５汎用選択種別
_SV_CAMNA5_C1_INI      .DATA.W	H'0001           ; ロータリカム６汎用選択種別
_SV_CAMNA6_C1_INI      .DATA.W	H'0001           ; ロータリカム７汎用選択種別
_SV_CAMNA7_C1_INI      .DATA.W	H'0001           ; ロータリカム８汎用選択種別
_SV_CAMNA8_C1_INI      .DATA.W	H'0001           ; ロータリカム９汎用選択種別
_SV_CAMNA9_C1_INI      .DATA.W	H'0001           ; ロータリカム１０汎用選択種別
_SV_CAMNAA_C1_INI      .DATA.W	H'0001           ; ロータリカム１１汎用選択種別
_SV_CAMNAB_C1_INI      .DATA.W	H'0001           ; ロータリカム１２汎用選択種別
_SV_CAMNAC_C1_INI      .DATA.W	H'0001           ; ロータリカム１３汎用選択種別
_SV_CAMNAD_C1_INI      .DATA.W	H'0001           ; ロータリカム１４汎用選択種別
_SV_CAMNAE_C1_INI      .DATA.W	H'0001           ; ロータリカム１５汎用選択種別
_SV_CAMNAF_C1_INI      .DATA.W	H'0001           ; ロータリカム１６汎用選択種別
_SV_SPDSET_B1_INI      .DATA.W	D'0000           ; 生産速度設定値
_SV_SPDDAN_B1_INI      .DATA.W	D'0000           ; 段取速度設定値
_SV_BARANS_C27_INI     .DATA.W	D'0000           ; バランサ圧／＊＊＊＊　未使用　＊＊＊＊／
_SV_DAIKA1_C27_INI     .DATA.W	D'0000           ; ダイクッション圧１／＊＊＊＊　未使用　＊＊＊＊／
_SV_DAIKA2_C27_INI     .DATA.W	D'0000           ; ダイクッション圧２／＊＊＊＊　未使用　＊＊＊＊／
_SV_DAITY1_C27_INI     .DATA.W	D'0000           ; ダイクッション調節１／＊＊＊＊　未使用　＊＊＊＊／
_SV_DAITY2_C27_INI     .DATA.W	D'0000           ; ダイクッション調節２／＊＊＊＊　未使用　＊＊＊＊／
_SV_COILL1_C30_INI     .DATA.W	D'0000           ; コイルライン設定１／＊＊＊＊　未使用　＊＊＊＊／
_SV_COILL2_C30_INI     .DATA.W	D'0000           ; コイルライン設定２／＊＊＊＊　未使用　＊＊＊＊／
_SV_COILL3_C30_INI     .DATA.W	D'0000           ; コイルライン設定３／＊＊＊＊　未使用　＊＊＊＊／
_SV_COILL4_C30_INI     .DATA.W	D'0000           ; コイルライン設定４／＊＊＊＊　未使用　＊＊＊＊／
_SV_COILL5_C30_INI     .DATA.W	D'0000           ; コイルライン設定５／＊＊＊＊　未使用　＊＊＊＊／
_SV_COILL6_C30_INI     .DATA.W	D'0000           ; コイルライン設定６／＊＊＊＊　未使用　＊＊＊＊／
_SV_COIMAI_C30_INI     .DATA.W	D'0000           ; コイルライン設定ﾏｲﾅｽ／＊＊＊＊　未使用　＊＊＊＊／
_SV_UPDANO_C28_INI     .DATA.W	D'0000           ; 上型クランパ６選択　パターン入力データ／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_C28_INI      .SRES        600         ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_C29_INI      .SRES        564         ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_PV_TOTLC1_B3_KAT_INI  .DATA.L	D'00000000       ; トータルカウンタ１実測値
_PV_LOTCT1_B4_KAT_INI  .DATA.L	D'00000000       ; ロットカウンタ１実測値／＊＊＊＊　未使用　＊＊＊＊／
_PV_TOTLC2_B31_KAT_INI .DATA.L	D'00000000       ; 未使用／＊＊＊＊　未使用　＊＊＊＊／
_PV_LOTCT2_B41_KAT_INI .DATA.L	D'00000000       ; ロットカウンタ２実測値／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_C30_INI      .SRES        174         ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_FRAM_KAT_END_INI      .DATA.W	D'0000           ; F-RAM領域の型データのエンドラベル／＊＊＊＊　未使用　＊＊＊＊／
_FRAM_KAT_SUM_INI      .SRES        16          ; 型データのチェックサム領域用／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_C31_INI      .SRES        768         ; 調整用(次オフセット・アドレス：0x１０００)／＊＊＊＊　未使用　＊＊＊＊／
_KAT_NEXT_FLG_INI      .DATA.W	H'0000           ; 次型データ有無ﾌﾗｸﾞ読み込み 1=有り／＊＊＊＊　未使用　＊＊＊＊／
_KT_MLDNO0_NF1_INI     .DATA.W	H'0000, H'0000, H'0000, H'0000, H'0000, H'0000, H'0000, H'0000         ; 次型金型名称／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_NF1_INI      .SRES        14          ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_PV_MLDNO1_F1_INI      .DATA.W	D'0000           ; 現在の型番号／＊＊＊＊　未使用　＊＊＊＊／
_PV_MLDNO2_F1_INI      .DATA.W	H'0000, H'0000, H'0000, H'0000, H'0000, H'0000, H'0000, H'0000         ; 現在の型名称／＊＊＊＊　未使用　＊＊＊＊／
_KAT_NOW_NO_INI        .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_PV_MLDNO3_F1_INI      .DATA.W	H'0000, H'0000, H'0000, H'0000, H'0000, H'0000, H'0000, H'0000         ; 空き（型名称画面の仮の名称）／＊＊＊＊　未使用　＊＊＊＊／
_SV_DUMMY_F1_INI       .SRES        30          ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SV_EJENAM01_C1_INI    .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; エジェクタ１名称
_SV_EJENAM02_C1_INI    .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; エジェクタ１名称
_SV_EJENAM03_C1_INI    .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; エジェクタ１名称
_SV_EJENAM04_C1_INI    .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; エジェクタ１名称
_SV_EJENAM05_C1_INI    .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; エジェクタ１名称
_SV_EJENAM06_C1_INI    .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; エジェクタ１名称
_SV_CAMNA01_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１名称
_SV_CAMNA02_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム２名称
_SV_CAMNA03_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム３名称
_SV_CAMNA04_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム４名称
_SV_CAMNA05_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム５名称
_SV_CAMNA06_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム６名称
_SV_CAMNA07_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム７名称
_SV_CAMNA08_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム８名称
_SV_CAMNA09_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム９名称
_SV_CAMNA10_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１０名称
_SV_CAMNA11_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１１名称
_SV_CAMNA12_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１２名称
_SV_CAMNA13_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１３名称
_SV_CAMNA14_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１４名称
_SV_CAMNA15_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１５名称
_SV_CAMNA16_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１６名称
_SV_CAMNA17_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１７名称
_SV_CAMNA18_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１８名称
_SV_CAMNA19_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム１９名称
_SV_CAMNA20_C1_INI     .DATA.B 	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00          ; ロータリカム２０名称
_KAT_JIKI_TOP_INI      .SRES        512         ; 次期金型用型データ領域／＊＊＊＊　未使用　＊＊＊＊／
                    .SRES        206         ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_PV_TOTLC1_B3_INI      .DATA.L	D'00000000       ; トータルカウンタ１実測値／＊＊＊＊　未使用　＊＊＊＊／
_PV_LOTCT1_B4_INI      .DATA.L	D'00000000       ; ロットカウンタ１実測値／＊＊＊＊　未使用　＊＊＊＊／
_PV_TOTLC2_B31_INI     .DATA.L	D'00000000       ; 未使用／＊＊＊＊　未使用　＊＊＊＊／
_PV_LOTCT2_B41_INI     .DATA.L	D'00000000       ; ロットカウンタ２実測値／＊＊＊＊　未使用　＊＊＊＊／
_PV_LIFE_COUNT_INI     .DATA.W	H'0000, H'0000, H'0000           ; 機械総カウンタ／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.W	H'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_PV_LIFE_TIME_10_INI   .DATA.L	D'00000000       ; 機械総時間（10msecカウンタ）／＊＊＊＊　未使用　＊＊＊＊／
_PV_LIFE_TIME_INI      .DATA.L	D'00000000       ; 機械総時間（1secカウンタ）／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.L	D'00000000       ; 空き／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_BAK_312_INI       .DATA.W	H'0000           ; キープリレーバックアップ３１２／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_BAK_313_INI       .DATA.W	H'0000           ; キープリレーバックアップ３１３／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_BAK_314_INI       .DATA.W	H'0000           ; キープリレーバックアップ３１４／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_BAK_315_INI       .DATA.W	H'0000           ; キープリレーバックアップ３１５／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_BAK_316_INI       .DATA.W	H'0000           ; キープリレーバックアップ３１６／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_BAK_317_INI       .DATA.W	H'0000           ; キープリレーバックアップ３１７／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_BAK_318_INI       .DATA.W	H'0000           ; キープリレーバックアップ３１８／＊＊＊＊　未使用　＊＊＊＊／
_SEQ_BAK_319_INI       .DATA.W	H'0000           ; キープリレーバックアップ３１９／＊＊＊＊　未使用　＊＊＊＊／
_SURA_CHG_LST_INI      .DATA.W	H'0000           ; リザーブ／＊＊＊＊　未使用　＊＊＊＊／
                    .SRES        8           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_CNT1_INI     .DATA.L	D'00000000       ; メンテナンスカウンタ１／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_CNT2_INI     .DATA.L	D'00000000       ; メンテナンスカウンタ２／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_CNT3_INI     .DATA.L	D'00000000       ; メンテナンスカウンタ３／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_CNT4_INI     .DATA.L	D'00000000       ; メンテナンスカウンタ４／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_CNT5_INI     .DATA.L	D'00000000       ; メンテナンスカウンタ５／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_CNT6_INI     .DATA.L	D'00000000       ; メンテナンスカウンタ６／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_CNT7_INI     .DATA.L	D'00000000       ; メンテナンスカウンタ７／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_CNT8_INI     .DATA.L	D'00000000       ; メンテナンスカウンタ８／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_TIM1_INI     .DATA.L	D'00000000       ; メンテナンス時間１（1secカウンタ）／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_TIM1_10_INI  .DATA.L	D'00000000       ; メンテナンス時間１（10msecカウンタ）／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_TIM2_INI     .DATA.L	D'00000000       ; メンテナンス時間２（1secカウンタ）／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_TIM2_10_INI  .DATA.L	D'00000000       ; メンテナンス時間２（10msecカウンタ）／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_TIM3_INI     .DATA.L	D'00000000       ; メンテナンス時間３（1secカウンタ）／＊＊＊＊　未使用　＊＊＊＊／
_MCN_MENT_TIM3_10_INI  .DATA.L	D'00000000       ; メンテナンス時間３（10msecカウンタ）／＊＊＊＊　未使用　＊＊＊＊／
                    .SRES        8           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK1L_INI     .DATA.W	D'0000           ; 最大歪み２０００左ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK1R_INI     .DATA.W	D'0000           ; 最大歪み２０００右ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK2L_INI     .DATA.W	D'0000           ; 最大歪み１５００左ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK2R_INI     .DATA.W	D'0000           ; 最大歪み１５００右ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK3L_INI     .DATA.W	D'0000           ; 最大歪み　８００左ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK3R_INI     .DATA.W	D'0000           ; 最大歪み　８００右ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK4L_INI     .DATA.W	D'0000           ; 最大歪み　４００左ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK4R_INI     .DATA.W	D'0000           ; 最大歪み　４００右ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK5L_INI     .DATA.W	D'0000           ; 最大歪み　２００左ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_GAIN_BAK5R_INI     .DATA.W	D'0000           ; 最大歪み　２００右ゲイン／＊＊＊＊　未使用　＊＊＊＊／
_PV_OF_BAKL_INI        .DATA.W	D'0000           ; オフセット値左／＊＊＊＊　未使用　＊＊＊＊／
_PV_OF_BAKR_INI        .DATA.W	D'0000           ; オフセット値右／＊＊＊＊　未使用　＊＊＊＊／
_PV_OF_AVE_BAKL_INI    .DATA.W	D'0000           ; オフセット補正左／＊＊＊＊　未使用　＊＊＊＊／
_PV_OF_AVE_BAKR_INI    .DATA.W	D'0000           ; オフセット補正右／＊＊＊＊　未使用　＊＊＊＊／
_PV_OF_AVE_BAKT_INI    .DATA.W	D'0000           ; オフセット補正合計／＊＊＊＊　未使用　＊＊＊＊／
                    .DATA.W	D'0000           ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_PV_GENITI_B2_INI      .DATA.L	D'00000000       ; 現位置データ／＊＊＊＊　未使用　＊＊＊＊／
                    .SRES        28          ; ／＊＊＊＊　未使用　＊＊＊＊／
_SUM_CHK_INI           .DATA.L	H'00000000       ; 設定値サムチェックコード／＊＊＊＊　未使用　＊＊＊＊／
_SUM_CHK_KAT_INI       .DATA.W	H'0000           ; 型ﾃﾞｰﾀ 名称＆メモ サムチェックコード／＊＊＊＊　未使用　＊＊＊＊／
                    .SRES        60          ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_PV_SEQDT1_A91_INI     .DATA.W	H'0000           ; シーケンスチェック１／＊＊＊＊　未使用　＊＊＊＊／
_PV_SEQDT2_A91_INI     .DATA.W	H'0000           ; シーケンスチェック２／＊＊＊＊　未使用　＊＊＊＊／
_PV_SEQDT3_A91_INI     .DATA.W	H'0000           ; シーケンスチェック３／＊＊＊＊　未使用　＊＊＊＊／
_PV_SEQDT4_A91_INI     .DATA.W	H'0000           ; シーケンスチェック４／＊＊＊＊　未使用　＊＊＊＊／
_PV_CB1_MAXSPD_INI     .DATA.W	H'0000           ; 仕様最高速設定時のＡＤ値／＊＊＊＊　未使用　＊＊＊＊／
_PV_CB2_MAXSPD_INI     .DATA.W	H'0000           ; 未使用／＊＊＊＊　未使用　＊＊＊＊／
_SV_EUPL_SYS_INI       .DATA.W	H'0000           ; 未使用／＊＊＊＊　未使用　＊＊＊＊／
_SV_CBRPM1_SYS_INI     .DATA.W	H'0000           ; 未使用／＊＊＊＊　未使用　＊＊＊＊／
_SV_CBRPM2_SYS_INI     .DATA.W	H'0000           ; 未使用／＊＊＊＊　未使用　＊＊＊＊／
_SV_CBRPM3_SYS_INI     .DATA.W	H'0000           ; 未使用／＊＊＊＊　未使用　＊＊＊＊／
_SV_HOSTIM_A12_INI     .DATA.W	H'0000           ; 起動補償時間設定値／＊＊＊＊　未使用　＊＊＊＊／
_SV_TAIKI1_A12_INI     .DATA.W	H'0000           ; 待機点１データ設定値／＊＊＊＊　未使用　＊＊＊＊／
_SV_TAIKI2_A12_INI     .DATA.W	H'0000           ; 待機点２データ設定値／＊＊＊＊　未使用　＊＊＊＊／
_SV_TAIKI3_A12_INI     .DATA.W	H'0000           ; 待機点３データ設定値／＊＊＊＊　未使用　＊＊＊＊／
_SV_RNZRPM_A12_INI     .DATA.W	H'0000           ; 連続回転設定値
_SV_RNZTIM_A12_INI     .DATA.W	H'0000           ; 連続タイマ設定値
                    .DATA.W	H'0000           ; クラッチ定数１  シーケンス２８．０～２８．１５
                    .DATA.W	H'0000           ; クラッチ定数２  シーケンス２９．０～２９．１５
                    .DATA.W	H'0000           ; クラッチ定数３  シーケンス３０．０～３０．１５
_KIDO_FLG_SV_INI       .DATA.W	H'0000           ; 輝度データ読込＆格納／＊＊＊＊　未使用　＊＊＊＊／
_KIDO_CNT_INI          .DATA.W	H'0000           ; 輝度調整設定値
_SV_PSDIMD_A1_INI      .DATA.W	H'0000           ; ＰＳＤＩ選択番号／＊＊＊＊　未使用　＊＊＊＊／
_SV_CAMNA_C1_INI       .DATA.W	H'0000           ; ロータリカム１７～２０用ダミー領域／＊＊＊＊　未使用　＊＊＊＊／
_PV_SEARCH_C15_INI     .DATA.W	H'0000           ; 型番号検索ナンバー読込／＊＊＊＊　未使用　＊＊＊＊／
_SV_RS4SEL_SYS_INI     .DATA.W	H'0000           ; ＲＳ４２２仕様の有無／＊＊＊＊　未使用　＊＊＊＊／
_SV_RS4BPS_SYS_INI     .DATA.W	H'0000           ; ぼーれいと設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RS4DTL_SYS_INI     .DATA.W	H'0000           ; データ長／＊＊＊＊　未使用　＊＊＊＊／
_SV_RS4STP_SYS_INI     .DATA.W	H'0000           ; ストップビット／＊＊＊＊　未使用　＊＊＊＊／
_SV_RS4PAR_SYS_INI     .DATA.W	H'0000           ; パリティ設定／＊＊＊＊　未使用　＊＊＊＊／
_SV_RS4KNO_SYS_INI     .DATA.W	H'0000           ; 局番／＊＊＊＊　未使用　＊＊＊＊／
_SV_OUTADR_SYS_INI     .DATA.W	H'0000           ; 拡張出力領域アドレス／＊＊＊＊　未使用　＊＊＊＊／
_SV_OUTCNT_SYS_INI     .DATA.W	H'0000           ; 拡張出力領域カウンタ／＊＊＊＊　未使用　＊＊＊＊／
_SV_UPDANO_MAX_INI     .DATA.W	H'0000           ; 上型クランパ６選択パターン入力MAX／＊＊＊＊　未使用　＊＊＊＊／
                    .SRES        194         ; 空き／＊＊＊＊　未使用　＊＊＊＊／
_KAT_NAME_01_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１
_KAT_MEMO_01_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１
_KAT_NAME_02_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２
_KAT_MEMO_02_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２
_KAT_NAME_03_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３
_KAT_MEMO_03_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３
_KAT_NAME_04_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４
_KAT_MEMO_04_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４
_KAT_NAME_05_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５
_KAT_MEMO_05_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５
_KAT_NAME_06_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６
_KAT_MEMO_06_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６
_KAT_NAME_07_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７
_KAT_MEMO_07_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７
_KAT_NAME_08_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８
_KAT_MEMO_08_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８
_KAT_NAME_09_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９
_KAT_MEMO_09_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９
_KAT_NAME_10_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称1０
_KAT_MEMO_10_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ1０
_KAT_NAME_11_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１１
_KAT_MEMO_11_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１１
_KAT_NAME_12_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１２
_KAT_MEMO_12_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１２
_KAT_NAME_13_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１３
_KAT_MEMO_13_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１３
_KAT_NAME_14_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１４
_KAT_MEMO_14_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１４
_KAT_NAME_15_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１５
_KAT_MEMO_15_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１５
_KAT_NAME_16_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１６
_KAT_MEMO_16_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１６
_KAT_NAME_17_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１７
_KAT_MEMO_17_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１７
_KAT_NAME_18_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１８
_KAT_MEMO_18_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１８
_KAT_NAME_19_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１９
_KAT_MEMO_19_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１９
_KAT_NAME_20_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２０
_KAT_MEMO_20_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２０
_KAT_NAME_21_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２１
_KAT_MEMO_21_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２１
_KAT_NAME_22_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２２
_KAT_MEMO_22_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２２
_KAT_NAME_23_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２３
_KAT_MEMO_23_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２３
_KAT_NAME_24_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２４
_KAT_MEMO_24_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２４
_KAT_NAME_25_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２５
_KAT_MEMO_25_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２５
_KAT_NAME_26_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２６
_KAT_MEMO_26_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２６
_KAT_NAME_27_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２７
_KAT_MEMO_27_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２７
_KAT_NAME_28_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２８
_KAT_MEMO_28_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２８
_KAT_NAME_29_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称２９
_KAT_MEMO_29_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ２９
_KAT_NAME_30_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３０
_KAT_MEMO_30_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３０
_KAT_NAME_31_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３１
_KAT_MEMO_31_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３１
_KAT_NAME_32_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３２
_KAT_MEMO_32_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３２
_KAT_NAME_33_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３３
_KAT_MEMO_33_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３３
_KAT_NAME_34_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３４
_KAT_MEMO_34_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３４
_KAT_NAME_35_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３５
_KAT_MEMO_35_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３５
_KAT_NAME_36_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３６
_KAT_MEMO_36_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３６
_KAT_NAME_37_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３７
_KAT_MEMO_37_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３７
_KAT_NAME_38_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３８
_KAT_MEMO_38_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３８
_KAT_NAME_39_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称３９
_KAT_MEMO_39_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ３９
_KAT_NAME_40_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４０
_KAT_MEMO_40_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４０
_KAT_NAME_41_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４１
_KAT_MEMO_41_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４１
_KAT_NAME_42_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４２
_KAT_MEMO_42_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４２
_KAT_NAME_43_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４３
_KAT_MEMO_43_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４３
_KAT_NAME_44_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４４
_KAT_MEMO_44_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４４
_KAT_NAME_45_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４５
_KAT_MEMO_45_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４５
_KAT_NAME_46_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４６
_KAT_MEMO_46_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４６
_KAT_NAME_47_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４７
_KAT_MEMO_47_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４７
_KAT_NAME_48_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４８
_KAT_MEMO_48_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４８
_KAT_NAME_49_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称４９
_KAT_MEMO_49_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ４９
_KAT_NAME_50_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５０
_KAT_MEMO_50_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５０
_KAT_NAME_51_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５１
_KAT_MEMO_51_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５１
_KAT_NAME_52_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５２
_KAT_MEMO_52_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５２
_KAT_NAME_53_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５３
_KAT_MEMO_53_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５３
_KAT_NAME_54_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５４
_KAT_MEMO_54_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５４
_KAT_NAME_55_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５５
_KAT_MEMO_55_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５５
_KAT_NAME_56_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５６
_KAT_MEMO_56_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５６
_KAT_NAME_57_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５７
_KAT_MEMO_57_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５７
_KAT_NAME_58_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５８
_KAT_MEMO_58_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５８
_KAT_NAME_59_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称５９
_KAT_MEMO_59_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ５９
_KAT_NAME_60_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６０
_KAT_MEMO_60_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６０
_KAT_NAME_61_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６１
_KAT_MEMO_61_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６１
_KAT_NAME_62_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６２
_KAT_MEMO_62_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６２
_KAT_NAME_63_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６３
_KAT_MEMO_63_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６３
_KAT_NAME_64_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６４
_KAT_MEMO_64_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６４
_KAT_NAME_65_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６５
_KAT_MEMO_65_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６５
_KAT_NAME_66_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６６
_KAT_MEMO_66_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６６
_KAT_NAME_67_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６７
_KAT_MEMO_67_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６７
_KAT_NAME_68_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６８
_KAT_MEMO_68_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６８
_KAT_NAME_69_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称６９
_KAT_MEMO_69_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ６９
_KAT_NAME_70_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７０
_KAT_MEMO_70_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７０
_KAT_NAME_71_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７１
_KAT_MEMO_71_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７１
_KAT_NAME_72_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７２
_KAT_MEMO_72_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７２
_KAT_NAME_73_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７３
_KAT_MEMO_73_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７３
_KAT_NAME_74_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７４
_KAT_MEMO_74_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７４
_KAT_NAME_75_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７５
_KAT_MEMO_75_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７５
_KAT_NAME_76_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７６
_KAT_MEMO_76_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７６
_KAT_NAME_77_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７７
_KAT_MEMO_77_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７７
_KAT_NAME_78_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７８
_KAT_MEMO_78_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７８
_KAT_NAME_79_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称７９
_KAT_MEMO_79_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ７９
_KAT_NAME_80_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８０
_KAT_MEMO_80_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８０
_KAT_NAME_81_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８１
_KAT_MEMO_81_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８１
_KAT_NAME_82_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８２
_KAT_MEMO_82_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８２
_KAT_NAME_83_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８３
_KAT_MEMO_83_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８３
_KAT_NAME_84_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８４
_KAT_MEMO_84_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８４
_KAT_NAME_85_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８５
_KAT_MEMO_85_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８５
_KAT_NAME_86_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８６
_KAT_MEMO_86_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８６
_KAT_NAME_87_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８７
_KAT_MEMO_87_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８７
_KAT_NAME_88_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８８
_KAT_MEMO_88_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８８
_KAT_NAME_89_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称８９
_KAT_MEMO_89_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ８９
_KAT_NAME_90_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９０
_KAT_MEMO_90_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９０
_KAT_NAME_91_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９１
_KAT_MEMO_91_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９１
_KAT_NAME_92_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９２
_KAT_MEMO_92_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９２
_KAT_NAME_93_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９３
_KAT_MEMO_93_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９３
_KAT_NAME_94_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９４
_KAT_MEMO_94_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９４
_KAT_NAME_95_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９５
_KAT_MEMO_95_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９５
_KAT_NAME_96_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９６
_KAT_MEMO_96_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９６
_KAT_NAME_97_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９７
_KAT_MEMO_97_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９７
_KAT_NAME_98_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９８
_KAT_MEMO_98_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９８
_KAT_NAME_99_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称９９
_KAT_MEMO_99_INI    .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ９９
_KAT_NAME_100_INI   .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データ名称１００
_KAT_MEMO_100_INI   .DATA.B	H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00,H'00         ; 型データメモ１００
_KAT_NAME_END_INI   .SRES        130         ; 空き(型データ　名称＆メモ終了ｱﾄﾞﾚｽ)／＊＊＊＊　未使用　＊＊＊＊／


; END
