/***********************************************************************/
/*                                                                     */
/*  FILE        :lowsrc.h                                              */
/*  DATE        :Fri, May 31, 2002                                     */
/*  DESCRIPTION :Header file of I/O Stream file                        */
/*  CPU TYPE    :SH7750                                                */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.2.1).     */
/*                                                                     */
/***********************************************************************/
/*Number of I/O Stream*/
#define IOSTREAM 20
