/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Mon, Jun 24, 2002                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :SH7750                                                */
/*                                                                     */
/*  This file is generated by Hitachi Project Generator (Ver.1.1).     */
/*                                                                     */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x400
